In [ ]:
import pandas as pd
import psycopg2

# Define connection parameters
conn_params = {
    'dbname': 'weather',
    'user': 'postgres',
    'password': 'r00t',
    'host': 'localhost',
    'port': '5433'
}

print("Connecting to the PostgreSQL database...")

# Connect to PostgreSQL
try:
    conn = psycopg2.connect(**conn_params)
    cur = conn.cursor()
    print("Connected successfully.")
except Exception as e:
    print(f"Error connecting to database: {e}")
    exit()

# Create table if not exists
create_table_query = '''
CREATE TABLE IF NOT EXISTS weather_data (
  "Date/Time" TIMESTAMP,
  "Temp_C" FLOAT,
  "Dew Point Temp_C" FLOAT,
  "Rel Hum_%" FLOAT,
  "Wind Speed_km/h" FLOAT,
  "Visibility_km" FLOAT,
  "Press_kPa" FLOAT,
  "Weather" TEXT
)
'''
print("Creating table if it does not exist...")
try:
    cur.execute(create_table_query)
    print("Table created or already exists.")
except Exception as e:
    print(f"Error creating table: {e}")
    conn.close()
    exit()

# Prepare the insert statement
insert_query = '''
INSERT INTO weather_data ("Date/Time", "Temp_C", "Dew Point Temp_C", "Rel Hum_%", "Wind Speed_km/h", "Visibility_km", "Press_kPa", "Weather")
VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
'''

print("Reading CSV file...")
# Read the CSV file
try:
    df = pd.read_csv(r'C:\Users\cyril\Documents\lux academy\1. Weather Data.csv')
    print(f"CSV file read successfully. Number of rows: {len(df)}")
except Exception as e:
    print(f"Error reading CSV file: {e}")
    cur.close()
    conn.close()
    exit()
print(df.head())

print("Inserting data into the table...")
try:
    for index, row in df.iterrows():
        try:
            print(f"Inserting row {index+1}")
            cur.execute(insert_query, tuple(row))
        except Exception as e:
            print(f"Error inserting row {index+1}: {e}")
            print(f"Row data: {row}")
            # Handle the error, e.g., log the error, skip the row, or raise an exception
    conn.commit()  # Commit the transaction
    print("Data inserted successfully.")
except Exception as e:
    print(f"Error inserting data: {e}")
    conn.rollback()  # Rollback the transaction in case of error
finally:
    cur.close()  # Close the cursor
    conn.close()  # Close the connection
    print("Database connection closed.")

Connecting to the PostgreSQL database...
Connected successfully.
Creating table if it does not exist...
Table created or already exists.
Reading CSV file...
CSV file read successfully. Number of rows: 8784
       Date/Time  Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  \
0  1/1/2012 0:00    -1.8              -3.9         86                4
1  1/1/2012 1:00    -1.8              -3.7         87                4
2  1/1/2012 2:00    -1.8              -3.4         89                7
3  1/1/2012 3:00    -1.5              -3.2         88                6
4  1/1/2012 4:00    -1.5              -3.3         88                7

   Visibility_km  Press_kPa               Weather
0            8.0     101.24                   Fog
1            8.0     101.24                   Fog
2            4.0     101.26  Freezing Drizzle,Fog
3            4.0     101.27  Freezing Drizzle,Fog
4            4.8     101.23                   Fog
Inserting data into the table...
Inserting row 1
Error inserting row 1: tuple index out of range
Row data: Date/Time           1/1/2012 0:00
Temp_C                       -1.8
Dew Point Temp_C             -3.9
Rel Hum_%                      86
Wind Speed_km/h                 4
Visibility_km                 8.0
Press_kPa                  101.24
Weather                       Fog
Name: 0, dtype: object
Inserting row 2
Error inserting row 2: tuple index out of range
Row data: Date/Time           1/1/2012 1:00
Temp_C                       -1.8
Dew Point Temp_C             -3.7
Rel Hum_%                      87
Wind Speed_km/h                 4
Visibility_km                 8.0
Press_kPa                  101.24
Weather                       Fog
Name: 1, dtype: object
Inserting row 3
Error inserting row 3: tuple index out of range
Row data: Date/Time                  1/1/2012 2:00
Temp_C                              -1.8
Dew Point Temp_C                    -3.4
Rel Hum_%                             89
Wind Speed_km/h                        7
Visibility_km                        4.0
Press_kPa                         101.26
Weather             Freezing Drizzle,Fog
Name: 2, dtype: object
Inserting row 4
Error inserting row 4: tuple index out of range
Row data: Date/Time                  1/1/2012 3:00
Temp_C                              -1.5
Dew Point Temp_C                    -3.2
Rel Hum_%                             88
Wind Speed_km/h                        6
Visibility_km                        4.0
Press_kPa                         101.27
Weather             Freezing Drizzle,Fog
Name: 3, dtype: object
Inserting row 5
Error inserting row 5: tuple index out of range
Row data: Date/Time           1/1/2012 4:00
Temp_C                       -1.5
Dew Point Temp_C             -3.3
Rel Hum_%                      88
Wind Speed_km/h                 7
Visibility_km                 4.8
Press_kPa                  101.23
Weather                       Fog
Name: 4, dtype: object
Inserting row 6
Error inserting row 6: tuple index out of range
Row data: Date/Time           1/1/2012 5:00
Temp_C                       -1.4
Dew Point Temp_C             -3.3
Rel Hum_%                      87
Wind Speed_km/h                 9
Visibility_km                 6.4
Press_kPa                  101.27
Weather                       Fog
Name: 5, dtype: object
Inserting row 7
Error inserting row 7: tuple index out of range
Row data: Date/Time           1/1/2012 6:00
Temp_C                       -1.5
Dew Point Temp_C             -3.1
Rel Hum_%                      89
Wind Speed_km/h                 7
Visibility_km                 6.4
Press_kPa                  101.29
Weather                       Fog
Name: 6, dtype: object
Inserting row 8
Error inserting row 8: tuple index out of range
Row data: Date/Time           1/1/2012 7:00
Temp_C                       -1.4
Dew Point Temp_C             -3.6
Rel Hum_%                      85
Wind Speed_km/h                 7
Visibility_km                 8.0
Press_kPa                  101.26
Weather                       Fog
Name: 7, dtype: object
Inserting row 9
Error inserting row 9: tuple index out of range
Row data: Date/Time           1/1/2012 8:00
Temp_C                       -1.4
Dew Point Temp_C             -3.6
Rel Hum_%                      85
Wind Speed_km/h                 9
Visibility_km                 8.0
Press_kPa                  101.23
Weather                       Fog
Name: 8, dtype: object
Inserting row 10
Error inserting row 10: tuple index out of range
Row data: Date/Time           1/1/2012 9:00
Temp_C                       -1.3
Dew Point Temp_C             -3.1
Rel Hum_%                      88
Wind Speed_km/h                15
Visibility_km                 4.0
Press_kPa                   101.2
Weather                       Fog
Name: 9, dtype: object
Inserting row 11
Error inserting row 11: tuple index out of range
Row data: Date/Time           1/1/2012 10:00
Temp_C                        -1.0
Dew Point Temp_C              -2.3
Rel Hum_%                       91
Wind Speed_km/h                  9
Visibility_km                  1.2
Press_kPa                   101.15
Weather                        Fog
Name: 10, dtype: object
Inserting row 12
Error inserting row 12: tuple index out of range
Row data: Date/Time           1/1/2012 11:00
Temp_C                        -0.5
Dew Point Temp_C              -2.1
Rel Hum_%                       89
Wind Speed_km/h                  7
Visibility_km                  4.0
Press_kPa                   100.98
Weather                        Fog
Name: 11, dtype: object
Inserting row 13
Error inserting row 13: tuple index out of range
Row data: Date/Time           1/1/2012 12:00
Temp_C                        -0.2
Dew Point Temp_C              -2.0
Rel Hum_%                       88
Wind Speed_km/h                  9
Visibility_km                  4.8
Press_kPa                   100.79
Weather                        Fog
Name: 12, dtype: object
Inserting row 14
Error inserting row 14: tuple index out of range
Row data: Date/Time           1/1/2012 13:00
Temp_C                         0.2
Dew Point Temp_C              -1.7
Rel Hum_%                       87
Wind Speed_km/h                 13
Visibility_km                  4.8
Press_kPa                   100.58
Weather                        Fog
Name: 13, dtype: object
Inserting row 15
Error inserting row 15: tuple index out of range
Row data: Date/Time           1/1/2012 14:00
Temp_C                         0.8
Dew Point Temp_C              -1.1
Rel Hum_%                       87
Wind Speed_km/h                 20
Visibility_km                  4.8
Press_kPa                   100.31
Weather                        Fog
Name: 14, dtype: object
Inserting row 16
Error inserting row 16: tuple index out of range
Row data: Date/Time           1/1/2012 15:00
Temp_C                         1.8
Dew Point Temp_C              -0.4
Rel Hum_%                       85
Wind Speed_km/h                 22
Visibility_km                  6.4
Press_kPa                   100.07
Weather                        Fog
Name: 15, dtype: object
Inserting row 17
Error inserting row 17: tuple index out of range
Row data: Date/Time           1/1/2012 16:00
Temp_C                         2.6
Dew Point Temp_C              -0.2
Rel Hum_%                       82
Wind Speed_km/h                 13
Visibility_km                 12.9
Press_kPa                    99.93
Weather              Mostly Cloudy
Name: 16, dtype: object
Inserting row 18
Error inserting row 18: tuple index out of range
Row data: Date/Time           1/1/2012 17:00
Temp_C                         3.0
Dew Point Temp_C               0.0
Rel Hum_%                       81
Wind Speed_km/h                 13
Visibility_km                 16.1
Press_kPa                    99.81
Weather                     Cloudy
Name: 17, dtype: object
Inserting row 19
Error inserting row 19: tuple index out of range
Row data: Date/Time           1/1/2012 18:00
Temp_C                         3.8
Dew Point Temp_C               1.0
Rel Hum_%                       82
Wind Speed_km/h                 15
Visibility_km                 12.9
Press_kPa                    99.74
Weather                       Rain
Name: 18, dtype: object
Inserting row 20
Error inserting row 20: tuple index out of range
Row data: Date/Time           1/1/2012 19:00
Temp_C                         3.1
Dew Point Temp_C               1.3
Rel Hum_%                       88
Wind Speed_km/h                 15
Visibility_km                 12.9
Press_kPa                    99.68
Weather                       Rain
Name: 19, dtype: object
Inserting row 21
Error inserting row 21: tuple index out of range
Row data: Date/Time           1/1/2012 20:00
Temp_C                         3.2
Dew Point Temp_C               1.3
Rel Hum_%                       87
Wind Speed_km/h                 19
Visibility_km                 25.0
Press_kPa                     99.5
Weather                     Cloudy
Name: 20, dtype: object
Inserting row 22
Error inserting row 22: tuple index out of range
Row data: Date/Time           1/1/2012 21:00
Temp_C                         4.0
Dew Point Temp_C               1.7
Rel Hum_%                       85
Wind Speed_km/h                 20
Visibility_km                 25.0
Press_kPa                    99.39
Weather                     Cloudy
Name: 21, dtype: object
Inserting row 23
Error inserting row 23: tuple index out of range
Row data: Date/Time           1/1/2012 22:00
Temp_C                         4.4
Dew Point Temp_C               1.9
Rel Hum_%                       84
Wind Speed_km/h                 24
Visibility_km                 19.3
Press_kPa                    99.32
Weather               Rain Showers
Name: 22, dtype: object
Inserting row 24
Error inserting row 24: tuple index out of range
Row data: Date/Time           1/1/2012 23:00
Temp_C                         5.3
Dew Point Temp_C               2.0
Rel Hum_%                       79
Wind Speed_km/h                 30
Visibility_km                 25.0
Press_kPa                    99.31
Weather                     Cloudy
Name: 23, dtype: object
Inserting row 25
Error inserting row 25: tuple index out of range
Row data: Date/Time           1/2/2012 0:00
Temp_C                        5.2
Dew Point Temp_C              1.5
Rel Hum_%                      77
Wind Speed_km/h                35
Visibility_km                25.0
Press_kPa                   99.26
Weather              Rain Showers
Name: 24, dtype: object
Inserting row 26
Error inserting row 26: tuple index out of range
Row data: Date/Time           1/2/2012 1:00
Temp_C                        4.6
Dew Point Temp_C              0.0
Rel Hum_%                      72
Wind Speed_km/h                39
Visibility_km                25.0
Press_kPa                   99.26
Weather                    Cloudy
Name: 25, dtype: object
Inserting row 27
Error inserting row 27: tuple index out of range
Row data: Date/Time           1/2/2012 2:00
Temp_C                        3.9
Dew Point Temp_C             -0.9
Rel Hum_%                      71
Wind Speed_km/h                32
Visibility_km                25.0
Press_kPa                   99.26
Weather             Mostly Cloudy
Name: 26, dtype: object
Inserting row 28
Error inserting row 28: tuple index out of range
Row data: Date/Time           1/2/2012 3:00
Temp_C                        3.7
Dew Point Temp_C             -1.5
Rel Hum_%                      69
Wind Speed_km/h                33
Visibility_km                25.0
Press_kPa                    99.3
Weather             Mostly Cloudy
Name: 27, dtype: object
Inserting row 29
Error inserting row 29: tuple index out of range
Row data: Date/Time           1/2/2012 4:00
Temp_C                        2.9
Dew Point Temp_C             -2.3
Rel Hum_%                      69
Wind Speed_km/h                32
Visibility_km                25.0
Press_kPa                   99.26
Weather             Mostly Cloudy
Name: 28, dtype: object
Inserting row 30
Error inserting row 30: tuple index out of range
Row data: Date/Time           1/2/2012 5:00
Temp_C                        2.6
Dew Point Temp_C             -2.3
Rel Hum_%                      70
Wind Speed_km/h                32
Visibility_km                25.0
Press_kPa                   99.21
Weather             Mostly Cloudy
Name: 29, dtype: object
Inserting row 31
Error inserting row 31: tuple index out of range
Row data: Date/Time           1/2/2012 6:00
Temp_C                        2.3
Dew Point Temp_C             -2.6
Rel Hum_%                      70
Wind Speed_km/h                26
Visibility_km                25.0
Press_kPa                   99.18
Weather             Mostly Cloudy
Name: 30, dtype: object
Inserting row 32
Error inserting row 32: tuple index out of range
Row data: Date/Time           1/2/2012 7:00
Temp_C                        2.0
Dew Point Temp_C             -2.9
Rel Hum_%                      70
Wind Speed_km/h                33
Visibility_km                25.0
Press_kPa                   99.14
Weather             Mostly Cloudy
Name: 31, dtype: object
Inserting row 33
Error inserting row 33: tuple index out of range
Row data: Date/Time           1/2/2012 8:00
Temp_C                        1.9
Dew Point Temp_C             -3.3
Rel Hum_%                      68
Wind Speed_km/h                39
Visibility_km                24.1
Press_kPa                   99.14
Weather             Mostly Cloudy
Name: 32, dtype: object
Inserting row 34
Error inserting row 34: tuple index out of range
Row data: Date/Time           1/2/2012 9:00
Temp_C                        1.8
Dew Point Temp_C             -3.7
Rel Hum_%                      67
Wind Speed_km/h                44
Visibility_km                24.1
Press_kPa                   99.14
Weather             Mostly Cloudy
Name: 33, dtype: object
Inserting row 35
Error inserting row 35: tuple index out of range
Row data: Date/Time           1/2/2012 10:00
Temp_C                         1.5
Dew Point Temp_C              -4.1
Rel Hum_%                       66
Wind Speed_km/h                 43
Visibility_km                 24.1
Press_kPa                    99.18
Weather              Mostly Cloudy
Name: 34, dtype: object
Inserting row 36
Error inserting row 36: tuple index out of range
Row data: Date/Time           1/2/2012 11:00
Temp_C                         2.2
Dew Point Temp_C              -3.5
Rel Hum_%                       66
Wind Speed_km/h                 30
Visibility_km                 24.1
Press_kPa                    99.19
Weather              Mostly Cloudy
Name: 35, dtype: object
Inserting row 37
Error inserting row 37: tuple index out of range
Row data: Date/Time           1/2/2012 12:00
Temp_C                         1.7
Dew Point Temp_C              -6.2
Rel Hum_%                       56
Wind Speed_km/h                 48
Visibility_km                 24.1
Press_kPa                    99.21
Weather               Mainly Clear
Name: 36, dtype: object
Inserting row 38
Error inserting row 38: tuple index out of range
Row data: Date/Time           1/2/2012 13:00
Temp_C                         1.1
Dew Point Temp_C              -6.5
Rel Hum_%                       57
Wind Speed_km/h                 37
Visibility_km                 24.1
Press_kPa                    99.27
Weather              Mostly Cloudy
Name: 37, dtype: object
Inserting row 39
Error inserting row 39: tuple index out of range
Row data: Date/Time           1/2/2012 14:00
Temp_C                         1.1
Dew Point Temp_C              -6.8
Rel Hum_%                       56
Wind Speed_km/h                 33
Visibility_km                 24.1
Press_kPa                    99.33
Weather              Mostly Cloudy
Name: 38, dtype: object
Inserting row 40
Error inserting row 40: tuple index out of range
Row data: Date/Time           1/2/2012 15:00
Temp_C                         0.0
Dew Point Temp_C              -7.0
Rel Hum_%                       59
Wind Speed_km/h                 33
Visibility_km                 24.1
Press_kPa                    99.41
Weather              Mostly Cloudy
Name: 39, dtype: object
Inserting row 41
Error inserting row 41: tuple index out of range
Row data: Date/Time           1/2/2012 16:00
Temp_C                        -0.7
Dew Point Temp_C              -8.7
Rel Hum_%                       55
Wind Speed_km/h                 24
Visibility_km                 24.1
Press_kPa                     99.5
Weather              Mostly Cloudy
Name: 40, dtype: object
Inserting row 42
Error inserting row 42: tuple index out of range
Row data: Date/Time           1/2/2012 17:00
Temp_C                        -2.1
Dew Point Temp_C              -9.5
Rel Hum_%                       57
Wind Speed_km/h                 22
Visibility_km                 25.0
Press_kPa                    99.66
Weather               Snow Showers
Name: 41, dtype: object
Inserting row 43
Error inserting row 43: tuple index out of range
Row data: Date/Time           1/2/2012 18:00
Temp_C                        -4.1
Dew Point Temp_C             -11.4
Rel Hum_%                       57
Wind Speed_km/h                 28
Visibility_km                 25.0
Press_kPa                    99.86
Weather              Mostly Cloudy
Name: 42, dtype: object
Inserting row 44
Error inserting row 44: tuple index out of range
Row data: Date/Time           1/2/2012 19:00
Temp_C                        -4.8
Dew Point Temp_C             -12.1
Rel Hum_%                       57
Wind Speed_km/h                 24
Visibility_km                 25.0
Press_kPa                    100.0
Weather              Mostly Cloudy
Name: 43, dtype: object
Inserting row 45
Error inserting row 45: tuple index out of range
Row data: Date/Time           1/2/2012 20:00
Temp_C                        -5.6
Dew Point Temp_C             -13.4
Rel Hum_%                       54
Wind Speed_km/h                 24
Visibility_km                 25.0
Press_kPa                   100.07
Weather               Snow Showers
Name: 44, dtype: object
Inserting row 46
Error inserting row 46: tuple index out of range
Row data: Date/Time           1/2/2012 21:00
Temp_C                        -5.8
Dew Point Temp_C             -12.8
Rel Hum_%                       58
Wind Speed_km/h                 26
Visibility_km                 25.0
Press_kPa                   100.15
Weather               Snow Showers
Name: 45, dtype: object
Inserting row 47
Error inserting row 47: tuple index out of range
Row data: Date/Time           1/2/2012 22:00
Temp_C                        -7.0
Dew Point Temp_C             -14.7
Rel Hum_%                       54
Wind Speed_km/h                 20
Visibility_km                 25.0
Press_kPa                   100.26
Weather                     Cloudy
Name: 46, dtype: object
Inserting row 48
Error inserting row 48: tuple index out of range
Row data: Date/Time           1/2/2012 23:00
Temp_C                        -7.4
Dew Point Temp_C             -14.1
Rel Hum_%                       59
Wind Speed_km/h                 17
Visibility_km                 19.3
Press_kPa                   100.27
Weather               Snow Showers
Name: 47, dtype: object
Inserting row 49
Error inserting row 49: tuple index out of range
Row data: Date/Time           1/3/2012 0:00
Temp_C                       -9.0
Dew Point Temp_C            -16.0
Rel Hum_%                      57
Wind Speed_km/h                28
Visibility_km                25.0
Press_kPa                  100.35
Weather              Snow Showers
Name: 48, dtype: object
Inserting row 50
Error inserting row 50: tuple index out of range
Row data: Date/Time           1/3/2012 1:00
Temp_C                       -9.7
Dew Point Temp_C            -17.2
Rel Hum_%                      54
Wind Speed_km/h                20
Visibility_km                25.0
Press_kPa                  100.43
Weather                    Cloudy
Name: 49, dtype: object
Inserting row 51
Error inserting row 51: tuple index out of range
Row data: Date/Time           1/3/2012 2:00

Row data: Date/Time           1/5/2012 9:00
Temp_C                       -6.6
Dew Point Temp_C            -10.1
Rel Hum_%                      76
Wind Speed_km/h                 9
Visibility_km                24.1
Press_kPa                  100.42
Weather              Mainly Clear
Name: 105, dtype: object
Inserting row 107
Error inserting row 107: tuple index out of range
Row data: Date/Time           1/5/2012 10:00
Temp_C                        -6.0
Dew Point Temp_C             -10.0
Rel Hum_%                       73
Wind Speed_km/h                 17
Visibility_km                 48.3
Press_kPa                   100.45
Weather               Mainly Clear
Name: 106, dtype: object
Inserting row 108
Error inserting row 108: tuple index out of range
Row data: Date/Time           1/5/2012 11:00
Temp_C                        -5.6
Dew Point Temp_C             -10.2
Rel Hum_%                       70
Wind Speed_km/h                 22
Visibility_km                 48.3
Press_kPa                   100.41
Weather               Mainly Clear
Name: 107, dtype: object
Inserting row 109
Error inserting row 109: tuple index out of range
Row data: Date/Time           1/5/2012 12:00
Temp_C                        -4.7
Dew Point Temp_C              -9.6
Rel Hum_%                       69
Wind Speed_km/h                 20
Visibility_km                 48.3
Press_kPa                   100.38
Weather               Mainly Clear
Name: 108, dtype: object
Inserting row 110
Error inserting row 110: tuple index out of range
Row data: Date/Time           1/5/2012 13:00
Temp_C                        -4.4
Dew Point Temp_C              -9.7
Rel Hum_%                       66
Wind Speed_km/h                 26
Visibility_km                 48.3
Press_kPa                    100.4
Weather               Mainly Clear
Name: 109, dtype: object
Inserting row 111
Error inserting row 111: tuple index out of range
Row data: Date/Time           1/5/2012 14:00
Temp_C                        -5.1
Dew Point Temp_C             -10.7
Rel Hum_%                       65
Wind Speed_km/h                 22
Visibility_km                 48.3
Press_kPa                   100.46
Weather               Mainly Clear
Name: 110, dtype: object
Inserting row 112
Error inserting row 112: tuple index out of range
Row data: Date/Time           1/5/2012 15:00
Temp_C                        -4.3
Dew Point Temp_C             -12.0
Rel Hum_%                       55
Wind Speed_km/h                 26
Visibility_km                 48.3
Press_kPa                   100.52
Weather               Mainly Clear
Name: 111, dtype: object
Inserting row 113
Error inserting row 113: tuple index out of range
Row data: Date/Time           1/5/2012 16:00
Temp_C                        -5.0
Dew Point Temp_C             -12.7
Rel Hum_%                       55
Wind Speed_km/h                 19
Visibility_km                 24.1
Press_kPa                    100.6
Weather               Mainly Clear
Name: 112, dtype: object
Inserting row 114
Error inserting row 114: tuple index out of range
Row data: Date/Time           1/5/2012 17:00
Temp_C                        -6.7
Dew Point Temp_C             -14.1
Rel Hum_%                       56
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   100.65
Weather               Mainly Clear
Name: 113, dtype: object
Inserting row 115
Error inserting row 115: tuple index out of range
Row data: Date/Time           1/5/2012 18:00
Temp_C                        -7.1
Dew Point Temp_C             -14.4
Rel Hum_%                       56
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   100.71
Weather                      Clear
Name: 114, dtype: object
Inserting row 116
Error inserting row 116: tuple index out of range
Row data: Date/Time           1/5/2012 19:00
Temp_C                        -9.2
Dew Point Temp_C             -15.4
Rel Hum_%                       61
Wind Speed_km/h                  7
Visibility_km                 25.0
Press_kPa                    100.8
Weather                      Clear
Name: 115, dtype: object
Inserting row 117
Error inserting row 117: tuple index out of range
Row data: Date/Time           1/5/2012 20:00
Temp_C                        -9.8
Dew Point Temp_C             -15.7
Rel Hum_%                       62
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                   100.83
Weather                      Clear
Name: 116, dtype: object
Inserting row 118
Error inserting row 118: tuple index out of range
Row data: Date/Time           1/5/2012 21:00
Temp_C                        -9.0
Dew Point Temp_C             -14.8
Rel Hum_%                       63
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   100.83
Weather                      Clear
Name: 117, dtype: object
Inserting row 119
Error inserting row 119: tuple index out of range
Row data: Date/Time           1/5/2012 22:00
Temp_C                        -9.9
Dew Point Temp_C             -15.7
Rel Hum_%                       63
Wind Speed_km/h                  7
Visibility_km                 25.0
Press_kPa                   100.85
Weather                     Cloudy
Name: 118, dtype: object
Inserting row 120
Error inserting row 120: tuple index out of range
Row data: Date/Time           1/5/2012 23:00
Temp_C                        -9.4
Dew Point Temp_C             -15.5
Rel Hum_%                       61
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                   100.83
Weather                     Cloudy
Name: 119, dtype: object
Inserting row 121
Error inserting row 121: tuple index out of range
Row data: Date/Time           1/6/2012 0:00
Temp_C                       -9.6
Dew Point Temp_C            -16.8
Rel Hum_%                      56
Wind Speed_km/h                13
Visibility_km                25.0
Press_kPa                  100.81
Weather                    Cloudy
Name: 120, dtype: object
Inserting row 122
Error inserting row 122: tuple index out of range
Row data: Date/Time           1/6/2012 1:00
Temp_C                      -10.0
Dew Point Temp_C            -17.3
Rel Hum_%                      55
Wind Speed_km/h                17
Visibility_km                25.0
Press_kPa                  100.81
Weather                    Cloudy
Name: 121, dtype: object
Inserting row 123
Error inserting row 123: tuple index out of range
Row data: Date/Time           1/6/2012 2:00
Temp_C                      -10.5
Dew Point Temp_C            -16.5
Rel Hum_%                      61
Wind Speed_km/h                 9
Visibility_km                25.0
Press_kPa                  100.84
Weather                    Cloudy
Name: 122, dtype: object
Inserting row 124
Error inserting row 124: tuple index out of range
Row data: Date/Time           1/6/2012 3:00
Temp_C                      -10.6
Dew Point Temp_C            -16.0
Rel Hum_%                      64
Wind Speed_km/h                 0
Visibility_km                 9.7
Press_kPa                  100.76
Weather                      Snow
Name: 123, dtype: object
Inserting row 125
Error inserting row 125: tuple index out of range
Row data: Date/Time           1/6/2012 4:00
Temp_C                      -11.3
Dew Point Temp_C            -16.1
Rel Hum_%                      68
Wind Speed_km/h                15
Visibility_km                 3.2
Press_kPa                   100.7
Weather                      Snow
Name: 124, dtype: object
Inserting row 126
Error inserting row 126: tuple index out of range
Row data: Date/Time           1/6/2012 5:00
Temp_C                      -11.8
Dew Point Temp_C            -16.0
Rel Hum_%                      71
Wind Speed_km/h                19
Visibility_km                 2.8
Press_kPa                  100.61
Weather                      Snow
Name: 125, dtype: object
Inserting row 127
Error inserting row 127: tuple index out of range
Row data: Date/Time           1/6/2012 6:00
Temp_C                      -12.0
Dew Point Temp_C            -16.2
Rel Hum_%                      71
Wind Speed_km/h                22
Visibility_km                 4.8
Press_kPa                  100.58
Weather                      Snow
Name: 126, dtype: object
Inserting row 128
Error inserting row 128: tuple index out of range
Row data: Date/Time           1/6/2012 7:00
Temp_C                      -14.4
Dew Point Temp_C            -16.3
Rel Hum_%                      85
Wind Speed_km/h                22
Visibility_km                 2.4
Press_kPa                  100.52
Weather                      Snow
Name: 127, dtype: object
Inserting row 129
Error inserting row 129: tuple index out of range
Row data: Date/Time           1/6/2012 8:00
Temp_C                      -12.3
Dew Point Temp_C            -16.2
Rel Hum_%                      73
Wind Speed_km/h                24
Visibility_km                11.3
Press_kPa                  100.51
Weather                      Snow
Name: 128, dtype: object
Inserting row 130
Error inserting row 130: tuple index out of range
Row data: Date/Time           1/6/2012 9:00
Temp_C                      -12.5
Dew Point Temp_C            -16.7
Rel Hum_%                      71
Wind Speed_km/h                26
Visibility_km                19.3
Press_kPa                  100.53
Weather                      Snow
Name: 129, dtype: object
Inserting row 131
Error inserting row 131: tuple index out of range
Row data: Date/Time           1/6/2012 10:00
Temp_C                       -12.3
Dew Point Temp_C             -16.3
Rel Hum_%                       72
Wind Speed_km/h                 28
Visibility_km                 16.1
Press_kPa                   100.47
Weather                       Snow
Name: 130, dtype: object
Inserting row 132
Error inserting row 132: tuple index out of range
Row data: Date/Time           1/6/2012 11:00
Temp_C                       -12.0
Dew Point Temp_C             -16.0
Rel Hum_%                       72
Wind Speed_km/h                 17
Visibility_km                 24.1
Press_kPa                   100.36
Weather                       Snow
Name: 131, dtype: object
Inserting row 133
Error inserting row 133: tuple index out of range
Row data: Date/Time           1/6/2012 12:00
Temp_C                       -11.7
Dew Point Temp_C             -15.4
Rel Hum_%                       74
Wind Speed_km/h                 28
Visibility_km                 19.3
Press_kPa                   100.23
Weather                       Snow
Name: 132, dtype: object
Inserting row 134
Error inserting row 134: tuple index out of range
Row data: Date/Time           1/6/2012 13:00
Temp_C                       -11.9
Dew Point Temp_C             -15.6
Rel Hum_%                       74
Wind Speed_km/h                 20
Visibility_km                 24.1
Press_kPa                   100.13
Weather                       Snow
Name: 133, dtype: object
Inserting row 135
Error inserting row 135: tuple index out of range
Row data: Date/Time           1/6/2012 14:00
Temp_C                       -11.2
Dew Point Temp_C             -14.8
Rel Hum_%                       75
Wind Speed_km/h                 19
Visibility_km                 19.3
Press_kPa                   100.07
Weather                       Snow
Name: 134, dtype: object
Inserting row 136
Error inserting row 136: tuple index out of range
Row data: Date/Time           1/6/2012 15:00
Temp_C                       -11.5
Dew Point Temp_C             -14.4
Rel Hum_%                       79
Wind Speed_km/h                 19
Visibility_km                 12.9
Press_kPa                   100.06
Weather                       Snow
Name: 135, dtype: object
Inserting row 137
Error inserting row 137: tuple index out of range
Row data: Date/Time           1/6/2012 16:00
Temp_C                       -11.6
Dew Point Temp_C             -14.7
Rel Hum_%                       78
Wind Speed_km/h                 19
Visibility_km                 19.3
Press_kPa                    100.1
Weather                       Snow
Name: 136, dtype: object
Inserting row 138
Error inserting row 138: tuple index out of range
Row data: Date/Time           1/6/2012 17:00
Temp_C                       -11.2
Dew Point Temp_C             -14.3
Rel Hum_%                       78
Wind Speed_km/h                 17
Visibility_km                 25.0
Press_kPa                   100.15
Weather                       Snow
Name: 137, dtype: object
Inserting row 139
Error inserting row 139: tuple index out of range
Row data: Date/Time           1/6/2012 18:00
Temp_C                       -10.5
Dew Point Temp_C             -13.6
Rel Hum_%                       78
Wind Speed_km/h                 17
Visibility_km                 19.3
Press_kPa                   100.12
Weather                     Cloudy
Name: 138, dtype: object
Inserting row 140
Error inserting row 140: tuple index out of range
Row data: Date/Time           1/6/2012 19:00
Temp_C                       -10.5
Dew Point Temp_C             -13.4
Rel Hum_%                       79
Wind Speed_km/h                 15
Visibility_km                 25.0
Press_kPa                   100.13
Weather                     Cloudy
Name: 139, dtype: object
Inserting row 141
Error inserting row 141: tuple index out of range
Row data: Date/Time           1/6/2012 20:00
Temp_C                       -10.2
Dew Point Temp_C             -13.0
Rel Hum_%                       80
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   100.15
Weather                     Cloudy
Name: 140, dtype: object
Inserting row 142
Error inserting row 142: tuple index out of range
Row data: Date/Time           1/6/2012 21:00
Temp_C                        -9.5
Dew Point Temp_C             -12.5
Rel Hum_%                       79
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                   100.13
Weather                     Cloudy
Name: 141, dtype: object
Inserting row 143
Error inserting row 143: tuple index out of range
Row data: Date/Time           1/6/2012 22:00
Temp_C                        -9.3
Dew Point Temp_C             -12.2
Rel Hum_%                       79
Wind Speed_km/h                 11
Visibility_km                 19.3
Press_kPa                   100.16
Weather                     Cloudy
Name: 142, dtype: object
Inserting row 144
Error inserting row 144: tuple index out of range
Row data: Date/Time           1/6/2012 23:00
Temp_C                        -9.0
Dew Point Temp_C             -12.0
Rel Hum_%                       79
Wind Speed_km/h                  7
Visibility_km                 16.1
Press_kPa                   100.15
Weather                     Cloudy
Name: 143, dtype: object
Inserting row 145
Error inserting row 145: tuple index out of range
Row data: Date/Time           1/7/2012 0:00
Temp_C                       -8.7
Dew Point Temp_C            -11.7
Rel Hum_%                      79
Wind Speed_km/h                 6
Visibility_km                16.1
Press_kPa                  100.13
Weather                    Cloudy
Name: 144, dtype: object
Inserting row 146
Error inserting row 146: tuple index out of range
Row data: Date/Time           1/7/2012 1:00
Temp_C                       -8.5
Dew Point Temp_C            -11.4
Rel Hum_%                      80
Wind Speed_km/h                 0
Visibility_km                19.3
Press_kPa                  100.11
Weather                    Cloudy
Name: 145, dtype: object
Inserting row 147
Error inserting row 147: tuple index out of range
Row data: Date/Time           1/7/2012 2:00
Temp_C                       -8.1
Dew Point Temp_C            -11.1
Rel Hum_%                      79
Wind Speed_km/h                 4
Visibility_km                19.3
Press_kPa                  100.15
Weather                    Cloudy
Name: 146, dtype: object
Inserting row 148
Error inserting row 148: tuple index out of range
Row data: Date/Time           1/7/2012 3:00
Temp_C                       -7.8
Dew Point Temp_C            -10.8
Rel Hum_%                      79
Wind Speed_km/h                 4
Visibility_km                19.3
Press_kPa                  100.12
Weather                    Cloudy
Name: 147, dtype: object
Inserting row 149
Error inserting row 149: tuple index out of range
Row data: Date/Time           1/7/2012 4:00
Temp_C                       -7.5
Dew Point Temp_C            -10.5
Rel Hum_%                      79
Wind Speed_km/h                 6
Visibility_km                19.3
Press_kPa                   100.1
Weather                    Cloudy
Name: 148, dtype: object
Inserting row 150
Error inserting row 150: tuple index out of range
Row data: Date/Time           1/7/2012 5:00
Temp_C                       -6.9
Dew Point Temp_C             -9.7
Rel Hum_%                      80
Wind Speed_km/h                 4
Visibility_km                19.3
Press_kPa                  100.12
Weather                    Cloudy
Name: 149, dtype: object
Inserting row 151
Error inserting row 151: tuple index out of range
Row data: Date/Time           1/7/2012 6:00
Temp_C                       -6.7
Dew Point Temp_C             -9.5
Rel Hum_%                      80
Wind Speed_km/h                 7
Visibility_km                16.1
Press_kPa                  100.12
Weather                    Cloudy
Name: 150, dtype: object
Inserting row 152
Error inserting row 152: tuple index out of range
Row data: Date/Time           1/7/2012 7:00
Temp_C                       -7.0
Dew Point Temp_C             -9.7
Rel Hum_%                      81
Wind Speed_km/h                 7
Visibility_km                16.1
Press_kPa                  100.16
Weather                    Cloudy
Name: 151, dtype: object
Inserting row 153
Error inserting row 153: tuple index out of range
Row data: Date/Time                  1/7/2012 8:00
Temp_C                              -6.4
Dew Point Temp_C                    -9.0
Rel Hum_%                             82
Wind Speed_km/h                        9
Visibility_km                        8.0
Press_kPa                          100.1
Weather             Freezing Drizzle,Fog
Name: 152, dtype: object
Inserting row 154
Error inserting row 154: tuple index out of range
Row data: Date/Time               1/7/2012 9:00
Temp_C                           -6.1
Dew Point Temp_C                 -8.7
Rel Hum_%                          82
Wind Speed_km/h                     7
Visibility_km                     9.7
Press_kPa                      100.15
Weather             Freezing Rain,Fog
Name: 153, dtype: object
Inserting row 155
Error inserting row 155: tuple index out of range
Row data: Date/Time           1/7/2012 10:00
Temp_C                        -5.7
Dew Point Temp_C              -8.0
Rel Hum_%                       84
Wind Speed_km/h                  7
Visibility_km                  8.0
Press_kPa                   100.13
Weather              Freezing Rain
Name: 154, dtype: object
Inserting row 156
Error inserting row 156: tuple index out of range
Row data: Date/Time             1/7/2012 11:00
Temp_C                          -5.4
Dew Point Temp_C                -7.7
Rel Hum_%                         84
Wind Speed_km/h                    9
Visibility_km                    9.7
Press_kPa                     100.08
Weather             Freezing Drizzle
Name: 155, dtype: object
Inserting row 157
Error inserting row 157: tuple index out of range
Row data: Date/Time             1/7/2012 12:00
Temp_C                          -5.5
Dew Point Temp_C                -7.8
Rel Hum_%                         84
Wind Speed_km/h                   13
Visibility_km                    9.7
Press_kPa                     100.05
Weather             Freezing Drizzle
Name: 156, dtype: object
Inserting row 158
Error inserting row 158: tuple index out of range
Row data: Date/Time           1/7/2012 13:00
Temp_C                        -4.8
Dew Point Temp_C              -7.2

Row data: Date/Time           1/16/2012 1:00
Temp_C                       -17.8
Dew Point Temp_C             -22.7
Rel Hum_%                       65
Wind Speed_km/h                  6
Visibility_km                 25.0
Press_kPa                   103.05
Weather                      Clear
Name: 361, dtype: object
Inserting row 363
Error inserting row 363: tuple index out of range
Row data: Date/Time           1/16/2012 2:00
Temp_C                       -18.5
Dew Point Temp_C             -23.0
Rel Hum_%                       68
Wind Speed_km/h                  6
Visibility_km                 25.0
Press_kPa                   103.08
Weather                      Clear
Name: 362, dtype: object
Inserting row 364
Error inserting row 364: tuple index out of range
Row data: Date/Time           1/16/2012 3:00
Temp_C                       -19.2
Dew Point Temp_C             -23.8
Rel Hum_%                       67
Wind Speed_km/h                  6
Visibility_km                 25.0
Press_kPa                   103.07
Weather                      Clear
Name: 363, dtype: object
Inserting row 365
Error inserting row 365: tuple index out of range
Row data: Date/Time           1/16/2012 4:00
Temp_C                       -18.7
Dew Point Temp_C             -23.5
Rel Hum_%                       66
Wind Speed_km/h                  0
Visibility_km                 25.0
Press_kPa                   103.05
Weather                      Clear
Name: 364, dtype: object
Inserting row 366
Error inserting row 366: tuple index out of range
Row data: Date/Time           1/16/2012 5:00
Temp_C                       -19.1
Dew Point Temp_C             -23.3
Rel Hum_%                       69
Wind Speed_km/h                  0
Visibility_km                 25.0
Press_kPa                   103.02
Weather                      Clear
Name: 365, dtype: object
Inserting row 367
Error inserting row 367: tuple index out of range
Row data: Date/Time           1/16/2012 6:00
Temp_C                       -18.7
Dew Point Temp_C             -23.2
Rel Hum_%                       68
Wind Speed_km/h                  0
Visibility_km                 25.0
Press_kPa                   103.01
Weather                      Clear
Name: 366, dtype: object
Inserting row 368
Error inserting row 368: tuple index out of range
Row data: Date/Time           1/16/2012 7:00
Temp_C                       -17.9
Dew Point Temp_C             -21.5
Rel Hum_%                       73
Wind Speed_km/h                  4
Visibility_km                 48.3
Press_kPa                   102.96
Weather               Mainly Clear
Name: 367, dtype: object
Inserting row 369
Error inserting row 369: tuple index out of range
Row data: Date/Time           1/16/2012 8:00
Temp_C                       -17.9
Dew Point Temp_C             -22.6
Rel Hum_%                       67
Wind Speed_km/h                  9
Visibility_km                 48.3
Press_kPa                    102.9
Weather              Mostly Cloudy
Name: 368, dtype: object
Inserting row 370
Error inserting row 370: tuple index out of range
Row data: Date/Time           1/16/2012 9:00
Temp_C                       -14.4
Dew Point Temp_C             -20.7
Rel Hum_%                       59
Wind Speed_km/h                 22
Visibility_km                 48.3
Press_kPa                   102.75
Weather                     Cloudy
Name: 369, dtype: object
Inserting row 371
Error inserting row 371: tuple index out of range
Row data: Date/Time           1/16/2012 10:00
Temp_C                        -13.6
Dew Point Temp_C              -18.7
Rel Hum_%                        65
Wind Speed_km/h                  19
Visibility_km                  48.3
Press_kPa                    102.62
Weather               Mostly Cloudy
Name: 370, dtype: object
Inserting row 372
Error inserting row 372: tuple index out of range
Row data: Date/Time           1/16/2012 11:00
Temp_C                        -12.7
Dew Point Temp_C              -17.7
Rel Hum_%                        66
Wind Speed_km/h                  20
Visibility_km                  48.3
Press_kPa                    102.44
Weather               Mostly Cloudy
Name: 371, dtype: object
Inserting row 373
Error inserting row 373: tuple index out of range
Row data: Date/Time           1/16/2012 12:00
Temp_C                        -10.7
Dew Point Temp_C              -16.9
Rel Hum_%                        60
Wind Speed_km/h                  19
Visibility_km                  48.3
Press_kPa                    102.17
Weather               Mostly Cloudy
Name: 372, dtype: object
Inserting row 374
Error inserting row 374: tuple index out of range
Row data: Date/Time           1/16/2012 13:00
Temp_C                        -10.1
Dew Point Temp_C              -16.1
Rel Hum_%                        61
Wind Speed_km/h                  13
Visibility_km                  48.3
Press_kPa                    101.92
Weather                      Cloudy
Name: 373, dtype: object
Inserting row 375
Error inserting row 375: tuple index out of range
Row data: Date/Time           1/16/2012 14:00
Temp_C                         -9.0
Dew Point Temp_C              -13.8
Rel Hum_%                        68
Wind Speed_km/h                  13
Visibility_km                  48.3
Press_kPa                    101.71
Weather               Mostly Cloudy
Name: 374, dtype: object
Inserting row 376
Error inserting row 376: tuple index out of range
Row data: Date/Time           1/16/2012 15:00
Temp_C                         -8.0
Dew Point Temp_C              -13.8
Rel Hum_%                        63
Wind Speed_km/h                  17
Visibility_km                  48.3
Press_kPa                    101.49
Weather                      Cloudy
Name: 375, dtype: object
Inserting row 377
Error inserting row 377: tuple index out of range
Row data: Date/Time           1/16/2012 16:00
Temp_C                         -7.1
Dew Point Temp_C              -14.1
Rel Hum_%                        57
Wind Speed_km/h                   9
Visibility_km                  48.3
Press_kPa                    101.41
Weather                      Cloudy
Name: 376, dtype: object
Inserting row 378
Error inserting row 378: tuple index out of range
Row data: Date/Time           1/16/2012 17:00
Temp_C                         -7.6
Dew Point Temp_C              -14.8
Rel Hum_%                        56
Wind Speed_km/h                   4
Visibility_km                  25.0
Press_kPa                    101.34
Weather               Mostly Cloudy
Name: 377, dtype: object
Inserting row 379
Error inserting row 379: tuple index out of range
Row data: Date/Time           1/16/2012 18:00
Temp_C                        -12.5
Dew Point Temp_C              -17.5
Rel Hum_%                        66
Wind Speed_km/h                  15
Visibility_km                  25.0
Press_kPa                    101.31
Weather                Mainly Clear
Name: 378, dtype: object
Inserting row 380
Error inserting row 380: tuple index out of range
Row data: Date/Time           1/16/2012 19:00
Temp_C                        -14.8
Dew Point Temp_C              -19.1
Rel Hum_%                        70
Wind Speed_km/h                  15
Visibility_km                  25.0
Press_kPa                    101.23
Weather                Mainly Clear
Name: 379, dtype: object
Inserting row 381
Error inserting row 381: tuple index out of range
Row data: Date/Time           1/16/2012 20:00
Temp_C                        -14.0
Dew Point Temp_C              -18.3
Rel Hum_%                        70
Wind Speed_km/h                  13
Visibility_km                  25.0
Press_kPa                    101.19
Weather                      Cloudy
Name: 380, dtype: object
Inserting row 382
Error inserting row 382: tuple index out of range
Row data: Date/Time           1/16/2012 21:00
Temp_C                        -12.9
Dew Point Temp_C              -17.1
Rel Hum_%                        71
Wind Speed_km/h                  11
Visibility_km                  25.0
Press_kPa                    101.12
Weather                      Cloudy
Name: 381, dtype: object
Inserting row 383
Error inserting row 383: tuple index out of range
Row data: Date/Time           1/16/2012 22:00
Temp_C                        -12.2
Dew Point Temp_C              -16.5
Rel Hum_%                        70
Wind Speed_km/h                   9
Visibility_km                  25.0
Press_kPa                    101.05
Weather                      Cloudy
Name: 382, dtype: object
Inserting row 384
Error inserting row 384: tuple index out of range
Row data: Date/Time           1/16/2012 23:00
Temp_C                        -11.5
Dew Point Temp_C              -15.7
Rel Hum_%                        71
Wind Speed_km/h                   7
Visibility_km                  25.0
Press_kPa                    100.98
Weather                      Cloudy
Name: 383, dtype: object
Inserting row 385
Error inserting row 385: tuple index out of range
Row data: Date/Time           1/17/2012 0:00
Temp_C                       -10.8
Dew Point Temp_C             -15.0
Rel Hum_%                       71
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                   100.94
Weather                     Cloudy
Name: 384, dtype: object
Inserting row 386
Error inserting row 386: tuple index out of range
Row data: Date/Time           1/17/2012 1:00
Temp_C                       -10.4
Dew Point Temp_C             -14.6
Rel Hum_%                       71
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                   100.88
Weather                     Cloudy
Name: 385, dtype: object
Inserting row 387
Error inserting row 387: tuple index out of range
Row data: Date/Time           1/17/2012 2:00
Temp_C                        -9.7
Dew Point Temp_C             -13.7
Rel Hum_%                       73
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                   100.84
Weather                     Cloudy
Name: 386, dtype: object
Inserting row 388
Error inserting row 388: tuple index out of range
Row data: Date/Time           1/17/2012 3:00
Temp_C                        -9.2
Dew Point Temp_C             -13.2
Rel Hum_%                       73
Wind Speed_km/h                  6
Visibility_km                 25.0
Press_kPa                   100.84
Weather                     Cloudy
Name: 387, dtype: object
Inserting row 389
Error inserting row 389: tuple index out of range
Row data: Date/Time             1/17/2012 4:00
Temp_C                          -9.0
Dew Point Temp_C               -12.2
Rel Hum_%                         78
Wind Speed_km/h                    6
Visibility_km                    6.4
Press_kPa                      100.8
Weather             Freezing Drizzle
Name: 388, dtype: object
Inserting row 390
Error inserting row 390: tuple index out of range
Row data: Date/Time                  1/17/2012 5:00
Temp_C                               -8.3
Dew Point Temp_C                    -10.4
Rel Hum_%                              85
Wind Speed_km/h                         6
Visibility_km                         3.6
Press_kPa                          100.75
Weather             Freezing Drizzle,Snow
Name: 389, dtype: object
Inserting row 391
Error inserting row 391: tuple index out of range
Row data: Date/Time                  1/17/2012 6:00
Temp_C                               -7.7
Dew Point Temp_C                     -9.9
Rel Hum_%                              84
Wind Speed_km/h                         6
Visibility_km                         2.4
Press_kPa                          100.72
Weather             Freezing Drizzle,Snow
Name: 390, dtype: object
Inserting row 392
Error inserting row 392: tuple index out of range
Row data: Date/Time           1/17/2012 7:00
Temp_C                        -7.5
Dew Point Temp_C              -9.6
Rel Hum_%                       85
Wind Speed_km/h                  9
Visibility_km                  2.0
Press_kPa                   100.69
Weather                       Snow
Name: 391, dtype: object
Inserting row 393
Error inserting row 393: tuple index out of range
Row data: Date/Time           1/17/2012 8:00
Temp_C                        -7.4
Dew Point Temp_C              -9.6
Rel Hum_%                       84
Wind Speed_km/h                  9
Visibility_km                  2.4
Press_kPa                   100.65
Weather                       Snow
Name: 392, dtype: object
Inserting row 394
Error inserting row 394: tuple index out of range
Row data: Date/Time           1/17/2012 9:00
Temp_C                        -7.0
Dew Point Temp_C              -9.5
Rel Hum_%                       82
Wind Speed_km/h                 15
Visibility_km                  4.0
Press_kPa                   100.59
Weather                       Snow
Name: 393, dtype: object
Inserting row 395
Error inserting row 395: tuple index out of range
Row data: Date/Time           1/17/2012 10:00
Temp_C                         -6.5
Dew Point Temp_C               -9.0
Rel Hum_%                        82
Wind Speed_km/h                  15
Visibility_km                   1.2
Press_kPa                     100.6
Weather                        Snow
Name: 394, dtype: object
Inserting row 396
Error inserting row 396: tuple index out of range
Row data: Date/Time           1/17/2012 11:00
Temp_C                         -6.1
Dew Point Temp_C               -8.5
Rel Hum_%                        83
Wind Speed_km/h                  15
Visibility_km                   2.4
Press_kPa                    100.53
Weather                        Snow
Name: 395, dtype: object
Inserting row 397
Error inserting row 397: tuple index out of range
Row data: Date/Time           1/17/2012 12:00
Temp_C                         -5.3
Dew Point Temp_C               -7.9
Rel Hum_%                        82
Wind Speed_km/h                  19
Visibility_km                   2.8
Press_kPa                    100.38
Weather                        Snow
Name: 396, dtype: object
Inserting row 398
Error inserting row 398: tuple index out of range
Row data: Date/Time           1/17/2012 13:00
Temp_C                         -5.1
Dew Point Temp_C               -7.7
Rel Hum_%                        82
Wind Speed_km/h                  22
Visibility_km                   2.4
Press_kPa                    100.23
Weather                        Snow
Name: 397, dtype: object
Inserting row 399
Error inserting row 399: tuple index out of range
Row data: Date/Time           1/17/2012 14:00
Temp_C                         -4.3
Dew Point Temp_C               -6.5
Rel Hum_%                        85
Wind Speed_km/h                  22
Visibility_km                   1.6
Press_kPa                    100.05
Weather                        Snow
Name: 398, dtype: object
Inserting row 400
Error inserting row 400: tuple index out of range
Row data: Date/Time           1/17/2012 15:00
Temp_C                         -3.7
Dew Point Temp_C               -6.0
Rel Hum_%                        84
Wind Speed_km/h                  24
Visibility_km                   1.2
Press_kPa                      99.9
Weather                        Snow
Name: 399, dtype: object
Inserting row 401
Error inserting row 401: tuple index out of range
Row data: Date/Time           1/17/2012 16:00
Temp_C                         -3.5
Dew Point Temp_C               -6.0
Rel Hum_%                        83
Wind Speed_km/h                  28
Visibility_km                   1.2
Press_kPa                     99.69
Weather                        Snow
Name: 400, dtype: object
Inserting row 402
Error inserting row 402: tuple index out of range
Row data: Date/Time           1/17/2012 17:00
Temp_C                         -3.6
Dew Point Temp_C               -5.9
Rel Hum_%                        84
Wind Speed_km/h                  22
Visibility_km                   1.6
Press_kPa                     99.57
Weather                        Snow
Name: 401, dtype: object
Inserting row 403
Error inserting row 403: tuple index out of range
Row data: Date/Time           1/17/2012 18:00
Temp_C                         -3.5
Dew Point Temp_C               -5.8
Rel Hum_%                        84
Wind Speed_km/h                  22
Visibility_km                   2.4
Press_kPa                     99.38
Weather                        Snow
Name: 402, dtype: object
Inserting row 404
Error inserting row 404: tuple index out of range
Row data: Date/Time                 1/17/2012 19:00
Temp_C                               -3.3
Dew Point Temp_C                     -5.6
Rel Hum_%                              84
Wind Speed_km/h                        24
Visibility_km                         4.8
Press_kPa                           99.22
Weather             Freezing Drizzle,Snow
Name: 403, dtype: object
Inserting row 405
Error inserting row 405: tuple index out of range
Row data: Date/Time           1/17/2012 20:00
Temp_C                         -3.6
Dew Point Temp_C               -5.7
Rel Hum_%                        85
Wind Speed_km/h                  24
Visibility_km                   3.2
Press_kPa                     98.98
Weather               Freezing Rain
Name: 404, dtype: object
Inserting row 406
Error inserting row 406: tuple index out of range
Row data: Date/Time           1/17/2012 21:00
Temp_C                         -2.9
Dew Point Temp_C               -4.9
Rel Hum_%                        86
Wind Speed_km/h                  26
Visibility_km                   2.8
Press_kPa                     98.71
Weather               Freezing Rain
Name: 405, dtype: object
Inserting row 407
Error inserting row 407: tuple index out of range
Row data: Date/Time           1/17/2012 22:00
Temp_C                         -1.6
Dew Point Temp_C               -3.2
Rel Hum_%                        89
Wind Speed_km/h                  17
Visibility_km                   3.2
Press_kPa                     98.47
Weather               Freezing Rain
Name: 406, dtype: object
Inserting row 408
Error inserting row 408: tuple index out of range
Row data: Date/Time             1/17/2012 23:00
Temp_C                           -0.6
Dew Point Temp_C                 -2.1
Rel Hum_%                          90
Wind Speed_km/h                     7
Visibility_km                     2.8
Press_kPa                       98.32
Weather             Freezing Rain,Fog
Name: 407, dtype: object
Inserting row 409
Error inserting row 409: tuple index out of range
Row data: Date/Time           1/18/2012 0:00
Temp_C                         2.1
Dew Point Temp_C               0.7
Rel Hum_%                       90
Wind Speed_km/h                 11
Visibility_km                  8.0
Press_kPa                    98.31
Weather                        Fog
Name: 408, dtype: object
Inserting row 410
Error inserting row 410: tuple index out of range
Row data: Date/Time           1/18/2012 1:00
Temp_C                         3.7
Dew Point Temp_C              -2.1
Rel Hum_%                       66
Wind Speed_km/h                 83
Visibility_km                 25.0
Press_kPa                    98.36
Weather              Mostly Cloudy
Name: 409, dtype: object
Inserting row 411
Error inserting row 411: tuple index out of range
Row data: Date/Time           1/18/2012 2:00
Temp_C                         0.5
Dew Point Temp_C              -4.0
Rel Hum_%                       72
Wind Speed_km/h                 70
Visibility_km                 25.0
Press_kPa                    98.62
Weather              Mostly Cloudy
Name: 410, dtype: object
Inserting row 412
Error inserting row 412: tuple index out of range
Row data: Date/Time           1/18/2012 3:00
Temp_C                        -3.5
Dew Point Temp_C              -8.2
Rel Hum_%                       70
Wind Speed_km/h                 57
Visibility_km                 25.0
Press_kPa                     99.0
Weather              Mostly Cloudy
Name: 411, dtype: object
Inserting row 413
Error inserting row 413: tuple index out of range
Row data: Date/Time           1/18/2012 4:00

Row data: Date/Time           1/26/2012 20:00
Temp_C                         -4.6
Dew Point Temp_C              -13.0
Rel Hum_%                        52
Wind Speed_km/h                  17
Visibility_km                  25.0
Press_kPa                    101.15
Weather                Snow Showers
Name: 620, dtype: object
Inserting row 622
Error inserting row 622: tuple index out of range
Row data: Date/Time           1/26/2012 21:00
Temp_C                         -5.2
Dew Point Temp_C              -12.1
Rel Hum_%                        58
Wind Speed_km/h                  20
Visibility_km                  25.0
Press_kPa                    100.99
Weather                        Snow
Name: 621, dtype: object
Inserting row 623
Error inserting row 623: tuple index out of range
Row data: Date/Time           1/26/2012 22:00
Temp_C                         -5.3
Dew Point Temp_C              -10.2
Rel Hum_%                        68
Wind Speed_km/h                  22
Visibility_km                  16.1
Press_kPa                    100.92
Weather                        Snow
Name: 622, dtype: object
Inserting row 624
Error inserting row 624: tuple index out of range
Row data: Date/Time           1/26/2012 23:00
Temp_C                         -5.8
Dew Point Temp_C               -9.1
Rel Hum_%                        77
Wind Speed_km/h                  22
Visibility_km                   6.4
Press_kPa                    100.81
Weather                        Snow
Name: 623, dtype: object
Inserting row 625
Error inserting row 625: tuple index out of range
Row data: Date/Time           1/27/2012 0:00
Temp_C                        -5.7
Dew Point Temp_C              -8.8
Rel Hum_%                       79
Wind Speed_km/h                 28
Visibility_km                  4.8
Press_kPa                   100.68
Weather                       Snow
Name: 624, dtype: object
Inserting row 626
Error inserting row 626: tuple index out of range
Row data: Date/Time           1/27/2012 1:00
Temp_C                        -5.5
Dew Point Temp_C              -8.3
Rel Hum_%                       81
Wind Speed_km/h                 24
Visibility_km                  2.4
Press_kPa                   100.58
Weather                       Snow
Name: 625, dtype: object
Inserting row 627
Error inserting row 627: tuple index out of range
Row data: Date/Time           1/27/2012 2:00
Temp_C                        -5.5
Dew Point Temp_C              -8.2
Rel Hum_%                       81
Wind Speed_km/h                 26
Visibility_km                  3.2
Press_kPa                   100.47
Weather                       Snow
Name: 626, dtype: object
Inserting row 628
Error inserting row 628: tuple index out of range
Row data: Date/Time           1/27/2012 3:00
Temp_C                        -5.3
Dew Point Temp_C              -8.1
Rel Hum_%                       81
Wind Speed_km/h                 28
Visibility_km                  4.0
Press_kPa                   100.33
Weather                       Snow
Name: 627, dtype: object
Inserting row 629
Error inserting row 629: tuple index out of range
Row data: Date/Time           1/27/2012 4:00
Temp_C                        -4.9
Dew Point Temp_C              -7.6
Rel Hum_%                       81
Wind Speed_km/h                 26
Visibility_km                  2.4
Press_kPa                   100.13
Weather                       Snow
Name: 628, dtype: object
Inserting row 630
Error inserting row 630: tuple index out of range
Row data: Date/Time           1/27/2012 5:00
Temp_C                        -4.0
Dew Point Temp_C              -6.6
Rel Hum_%                       82
Wind Speed_km/h                 22
Visibility_km                 16.1
Press_kPa                    99.98
Weather                       Snow
Name: 629, dtype: object
Inserting row 631
Error inserting row 631: tuple index out of range
Row data: Date/Time           1/27/2012 6:00
Temp_C                        -2.1
Dew Point Temp_C              -4.2
Rel Hum_%                       86
Wind Speed_km/h                 19
Visibility_km                 19.3
Press_kPa                     99.8
Weather                       Snow
Name: 630, dtype: object
Inserting row 632
Error inserting row 632: tuple index out of range
Row data: Date/Time           1/27/2012 7:00
Temp_C                        -0.8
Dew Point Temp_C              -2.9
Rel Hum_%                       86
Wind Speed_km/h                 22
Visibility_km                 16.1
Press_kPa                    99.61
Weather              Freezing Rain
Name: 631, dtype: object
Inserting row 633
Error inserting row 633: tuple index out of range
Row data: Date/Time           1/27/2012 8:00
Temp_C                         0.3
Dew Point Temp_C              -1.7
Rel Hum_%                       86
Wind Speed_km/h                 20
Visibility_km                 12.9
Press_kPa                    99.47
Weather              Freezing Rain
Name: 632, dtype: object
Inserting row 634
Error inserting row 634: tuple index out of range
Row data: Date/Time           1/27/2012 9:00
Temp_C                         0.7
Dew Point Temp_C              -1.4
Rel Hum_%                       86
Wind Speed_km/h                 17
Visibility_km                 12.9
Press_kPa                    99.34
Weather                       Rain
Name: 633, dtype: object
Inserting row 635
Error inserting row 635: tuple index out of range
Row data: Date/Time           1/27/2012 10:00
Temp_C                          0.6
Dew Point Temp_C               -1.2
Rel Hum_%                        88
Wind Speed_km/h                  17
Visibility_km                   8.0
Press_kPa                     99.18
Weather                    Rain,Fog
Name: 634, dtype: object
Inserting row 636
Error inserting row 636: tuple index out of range
Row data: Date/Time           1/27/2012 11:00
Temp_C                          0.7
Dew Point Temp_C               -1.0
Rel Hum_%                        88
Wind Speed_km/h                  20
Visibility_km                   2.4
Press_kPa                     99.08
Weather                 Drizzle,Fog
Name: 635, dtype: object
Inserting row 637
Error inserting row 637: tuple index out of range
Row data: Date/Time           1/27/2012 12:00
Temp_C                          0.7
Dew Point Temp_C               -0.9
Rel Hum_%                        89
Wind Speed_km/h                  20
Visibility_km                   2.8
Press_kPa                     98.91
Weather                 Drizzle,Fog
Name: 636, dtype: object
Inserting row 638
Error inserting row 638: tuple index out of range
Row data: Date/Time           1/27/2012 13:00
Temp_C                          0.7
Dew Point Temp_C               -1.0
Rel Hum_%                        88
Wind Speed_km/h                  22
Visibility_km                   3.2
Press_kPa                     98.76
Weather                 Drizzle,Fog
Name: 637, dtype: object
Inserting row 639
Error inserting row 639: tuple index out of range
Row data: Date/Time           1/27/2012 14:00
Temp_C                          0.5
Dew Point Temp_C               -1.3
Rel Hum_%                        88
Wind Speed_km/h                  20
Visibility_km                   2.4
Press_kPa                     98.69
Weather                 Drizzle,Fog
Name: 638, dtype: object
Inserting row 640
Error inserting row 640: tuple index out of range
Row data: Date/Time           1/27/2012 15:00
Temp_C                          0.3
Dew Point Temp_C               -1.6
Rel Hum_%                        87
Wind Speed_km/h                  19
Visibility_km                   2.4
Press_kPa                     98.65
Weather                 Drizzle,Fog
Name: 639, dtype: object
Inserting row 641
Error inserting row 641: tuple index out of range
Row data: Date/Time                1/27/2012 16:00
Temp_C                              -0.3
Dew Point Temp_C                    -2.3
Rel Hum_%                             86
Wind Speed_km/h                       19
Visibility_km                        8.0
Press_kPa                          98.74
Weather             Freezing Drizzle,Fog
Name: 640, dtype: object
Inserting row 642
Error inserting row 642: tuple index out of range
Row data: Date/Time           1/27/2012 17:00
Temp_C                         -0.6
Dew Point Temp_C               -2.3
Rel Hum_%                        88
Wind Speed_km/h                  22
Visibility_km                   2.8
Press_kPa                     98.97
Weather                        Snow
Name: 641, dtype: object
Inserting row 643
Error inserting row 643: tuple index out of range
Row data: Date/Time           1/27/2012 18:00
Temp_C                         -0.3
Dew Point Temp_C               -1.8
Rel Hum_%                        90
Wind Speed_km/h                  11
Visibility_km                   2.4
Press_kPa                     99.13
Weather                        Snow
Name: 642, dtype: object
Inserting row 644
Error inserting row 644: tuple index out of range
Row data: Date/Time           1/27/2012 19:00
Temp_C                          0.1
Dew Point Temp_C               -1.6
Rel Hum_%                        88
Wind Speed_km/h                  30
Visibility_km                  12.9
Press_kPa                     99.31
Weather                        Snow
Name: 643, dtype: object
Inserting row 645
Error inserting row 645: tuple index out of range
Row data: Date/Time           1/27/2012 20:00
Temp_C                         -0.7
Dew Point Temp_C               -2.7
Rel Hum_%                        86
Wind Speed_km/h                  32
Visibility_km                  16.1
Press_kPa                     99.54
Weather                      Cloudy
Name: 644, dtype: object
Inserting row 646
Error inserting row 646: tuple index out of range
Row data: Date/Time           1/27/2012 21:00
Temp_C                         -1.3
Dew Point Temp_C               -3.9
Rel Hum_%                        82
Wind Speed_km/h                  19
Visibility_km                  24.1
Press_kPa                     99.75
Weather                      Cloudy
Name: 645, dtype: object
Inserting row 647
Error inserting row 647: tuple index out of range
Row data: Date/Time           1/27/2012 22:00
Temp_C                         -1.5
Dew Point Temp_C               -4.4
Rel Hum_%                        81
Wind Speed_km/h                  19
Visibility_km                  25.0
Press_kPa                     99.88
Weather               Mostly Cloudy
Name: 646, dtype: object
Inserting row 648
Error inserting row 648: tuple index out of range
Row data: Date/Time           1/27/2012 23:00
Temp_C                         -1.6
Dew Point Temp_C               -4.5
Rel Hum_%                        81
Wind Speed_km/h                  20
Visibility_km                  25.0
Press_kPa                    100.03
Weather                Mainly Clear
Name: 647, dtype: object
Inserting row 649
Error inserting row 649: tuple index out of range
Row data: Date/Time           1/28/2012 0:00
Temp_C                        -1.5
Dew Point Temp_C              -4.3
Rel Hum_%                       81
Wind Speed_km/h                 19
Visibility_km                 25.0
Press_kPa                   100.19
Weather               Mainly Clear
Name: 648, dtype: object
Inserting row 650
Error inserting row 650: tuple index out of range
Row data: Date/Time           1/28/2012 1:00
Temp_C                        -0.2
Dew Point Temp_C              -2.9
Rel Hum_%                       82
Wind Speed_km/h                 22
Visibility_km                 25.0
Press_kPa                   100.34
Weather               Snow Showers
Name: 649, dtype: object
Inserting row 651
Error inserting row 651: tuple index out of range
Row data: Date/Time           1/28/2012 2:00
Temp_C                         0.2
Dew Point Temp_C              -2.6
Rel Hum_%                       81
Wind Speed_km/h                 24
Visibility_km                 25.0
Press_kPa                   100.49
Weather              Mostly Cloudy
Name: 650, dtype: object
Inserting row 652
Error inserting row 652: tuple index out of range
Row data: Date/Time           1/28/2012 3:00
Temp_C                         0.4
Dew Point Temp_C              -3.0
Rel Hum_%                       78
Wind Speed_km/h                 17
Visibility_km                 25.0
Press_kPa                   100.59
Weather              Mostly Cloudy
Name: 651, dtype: object
Inserting row 653
Error inserting row 653: tuple index out of range
Row data: Date/Time           1/28/2012 4:00
Temp_C                         0.1
Dew Point Temp_C              -3.4
Rel Hum_%                       77
Wind Speed_km/h                 15
Visibility_km                 25.0
Press_kPa                   100.64
Weather              Mostly Cloudy
Name: 652, dtype: object
Inserting row 654
Error inserting row 654: tuple index out of range
Row data: Date/Time           1/28/2012 5:00
Temp_C                         0.3
Dew Point Temp_C              -2.7
Rel Hum_%                       80
Wind Speed_km/h                 19
Visibility_km                 25.0
Press_kPa                   100.72
Weather              Mostly Cloudy
Name: 653, dtype: object
Inserting row 655
Error inserting row 655: tuple index out of range
Row data: Date/Time           1/28/2012 6:00
Temp_C                        -1.7
Dew Point Temp_C              -5.4
Rel Hum_%                       76
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                   100.79
Weather              Mostly Cloudy
Name: 654, dtype: object
Inserting row 656
Error inserting row 656: tuple index out of range
Row data: Date/Time           1/28/2012 7:00
Temp_C                        -1.2
Dew Point Temp_C              -4.6
Rel Hum_%                       78
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   100.85
Weather               Mainly Clear
Name: 655, dtype: object
Inserting row 657
Error inserting row 657: tuple index out of range
Row data: Date/Time           1/28/2012 8:00
Temp_C                        -2.1
Dew Point Temp_C              -5.1
Rel Hum_%                       80
Wind Speed_km/h                  7
Visibility_km                 48.3
Press_kPa                   100.91
Weather               Mainly Clear
Name: 656, dtype: object
Inserting row 658
Error inserting row 658: tuple index out of range
Row data: Date/Time           1/28/2012 9:00
Temp_C                        -1.6
Dew Point Temp_C              -4.5
Rel Hum_%                       81
Wind Speed_km/h                 13
Visibility_km                 24.1
Press_kPa                   100.93
Weather              Mostly Cloudy
Name: 657, dtype: object
Inserting row 659
Error inserting row 659: tuple index out of range
Row data: Date/Time           1/28/2012 10:00
Temp_C                         -1.1
Dew Point Temp_C               -4.4
Rel Hum_%                        78
Wind Speed_km/h                  13
Visibility_km                  48.3
Press_kPa                    100.94
Weather                      Cloudy
Name: 658, dtype: object
Inserting row 660
Error inserting row 660: tuple index out of range
Row data: Date/Time           1/28/2012 11:00
Temp_C                         -0.6
Dew Point Temp_C               -3.6
Rel Hum_%                        80
Wind Speed_km/h                   6
Visibility_km                  48.3
Press_kPa                     100.9
Weather                      Cloudy
Name: 659, dtype: object
Inserting row 661
Error inserting row 661: tuple index out of range
Row data: Date/Time           1/28/2012 12:00
Temp_C                         -0.3
Dew Point Temp_C               -3.4
Rel Hum_%                        80
Wind Speed_km/h                   7
Visibility_km                  48.3
Press_kPa                    100.74
Weather               Mostly Cloudy
Name: 660, dtype: object
Inserting row 662
Error inserting row 662: tuple index out of range
Row data: Date/Time           1/28/2012 13:00
Temp_C                          0.9
Dew Point Temp_C               -3.5
Rel Hum_%                        72
Wind Speed_km/h                   4
Visibility_km                  48.3
Press_kPa                    100.58
Weather                      Cloudy
Name: 661, dtype: object
Inserting row 663
Error inserting row 663: tuple index out of range
Row data: Date/Time           1/28/2012 14:00
Temp_C                          1.2
Dew Point Temp_C               -3.5
Rel Hum_%                        71
Wind Speed_km/h                   9
Visibility_km                  48.3
Press_kPa                    100.48
Weather                      Cloudy
Name: 662, dtype: object
Inserting row 664
Error inserting row 664: tuple index out of range
Row data: Date/Time           1/28/2012 15:00
Temp_C                          1.2
Dew Point Temp_C               -3.7
Rel Hum_%                        70
Wind Speed_km/h                  15
Visibility_km                  48.3
Press_kPa                    100.28
Weather                      Cloudy
Name: 663, dtype: object
Inserting row 665
Error inserting row 665: tuple index out of range
Row data: Date/Time           1/28/2012 16:00
Temp_C                          1.4
Dew Point Temp_C               -3.7
Rel Hum_%                        69
Wind Speed_km/h                  22
Visibility_km                  48.3
Press_kPa                    100.14
Weather                      Cloudy
Name: 664, dtype: object
Inserting row 666
Error inserting row 666: tuple index out of range
Row data: Date/Time           1/28/2012 17:00
Temp_C                          1.2
Dew Point Temp_C               -3.5
Rel Hum_%                        71
Wind Speed_km/h                  11
Visibility_km                  48.3
Press_kPa                    100.16
Weather                      Cloudy
Name: 665, dtype: object
Inserting row 667
Error inserting row 667: tuple index out of range
Row data: Date/Time           1/28/2012 18:00
Temp_C                          1.6
Dew Point Temp_C               -3.4
Rel Hum_%                        69
Wind Speed_km/h                   9
Visibility_km                  25.0
Press_kPa                    100.08
Weather                      Cloudy
Name: 666, dtype: object
Inserting row 668
Error inserting row 668: tuple index out of range
Row data: Date/Time           1/28/2012 19:00
Temp_C                          2.2
Dew Point Temp_C               -2.6
Rel Hum_%                        71
Wind Speed_km/h                  19
Visibility_km                  19.3
Press_kPa                    100.09
Weather                        Snow
Name: 667, dtype: object
Inserting row 669
Error inserting row 669: tuple index out of range
Row data: Date/Time           1/28/2012 20:00
Temp_C                          1.7
Dew Point Temp_C               -1.2
Rel Hum_%                        81
Wind Speed_km/h                  24
Visibility_km                  19.3
Press_kPa                    100.05
Weather                        Snow
Name: 668, dtype: object
Inserting row 670
Error inserting row 670: tuple index out of range
Row data: Date/Time           1/28/2012 21:00
Temp_C                          2.1
Dew Point Temp_C               -1.7
Rel Hum_%                        76
Wind Speed_km/h                  24
Visibility_km                  25.0
Press_kPa                     99.95
Weather                Mainly Clear
Name: 669, dtype: object
Inserting row 671
Error inserting row 671: tuple index out of range
Row data: Date/Time           1/28/2012 22:00
Temp_C                          2.3
Dew Point Temp_C               -2.0
Rel Hum_%                        73
Wind Speed_km/h                  37
Visibility_km                  25.0
Press_kPa                     99.85
Weather               Mostly Cloudy
Name: 670, dtype: object
Inserting row 672
Error inserting row 672: tuple index out of range
Row data: Date/Time           1/28/2012 23:00
Temp_C                          1.2
Dew Point Temp_C               -1.7
Rel Hum_%                        81

Row data: Date/Time           2/6/2012 11:00
Temp_C                         1.9
Dew Point Temp_C              -2.8
Rel Hum_%                       71
Wind Speed_km/h                 35
Visibility_km                 24.1
Press_kPa                   100.57
Weather                     Cloudy
Name: 875, dtype: object
Inserting row 877
Error inserting row 877: tuple index out of range
Row data: Date/Time           2/6/2012 12:00
Temp_C                         2.6
Dew Point Temp_C              -2.4
Rel Hum_%                       70
Wind Speed_km/h                 22
Visibility_km                 24.1
Press_kPa                    100.5
Weather                     Cloudy
Name: 876, dtype: object
Inserting row 878
Error inserting row 878: tuple index out of range
Row data: Date/Time           2/6/2012 13:00
Temp_C                         2.6
Dew Point Temp_C              -2.9
Rel Hum_%                       67
Wind Speed_km/h                 32
Visibility_km                 24.1
Press_kPa                   100.47
Weather                     Cloudy
Name: 877, dtype: object
Inserting row 879
Error inserting row 879: tuple index out of range
Row data: Date/Time           2/6/2012 14:00
Temp_C                         3.0
Dew Point Temp_C              -3.3
Rel Hum_%                       63
Wind Speed_km/h                 33
Visibility_km                 24.1
Press_kPa                   100.45
Weather              Mostly Cloudy
Name: 878, dtype: object
Inserting row 880
Error inserting row 880: tuple index out of range
Row data: Date/Time           2/6/2012 15:00
Temp_C                         3.3
Dew Point Temp_C              -3.3
Rel Hum_%                       62
Wind Speed_km/h                 30
Visibility_km                 24.1
Press_kPa                   100.46
Weather                     Cloudy
Name: 879, dtype: object
Inserting row 881
Error inserting row 881: tuple index out of range
Row data: Date/Time           2/6/2012 16:00
Temp_C                         3.3
Dew Point Temp_C              -3.1
Rel Hum_%                       63
Wind Speed_km/h                 17
Visibility_km                 24.1
Press_kPa                   100.47
Weather                     Cloudy
Name: 880, dtype: object
Inserting row 882
Error inserting row 882: tuple index out of range
Row data: Date/Time           2/6/2012 17:00
Temp_C                         2.9
Dew Point Temp_C              -2.8
Rel Hum_%                       66
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   100.51
Weather                     Cloudy
Name: 881, dtype: object
Inserting row 883
Error inserting row 883: tuple index out of range
Row data: Date/Time           2/6/2012 18:00
Temp_C                         3.2
Dew Point Temp_C              -2.8
Rel Hum_%                       65
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   100.57
Weather                     Cloudy
Name: 882, dtype: object
Inserting row 884
Error inserting row 884: tuple index out of range
Row data: Date/Time           2/6/2012 19:00
Temp_C                         3.1
Dew Point Temp_C              -2.6
Rel Hum_%                       66
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   100.62
Weather                     Cloudy
Name: 883, dtype: object
Inserting row 885
Error inserting row 885: tuple index out of range
Row data: Date/Time           2/6/2012 20:00
Temp_C                         2.6
Dew Point Temp_C              -2.6
Rel Hum_%                       69
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   100.65
Weather                     Cloudy
Name: 884, dtype: object
Inserting row 886
Error inserting row 886: tuple index out of range
Row data: Date/Time           2/6/2012 21:00
Temp_C                         3.0
Dew Point Temp_C              -2.2
Rel Hum_%                       69
Wind Speed_km/h                 15
Visibility_km                 25.0
Press_kPa                   100.67
Weather                     Cloudy
Name: 885, dtype: object
Inserting row 887
Error inserting row 887: tuple index out of range
Row data: Date/Time           2/6/2012 22:00
Temp_C                         2.7
Dew Point Temp_C              -2.6
Rel Hum_%                       68
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   100.68
Weather              Mostly Cloudy
Name: 886, dtype: object
Inserting row 888
Error inserting row 888: tuple index out of range
Row data: Date/Time           2/6/2012 23:00
Temp_C                         2.2
Dew Point Temp_C              -2.9
Rel Hum_%                       69
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                    100.7
Weather              Mostly Cloudy
Name: 887, dtype: object
Inserting row 889
Error inserting row 889: tuple index out of range
Row data: Date/Time           2/7/2012 0:00
Temp_C                        1.9
Dew Point Temp_C             -3.1
Rel Hum_%                      69
Wind Speed_km/h                13
Visibility_km                25.0
Press_kPa                  100.77
Weather                    Cloudy
Name: 888, dtype: object
Inserting row 890
Error inserting row 890: tuple index out of range
Row data: Date/Time           2/7/2012 1:00
Temp_C                        1.8
Dew Point Temp_C             -3.4
Rel Hum_%                      68
Wind Speed_km/h                15
Visibility_km                25.0
Press_kPa                  100.82
Weather             Mostly Cloudy
Name: 889, dtype: object
Inserting row 891
Error inserting row 891: tuple index out of range
Row data: Date/Time           2/7/2012 2:00
Temp_C                        1.5
Dew Point Temp_C             -4.4
Rel Hum_%                      65
Wind Speed_km/h                15
Visibility_km                25.0
Press_kPa                  100.89
Weather             Mostly Cloudy
Name: 890, dtype: object
Inserting row 892
Error inserting row 892: tuple index out of range
Row data: Date/Time           2/7/2012 3:00
Temp_C                        0.8
Dew Point Temp_C             -5.0
Rel Hum_%                      65
Wind Speed_km/h                19
Visibility_km                25.0
Press_kPa                  100.94
Weather              Snow Showers
Name: 891, dtype: object
Inserting row 893
Error inserting row 893: tuple index out of range
Row data: Date/Time           2/7/2012 4:00
Temp_C                       -1.0
Dew Point Temp_C             -8.3
Rel Hum_%                      58
Wind Speed_km/h                19
Visibility_km                25.0
Press_kPa                  101.03
Weather             Mostly Cloudy
Name: 892, dtype: object
Inserting row 894
Error inserting row 894: tuple index out of range
Row data: Date/Time           2/7/2012 5:00
Temp_C                       -1.9
Dew Point Temp_C             -8.4
Rel Hum_%                      61
Wind Speed_km/h                15
Visibility_km                25.0
Press_kPa                  101.14
Weather              Mainly Clear
Name: 893, dtype: object
Inserting row 895
Error inserting row 895: tuple index out of range
Row data: Date/Time           2/7/2012 6:00
Temp_C                       -2.9
Dew Point Temp_C             -8.8
Rel Hum_%                      64
Wind Speed_km/h                20
Visibility_km                25.0
Press_kPa                  101.27
Weather             Mostly Cloudy
Name: 894, dtype: object
Inserting row 896
Error inserting row 896: tuple index out of range
Row data: Date/Time           2/7/2012 7:00
Temp_C                       -5.5
Dew Point Temp_C            -12.6
Rel Hum_%                      57
Wind Speed_km/h                17
Visibility_km                24.1
Press_kPa                  101.39
Weather              Mainly Clear
Name: 895, dtype: object
Inserting row 897
Error inserting row 897: tuple index out of range
Row data: Date/Time           2/7/2012 8:00
Temp_C                       -6.1
Dew Point Temp_C            -12.8
Rel Hum_%                      59
Wind Speed_km/h                17
Visibility_km                24.1
Press_kPa                  101.53
Weather              Mainly Clear
Name: 896, dtype: object
Inserting row 898
Error inserting row 898: tuple index out of range
Row data: Date/Time           2/7/2012 9:00
Temp_C                       -6.2
Dew Point Temp_C            -13.3
Rel Hum_%                      57
Wind Speed_km/h                19
Visibility_km                24.1
Press_kPa                  101.64
Weather              Mainly Clear
Name: 897, dtype: object
Inserting row 899
Error inserting row 899: tuple index out of range
Row data: Date/Time           2/7/2012 10:00
Temp_C                        -6.2
Dew Point Temp_C             -13.4
Rel Hum_%                       57
Wind Speed_km/h                 19
Visibility_km                 24.1
Press_kPa                   101.69
Weather               Mainly Clear
Name: 898, dtype: object
Inserting row 900
Error inserting row 900: tuple index out of range
Row data: Date/Time           2/7/2012 11:00
Temp_C                        -6.0
Dew Point Temp_C             -13.7
Rel Hum_%                       54
Wind Speed_km/h                 11
Visibility_km                 24.1
Press_kPa                   101.74
Weather               Mainly Clear
Name: 899, dtype: object
Inserting row 901
Error inserting row 901: tuple index out of range
Row data: Date/Time           2/7/2012 12:00
Temp_C                        -5.6
Dew Point Temp_C             -13.1
Rel Hum_%                       55
Wind Speed_km/h                 13
Visibility_km                 24.1
Press_kPa                   101.73
Weather               Mainly Clear
Name: 900, dtype: object
Inserting row 902
Error inserting row 902: tuple index out of range
Row data: Date/Time           2/7/2012 13:00
Temp_C                        -5.2
Dew Point Temp_C             -14.3
Rel Hum_%                       49
Wind Speed_km/h                 15
Visibility_km                 24.1
Press_kPa                   101.73
Weather                      Clear
Name: 901, dtype: object
Inserting row 903
Error inserting row 903: tuple index out of range
Row data: Date/Time           2/7/2012 14:00
Temp_C                        -5.1
Dew Point Temp_C             -15.1
Rel Hum_%                       45
Wind Speed_km/h                 15
Visibility_km                 24.1
Press_kPa                   101.79
Weather                      Clear
Name: 902, dtype: object
Inserting row 904
Error inserting row 904: tuple index out of range
Row data: Date/Time           2/7/2012 15:00
Temp_C                        -4.8
Dew Point Temp_C             -15.4
Rel Hum_%                       43
Wind Speed_km/h                 19
Visibility_km                 24.1
Press_kPa                   101.85
Weather                      Clear
Name: 903, dtype: object
Inserting row 905
Error inserting row 905: tuple index out of range
Row data: Date/Time           2/7/2012 16:00
Temp_C                        -5.0
Dew Point Temp_C             -16.4
Rel Hum_%                       40
Wind Speed_km/h                 22
Visibility_km                 24.1
Press_kPa                   101.88
Weather                      Clear
Name: 904, dtype: object
Inserting row 906
Error inserting row 906: tuple index out of range
Row data: Date/Time           2/7/2012 17:00
Temp_C                        -5.9
Dew Point Temp_C             -17.6
Rel Hum_%                       39
Wind Speed_km/h                 19
Visibility_km                 48.3
Press_kPa                   101.94
Weather                      Clear
Name: 905, dtype: object
Inserting row 907
Error inserting row 907: tuple index out of range
Row data: Date/Time           2/7/2012 18:00
Temp_C                        -7.3
Dew Point Temp_C             -17.4
Rel Hum_%                       44
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   102.03
Weather                      Clear
Name: 906, dtype: object
Inserting row 908
Error inserting row 908: tuple index out of range
Row data: Date/Time           2/7/2012 19:00
Temp_C                        -8.2
Dew Point Temp_C             -17.8
Rel Hum_%                       46
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                   102.09
Weather                      Clear
Name: 907, dtype: object
Inserting row 909
Error inserting row 909: tuple index out of range
Row data: Date/Time           2/7/2012 20:00
Temp_C                        -9.2
Dew Point Temp_C             -18.4
Rel Hum_%                       47
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   102.12
Weather                      Clear
Name: 908, dtype: object
Inserting row 910
Error inserting row 910: tuple index out of range
Row data: Date/Time           2/7/2012 21:00
Temp_C                        -9.6
Dew Point Temp_C             -18.9
Rel Hum_%                       47
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   102.15
Weather                      Clear
Name: 909, dtype: object
Inserting row 911
Error inserting row 911: tuple index out of range
Row data: Date/Time           2/7/2012 22:00
Temp_C                       -10.8
Dew Point Temp_C             -20.1
Rel Hum_%                       46
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                   102.21
Weather                      Clear
Name: 910, dtype: object
Inserting row 912
Error inserting row 912: tuple index out of range
Row data: Date/Time           2/7/2012 23:00
Temp_C                       -11.8
Dew Point Temp_C             -20.8
Rel Hum_%                       47
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                   102.21
Weather                      Clear
Name: 911, dtype: object
Inserting row 913
Error inserting row 913: tuple index out of range
Row data: Date/Time           2/8/2012 0:00
Temp_C                      -13.8
Dew Point Temp_C            -21.5
Rel Hum_%                      52
Wind Speed_km/h                 4
Visibility_km                25.0
Press_kPa                  102.21
Weather                     Clear
Name: 912, dtype: object
Inserting row 914
Error inserting row 914: tuple index out of range
Row data: Date/Time           2/8/2012 1:00
Temp_C                      -11.9
Dew Point Temp_C            -20.6
Rel Hum_%                      48
Wind Speed_km/h                 9
Visibility_km                25.0
Press_kPa                  102.21
Weather                     Clear
Name: 913, dtype: object
Inserting row 915
Error inserting row 915: tuple index out of range
Row data: Date/Time           2/8/2012 2:00
Temp_C                      -12.1
Dew Point Temp_C            -20.4
Rel Hum_%                      50
Wind Speed_km/h                 6
Visibility_km                25.0
Press_kPa                   102.2
Weather                     Clear
Name: 914, dtype: object
Inserting row 916
Error inserting row 916: tuple index out of range
Row data: Date/Time           2/8/2012 3:00
Temp_C                      -12.4
Dew Point Temp_C            -20.4
Rel Hum_%                      51
Wind Speed_km/h                11
Visibility_km                25.0
Press_kPa                  102.15
Weather                     Clear
Name: 915, dtype: object
Inserting row 917
Error inserting row 917: tuple index out of range
Row data: Date/Time           2/8/2012 4:00
Temp_C                      -14.0
Dew Point Temp_C            -21.0
Rel Hum_%                      55
Wind Speed_km/h                 4
Visibility_km                25.0
Press_kPa                  102.13
Weather                     Clear
Name: 916, dtype: object
Inserting row 918
Error inserting row 918: tuple index out of range
Row data: Date/Time           2/8/2012 5:00
Temp_C                      -12.6
Dew Point Temp_C            -21.2
Rel Hum_%                      49
Wind Speed_km/h                 0
Visibility_km                25.0
Press_kPa                  102.11
Weather                     Clear
Name: 917, dtype: object
Inserting row 919
Error inserting row 919: tuple index out of range
Row data: Date/Time           2/8/2012 6:00
Temp_C                      -12.4
Dew Point Temp_C            -21.1
Rel Hum_%                      48
Wind Speed_km/h                 9
Visibility_km                25.0
Press_kPa                  102.06
Weather              Mainly Clear
Name: 918, dtype: object
Inserting row 920
Error inserting row 920: tuple index out of range
Row data: Date/Time           2/8/2012 7:00
Temp_C                      -11.7
Dew Point Temp_C            -18.0
Rel Hum_%                      59
Wind Speed_km/h                15
Visibility_km                24.1
Press_kPa                  102.07
Weather              Mainly Clear
Name: 919, dtype: object
Inserting row 921
Error inserting row 921: tuple index out of range
Row data: Date/Time           2/8/2012 8:00
Temp_C                      -10.8
Dew Point Temp_C            -17.0
Rel Hum_%                      60
Wind Speed_km/h                13
Visibility_km                48.3
Press_kPa                  102.09
Weather              Mainly Clear
Name: 920, dtype: object
Inserting row 922
Error inserting row 922: tuple index out of range
Row data: Date/Time           2/8/2012 9:00
Temp_C                       -9.6
Dew Point Temp_C            -15.1
Rel Hum_%                      64
Wind Speed_km/h                15
Visibility_km                48.3
Press_kPa                  102.07
Weather              Mainly Clear
Name: 921, dtype: object
Inserting row 923
Error inserting row 923: tuple index out of range
Row data: Date/Time           2/8/2012 10:00
Temp_C                        -8.2
Dew Point Temp_C             -14.6
Rel Hum_%                       60
Wind Speed_km/h                 17
Visibility_km                 48.3
Press_kPa                   102.04
Weather               Mainly Clear
Name: 922, dtype: object
Inserting row 924
Error inserting row 924: tuple index out of range
Row data: Date/Time           2/8/2012 11:00
Temp_C                        -6.3
Dew Point Temp_C             -13.7
Rel Hum_%                       56
Wind Speed_km/h                 17
Visibility_km                 48.3
Press_kPa                   101.93
Weather               Mainly Clear
Name: 923, dtype: object
Inserting row 925
Error inserting row 925: tuple index out of range
Row data: Date/Time           2/8/2012 12:00
Temp_C                        -4.6
Dew Point Temp_C             -12.9
Rel Hum_%                       52
Wind Speed_km/h                 20
Visibility_km                 48.3
Press_kPa                   101.76
Weather                      Clear
Name: 924, dtype: object
Inserting row 926
Error inserting row 926: tuple index out of range
Row data: Date/Time           2/8/2012 13:00
Temp_C                        -3.3
Dew Point Temp_C             -12.9
Rel Hum_%                       47
Wind Speed_km/h                 32
Visibility_km                 48.3
Press_kPa                   101.63
Weather                      Clear
Name: 925, dtype: object
Inserting row 927
Error inserting row 927: tuple index out of range
Row data: Date/Time           2/8/2012 14:00
Temp_C                        -2.4
Dew Point Temp_C             -12.2
Rel Hum_%                       47
Wind Speed_km/h                 24
Visibility_km                 48.3
Press_kPa                   101.54
Weather               Mainly Clear
Name: 926, dtype: object
Inserting row 928
Error inserting row 928: tuple index out of range
Row data: Date/Time           2/8/2012 15:00
Temp_C                        -1.8
Dew Point Temp_C             -12.8
Rel Hum_%                       43
Wind Speed_km/h                 32
Visibility_km                 48.3

Row data: Date/Time           2/16/2012 2:00
Temp_C                         0.7
Dew Point Temp_C              -0.8
Rel Hum_%                       90
Wind Speed_km/h                  4
Visibility_km                 12.9
Press_kPa                   101.97
Weather                     Cloudy
Name: 1106, dtype: object
Inserting row 1108
Error inserting row 1108: tuple index out of range
Row data: Date/Time           2/16/2012 3:00
Temp_C                         0.7
Dew Point Temp_C              -0.7
Rel Hum_%                       90
Wind Speed_km/h                  6
Visibility_km                 25.0
Press_kPa                   101.94
Weather                     Cloudy
Name: 1107, dtype: object
Inserting row 1109
Error inserting row 1109: tuple index out of range
Row data: Date/Time           2/16/2012 4:00
Temp_C                         0.9
Dew Point Temp_C              -0.7
Rel Hum_%                       89
Wind Speed_km/h                  7
Visibility_km                 12.9
Press_kPa                   101.94
Weather                     Cloudy
Name: 1108, dtype: object
Inserting row 1110
Error inserting row 1110: tuple index out of range
Row data: Date/Time           2/16/2012 5:00
Temp_C                         0.7
Dew Point Temp_C              -0.9
Rel Hum_%                       89
Wind Speed_km/h                  4
Visibility_km                 12.9
Press_kPa                   101.92
Weather                     Cloudy
Name: 1109, dtype: object
Inserting row 1111
Error inserting row 1111: tuple index out of range
Row data: Date/Time           2/16/2012 6:00
Temp_C                         1.3
Dew Point Temp_C              -0.9
Rel Hum_%                       85
Wind Speed_km/h                  6
Visibility_km                 12.9
Press_kPa                   101.93
Weather                     Cloudy
Name: 1110, dtype: object
Inserting row 1112
Error inserting row 1112: tuple index out of range
Row data: Date/Time           2/16/2012 7:00
Temp_C                         1.7
Dew Point Temp_C              -0.9
Rel Hum_%                       83
Wind Speed_km/h                  7
Visibility_km                 12.9
Press_kPa                   101.96
Weather                     Cloudy
Name: 1111, dtype: object
Inserting row 1113
Error inserting row 1113: tuple index out of range
Row data: Date/Time           2/16/2012 8:00
Temp_C                         1.2
Dew Point Temp_C              -1.2
Rel Hum_%                       84
Wind Speed_km/h                  7
Visibility_km                 16.1
Press_kPa                   101.95
Weather                     Cloudy
Name: 1112, dtype: object
Inserting row 1114
Error inserting row 1114: tuple index out of range
Row data: Date/Time           2/16/2012 9:00
Temp_C                         1.8
Dew Point Temp_C              -1.3
Rel Hum_%                       80
Wind Speed_km/h                  0
Visibility_km                 16.1
Press_kPa                   101.91
Weather              Mostly Cloudy
Name: 1113, dtype: object
Inserting row 1115
Error inserting row 1115: tuple index out of range
Row data: Date/Time           2/16/2012 10:00
Temp_C                          2.7
Dew Point Temp_C               -1.1
Rel Hum_%                        76
Wind Speed_km/h                  11
Visibility_km                  24.1
Press_kPa                    101.83
Weather                Mainly Clear
Name: 1114, dtype: object
Inserting row 1116
Error inserting row 1116: tuple index out of range
Row data: Date/Time           2/16/2012 11:00
Temp_C                          3.3
Dew Point Temp_C               -2.1
Rel Hum_%                        68
Wind Speed_km/h                  11
Visibility_km                  24.1
Press_kPa                    101.76
Weather               Mostly Cloudy
Name: 1115, dtype: object
Inserting row 1117
Error inserting row 1117: tuple index out of range
Row data: Date/Time           2/16/2012 12:00
Temp_C                          3.6
Dew Point Temp_C               -3.1
Rel Hum_%                        62
Wind Speed_km/h                  19
Visibility_km                  24.1
Press_kPa                    101.65
Weather               Mostly Cloudy
Name: 1116, dtype: object
Inserting row 1118
Error inserting row 1118: tuple index out of range
Row data: Date/Time           2/16/2012 13:00
Temp_C                          3.3
Dew Point Temp_C               -2.7
Rel Hum_%                        65
Wind Speed_km/h                  19
Visibility_km                  24.1
Press_kPa                    101.53
Weather               Mostly Cloudy
Name: 1117, dtype: object
Inserting row 1119
Error inserting row 1119: tuple index out of range
Row data: Date/Time           2/16/2012 14:00
Temp_C                          3.5
Dew Point Temp_C               -2.7
Rel Hum_%                        64
Wind Speed_km/h                  19
Visibility_km                  24.1
Press_kPa                    101.39
Weather               Mostly Cloudy
Name: 1118, dtype: object
Inserting row 1120
Error inserting row 1120: tuple index out of range
Row data: Date/Time           2/16/2012 15:00
Temp_C                          3.6
Dew Point Temp_C               -2.8
Rel Hum_%                        63
Wind Speed_km/h                  19
Visibility_km                  24.1
Press_kPa                    101.29
Weather               Mostly Cloudy
Name: 1119, dtype: object
Inserting row 1121
Error inserting row 1121: tuple index out of range
Row data: Date/Time           2/16/2012 16:00
Temp_C                          3.7
Dew Point Temp_C               -2.5
Rel Hum_%                        64
Wind Speed_km/h                  15
Visibility_km                  24.1
Press_kPa                    101.22
Weather                      Cloudy
Name: 1120, dtype: object
Inserting row 1122
Error inserting row 1122: tuple index out of range
Row data: Date/Time           2/16/2012 17:00
Temp_C                          3.6
Dew Point Temp_C               -2.7
Rel Hum_%                        63
Wind Speed_km/h                  15
Visibility_km                  24.1
Press_kPa                    101.17
Weather                      Cloudy
Name: 1121, dtype: object
Inserting row 1123
Error inserting row 1123: tuple index out of range
Row data: Date/Time           2/16/2012 18:00
Temp_C                          3.0
Dew Point Temp_C               -2.1
Rel Hum_%                        69
Wind Speed_km/h                  19
Visibility_km                  24.1
Press_kPa                    101.13
Weather                        Rain
Name: 1122, dtype: object
Inserting row 1124
Error inserting row 1124: tuple index out of range
Row data: Date/Time           2/16/2012 19:00
Temp_C                          2.5
Dew Point Temp_C               -1.4
Rel Hum_%                        75
Wind Speed_km/h                  17
Visibility_km                  25.0
Press_kPa                    101.02
Weather                        Rain
Name: 1123, dtype: object
Inserting row 1125
Error inserting row 1125: tuple index out of range
Row data: Date/Time           2/16/2012 20:00
Temp_C                          1.7
Dew Point Temp_C               -0.7
Rel Hum_%                        84
Wind Speed_km/h                  17
Visibility_km                  16.1
Press_kPa                    100.94
Weather                        Rain
Name: 1124, dtype: object
Inserting row 1126
Error inserting row 1126: tuple index out of range
Row data: Date/Time           2/16/2012 21:00
Temp_C                          1.5
Dew Point Temp_C               -0.5
Rel Hum_%                        87
Wind Speed_km/h                  15
Visibility_km                  25.0
Press_kPa                    100.88
Weather                        Rain
Name: 1125, dtype: object
Inserting row 1127
Error inserting row 1127: tuple index out of range
Row data: Date/Time           2/16/2012 22:00
Temp_C                          1.5
Dew Point Temp_C               -0.6
Rel Hum_%                        86
Wind Speed_km/h                  17
Visibility_km                  12.9
Press_kPa                     100.8
Weather                        Rain
Name: 1126, dtype: object
Inserting row 1128
Error inserting row 1128: tuple index out of range
Row data: Date/Time           2/16/2012 23:00
Temp_C                          1.3
Dew Point Temp_C               -0.3
Rel Hum_%                        89
Wind Speed_km/h                  19
Visibility_km                  16.1
Press_kPa                    100.71
Weather                        Rain
Name: 1127, dtype: object
Inserting row 1129
Error inserting row 1129: tuple index out of range
Row data: Date/Time           2/17/2012 0:00
Temp_C                         1.3
Dew Point Temp_C              -0.3
Rel Hum_%                       89
Wind Speed_km/h                 19
Visibility_km                 12.9
Press_kPa                   100.64
Weather                       Rain
Name: 1128, dtype: object
Inserting row 1130
Error inserting row 1130: tuple index out of range
Row data: Date/Time           2/17/2012 1:00
Temp_C                         1.3
Dew Point Temp_C              -0.2
Rel Hum_%                       90
Wind Speed_km/h                 19
Visibility_km                 12.9
Press_kPa                   100.57
Weather                       Rain
Name: 1129, dtype: object
Inserting row 1131
Error inserting row 1131: tuple index out of range
Row data: Date/Time           2/17/2012 2:00
Temp_C                         1.3
Dew Point Temp_C               0.1
Rel Hum_%                       92
Wind Speed_km/h                 17
Visibility_km                  9.7
Press_kPa                    100.5
Weather                       Rain
Name: 1130, dtype: object
Inserting row 1132
Error inserting row 1132: tuple index out of range
Row data: Date/Time           2/17/2012 3:00
Temp_C                         1.4
Dew Point Temp_C               0.2
Rel Hum_%                       92
Wind Speed_km/h                 19
Visibility_km                 12.9
Press_kPa                   100.45
Weather                       Rain
Name: 1131, dtype: object
Inserting row 1133
Error inserting row 1133: tuple index out of range
Row data: Date/Time           2/17/2012 4:00
Temp_C                         2.3
Dew Point Temp_C               1.1
Rel Hum_%                       92
Wind Speed_km/h                 20
Visibility_km                  8.0
Press_kPa                   100.47
Weather                    Drizzle
Name: 1132, dtype: object
Inserting row 1134
Error inserting row 1134: tuple index out of range
Row data: Date/Time           2/17/2012 5:00
Temp_C                         2.8
Dew Point Temp_C               1.6
Rel Hum_%                       92
Wind Speed_km/h                 24
Visibility_km                 12.9
Press_kPa                   100.49
Weather                     Cloudy
Name: 1133, dtype: object
Inserting row 1135
Error inserting row 1135: tuple index out of range
Row data: Date/Time           2/17/2012 6:00
Temp_C                         3.0
Dew Point Temp_C               0.9
Rel Hum_%                       86
Wind Speed_km/h                 30
Visibility_km                 16.1
Press_kPa                   100.54
Weather                     Cloudy
Name: 1134, dtype: object
Inserting row 1136
Error inserting row 1136: tuple index out of range
Row data: Date/Time           2/17/2012 7:00
Temp_C                         3.0
Dew Point Temp_C              -0.3
Rel Hum_%                       79
Wind Speed_km/h                 24
Visibility_km                 24.1
Press_kPa                   100.58
Weather              Mostly Cloudy
Name: 1135, dtype: object
Inserting row 1137
Error inserting row 1137: tuple index out of range
Row data: Date/Time           2/17/2012 8:00
Temp_C                         2.8
Dew Point Temp_C              -1.2
Rel Hum_%                       75
Wind Speed_km/h                 32
Visibility_km                 24.1
Press_kPa                   100.67
Weather                     Cloudy
Name: 1136, dtype: object
Inserting row 1138
Error inserting row 1138: tuple index out of range
Row data: Date/Time           2/17/2012 9:00
Temp_C                         2.3
Dew Point Temp_C              -2.4
Rel Hum_%                       71
Wind Speed_km/h                 32
Visibility_km                 24.1
Press_kPa                   100.74
Weather              Mostly Cloudy
Name: 1137, dtype: object
Inserting row 1139
Error inserting row 1139: tuple index out of range
Row data: Date/Time           2/17/2012 10:00
Temp_C                          2.5
Dew Point Temp_C               -3.0
Rel Hum_%                        67
Wind Speed_km/h                  41
Visibility_km                  48.3
Press_kPa                    100.76
Weather               Mostly Cloudy
Name: 1138, dtype: object
Inserting row 1140
Error inserting row 1140: tuple index out of range
Row data: Date/Time           2/17/2012 11:00
Temp_C                          2.6
Dew Point Temp_C               -4.0
Rel Hum_%                        62
Wind Speed_km/h                  32
Visibility_km                  48.3
Press_kPa                    100.77
Weather                      Cloudy
Name: 1139, dtype: object
Inserting row 1141
Error inserting row 1141: tuple index out of range
Row data: Date/Time           2/17/2012 12:00
Temp_C                          2.6
Dew Point Temp_C               -4.1
Rel Hum_%                        61
Wind Speed_km/h                  24
Visibility_km                  24.1
Press_kPa                    100.71
Weather                      Cloudy
Name: 1140, dtype: object
Inserting row 1142
Error inserting row 1142: tuple index out of range
Row data: Date/Time           2/17/2012 13:00
Temp_C                          3.0
Dew Point Temp_C               -4.3
Rel Hum_%                        59
Wind Speed_km/h                  22
Visibility_km                  24.1
Press_kPa                    100.66
Weather               Mostly Cloudy
Name: 1141, dtype: object
Inserting row 1143
Error inserting row 1143: tuple index out of range
Row data: Date/Time           2/17/2012 14:00
Temp_C                          3.5
Dew Point Temp_C               -5.1
Rel Hum_%                        53
Wind Speed_km/h                  28
Visibility_km                  24.1
Press_kPa                    100.62
Weather               Mostly Cloudy
Name: 1142, dtype: object
Inserting row 1144
Error inserting row 1144: tuple index out of range
Row data: Date/Time           2/17/2012 15:00
Temp_C                          3.0
Dew Point Temp_C               -4.4
Rel Hum_%                        58
Wind Speed_km/h                  30
Visibility_km                  24.1
Press_kPa                    100.63
Weather               Mostly Cloudy
Name: 1143, dtype: object
Inserting row 1145
Error inserting row 1145: tuple index out of range
Row data: Date/Time           2/17/2012 16:00
Temp_C                          3.1
Dew Point Temp_C               -4.9
Rel Hum_%                        56
Wind Speed_km/h                  26
Visibility_km                  24.1
Press_kPa                    100.64
Weather                      Cloudy
Name: 1144, dtype: object
Inserting row 1146
Error inserting row 1146: tuple index out of range
Row data: Date/Time           2/17/2012 17:00
Temp_C                          2.6
Dew Point Temp_C               -3.9
Rel Hum_%                        62
Wind Speed_km/h                  26
Visibility_km                  24.1
Press_kPa                    100.66
Weather               Mostly Cloudy
Name: 1145, dtype: object
Inserting row 1147
Error inserting row 1147: tuple index out of range
Row data: Date/Time           2/17/2012 18:00
Temp_C                          2.3
Dew Point Temp_C               -3.7
Rel Hum_%                        64
Wind Speed_km/h                  22
Visibility_km                  25.0
Press_kPa                    100.69
Weather               Mostly Cloudy
Name: 1146, dtype: object
Inserting row 1148
Error inserting row 1148: tuple index out of range
Row data: Date/Time           2/17/2012 19:00
Temp_C                          2.0
Dew Point Temp_C               -3.5
Rel Hum_%                        67
Wind Speed_km/h                  28
Visibility_km                  25.0
Press_kPa                    100.68
Weather               Mostly Cloudy
Name: 1147, dtype: object
Inserting row 1149
Error inserting row 1149: tuple index out of range
Row data: Date/Time           2/17/2012 20:00
Temp_C                          1.8
Dew Point Temp_C               -3.4
Rel Hum_%                        68
Wind Speed_km/h                  24
Visibility_km                  25.0
Press_kPa                    100.68
Weather               Mostly Cloudy
Name: 1148, dtype: object
Inserting row 1150
Error inserting row 1150: tuple index out of range
Row data: Date/Time           2/17/2012 21:00
Temp_C                          1.7
Dew Point Temp_C               -3.6
Rel Hum_%                        68
Wind Speed_km/h                  19
Visibility_km                  25.0
Press_kPa                     100.7
Weather               Mostly Cloudy
Name: 1149, dtype: object
Inserting row 1151
Error inserting row 1151: tuple index out of range
Row data: Date/Time           2/17/2012 22:00
Temp_C                          1.2
Dew Point Temp_C               -3.9
Rel Hum_%                        69
Wind Speed_km/h                  15
Visibility_km                  25.0
Press_kPa                    100.72
Weather                Mainly Clear
Name: 1150, dtype: object
Inserting row 1152
Error inserting row 1152: tuple index out of range
Row data: Date/Time           2/17/2012 23:00
Temp_C                          0.9
Dew Point Temp_C               -4.1
Rel Hum_%                        69
Wind Speed_km/h                  26
Visibility_km                  25.0
Press_kPa                     100.7
Weather                Mainly Clear
Name: 1151, dtype: object
Inserting row 1153
Error inserting row 1153: tuple index out of range
Row data: Date/Time           2/18/2012 0:00
Temp_C                         0.7
Dew Point Temp_C              -3.9
Rel Hum_%                       71
Wind Speed_km/h                 24
Visibility_km                 25.0
Press_kPa                   100.71
Weather               Mainly Clear
Name: 1152, dtype: object
Inserting row 1154
Error inserting row 1154: tuple index out of range
Row data: Date/Time           2/18/2012 1:00
Temp_C                         0.7
Dew Point Temp_C              -4.5
Rel Hum_%                       68
Wind Speed_km/h                 22
Visibility_km                 25.0
Press_kPa                   100.71
Weather               Mainly Clear
Name: 1153, dtype: object
Inserting row 1155
Error inserting row 1155: tuple index out of range
Row data: Date/Time           2/18/2012 2:00
Temp_C                         0.3
Dew Point Temp_C              -4.4
Rel Hum_%                       71
Wind Speed_km/h                 22
Visibility_km                 25.0
Press_kPa                   100.74
Weather               Mainly Clear
Name: 1154, dtype: object
Inserting row 1156
Error inserting row 1156: tuple index out of range
Row data: Date/Time           2/18/2012 3:00
Temp_C                         0.3
Dew Point Temp_C              -4.7
Rel Hum_%                       69
Wind Speed_km/h                 26
Visibility_km                 25.0
Press_kPa                   100.72
Weather              Mostly Cloudy
Name: 1155, dtype: object
Inserting row 1157
Error inserting row 1157: tuple index out of range
Row data: Date/Time           2/18/2012 4:00
Temp_C                        -0.3
Dew Point Temp_C              -4.9
Rel Hum_%                       71
Wind Speed_km/h                 22
Visibility_km                 25.0
Press_kPa                   100.74
Weather              Mostly Cloudy
Name: 1156, dtype: object
Inserting row 1158
Error inserting row 1158: tuple index out of range
Row data: Date/Time           2/18/2012 5:00
Temp_C                        -0.6

Row data: Date/Time           2/25/2012 19:00
Temp_C                         -4.7
Dew Point Temp_C              -10.5
Rel Hum_%                        64
Wind Speed_km/h                  35
Visibility_km                  25.0
Press_kPa                    100.04
Weather                      Cloudy
Name: 1339, dtype: object
Inserting row 1341
Error inserting row 1341: tuple index out of range
Row data: Date/Time           2/25/2012 20:00
Temp_C                         -5.3
Dew Point Temp_C              -11.2
Rel Hum_%                        63
Wind Speed_km/h                  26
Visibility_km                  25.0
Press_kPa                    100.24
Weather                      Cloudy
Name: 1340, dtype: object
Inserting row 1342
Error inserting row 1342: tuple index out of range
Row data: Date/Time           2/25/2012 21:00
Temp_C                         -5.6
Dew Point Temp_C              -11.1
Rel Hum_%                        65
Wind Speed_km/h                  32
Visibility_km                  25.0
Press_kPa                    100.42
Weather               Mostly Cloudy
Name: 1341, dtype: object
Inserting row 1343
Error inserting row 1343: tuple index out of range
Row data: Date/Time           2/25/2012 22:00
Temp_C                         -6.6
Dew Point Temp_C              -12.8
Rel Hum_%                        61
Wind Speed_km/h                  28
Visibility_km                  25.0
Press_kPa                    100.62
Weather                      Cloudy
Name: 1342, dtype: object
Inserting row 1344
Error inserting row 1344: tuple index out of range
Row data: Date/Time           2/25/2012 23:00
Temp_C                         -7.6
Dew Point Temp_C              -13.8
Rel Hum_%                        61
Wind Speed_km/h                  26
Visibility_km                  25.0
Press_kPa                    100.76
Weather                      Cloudy
Name: 1343, dtype: object
Inserting row 1345
Error inserting row 1345: tuple index out of range
Row data: Date/Time           2/26/2012 0:00
Temp_C                        -8.3
Dew Point Temp_C             -14.3
Rel Hum_%                       62
Wind Speed_km/h                 19
Visibility_km                 25.0
Press_kPa                   100.89
Weather              Mostly Cloudy
Name: 1344, dtype: object
Inserting row 1346
Error inserting row 1346: tuple index out of range
Row data: Date/Time           2/26/2012 1:00
Temp_C                        -9.0
Dew Point Temp_C             -14.5
Rel Hum_%                       64
Wind Speed_km/h                 20
Visibility_km                 25.0
Press_kPa                   101.09
Weather               Mainly Clear
Name: 1345, dtype: object
Inserting row 1347
Error inserting row 1347: tuple index out of range
Row data: Date/Time           2/26/2012 2:00
Temp_C                        -9.2
Dew Point Temp_C             -14.6
Rel Hum_%                       65
Wind Speed_km/h                 22
Visibility_km                 25.0
Press_kPa                   101.26
Weather                      Clear
Name: 1346, dtype: object
Inserting row 1348
Error inserting row 1348: tuple index out of range
Row data: Date/Time           2/26/2012 3:00
Temp_C                        -9.9
Dew Point Temp_C             -15.1
Rel Hum_%                       66
Wind Speed_km/h                 28
Visibility_km                 25.0
Press_kPa                   101.42
Weather               Mainly Clear
Name: 1347, dtype: object
Inserting row 1349
Error inserting row 1349: tuple index out of range
Row data: Date/Time           2/26/2012 4:00
Temp_C                       -10.8
Dew Point Temp_C             -15.3
Rel Hum_%                       69
Wind Speed_km/h                 30
Visibility_km                 25.0
Press_kPa                    101.6
Weather              Mostly Cloudy
Name: 1348, dtype: object
Inserting row 1350
Error inserting row 1350: tuple index out of range
Row data: Date/Time           2/26/2012 5:00
Temp_C                       -11.6
Dew Point Temp_C             -15.9
Rel Hum_%                       70
Wind Speed_km/h                 20
Visibility_km                 25.0
Press_kPa                   101.77
Weather                      Clear
Name: 1349, dtype: object
Inserting row 1351
Error inserting row 1351: tuple index out of range
Row data: Date/Time           2/26/2012 6:00
Temp_C                       -11.3
Dew Point Temp_C             -16.8
Rel Hum_%                       64
Wind Speed_km/h                 22
Visibility_km                 25.0
Press_kPa                   101.92
Weather                      Clear
Name: 1350, dtype: object
Inserting row 1352
Error inserting row 1352: tuple index out of range
Row data: Date/Time           2/26/2012 7:00
Temp_C                       -12.1
Dew Point Temp_C             -17.8
Rel Hum_%                       62
Wind Speed_km/h                 22
Visibility_km                 48.3
Press_kPa                   102.07
Weather                      Clear
Name: 1351, dtype: object
Inserting row 1353
Error inserting row 1353: tuple index out of range
Row data: Date/Time           2/26/2012 8:00
Temp_C                       -12.1
Dew Point Temp_C             -18.0
Rel Hum_%                       61
Wind Speed_km/h                 26
Visibility_km                 48.3
Press_kPa                   102.23
Weather               Mainly Clear
Name: 1352, dtype: object
Inserting row 1354
Error inserting row 1354: tuple index out of range
Row data: Date/Time           2/26/2012 9:00
Temp_C                       -11.6
Dew Point Temp_C             -18.6
Rel Hum_%                       56
Wind Speed_km/h                 32
Visibility_km                 48.3
Press_kPa                   102.32
Weather               Mainly Clear
Name: 1353, dtype: object
Inserting row 1355
Error inserting row 1355: tuple index out of range
Row data: Date/Time           2/26/2012 10:00
Temp_C                        -11.2
Dew Point Temp_C              -20.3
Rel Hum_%                        47
Wind Speed_km/h                  22
Visibility_km                  48.3
Press_kPa                    102.35
Weather                       Clear
Name: 1354, dtype: object
Inserting row 1356
Error inserting row 1356: tuple index out of range
Row data: Date/Time           2/26/2012 11:00
Temp_C                        -10.1
Dew Point Temp_C              -20.1
Rel Hum_%                        44
Wind Speed_km/h                  26
Visibility_km                  48.3
Press_kPa                    102.39
Weather                       Clear
Name: 1355, dtype: object
Inserting row 1357
Error inserting row 1357: tuple index out of range
Row data: Date/Time           2/26/2012 12:00
Temp_C                         -9.3
Dew Point Temp_C              -18.6
Rel Hum_%                        47
Wind Speed_km/h                  28
Visibility_km                  48.3
Press_kPa                    102.42
Weather                       Clear
Name: 1356, dtype: object
Inserting row 1358
Error inserting row 1358: tuple index out of range
Row data: Date/Time           2/26/2012 13:00
Temp_C                         -8.3
Dew Point Temp_C              -17.4
Rel Hum_%                        48
Wind Speed_km/h                  26
Visibility_km                  48.3
Press_kPa                    102.41
Weather                Mainly Clear
Name: 1357, dtype: object
Inserting row 1359
Error inserting row 1359: tuple index out of range
Row data: Date/Time           2/26/2012 14:00
Temp_C                         -7.6
Dew Point Temp_C              -17.2
Rel Hum_%                        46
Wind Speed_km/h                  28
Visibility_km                  48.3
Press_kPa                    102.42
Weather                Mainly Clear
Name: 1358, dtype: object
Inserting row 1360
Error inserting row 1360: tuple index out of range
Row data: Date/Time           2/26/2012 15:00
Temp_C                         -7.1
Dew Point Temp_C              -16.3
Rel Hum_%                        48
Wind Speed_km/h                  26
Visibility_km                  48.3
Press_kPa                    102.49
Weather                Mainly Clear
Name: 1359, dtype: object
Inserting row 1361
Error inserting row 1361: tuple index out of range
Row data: Date/Time           2/26/2012 16:00
Temp_C                         -6.8
Dew Point Temp_C              -16.4
Rel Hum_%                        46
Wind Speed_km/h                  24
Visibility_km                  48.3
Press_kPa                    102.52
Weather                Mainly Clear
Name: 1360, dtype: object
Inserting row 1362
Error inserting row 1362: tuple index out of range
Row data: Date/Time           2/26/2012 17:00
Temp_C                         -7.6
Dew Point Temp_C              -17.1
Rel Hum_%                        46
Wind Speed_km/h                  24
Visibility_km                  48.3
Press_kPa                    102.55
Weather               Mostly Cloudy
Name: 1361, dtype: object
Inserting row 1363
Error inserting row 1363: tuple index out of range
Row data: Date/Time           2/26/2012 18:00
Temp_C                         -7.9
Dew Point Temp_C              -16.7
Rel Hum_%                        49
Wind Speed_km/h                  19
Visibility_km                  25.0
Press_kPa                     102.6
Weather                      Cloudy
Name: 1362, dtype: object
Inserting row 1364
Error inserting row 1364: tuple index out of range
Row data: Date/Time           2/26/2012 19:00
Temp_C                         -7.8
Dew Point Temp_C              -16.8
Rel Hum_%                        48
Wind Speed_km/h                  13
Visibility_km                  25.0
Press_kPa                    102.63
Weather                      Cloudy
Name: 1363, dtype: object
Inserting row 1365
Error inserting row 1365: tuple index out of range
Row data: Date/Time           2/26/2012 20:00
Temp_C                         -7.9
Dew Point Temp_C              -16.4
Rel Hum_%                        50
Wind Speed_km/h                  11
Visibility_km                  25.0
Press_kPa                    102.64
Weather                      Cloudy
Name: 1364, dtype: object
Inserting row 1366
Error inserting row 1366: tuple index out of range
Row data: Date/Time           2/26/2012 21:00
Temp_C                         -8.5
Dew Point Temp_C              -16.6
Rel Hum_%                        52
Wind Speed_km/h                   9
Visibility_km                  25.0
Press_kPa                    102.72
Weather                      Cloudy
Name: 1365, dtype: object
Inserting row 1367
Error inserting row 1367: tuple index out of range
Row data: Date/Time           2/26/2012 22:00
Temp_C                         -8.6
Dew Point Temp_C              -16.5
Rel Hum_%                        53
Wind Speed_km/h                   0
Visibility_km                  25.0
Press_kPa                    102.68
Weather               Mostly Cloudy
Name: 1366, dtype: object
Inserting row 1368
Error inserting row 1368: tuple index out of range
Row data: Date/Time           2/26/2012 23:00
Temp_C                         -9.5
Dew Point Temp_C              -16.2
Rel Hum_%                        58
Wind Speed_km/h                   0
Visibility_km                  25.0
Press_kPa                    102.64
Weather                      Cloudy
Name: 1367, dtype: object
Inserting row 1369
Error inserting row 1369: tuple index out of range
Row data: Date/Time           2/27/2012 0:00
Temp_C                        -8.2
Dew Point Temp_C             -16.2
Rel Hum_%                       52
Wind Speed_km/h                  7
Visibility_km                 25.0
Press_kPa                   102.63
Weather                     Cloudy
Name: 1368, dtype: object
Inserting row 1370
Error inserting row 1370: tuple index out of range
Row data: Date/Time           2/27/2012 1:00
Temp_C                        -8.6
Dew Point Temp_C             -15.5
Rel Hum_%                       57
Wind Speed_km/h                  4
Visibility_km                 25.0
Press_kPa                   102.61
Weather                     Cloudy
Name: 1369, dtype: object
Inserting row 1371
Error inserting row 1371: tuple index out of range
Row data: Date/Time           2/27/2012 2:00
Temp_C                        -8.5
Dew Point Temp_C             -14.2
Rel Hum_%                       63
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                    102.6
Weather                     Cloudy
Name: 1370, dtype: object
Inserting row 1372
Error inserting row 1372: tuple index out of range
Row data: Date/Time           2/27/2012 3:00
Temp_C                        -8.3
Dew Point Temp_C             -13.7
Rel Hum_%                       65
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                   102.59
Weather                     Cloudy
Name: 1371, dtype: object
Inserting row 1373
Error inserting row 1373: tuple index out of range
Row data: Date/Time           2/27/2012 4:00
Temp_C                        -8.2
Dew Point Temp_C             -14.4
Rel Hum_%                       61
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                   102.58
Weather                     Cloudy
Name: 1372, dtype: object
Inserting row 1374
Error inserting row 1374: tuple index out of range
Row data: Date/Time           2/27/2012 5:00
Temp_C                        -8.4
Dew Point Temp_C             -15.1
Rel Hum_%                       58
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   102.54
Weather              Mostly Cloudy
Name: 1373, dtype: object
Inserting row 1375
Error inserting row 1375: tuple index out of range
Row data: Date/Time           2/27/2012 6:00
Temp_C                        -9.0
Dew Point Temp_C             -15.2
Rel Hum_%                       61
Wind Speed_km/h                 17
Visibility_km                 25.0
Press_kPa                   102.42
Weather              Mostly Cloudy
Name: 1374, dtype: object
Inserting row 1376
Error inserting row 1376: tuple index out of range
Row data: Date/Time           2/27/2012 7:00
Temp_C                        -9.4
Dew Point Temp_C             -14.6
Rel Hum_%                       66
Wind Speed_km/h                 20
Visibility_km                 48.3
Press_kPa                   102.31
Weather                     Cloudy
Name: 1375, dtype: object
Inserting row 1377
Error inserting row 1377: tuple index out of range
Row data: Date/Time           2/27/2012 8:00
Temp_C                        -9.8
Dew Point Temp_C             -14.8
Rel Hum_%                       67
Wind Speed_km/h                 19
Visibility_km                 48.3
Press_kPa                   102.25
Weather                     Cloudy
Name: 1376, dtype: object
Inserting row 1378
Error inserting row 1378: tuple index out of range
Row data: Date/Time           2/27/2012 9:00
Temp_C                        -9.4
Dew Point Temp_C             -14.9
Rel Hum_%                       64
Wind Speed_km/h                 22
Visibility_km                 48.3
Press_kPa                    102.1
Weather                     Cloudy
Name: 1377, dtype: object
Inserting row 1379
Error inserting row 1379: tuple index out of range
Row data: Date/Time           2/27/2012 10:00
Temp_C                         -8.7
Dew Point Temp_C              -14.6
Rel Hum_%                        62
Wind Speed_km/h                  22
Visibility_km                  24.1
Press_kPa                    101.94
Weather                      Cloudy
Name: 1378, dtype: object
Inserting row 1380
Error inserting row 1380: tuple index out of range
Row data: Date/Time           2/27/2012 11:00
Temp_C                         -8.7
Dew Point Temp_C              -14.2
Rel Hum_%                        64
Wind Speed_km/h                  28
Visibility_km                  48.3
Press_kPa                    101.74
Weather               Mostly Cloudy
Name: 1379, dtype: object
Inserting row 1381
Error inserting row 1381: tuple index out of range
Row data: Date/Time           2/27/2012 12:00
Temp_C                         -6.3
Dew Point Temp_C              -12.8
Rel Hum_%                        60
Wind Speed_km/h                  15
Visibility_km                  48.3
Press_kPa                    101.59
Weather               Mostly Cloudy
Name: 1380, dtype: object
Inserting row 1382
Error inserting row 1382: tuple index out of range
Row data: Date/Time           2/27/2012 13:00
Temp_C                         -4.9
Dew Point Temp_C              -11.6
Rel Hum_%                        59
Wind Speed_km/h                  19
Visibility_km                  48.3
Press_kPa                    101.41
Weather                      Cloudy
Name: 1381, dtype: object
Inserting row 1383
Error inserting row 1383: tuple index out of range
Row data: Date/Time           2/27/2012 14:00
Temp_C                         -5.5
Dew Point Temp_C              -11.5
Rel Hum_%                        63
Wind Speed_km/h                  22
Visibility_km                  24.1
Press_kPa                    101.34
Weather                      Cloudy
Name: 1382, dtype: object
Inserting row 1384
Error inserting row 1384: tuple index out of range
Row data: Date/Time           2/27/2012 15:00
Temp_C                         -5.1
Dew Point Temp_C               -9.4
Rel Hum_%                        72
Wind Speed_km/h                  20
Visibility_km                   1.6
Press_kPa                    101.19
Weather                        Snow
Name: 1383, dtype: object
Inserting row 1385
Error inserting row 1385: tuple index out of range
Row data: Date/Time           2/27/2012 16:00
Temp_C                         -4.9
Dew Point Temp_C               -7.9
Rel Hum_%                        79
Wind Speed_km/h                  19
Visibility_km                  19.3
Press_kPa                    101.13
Weather                        Snow
Name: 1384, dtype: object
Inserting row 1386
Error inserting row 1386: tuple index out of range
Row data: Date/Time           2/27/2012 17:00
Temp_C                         -5.2
Dew Point Temp_C               -7.9
Rel Hum_%                        81
Wind Speed_km/h                  20
Visibility_km                  24.1
Press_kPa                    101.01
Weather                      Cloudy
Name: 1385, dtype: object
Inserting row 1387
Error inserting row 1387: tuple index out of range
Row data: Date/Time           2/27/2012 18:00
Temp_C                         -6.3
Dew Point Temp_C               -8.9
Rel Hum_%                        82
Wind Speed_km/h                  24
Visibility_km                  25.0
Press_kPa                     101.1
Weather                      Cloudy
Name: 1386, dtype: object
Inserting row 1388
Error inserting row 1388: tuple index out of range
Row data: Date/Time           2/27/2012 19:00
Temp_C                         -7.1
Dew Point Temp_C               -9.6
Rel Hum_%                        82
Wind Speed_km/h                  22
Visibility_km                   2.0
Press_kPa                    101.14
Weather                        Snow
Name: 1387, dtype: object
Inserting row 1389
Error inserting row 1389: tuple index out of range
Row data: Date/Time           2/27/2012 20:00
Temp_C                         -7.2
Dew Point Temp_C               -9.6
Rel Hum_%                        83
Wind Speed_km/h                   9
Visibility_km                  25.0
Press_kPa                    101.25
Weather                        Snow
Name: 1388, dtype: object
Inserting row 1390
Error inserting row 1390: tuple index out of range
Row data: Date/Time           2/27/2012 21:00
Temp_C                         -7.3
Dew Point Temp_C               -9.7
Rel Hum_%                        83
Wind Speed_km/h                   4
Visibility_km                  25.0
Press_kPa                    101.29
Weather                        Snow
Name: 1389, dtype: object
Inserting row 1391
Error inserting row 1391: tuple index out of range
Row data: Date/Time           2/27/2012 22:00

Row data: Date/Time           3/7/2012 11:00
Temp_C                         3.0
Dew Point Temp_C              -4.7
Rel Hum_%                       57
Wind Speed_km/h                  6
Visibility_km                 24.1
Press_kPa                   101.67
Weather               Mainly Clear
Name: 1595, dtype: object
Inserting row 1597
Error inserting row 1597: tuple index out of range
Row data: Date/Time           3/7/2012 12:00
Temp_C                         6.4
Dew Point Temp_C              -3.6
Rel Hum_%                       49
Wind Speed_km/h                  4
Visibility_km                 24.1
Press_kPa                   101.58
Weather               Mainly Clear
Name: 1596, dtype: object
Inserting row 1598
Error inserting row 1598: tuple index out of range
Row data: Date/Time           3/7/2012 13:00
Temp_C                         8.9
Dew Point Temp_C              -4.4
Rel Hum_%                       39
Wind Speed_km/h                 13
Visibility_km                 24.1
Press_kPa                   101.49
Weather               Mainly Clear
Name: 1597, dtype: object
Inserting row 1599
Error inserting row 1599: tuple index out of range
Row data: Date/Time           3/7/2012 14:00
Temp_C                         9.3
Dew Point Temp_C              -4.1
Rel Hum_%                       39
Wind Speed_km/h                 13
Visibility_km                 24.1
Press_kPa                   101.41
Weather               Mainly Clear
Name: 1598, dtype: object
Inserting row 1600
Error inserting row 1600: tuple index out of range
Row data: Date/Time           3/7/2012 15:00
Temp_C                         9.7
Dew Point Temp_C              -2.7
Rel Hum_%                       42
Wind Speed_km/h                 13
Visibility_km                 24.1
Press_kPa                   101.36
Weather               Mainly Clear
Name: 1599, dtype: object
Inserting row 1601
Error inserting row 1601: tuple index out of range
Row data: Date/Time           3/7/2012 16:00
Temp_C                        11.4
Dew Point Temp_C              -2.3
Rel Hum_%                       38
Wind Speed_km/h                 15
Visibility_km                 24.1
Press_kPa                   101.31
Weather              Mostly Cloudy
Name: 1600, dtype: object
Inserting row 1602
Error inserting row 1602: tuple index out of range
Row data: Date/Time           3/7/2012 17:00
Temp_C                         9.9
Dew Point Temp_C              -1.9
Rel Hum_%                       44
Wind Speed_km/h                  9
Visibility_km                 24.1
Press_kPa                   101.25
Weather              Mostly Cloudy
Name: 1601, dtype: object
Inserting row 1603
Error inserting row 1603: tuple index out of range
Row data: Date/Time           3/7/2012 18:00
Temp_C                         5.5
Dew Point Temp_C              -1.6
Rel Hum_%                       60
Wind Speed_km/h                  7
Visibility_km                 24.1
Press_kPa                   101.25
Weather               Mainly Clear
Name: 1602, dtype: object
Inserting row 1604
Error inserting row 1604: tuple index out of range
Row data: Date/Time           3/7/2012 19:00
Temp_C                         6.0
Dew Point Temp_C              -1.8
Rel Hum_%                       57
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   101.22
Weather              Mostly Cloudy
Name: 1603, dtype: object
Inserting row 1605
Error inserting row 1605: tuple index out of range
Row data: Date/Time           3/7/2012 20:00
Temp_C                         7.6
Dew Point Temp_C              -2.1
Rel Hum_%                       50
Wind Speed_km/h                 20
Visibility_km                 25.0
Press_kPa                   101.18
Weather              Mostly Cloudy
Name: 1604, dtype: object
Inserting row 1606
Error inserting row 1606: tuple index out of range
Row data: Date/Time           3/7/2012 21:00
Temp_C                         6.8
Dew Point Temp_C              -2.1
Rel Hum_%                       53
Wind Speed_km/h                 22
Visibility_km                 25.0
Press_kPa                   101.16
Weather              Mostly Cloudy
Name: 1605, dtype: object
Inserting row 1607
Error inserting row 1607: tuple index out of range
Row data: Date/Time           3/7/2012 22:00
Temp_C                         6.0
Dew Point Temp_C              -1.7
Rel Hum_%                       58
Wind Speed_km/h                 17
Visibility_km                 25.0
Press_kPa                   101.12
Weather                     Cloudy
Name: 1606, dtype: object
Inserting row 1608
Error inserting row 1608: tuple index out of range
Row data: Date/Time           3/7/2012 23:00
Temp_C                         4.8
Dew Point Temp_C              -1.7
Rel Hum_%                       63
Wind Speed_km/h                 15
Visibility_km                 25.0
Press_kPa                   101.05
Weather                     Cloudy
Name: 1607, dtype: object
Inserting row 1609
Error inserting row 1609: tuple index out of range
Row data: Date/Time           3/8/2012 0:00
Temp_C                        6.2
Dew Point Temp_C             -1.5
Rel Hum_%                      58
Wind Speed_km/h                20
Visibility_km                25.0
Press_kPa                  100.98
Weather                    Cloudy
Name: 1608, dtype: object
Inserting row 1610
Error inserting row 1610: tuple index out of range
Row data: Date/Time           3/8/2012 1:00
Temp_C                        5.5
Dew Point Temp_C             -1.4
Rel Hum_%                      61
Wind Speed_km/h                11
Visibility_km                25.0
Press_kPa                  100.92
Weather                    Cloudy
Name: 1609, dtype: object
Inserting row 1611
Error inserting row 1611: tuple index out of range
Row data: Date/Time           3/8/2012 2:00
Temp_C                        7.9
Dew Point Temp_C             -1.2
Rel Hum_%                      53
Wind Speed_km/h                17
Visibility_km                25.0
Press_kPa                  100.81
Weather             Mostly Cloudy
Name: 1610, dtype: object
Inserting row 1612
Error inserting row 1612: tuple index out of range
Row data: Date/Time           3/8/2012 3:00
Temp_C                       10.1
Dew Point Temp_C             -0.9
Rel Hum_%                      46
Wind Speed_km/h                24
Visibility_km                25.0
Press_kPa                  100.69
Weather             Mostly Cloudy
Name: 1611, dtype: object
Inserting row 1613
Error inserting row 1613: tuple index out of range
Row data: Date/Time           3/8/2012 4:00
Temp_C                       10.0
Dew Point Temp_C             -0.7
Rel Hum_%                      47
Wind Speed_km/h                28
Visibility_km                25.0
Press_kPa                  100.64
Weather             Mostly Cloudy
Name: 1612, dtype: object
Inserting row 1614
Error inserting row 1614: tuple index out of range
Row data: Date/Time           3/8/2012 5:00
Temp_C                        5.7
Dew Point Temp_C             -0.8
Rel Hum_%                      63
Wind Speed_km/h                19
Visibility_km                25.0
Press_kPa                  100.57
Weather             Mostly Cloudy
Name: 1613, dtype: object
Inserting row 1615
Error inserting row 1615: tuple index out of range
Row data: Date/Time           3/8/2012 6:00
Temp_C                        7.6
Dew Point Temp_C             -0.4
Rel Hum_%                      57
Wind Speed_km/h                19
Visibility_km                24.1
Press_kPa                  100.52
Weather                    Cloudy
Name: 1614, dtype: object
Inserting row 1616
Error inserting row 1616: tuple index out of range
Row data: Date/Time           3/8/2012 7:00
Temp_C                       10.3
Dew Point Temp_C              0.8
Rel Hum_%                      52
Wind Speed_km/h                26
Visibility_km                48.3
Press_kPa                  100.47
Weather                    Cloudy
Name: 1615, dtype: object
Inserting row 1617
Error inserting row 1617: tuple index out of range
Row data: Date/Time           3/8/2012 8:00
Temp_C                        6.7
Dew Point Temp_C              0.2
Rel Hum_%                      63
Wind Speed_km/h                19
Visibility_km                48.3
Press_kPa                  100.39
Weather                    Cloudy
Name: 1616, dtype: object
Inserting row 1618
Error inserting row 1618: tuple index out of range
Row data: Date/Time           3/8/2012 9:00
Temp_C                       10.2
Dew Point Temp_C              1.6
Rel Hum_%                      55
Wind Speed_km/h                26
Visibility_km                48.3
Press_kPa                  100.29
Weather                    Cloudy
Name: 1617, dtype: object
Inserting row 1619
Error inserting row 1619: tuple index out of range
Row data: Date/Time           3/8/2012 10:00
Temp_C                        12.1
Dew Point Temp_C               2.9
Rel Hum_%                       53
Wind Speed_km/h                 30
Visibility_km                 24.1
Press_kPa                   100.22
Weather                     Cloudy
Name: 1618, dtype: object
Inserting row 1620
Error inserting row 1620: tuple index out of range
Row data: Date/Time           3/8/2012 11:00
Temp_C                        12.7
Dew Point Temp_C               3.8
Rel Hum_%                       55
Wind Speed_km/h                 26
Visibility_km                 24.1
Press_kPa                   100.13
Weather                     Cloudy
Name: 1619, dtype: object
Inserting row 1621
Error inserting row 1621: tuple index out of range
Row data: Date/Time           3/8/2012 12:00
Temp_C                        11.7
Dew Point Temp_C               4.0
Rel Hum_%                       59
Wind Speed_km/h                 20
Visibility_km                 24.1
Press_kPa                   100.08
Weather                       Rain
Name: 1620, dtype: object
Inserting row 1622
Error inserting row 1622: tuple index out of range
Row data: Date/Time           3/8/2012 13:00
Temp_C                        11.5
Dew Point Temp_C               5.2
Rel Hum_%                       65
Wind Speed_km/h                 20
Visibility_km                 24.1
Press_kPa                    99.99
Weather                     Cloudy
Name: 1621, dtype: object
Inserting row 1623
Error inserting row 1623: tuple index out of range
Row data: Date/Time           3/8/2012 14:00
Temp_C                        11.7
Dew Point Temp_C               5.9
Rel Hum_%                       68
Wind Speed_km/h                 26
Visibility_km                 24.1
Press_kPa                    99.88
Weather                     Cloudy
Name: 1622, dtype: object
Inserting row 1624
Error inserting row 1624: tuple index out of range
Row data: Date/Time           3/8/2012 15:00
Temp_C                        11.7
Dew Point Temp_C               6.6
Rel Hum_%                       71
Wind Speed_km/h                 37
Visibility_km                 19.3
Press_kPa                    99.82
Weather                       Rain
Name: 1623, dtype: object
Inserting row 1625
Error inserting row 1625: tuple index out of range
Row data: Date/Time           3/8/2012 16:00
Temp_C                        11.6
Dew Point Temp_C               6.4
Rel Hum_%                       70
Wind Speed_km/h                 32
Visibility_km                 24.1
Press_kPa                    99.75
Weather                       Rain
Name: 1624, dtype: object
Inserting row 1626
Error inserting row 1626: tuple index out of range
Row data: Date/Time           3/8/2012 17:00
Temp_C                        11.3
Dew Point Temp_C               6.9
Rel Hum_%                       74
Wind Speed_km/h                 37
Visibility_km                 19.3
Press_kPa                    99.66
Weather                       Rain
Name: 1625, dtype: object
Inserting row 1627
Error inserting row 1627: tuple index out of range
Row data: Date/Time           3/8/2012 18:00
Temp_C                        10.5
Dew Point Temp_C               7.8
Rel Hum_%                       83
Wind Speed_km/h                 46
Visibility_km                  6.4
Press_kPa                    99.64
Weather                       Rain
Name: 1626, dtype: object
Inserting row 1628
Error inserting row 1628: tuple index out of range
Row data: Date/Time           3/8/2012 19:00
Temp_C                         6.1
Dew Point Temp_C               3.2
Rel Hum_%                       82
Wind Speed_km/h                 30
Visibility_km                 16.1
Press_kPa                    99.78
Weather                       Rain
Name: 1627, dtype: object
Inserting row 1629
Error inserting row 1629: tuple index out of range
Row data: Date/Time           3/8/2012 20:00
Temp_C                         5.0
Dew Point Temp_C               1.6
Rel Hum_%                       79
Wind Speed_km/h                 41
Visibility_km                 25.0
Press_kPa                     99.9
Weather                       Rain
Name: 1628, dtype: object
Inserting row 1630
Error inserting row 1630: tuple index out of range
Row data: Date/Time           3/8/2012 21:00
Temp_C                         3.7
Dew Point Temp_C               1.0
Rel Hum_%                       82
Wind Speed_km/h                 41
Visibility_km                 12.9
Press_kPa                   100.04
Weather                       Rain
Name: 1629, dtype: object
Inserting row 1631
Error inserting row 1631: tuple index out of range
Row data: Date/Time           3/8/2012 22:00
Temp_C                         2.0
Dew Point Temp_C              -0.5
Rel Hum_%                       83
Wind Speed_km/h                 46
Visibility_km                  9.7
Press_kPa                   100.13
Weather                   Rain,Fog
Name: 1630, dtype: object
Inserting row 1632
Error inserting row 1632: tuple index out of range
Row data: Date/Time           3/8/2012 23:00
Temp_C                         0.8
Dew Point Temp_C              -1.4
Rel Hum_%                       85
Wind Speed_km/h                 35
Visibility_km                  2.4
Press_kPa                   100.25
Weather                       Snow
Name: 1631, dtype: object
Inserting row 1633
Error inserting row 1633: tuple index out of range
Row data: Date/Time           3/9/2012 0:00
Temp_C                       -0.1
Dew Point Temp_C             -2.0
Rel Hum_%                      87
Wind Speed_km/h                28
Visibility_km                 2.8
Press_kPa                  100.33
Weather                      Snow
Name: 1632, dtype: object
Inserting row 1634
Error inserting row 1634: tuple index out of range
Row data: Date/Time           3/9/2012 1:00
Temp_C                        0.0
Dew Point Temp_C             -3.7
Rel Hum_%                      76
Wind Speed_km/h                22
Visibility_km                25.0
Press_kPa                  100.41
Weather             Mostly Cloudy
Name: 1633, dtype: object
Inserting row 1635
Error inserting row 1635: tuple index out of range
Row data: Date/Time           3/9/2012 2:00
Temp_C                       -1.2
Dew Point Temp_C             -6.6
Rel Hum_%                      67
Wind Speed_km/h                20
Visibility_km                25.0
Press_kPa                  100.62
Weather              Mainly Clear
Name: 1634, dtype: object
Inserting row 1636
Error inserting row 1636: tuple index out of range
Row data: Date/Time           3/9/2012 3:00
Temp_C                       -2.6
Dew Point Temp_C             -8.5
Rel Hum_%                      64
Wind Speed_km/h                24
Visibility_km                25.0
Press_kPa                  100.81
Weather              Mainly Clear
Name: 1635, dtype: object
Inserting row 1637
Error inserting row 1637: tuple index out of range
Row data: Date/Time           3/9/2012 4:00
Temp_C                       -3.9
Dew Point Temp_C             -8.7
Rel Hum_%                      69
Wind Speed_km/h                11
Visibility_km                25.0
Press_kPa                  100.97
Weather              Mainly Clear
Name: 1636, dtype: object
Inserting row 1638
Error inserting row 1638: tuple index out of range
Row data: Date/Time           3/9/2012 5:00
Temp_C                       -3.9
Dew Point Temp_C             -9.1
Rel Hum_%                      67
Wind Speed_km/h                20
Visibility_km                25.0
Press_kPa                  101.13
Weather              Mainly Clear
Name: 1637, dtype: object
Inserting row 1639
Error inserting row 1639: tuple index out of range
Row data: Date/Time           3/9/2012 6:00
Temp_C                       -4.3
Dew Point Temp_C             -9.0
Rel Hum_%                      70
Wind Speed_km/h                15
Visibility_km                25.0
Press_kPa                  101.26
Weather              Mainly Clear
Name: 1638, dtype: object
Inserting row 1640
Error inserting row 1640: tuple index out of range
Row data: Date/Time           3/9/2012 7:00
Temp_C                       -5.0
Dew Point Temp_C             -9.7
Rel Hum_%                      70
Wind Speed_km/h                15
Visibility_km                24.1
Press_kPa                  101.31
Weather                     Clear
Name: 1639, dtype: object
Inserting row 1641
Error inserting row 1641: tuple index out of range
Row data: Date/Time           3/9/2012 8:00
Temp_C                       -4.7
Dew Point Temp_C            -10.2
Rel Hum_%                      65
Wind Speed_km/h                15
Visibility_km                24.1
Press_kPa                  101.41
Weather                     Clear
Name: 1640, dtype: object
Inserting row 1642
Error inserting row 1642: tuple index out of range
Row data: Date/Time           3/9/2012 9:00
Temp_C                       -4.0
Dew Point Temp_C             -9.5
Rel Hum_%                      66
Wind Speed_km/h                20
Visibility_km                24.1
Press_kPa                  101.46
Weather                     Clear
Name: 1641, dtype: object
Inserting row 1643
Error inserting row 1643: tuple index out of range
Row data: Date/Time           3/9/2012 10:00
Temp_C                        -3.7
Dew Point Temp_C             -10.1
Rel Hum_%                       61
Wind Speed_km/h                 19
Visibility_km                 48.3
Press_kPa                   101.48
Weather               Mainly Clear
Name: 1642, dtype: object
Inserting row 1644
Error inserting row 1644: tuple index out of range
Row data: Date/Time           3/9/2012 11:00
Temp_C                        -3.0
Dew Point Temp_C             -10.0
Rel Hum_%                       58
Wind Speed_km/h                 17
Visibility_km                 48.3
Press_kPa                   101.47
Weather               Mainly Clear
Name: 1643, dtype: object
Inserting row 1645
Error inserting row 1645: tuple index out of range
Row data: Date/Time           3/9/2012 12:00
Temp_C                        -2.1
Dew Point Temp_C              -8.5
Rel Hum_%                       62
Wind Speed_km/h                 20
Visibility_km                 48.3
Press_kPa                   101.44
Weather               Mainly Clear
Name: 1644, dtype: object
Inserting row 1646
Error inserting row 1646: tuple index out of range
Row data: Date/Time           3/9/2012 13:00
Temp_C                        -1.5
Dew Point Temp_C              -8.8
Rel Hum_%                       57
Wind Speed_km/h                 15
Visibility_km                 48.3
Press_kPa                   101.42
Weather               Mainly Clear
Name: 1645, dtype: object
Inserting row 1647
Error inserting row 1647: tuple index out of range
Row data: Date/Time           3/9/2012 14:00
Temp_C                        -1.0
Dew Point Temp_C              -7.6
Rel Hum_%                       61
Wind Speed_km/h                 19
Visibility_km                 48.3
Press_kPa                   101.43
Weather               Mainly Clear
Name: 1646, dtype: object
Inserting row 1648
Error inserting row 1648: tuple index out of range
Row data: Date/Time           3/9/2012 15:00
Temp_C                        -1.1

Row data: Date/Time           3/15/2012 20:00
Temp_C                          2.3
Dew Point Temp_C               -0.2
Rel Hum_%                        84
Wind Speed_km/h                  24
Visibility_km                  25.0
Press_kPa                    101.86
Weather               Mostly Cloudy
Name: 1796, dtype: object
Inserting row 1798
Error inserting row 1798: tuple index out of range
Row data: Date/Time           3/15/2012 21:00
Temp_C                          2.0
Dew Point Temp_C                0.4
Rel Hum_%                        89
Wind Speed_km/h                  28
Visibility_km                  25.0
Press_kPa                     101.8
Weather                Rain Showers
Name: 1797, dtype: object
Inserting row 1799
Error inserting row 1799: tuple index out of range
Row data: Date/Time           3/15/2012 22:00
Temp_C                          2.1
Dew Point Temp_C                0.5
Rel Hum_%                        89
Wind Speed_km/h                  20
Visibility_km                  25.0
Press_kPa                    101.77
Weather               Mostly Cloudy
Name: 1798, dtype: object
Inserting row 1800
Error inserting row 1800: tuple index out of range
Row data: Date/Time           3/15/2012 23:00
Temp_C                          1.8
Dew Point Temp_C                0.2
Rel Hum_%                        89
Wind Speed_km/h                  19
Visibility_km                  25.0
Press_kPa                     101.7
Weather               Mostly Cloudy
Name: 1799, dtype: object
Inserting row 1801
Error inserting row 1801: tuple index out of range
Row data: Date/Time           3/16/2012 0:00
Temp_C                         1.8
Dew Point Temp_C               0.4
Rel Hum_%                       90
Wind Speed_km/h                 19
Visibility_km                 25.0
Press_kPa                   101.67
Weather                     Cloudy
Name: 1800, dtype: object
Inserting row 1802
Error inserting row 1802: tuple index out of range
Row data: Date/Time           3/16/2012 1:00
Temp_C                         1.9
Dew Point Temp_C               0.6
Rel Hum_%                       91
Wind Speed_km/h                 15
Visibility_km                 25.0
Press_kPa                   101.54
Weather               Rain Showers
Name: 1801, dtype: object
Inserting row 1803
Error inserting row 1803: tuple index out of range
Row data: Date/Time           3/16/2012 2:00
Temp_C                         1.1
Dew Point Temp_C               0.2
Rel Hum_%                       94
Wind Speed_km/h                 17
Visibility_km                 12.9
Press_kPa                   101.56
Weather                       Rain
Name: 1802, dtype: object
Inserting row 1804
Error inserting row 1804: tuple index out of range
Row data: Date/Time           3/16/2012 3:00
Temp_C                         1.1
Dew Point Temp_C               0.5
Rel Hum_%                       96
Wind Speed_km/h                 19
Visibility_km                  6.4
Press_kPa                   101.46
Weather                       Rain
Name: 1803, dtype: object
Inserting row 1805
Error inserting row 1805: tuple index out of range
Row data: Date/Time           3/16/2012 4:00
Temp_C                         1.0
Dew Point Temp_C               0.5
Rel Hum_%                       96
Wind Speed_km/h                 17
Visibility_km                  4.8
Press_kPa                   101.39
Weather                       Rain
Name: 1804, dtype: object
Inserting row 1806
Error inserting row 1806: tuple index out of range
Row data: Date/Time           3/16/2012 5:00
Temp_C                         0.7
Dew Point Temp_C               0.3
Rel Hum_%                       97
Wind Speed_km/h                 20
Visibility_km                  4.8
Press_kPa                   101.36
Weather                       Rain
Name: 1805, dtype: object
Inserting row 1807
Error inserting row 1807: tuple index out of range
Row data: Date/Time           3/16/2012 6:00
Temp_C                         0.6
Dew Point Temp_C               0.2
Rel Hum_%                       97
Wind Speed_km/h                 24
Visibility_km                  6.4
Press_kPa                   101.39
Weather                   Rain,Fog
Name: 1806, dtype: object
Inserting row 1808
Error inserting row 1808: tuple index out of range
Row data: Date/Time           3/16/2012 7:00
Temp_C                         1.1
Dew Point Temp_C               0.6
Rel Hum_%                       96
Wind Speed_km/h                 19
Visibility_km                  4.8
Press_kPa                   101.37
Weather                   Rain,Fog
Name: 1807, dtype: object
Inserting row 1809
Error inserting row 1809: tuple index out of range
Row data: Date/Time           3/16/2012 8:00
Temp_C                         1.1
Dew Point Temp_C               0.7
Rel Hum_%                       97
Wind Speed_km/h                 15
Visibility_km                  4.0
Press_kPa                   101.38
Weather                   Rain,Fog
Name: 1808, dtype: object
Inserting row 1810
Error inserting row 1810: tuple index out of range
Row data: Date/Time           3/16/2012 9:00
Temp_C                         1.1
Dew Point Temp_C               0.7
Rel Hum_%                       97
Wind Speed_km/h                 17
Visibility_km                  4.0
Press_kPa                   101.41
Weather                   Rain,Fog
Name: 1809, dtype: object
Inserting row 1811
Error inserting row 1811: tuple index out of range
Row data: Date/Time           3/16/2012 10:00
Temp_C                          1.5
Dew Point Temp_C                1.1
Rel Hum_%                        97
Wind Speed_km/h                  13
Visibility_km                   4.8
Press_kPa                    101.41
Weather                    Rain,Fog
Name: 1810, dtype: object
Inserting row 1812
Error inserting row 1812: tuple index out of range
Row data: Date/Time           3/16/2012 11:00
Temp_C                          1.8
Dew Point Temp_C                1.3
Rel Hum_%                        96
Wind Speed_km/h                  13
Visibility_km                   8.0
Press_kPa                     101.4
Weather                    Rain,Fog
Name: 1811, dtype: object
Inserting row 1813
Error inserting row 1813: tuple index out of range
Row data: Date/Time           3/16/2012 12:00
Temp_C                          2.5
Dew Point Temp_C                2.0
Rel Hum_%                        96
Wind Speed_km/h                   6
Visibility_km                   8.0
Press_kPa                    101.42
Weather                         Fog
Name: 1812, dtype: object
Inserting row 1814
Error inserting row 1814: tuple index out of range
Row data: Date/Time           3/16/2012 13:00
Temp_C                          3.3
Dew Point Temp_C                2.8
Rel Hum_%                        97
Wind Speed_km/h                   6
Visibility_km                   9.7
Press_kPa                    101.38
Weather                         Fog
Name: 1813, dtype: object
Inserting row 1815
Error inserting row 1815: tuple index out of range
Row data: Date/Time           3/16/2012 14:00
Temp_C                          4.0
Dew Point Temp_C                3.2
Rel Hum_%                        95
Wind Speed_km/h                  11
Visibility_km                   9.7
Press_kPa                     101.4
Weather                         Fog
Name: 1814, dtype: object
Inserting row 1816
Error inserting row 1816: tuple index out of range
Row data: Date/Time           3/16/2012 15:00
Temp_C                          3.7
Dew Point Temp_C                3.2
Rel Hum_%                        97
Wind Speed_km/h                   7
Visibility_km                   6.4
Press_kPa                    101.48
Weather                         Fog
Name: 1815, dtype: object
Inserting row 1817
Error inserting row 1817: tuple index out of range
Row data: Date/Time           3/16/2012 16:00
Temp_C                          4.3
Dew Point Temp_C                3.5
Rel Hum_%                        95
Wind Speed_km/h                   4
Visibility_km                   8.0
Press_kPa                    101.53
Weather                         Fog
Name: 1816, dtype: object
Inserting row 1818
Error inserting row 1818: tuple index out of range
Row data: Date/Time           3/16/2012 17:00
Temp_C                          4.1
Dew Point Temp_C                3.2
Rel Hum_%                        94
Wind Speed_km/h                   7
Visibility_km                   8.0
Press_kPa                    101.61
Weather                         Fog
Name: 1817, dtype: object
Inserting row 1819
Error inserting row 1819: tuple index out of range
Row data: Date/Time           3/16/2012 18:00
Temp_C                          3.8
Dew Point Temp_C                3.2
Rel Hum_%                        96
Wind Speed_km/h                   7
Visibility_km                   4.8
Press_kPa                    101.71
Weather                 Drizzle,Fog
Name: 1818, dtype: object
Inserting row 1820
Error inserting row 1820: tuple index out of range
Row data: Date/Time           3/16/2012 19:00
Temp_C                          3.8
Dew Point Temp_C                3.2
Rel Hum_%                        96
Wind Speed_km/h                   0
Visibility_km                   3.2
Press_kPa                    101.77
Weather                 Drizzle,Fog
Name: 1819, dtype: object
Inserting row 1821
Error inserting row 1821: tuple index out of range
Row data: Date/Time           3/16/2012 20:00
Temp_C                          3.7
Dew Point Temp_C                3.3
Rel Hum_%                        97
Wind Speed_km/h                   0
Visibility_km                   2.0
Press_kPa                    101.93
Weather                 Drizzle,Fog
Name: 1820, dtype: object
Inserting row 1822
Error inserting row 1822: tuple index out of range
Row data: Date/Time           3/16/2012 21:00
Temp_C                          4.0
Dew Point Temp_C                3.7
Rel Hum_%                        98
Wind Speed_km/h                   7
Visibility_km                   3.2
Press_kPa                    101.93
Weather                 Drizzle,Fog
Name: 1821, dtype: object
Inserting row 1823
Error inserting row 1823: tuple index out of range
Row data: Date/Time           3/16/2012 22:00
Temp_C                          3.8
Dew Point Temp_C                3.4
Rel Hum_%                        97
Wind Speed_km/h                   0
Visibility_km                   6.4
Press_kPa                    102.04
Weather                 Drizzle,Fog
Name: 1822, dtype: object
Inserting row 1824
Error inserting row 1824: tuple index out of range
Row data: Date/Time           3/16/2012 23:00
Temp_C                          3.7
Dew Point Temp_C                3.3
Rel Hum_%                        97
Wind Speed_km/h                   0
Visibility_km                   3.2
Press_kPa                    102.07
Weather                 Drizzle,Fog
Name: 1823, dtype: object
Inserting row 1825
Error inserting row 1825: tuple index out of range
Row data: Date/Time           3/17/2012 0:00
Temp_C                         3.8
Dew Point Temp_C               3.5
Rel Hum_%                       98
Wind Speed_km/h                  4
Visibility_km                  1.6
Press_kPa                   102.05
Weather                Drizzle,Fog
Name: 1824, dtype: object
Inserting row 1826
Error inserting row 1826: tuple index out of range
Row data: Date/Time           3/17/2012 1:00
Temp_C                         3.0
Dew Point Temp_C               2.7
Rel Hum_%                       98
Wind Speed_km/h                  6
Visibility_km                  0.6
Press_kPa                   102.05
Weather                        Fog
Name: 1825, dtype: object
Inserting row 1827
Error inserting row 1827: tuple index out of range
Row data: Date/Time           3/17/2012 2:00
Temp_C                         2.7
Dew Point Temp_C               2.5
Rel Hum_%                       99
Wind Speed_km/h                  4
Visibility_km                  0.2
Press_kPa                   102.09
Weather                        Fog
Name: 1826, dtype: object
Inserting row 1828
Error inserting row 1828: tuple index out of range
Row data: Date/Time           3/17/2012 3:00
Temp_C                         1.8
Dew Point Temp_C               1.6
Rel Hum_%                       99
Wind Speed_km/h                  4
Visibility_km                  0.2
Press_kPa                    102.1
Weather                        Fog
Name: 1827, dtype: object
Inserting row 1829
Error inserting row 1829: tuple index out of range
Row data: Date/Time           3/17/2012 4:00
Temp_C                         0.3
Dew Point Temp_C               0.1
Rel Hum_%                       99
Wind Speed_km/h                  0
Visibility_km                  0.2
Press_kPa                   102.15
Weather                        Fog
Name: 1828, dtype: object
Inserting row 1830
Error inserting row 1830: tuple index out of range
Row data: Date/Time           3/17/2012 5:00
Temp_C                        -0.1
Dew Point Temp_C              -0.3
Rel Hum_%                       99
Wind Speed_km/h                  0
Visibility_km                  0.8
Press_kPa                    102.2
Weather               Freezing Fog
Name: 1829, dtype: object
Inserting row 1831
Error inserting row 1831: tuple index out of range
Row data: Date/Time           3/17/2012 6:00
Temp_C                        -0.1
Dew Point Temp_C              -0.4
Rel Hum_%                       98
Wind Speed_km/h                  4
Visibility_km                  0.2
Press_kPa                   102.26
Weather               Freezing Fog
Name: 1830, dtype: object
Inserting row 1832
Error inserting row 1832: tuple index out of range
Row data: Date/Time           3/17/2012 7:00
Temp_C                         0.5
Dew Point Temp_C               0.4
Rel Hum_%                       99
Wind Speed_km/h                  0
Visibility_km                  0.2
Press_kPa                   102.34
Weather                        Fog
Name: 1831, dtype: object
Inserting row 1833
Error inserting row 1833: tuple index out of range
Row data: Date/Time           3/17/2012 8:00
Temp_C                         1.0
Dew Point Temp_C               0.9
Rel Hum_%                       99
Wind Speed_km/h                  0
Visibility_km                  0.2
Press_kPa                   102.39
Weather                        Fog
Name: 1832, dtype: object
Inserting row 1834
Error inserting row 1834: tuple index out of range
Row data: Date/Time           3/17/2012 9:00
Temp_C                         1.6
Dew Point Temp_C               1.5
Rel Hum_%                       99
Wind Speed_km/h                  4
Visibility_km                  0.2
Press_kPa                   102.38
Weather                        Fog
Name: 1833, dtype: object
Inserting row 1835
Error inserting row 1835: tuple index out of range
Row data: Date/Time           3/17/2012 10:00
Temp_C                          2.6
Dew Point Temp_C                2.6
Rel Hum_%                       100
Wind Speed_km/h                   0
Visibility_km                   0.2
Press_kPa                    102.37
Weather                         Fog
Name: 1834, dtype: object
Inserting row 1836
Error inserting row 1836: tuple index out of range
Row data: Date/Time           3/17/2012 11:00
Temp_C                          4.1
Dew Point Temp_C                3.8
Rel Hum_%                        98
Wind Speed_km/h                   4
Visibility_km                   0.6
Press_kPa                    102.34
Weather                         Fog
Name: 1835, dtype: object
Inserting row 1837
Error inserting row 1837: tuple index out of range
Row data: Date/Time           3/17/2012 12:00
Temp_C                          5.7
Dew Point Temp_C                5.3
Rel Hum_%                        97
Wind Speed_km/h                   4
Visibility_km                   9.7
Press_kPa                    102.32
Weather                         Fog
Name: 1836, dtype: object
Inserting row 1838
Error inserting row 1838: tuple index out of range
Row data: Date/Time           3/17/2012 13:00
Temp_C                          8.1
Dew Point Temp_C                6.2
Rel Hum_%                        88
Wind Speed_km/h                   7
Visibility_km                  16.1
Press_kPa                    102.18
Weather                      Cloudy
Name: 1837, dtype: object
Inserting row 1839
Error inserting row 1839: tuple index out of range
Row data: Date/Time           3/17/2012 14:00
Temp_C                          9.2
Dew Point Temp_C                4.3
Rel Hum_%                        71
Wind Speed_km/h                   7
Visibility_km                  24.1
Press_kPa                    102.13
Weather                      Cloudy
Name: 1838, dtype: object
Inserting row 1840
Error inserting row 1840: tuple index out of range
Row data: Date/Time           3/17/2012 15:00
Temp_C                         10.2
Dew Point Temp_C                4.4
Rel Hum_%                        67
Wind Speed_km/h                   6
Visibility_km                  24.1
Press_kPa                    102.07
Weather                      Cloudy
Name: 1839, dtype: object
Inserting row 1841
Error inserting row 1841: tuple index out of range
Row data: Date/Time           3/17/2012 16:00
Temp_C                         10.5
Dew Point Temp_C                4.1
Rel Hum_%                        65
Wind Speed_km/h                   7
Visibility_km                  48.3
Press_kPa                    102.02
Weather                      Cloudy
Name: 1840, dtype: object
Inserting row 1842
Error inserting row 1842: tuple index out of range
Row data: Date/Time           3/17/2012 17:00
Temp_C                         10.1
Dew Point Temp_C                4.7
Rel Hum_%                        69
Wind Speed_km/h                   9
Visibility_km                  48.3
Press_kPa                    101.97
Weather                      Cloudy
Name: 1841, dtype: object
Inserting row 1843
Error inserting row 1843: tuple index out of range
Row data: Date/Time           3/17/2012 18:00
Temp_C                         10.1
Dew Point Temp_C                5.4
Rel Hum_%                        73
Wind Speed_km/h                   7
Visibility_km                  48.3
Press_kPa                    101.95
Weather                      Cloudy
Name: 1842, dtype: object
Inserting row 1844
Error inserting row 1844: tuple index out of range
Row data: Date/Time           3/17/2012 19:00
Temp_C                          9.8
Dew Point Temp_C                5.9
Rel Hum_%                        77
Wind Speed_km/h                   6
Visibility_km                  25.0
Press_kPa                    101.93
Weather                      Cloudy
Name: 1843, dtype: object
Inserting row 1845
Error inserting row 1845: tuple index out of range
Row data: Date/Time           3/17/2012 20:00
Temp_C                          9.3
Dew Point Temp_C                5.2
Rel Hum_%                        76
Wind Speed_km/h                   0
Visibility_km                  25.0
Press_kPa                    101.92
Weather                      Cloudy
Name: 1844, dtype: object
Inserting row 1846
Error inserting row 1846: tuple index out of range
Row data: Date/Time           3/17/2012 21:00
Temp_C                          8.8
Dew Point Temp_C                5.5
Rel Hum_%                        80
Wind Speed_km/h                   4
Visibility_km                  25.0
Press_kPa                     101.8
Weather               Mostly Cloudy
Name: 1845, dtype: object
Inserting row 1847
Error inserting row 1847: tuple index out of range
Row data: Date/Time           3/17/2012 22:00
Temp_C                          7.7
Dew Point Temp_C                4.9
Rel Hum_%                        82
Wind Speed_km/h                   0
Visibility_km                  25.0
Press_kPa                    101.77
Weather                Mainly Clear
Name: 1846, dtype: object
Inserting row 1848
Error inserting row 1848: tuple index out of range
Row data: Date/Time           3/17/2012 23:00

Row data: Date/Time           3/23/2012 13:00
Temp_C                         16.8
Dew Point Temp_C               -2.3
Rel Hum_%                        27
Wind Speed_km/h                   7
Visibility_km                  48.3
Press_kPa                    101.71
Weather               Mostly Cloudy
Name: 1981, dtype: object
Inserting row 1983
Error inserting row 1983: tuple index out of range
Row data: Date/Time           3/23/2012 14:00
Temp_C                         16.6
Dew Point Temp_C               -6.8
Rel Hum_%                        19
Wind Speed_km/h                  15
Visibility_km                  48.3
Press_kPa                    101.66
Weather               Mostly Cloudy
Name: 1982, dtype: object
Inserting row 1984
Error inserting row 1984: tuple index out of range
Row data: Date/Time           3/23/2012 15:00
Temp_C                         16.4
Dew Point Temp_C               -6.8
Rel Hum_%                        20
Wind Speed_km/h                  15
Visibility_km                  48.3
Press_kPa                    101.63
Weather               Mostly Cloudy
Name: 1983, dtype: object
Inserting row 1985
Error inserting row 1985: tuple index out of range
Row data: Date/Time           3/23/2012 16:00
Temp_C                         15.5
Dew Point Temp_C               -9.0
Rel Hum_%                        18
Wind Speed_km/h                  22
Visibility_km                  48.3
Press_kPa                     101.6
Weather                      Cloudy
Name: 1984, dtype: object
Inserting row 1986
Error inserting row 1986: tuple index out of range
Row data: Date/Time           3/23/2012 17:00
Temp_C                         14.7
Dew Point Temp_C               -5.1
Rel Hum_%                        25
Wind Speed_km/h                  13
Visibility_km                  48.3
Press_kPa                    101.62
Weather                      Cloudy
Name: 1985, dtype: object
Inserting row 1987
Error inserting row 1987: tuple index out of range
Row data: Date/Time           3/23/2012 18:00
Temp_C                         13.4
Dew Point Temp_C               -5.8
Rel Hum_%                        26
Wind Speed_km/h                  13
Visibility_km                  48.3
Press_kPa                    101.64
Weather                      Cloudy
Name: 1986, dtype: object
Inserting row 1988
Error inserting row 1988: tuple index out of range
Row data: Date/Time           3/23/2012 19:00
Temp_C                         11.8
Dew Point Temp_C               -5.5
Rel Hum_%                        29
Wind Speed_km/h                  11
Visibility_km                  25.0
Press_kPa                    101.68
Weather               Mostly Cloudy
Name: 1987, dtype: object
Inserting row 1989
Error inserting row 1989: tuple index out of range
Row data: Date/Time           3/23/2012 20:00
Temp_C                         10.9
Dew Point Temp_C               -5.9
Rel Hum_%                        30
Wind Speed_km/h                   6
Visibility_km                  25.0
Press_kPa                    101.72
Weather                      Cloudy
Name: 1988, dtype: object
Inserting row 1990
Error inserting row 1990: tuple index out of range
Row data: Date/Time           3/23/2012 21:00
Temp_C                         10.8
Dew Point Temp_C               -8.0
Rel Hum_%                        26
Wind Speed_km/h                  15
Visibility_km                  25.0
Press_kPa                     101.7
Weather               Mostly Cloudy
Name: 1989, dtype: object
Inserting row 1991
Error inserting row 1991: tuple index out of range
Row data: Date/Time           3/23/2012 22:00
Temp_C                         10.6
Dew Point Temp_C               -8.9
Rel Hum_%                        24
Wind Speed_km/h                  19
Visibility_km                  25.0
Press_kPa                    101.73
Weather                      Cloudy
Name: 1990, dtype: object
Inserting row 1992
Error inserting row 1992: tuple index out of range
Row data: Date/Time           3/23/2012 23:00
Temp_C                          9.9
Dew Point Temp_C               -8.7
Rel Hum_%                        26
Wind Speed_km/h                  19
Visibility_km                  25.0
Press_kPa                    101.78
Weather               Mostly Cloudy
Name: 1991, dtype: object
Inserting row 1993
Error inserting row 1993: tuple index out of range
Row data: Date/Time           3/24/2012 0:00
Temp_C                         8.4
Dew Point Temp_C              -9.1
Rel Hum_%                       28
Wind Speed_km/h                 22
Visibility_km                 25.0
Press_kPa                    101.8
Weather              Mostly Cloudy
Name: 1992, dtype: object
Inserting row 1994
Error inserting row 1994: tuple index out of range
Row data: Date/Time           3/24/2012 1:00
Temp_C                         7.3
Dew Point Temp_C              -9.4
Rel Hum_%                       29
Wind Speed_km/h                 20
Visibility_km                 25.0
Press_kPa                   101.85
Weather               Mainly Clear
Name: 1993, dtype: object
Inserting row 1995
Error inserting row 1995: tuple index out of range
Row data: Date/Time           3/24/2012 2:00
Temp_C                         6.2
Dew Point Temp_C             -10.6
Rel Hum_%                       29
Wind Speed_km/h                 19
Visibility_km                 25.0
Press_kPa                   101.86
Weather              Mostly Cloudy
Name: 1994, dtype: object
Inserting row 1996
Error inserting row 1996: tuple index out of range
Row data: Date/Time           3/24/2012 3:00
Temp_C                         5.3
Dew Point Temp_C              -9.4
Rel Hum_%                       34
Wind Speed_km/h                 22
Visibility_km                 25.0
Press_kPa                   101.86
Weather              Mostly Cloudy
Name: 1995, dtype: object
Inserting row 1997
Error inserting row 1997: tuple index out of range
Row data: Date/Time           3/24/2012 4:00
Temp_C                         4.4
Dew Point Temp_C              -8.9
Rel Hum_%                       37
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   101.88
Weather                     Cloudy
Name: 1996, dtype: object
Inserting row 1998
Error inserting row 1998: tuple index out of range
Row data: Date/Time           3/24/2012 5:00
Temp_C                         3.6
Dew Point Temp_C              -8.5
Rel Hum_%                       41
Wind Speed_km/h                 19
Visibility_km                 25.0
Press_kPa                   101.89
Weather                     Cloudy
Name: 1997, dtype: object
Inserting row 1999
Error inserting row 1999: tuple index out of range
Row data: Date/Time           3/24/2012 6:00
Temp_C                         3.2
Dew Point Temp_C              -8.8
Rel Hum_%                       41
Wind Speed_km/h                 19
Visibility_km                 24.1
Press_kPa                   101.93
Weather                     Cloudy
Name: 1998, dtype: object
Inserting row 2000
Error inserting row 2000: tuple index out of range
Row data: Date/Time           3/24/2012 7:00
Temp_C                         3.1
Dew Point Temp_C              -9.3
Rel Hum_%                       40
Wind Speed_km/h                 15
Visibility_km                 24.1
Press_kPa                   101.97
Weather                     Cloudy
Name: 1999, dtype: object
Inserting row 2001
Error inserting row 2001: tuple index out of range
Row data: Date/Time           3/24/2012 8:00
Temp_C                         2.7
Dew Point Temp_C              -9.4
Rel Hum_%                       40
Wind Speed_km/h                 19
Visibility_km                 24.1
Press_kPa                   101.98
Weather                     Cloudy
Name: 2000, dtype: object
Inserting row 2002
Error inserting row 2002: tuple index out of range
Row data: Date/Time           3/24/2012 9:00
Temp_C                         3.0
Dew Point Temp_C             -11.2
Rel Hum_%                       34
Wind Speed_km/h                 22
Visibility_km                 48.3
Press_kPa                   101.94
Weather                     Cloudy
Name: 2001, dtype: object
Inserting row 2003
Error inserting row 2003: tuple index out of range
Row data: Date/Time           3/24/2012 10:00
Temp_C                          3.7
Dew Point Temp_C               -9.5
Rel Hum_%                        37
Wind Speed_km/h                  22
Visibility_km                  48.3
Press_kPa                    101.89
Weather                      Cloudy
Name: 2002, dtype: object
Inserting row 2004
Error inserting row 2004: tuple index out of range
Row data: Date/Time           3/24/2012 11:00
Temp_C                          3.7
Dew Point Temp_C              -11.1
Rel Hum_%                        33
Wind Speed_km/h                  22
Visibility_km                  48.3
Press_kPa                    101.86
Weather                      Cloudy
Name: 2003, dtype: object
Inserting row 2005
Error inserting row 2005: tuple index out of range
Row data: Date/Time           3/24/2012 12:00
Temp_C                          4.8
Dew Point Temp_C              -10.3
Rel Hum_%                        33
Wind Speed_km/h                  19
Visibility_km                  48.3
Press_kPa                     101.8
Weather                      Cloudy
Name: 2004, dtype: object
Inserting row 2006
Error inserting row 2006: tuple index out of range
Row data: Date/Time           3/24/2012 13:00
Temp_C                          4.7
Dew Point Temp_C              -10.9
Rel Hum_%                        31
Wind Speed_km/h                  19
Visibility_km                  48.3
Press_kPa                    101.74
Weather                      Cloudy
Name: 2005, dtype: object
Inserting row 2007
Error inserting row 2007: tuple index out of range
Row data: Date/Time           3/24/2012 14:00
Temp_C                          6.1
Dew Point Temp_C               -8.7
Rel Hum_%                        34
Wind Speed_km/h                   9
Visibility_km                  48.3
Press_kPa                    101.68
Weather                      Cloudy
Name: 2006, dtype: object
Inserting row 2008
Error inserting row 2008: tuple index out of range
Row data: Date/Time           3/24/2012 15:00
Temp_C                          5.8
Dew Point Temp_C               -9.8
Rel Hum_%                        32
Wind Speed_km/h                   4
Visibility_km                  48.3
Press_kPa                    101.61
Weather                      Cloudy
Name: 2007, dtype: object
Inserting row 2009
Error inserting row 2009: tuple index out of range
Row data: Date/Time           3/24/2012 16:00
Temp_C                          6.1
Dew Point Temp_C               -9.5
Rel Hum_%                        32
Wind Speed_km/h                   7
Visibility_km                  48.3
Press_kPa                    101.53
Weather                      Cloudy
Name: 2008, dtype: object
Inserting row 2010
Error inserting row 2010: tuple index out of range
Row data: Date/Time           3/24/2012 17:00
Temp_C                          6.1
Dew Point Temp_C              -10.3
Rel Hum_%                        30
Wind Speed_km/h                  13
Visibility_km                  48.3
Press_kPa                    101.47
Weather                      Cloudy
Name: 2009, dtype: object
Inserting row 2011
Error inserting row 2011: tuple index out of range
Row data: Date/Time           3/24/2012 18:00
Temp_C                          6.1
Dew Point Temp_C               -9.9
Rel Hum_%                        31
Wind Speed_km/h                  13
Visibility_km                  48.3
Press_kPa                    101.46
Weather                      Cloudy
Name: 2010, dtype: object
Inserting row 2012
Error inserting row 2012: tuple index out of range
Row data: Date/Time           3/24/2012 19:00
Temp_C                          6.2
Dew Point Temp_C               -8.4
Rel Hum_%                        34
Wind Speed_km/h                  13
Visibility_km                  25.0
Press_kPa                    101.38
Weather                      Cloudy
Name: 2011, dtype: object
Inserting row 2013
Error inserting row 2013: tuple index out of range
Row data: Date/Time           3/24/2012 20:00
Temp_C                          6.3
Dew Point Temp_C               -7.4
Rel Hum_%                        37
Wind Speed_km/h                   9
Visibility_km                  25.0
Press_kPa                    101.35
Weather                      Cloudy
Name: 2012, dtype: object
Inserting row 2014
Error inserting row 2014: tuple index out of range
Row data: Date/Time           3/24/2012 21:00
Temp_C                          6.6
Dew Point Temp_C               -8.1
Rel Hum_%                        34
Wind Speed_km/h                   9
Visibility_km                  25.0
Press_kPa                    101.28
Weather                      Cloudy
Name: 2013, dtype: object
Inserting row 2015
Error inserting row 2015: tuple index out of range
Row data: Date/Time           3/24/2012 22:00
Temp_C                          6.6
Dew Point Temp_C               -7.8
Rel Hum_%                        35
Wind Speed_km/h                  11
Visibility_km                  25.0
Press_kPa                    101.22
Weather                      Cloudy
Name: 2014, dtype: object
Inserting row 2016
Error inserting row 2016: tuple index out of range
Row data: Date/Time           3/24/2012 23:00
Temp_C                          6.5
Dew Point Temp_C               -7.2
Rel Hum_%                        37
Wind Speed_km/h                   7
Visibility_km                  25.0
Press_kPa                    101.15
Weather                Rain Showers
Name: 2015, dtype: object
Inserting row 2017
Error inserting row 2017: tuple index out of range
Row data: Date/Time           3/25/2012 0:00
Temp_C                         5.8
Dew Point Temp_C              -5.7
Rel Hum_%                       43
Wind Speed_km/h                 20
Visibility_km                 25.0
Press_kPa                   101.05
Weather                       Rain
Name: 2016, dtype: object
Inserting row 2018
Error inserting row 2018: tuple index out of range
Row data: Date/Time           3/25/2012 1:00
Temp_C                         5.9
Dew Point Temp_C              -6.2
Rel Hum_%                       41
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   101.03
Weather                     Cloudy
Name: 2017, dtype: object
Inserting row 2019
Error inserting row 2019: tuple index out of range
Row data: Date/Time           3/25/2012 2:00
Temp_C                         5.9
Dew Point Temp_C              -5.0
Rel Hum_%                       45
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                   100.91
Weather               Rain Showers
Name: 2018, dtype: object
Inserting row 2020
Error inserting row 2020: tuple index out of range
Row data: Date/Time           3/25/2012 3:00
Temp_C                         5.8
Dew Point Temp_C              -4.2
Rel Hum_%                       49
Wind Speed_km/h                  7
Visibility_km                 25.0
Press_kPa                   100.84
Weather                     Cloudy
Name: 2019, dtype: object
Inserting row 2021
Error inserting row 2021: tuple index out of range
Row data: Date/Time           3/25/2012 4:00
Temp_C                         5.3
Dew Point Temp_C              -4.3
Rel Hum_%                       50
Wind Speed_km/h                 19
Visibility_km                 25.0
Press_kPa                   100.79
Weather                     Cloudy
Name: 2020, dtype: object
Inserting row 2022
Error inserting row 2022: tuple index out of range
Row data: Date/Time           3/25/2012 5:00
Temp_C                         4.5
Dew Point Temp_C              -2.9
Rel Hum_%                       59
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   100.73
Weather                     Cloudy
Name: 2021, dtype: object
Inserting row 2023
Error inserting row 2023: tuple index out of range
Row data: Date/Time           3/25/2012 6:00
Temp_C                         3.8
Dew Point Temp_C              -0.9
Rel Hum_%                       71
Wind Speed_km/h                 15
Visibility_km                 24.1
Press_kPa                   100.76
Weather               Rain Showers
Name: 2022, dtype: object
Inserting row 2024
Error inserting row 2024: tuple index out of range
Row data: Date/Time           3/25/2012 7:00
Temp_C                         2.5
Dew Point Temp_C               0.9
Rel Hum_%                       89
Wind Speed_km/h                 17
Visibility_km                 24.1
Press_kPa                   100.76
Weather                       Rain
Name: 2023, dtype: object
Inserting row 2025
Error inserting row 2025: tuple index out of range
Row data: Date/Time           3/25/2012 8:00
Temp_C                         3.0
Dew Point Temp_C               1.5
Rel Hum_%                       90
Wind Speed_km/h                  6
Visibility_km                 24.1
Press_kPa                   100.74
Weather                       Rain
Name: 2024, dtype: object
Inserting row 2026
Error inserting row 2026: tuple index out of range
Row data: Date/Time           3/25/2012 9:00
Temp_C                         3.1
Dew Point Temp_C               2.0
Rel Hum_%                       92
Wind Speed_km/h                  0
Visibility_km                  6.4
Press_kPa                   100.71
Weather                   Rain,Fog
Name: 2025, dtype: object
Inserting row 2027
Error inserting row 2027: tuple index out of range
Row data: Date/Time           3/25/2012 10:00
Temp_C                          3.9
Dew Point Temp_C                2.7
Rel Hum_%                        92
Wind Speed_km/h                   0
Visibility_km                  12.9
Press_kPa                    100.66
Weather                      Cloudy
Name: 2026, dtype: object
Inserting row 2028
Error inserting row 2028: tuple index out of range
Row data: Date/Time           3/25/2012 11:00
Temp_C                          5.2
Dew Point Temp_C                3.6
Rel Hum_%                        89
Wind Speed_km/h                   6
Visibility_km                  16.1
Press_kPa                    100.58
Weather                      Cloudy
Name: 2027, dtype: object
Inserting row 2029
Error inserting row 2029: tuple index out of range
Row data: Date/Time           3/25/2012 12:00
Temp_C                          5.9
Dew Point Temp_C                3.7
Rel Hum_%                        86
Wind Speed_km/h                   6
Visibility_km                  24.1
Press_kPa                    100.54
Weather                      Cloudy
Name: 2028, dtype: object
Inserting row 2030
Error inserting row 2030: tuple index out of range
Row data: Date/Time           3/25/2012 13:00
Temp_C                          6.6
Dew Point Temp_C                4.0
Rel Hum_%                        83
Wind Speed_km/h                   6
Visibility_km                  24.1
Press_kPa                    100.47
Weather                      Cloudy
Name: 2029, dtype: object
Inserting row 2031
Error inserting row 2031: tuple index out of range
Row data: Date/Time           3/25/2012 14:00
Temp_C                          7.5
Dew Point Temp_C                4.1
Rel Hum_%                        79
Wind Speed_km/h                  11
Visibility_km                  24.1
Press_kPa                    100.39
Weather                      Cloudy
Name: 2030, dtype: object
Inserting row 2032
Error inserting row 2032: tuple index out of range
Row data: Date/Time           3/25/2012 15:00
Temp_C                          7.6
Dew Point Temp_C                4.6
Rel Hum_%                        81
Wind Speed_km/h                   9
Visibility_km                  24.1
Press_kPa                    100.29
Weather               Mostly Cloudy
Name: 2031, dtype: object
Inserting row 2033
Error inserting row 2033: tuple index out of range
Row data: Date/Time           3/25/2012 16:00

Row data: Date/Time           4/1/2012 14:00
Temp_C                         4.7
Dew Point Temp_C               1.1
Rel Hum_%                       77
Wind Speed_km/h                  9
Visibility_km                 24.1
Press_kPa                    100.2
Weather                       Rain
Name: 2198, dtype: object
Inserting row 2200
Error inserting row 2200: tuple index out of range
Row data: Date/Time           4/1/2012 15:00
Temp_C                         3.8
Dew Point Temp_C               1.5
Rel Hum_%                       85
Wind Speed_km/h                 19
Visibility_km                 24.1
Press_kPa                   100.14
Weather                       Rain
Name: 2199, dtype: object
Inserting row 2201
Error inserting row 2201: tuple index out of range
Row data: Date/Time           4/1/2012 16:00
Temp_C                         3.0
Dew Point Temp_C               0.7
Rel Hum_%                       85
Wind Speed_km/h                 17
Visibility_km                 24.1
Press_kPa                    100.1
Weather                       Rain
Name: 2200, dtype: object
Inserting row 2202
Error inserting row 2202: tuple index out of range
Row data: Date/Time           4/1/2012 17:00
Temp_C                         2.8
Dew Point Temp_C               0.5
Rel Hum_%                       85
Wind Speed_km/h                 22
Visibility_km                 24.1
Press_kPa                   100.12
Weather                       Rain
Name: 2201, dtype: object
Inserting row 2203
Error inserting row 2203: tuple index out of range
Row data: Date/Time           4/1/2012 18:00
Temp_C                         2.5
Dew Point Temp_C               0.3
Rel Hum_%                       85
Wind Speed_km/h                 11
Visibility_km                 24.1
Press_kPa                   100.11
Weather                       Rain
Name: 2202, dtype: object
Inserting row 2204
Error inserting row 2204: tuple index out of range
Row data: Date/Time           4/1/2012 19:00
Temp_C                         2.6
Dew Point Temp_C               0.2
Rel Hum_%                       84
Wind Speed_km/h                  0
Visibility_km                 25.0
Press_kPa                   100.14
Weather                       Rain
Name: 2203, dtype: object
Inserting row 2205
Error inserting row 2205: tuple index out of range
Row data: Date/Time           4/1/2012 20:00
Temp_C                         2.6
Dew Point Temp_C               0.2
Rel Hum_%                       84
Wind Speed_km/h                 11
Visibility_km                 19.3
Press_kPa                   100.18
Weather                       Rain
Name: 2204, dtype: object
Inserting row 2206
Error inserting row 2206: tuple index out of range
Row data: Date/Time           4/1/2012 21:00
Temp_C                         2.6
Dew Point Temp_C               0.7
Rel Hum_%                       87
Wind Speed_km/h                 13
Visibility_km                 16.1
Press_kPa                   100.21
Weather                       Rain
Name: 2205, dtype: object
Inserting row 2207
Error inserting row 2207: tuple index out of range
Row data: Date/Time           4/1/2012 22:00
Temp_C                         2.5
Dew Point Temp_C               0.7
Rel Hum_%                       88
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   100.22
Weather                     Cloudy
Name: 2206, dtype: object
Inserting row 2208
Error inserting row 2208: tuple index out of range
Row data: Date/Time           4/1/2012 23:00
Temp_C                         2.0
Dew Point Temp_C               0.3
Rel Hum_%                       88
Wind Speed_km/h                  7
Visibility_km                 25.0
Press_kPa                   100.21
Weather                     Cloudy
Name: 2207, dtype: object
Inserting row 2209
Error inserting row 2209: tuple index out of range
Row data: Date/Time           4/2/2012 0:00
Temp_C                        0.4
Dew Point Temp_C             -1.2
Rel Hum_%                      89
Wind Speed_km/h                11
Visibility_km                16.1
Press_kPa                  100.22
Weather              Mainly Clear
Name: 2208, dtype: object
Inserting row 2210
Error inserting row 2210: tuple index out of range
Row data: Date/Time           4/2/2012 1:00
Temp_C                       -0.1
Dew Point Temp_C             -1.4
Rel Hum_%                      91
Wind Speed_km/h                 7
Visibility_km                 9.7
Press_kPa                  100.27
Weather                       Fog
Name: 2209, dtype: object
Inserting row 2211
Error inserting row 2211: tuple index out of range
Row data: Date/Time           4/2/2012 2:00
Temp_C                       -0.4
Dew Point Temp_C             -1.8
Rel Hum_%                      90
Wind Speed_km/h                 0
Visibility_km                12.9
Press_kPa                  100.31
Weather                     Clear
Name: 2210, dtype: object
Inserting row 2212
Error inserting row 2212: tuple index out of range
Row data: Date/Time           4/2/2012 3:00
Temp_C                       -1.4
Dew Point Temp_C             -2.8
Rel Hum_%                      90
Wind Speed_km/h                 0
Visibility_km                 8.0
Press_kPa                  100.33
Weather                       Fog
Name: 2211, dtype: object
Inserting row 2213
Error inserting row 2213: tuple index out of range
Row data: Date/Time           4/2/2012 4:00
Temp_C                       -1.2
Dew Point Temp_C             -2.2
Rel Hum_%                      93
Wind Speed_km/h                 4
Visibility_km                 9.7
Press_kPa                  100.38
Weather                       Fog
Name: 2212, dtype: object
Inserting row 2214
Error inserting row 2214: tuple index out of range
Row data: Date/Time           4/2/2012 5:00
Temp_C                       -1.7
Dew Point Temp_C             -2.5
Rel Hum_%                      94
Wind Speed_km/h                 6
Visibility_km                25.0
Press_kPa                  100.47
Weather                     Clear
Name: 2213, dtype: object
Inserting row 2215
Error inserting row 2215: tuple index out of range
Row data: Date/Time           4/2/2012 6:00
Temp_C                       -1.8
Dew Point Temp_C             -3.5
Rel Hum_%                      88
Wind Speed_km/h                 6
Visibility_km                24.1
Press_kPa                  100.56
Weather                     Clear
Name: 2214, dtype: object
Inserting row 2216
Error inserting row 2216: tuple index out of range
Row data: Date/Time           4/2/2012 7:00
Temp_C                        0.2
Dew Point Temp_C             -2.1
Rel Hum_%                      84
Wind Speed_km/h                 6
Visibility_km                48.3
Press_kPa                  100.65
Weather                     Clear
Name: 2215, dtype: object
Inserting row 2217
Error inserting row 2217: tuple index out of range
Row data: Date/Time           4/2/2012 8:00
Temp_C                        2.1
Dew Point Temp_C             -4.5
Rel Hum_%                      62
Wind Speed_km/h                13
Visibility_km                48.3
Press_kPa                  100.69
Weather                     Clear
Name: 2216, dtype: object
Inserting row 2218
Error inserting row 2218: tuple index out of range
Row data: Date/Time           4/2/2012 9:00
Temp_C                        3.4
Dew Point Temp_C             -7.3
Rel Hum_%                      45
Wind Speed_km/h                22
Visibility_km                48.3
Press_kPa                  100.72
Weather                     Clear
Name: 2217, dtype: object
Inserting row 2219
Error inserting row 2219: tuple index out of range
Row data: Date/Time           4/2/2012 10:00
Temp_C                         4.5
Dew Point Temp_C              -8.5
Rel Hum_%                       38
Wind Speed_km/h                 28
Visibility_km                 48.3
Press_kPa                   100.73
Weather                      Clear
Name: 2218, dtype: object
Inserting row 2220
Error inserting row 2220: tuple index out of range
Row data: Date/Time           4/2/2012 11:00
Temp_C                         4.6
Dew Point Temp_C              -7.8
Rel Hum_%                       40
Wind Speed_km/h                 24
Visibility_km                 48.3
Press_kPa                   100.72
Weather                      Clear
Name: 2219, dtype: object
Inserting row 2221
Error inserting row 2221: tuple index out of range
Row data: Date/Time           4/2/2012 12:00
Temp_C                         6.2
Dew Point Temp_C              -7.8
Rel Hum_%                       36
Wind Speed_km/h                 17
Visibility_km                 48.3
Press_kPa                   100.65
Weather                      Clear
Name: 2220, dtype: object
Inserting row 2222
Error inserting row 2222: tuple index out of range
Row data: Date/Time           4/2/2012 13:00
Temp_C                         6.7
Dew Point Temp_C              -7.2
Rel Hum_%                       36
Wind Speed_km/h                 24
Visibility_km                 48.3
Press_kPa                   100.64
Weather                      Clear
Name: 2221, dtype: object
Inserting row 2223
Error inserting row 2223: tuple index out of range
Row data: Date/Time           4/2/2012 14:00
Temp_C                         7.3
Dew Point Temp_C              -8.5
Rel Hum_%                       32
Wind Speed_km/h                 26
Visibility_km                 48.3
Press_kPa                   100.62
Weather                      Clear
Name: 2222, dtype: object
Inserting row 2224
Error inserting row 2224: tuple index out of range
Row data: Date/Time           4/2/2012 15:00
Temp_C                         7.9
Dew Point Temp_C             -10.0
Rel Hum_%                       27
Wind Speed_km/h                 19
Visibility_km                 48.3
Press_kPa                    100.6
Weather                      Clear
Name: 2223, dtype: object
Inserting row 2225
Error inserting row 2225: tuple index out of range
Row data: Date/Time           4/2/2012 16:00
Temp_C                         7.9
Dew Point Temp_C             -12.0
Rel Hum_%                       23
Wind Speed_km/h                 28
Visibility_km                 48.3
Press_kPa                   100.59
Weather                      Clear
Name: 2224, dtype: object
Inserting row 2226
Error inserting row 2226: tuple index out of range
Row data: Date/Time           4/2/2012 17:00
Temp_C                         8.0
Dew Point Temp_C             -12.2
Rel Hum_%                       22
Wind Speed_km/h                 30
Visibility_km                 48.3
Press_kPa                   100.61
Weather               Mainly Clear
Name: 2225, dtype: object
Inserting row 2227
Error inserting row 2227: tuple index out of range
Row data: Date/Time           4/2/2012 18:00
Temp_C                         6.9
Dew Point Temp_C             -13.6
Rel Hum_%                       22
Wind Speed_km/h                 19
Visibility_km                 48.3
Press_kPa                   100.65
Weather                      Clear
Name: 2226, dtype: object
Inserting row 2228
Error inserting row 2228: tuple index out of range
Row data: Date/Time           4/2/2012 19:00
Temp_C                         4.9
Dew Point Temp_C             -12.6
Rel Hum_%                       27
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   100.69
Weather                      Clear
Name: 2227, dtype: object
Inserting row 2229
Error inserting row 2229: tuple index out of range
Row data: Date/Time           4/2/2012 20:00
Temp_C                         3.5
Dew Point Temp_C             -13.1
Rel Hum_%                       28
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   100.75
Weather                      Clear
Name: 2228, dtype: object
Inserting row 2230
Error inserting row 2230: tuple index out of range
Row data: Date/Time           4/2/2012 21:00
Temp_C                         3.1
Dew Point Temp_C             -13.0
Rel Hum_%                       30
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   100.78
Weather                      Clear
Name: 2229, dtype: object
Inserting row 2231
Error inserting row 2231: tuple index out of range
Row data: Date/Time           4/2/2012 22:00
Temp_C                         0.6
Dew Point Temp_C             -12.8
Rel Hum_%                       36
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                   100.84
Weather                      Clear
Name: 2230, dtype: object
Inserting row 2232
Error inserting row 2232: tuple index out of range
Row data: Date/Time           4/2/2012 23:00
Temp_C                         1.0
Dew Point Temp_C             -12.8
Rel Hum_%                       35
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   100.83
Weather                      Clear
Name: 2231, dtype: object
Inserting row 2233
Error inserting row 2233: tuple index out of range
Row data: Date/Time           4/3/2012 0:00
Temp_C                       -0.3
Dew Point Temp_C            -11.9
Rel Hum_%                      41
Wind Speed_km/h                 6
Visibility_km                25.0
Press_kPa                  100.84
Weather                     Clear
Name: 2232, dtype: object
Inserting row 2234
Error inserting row 2234: tuple index out of range
Row data: Date/Time           4/3/2012 1:00
Temp_C                       -1.1
Dew Point Temp_C            -11.4
Rel Hum_%                      45
Wind Speed_km/h                 9
Visibility_km                25.0
Press_kPa                  100.86
Weather                     Clear
Name: 2233, dtype: object
Inserting row 2235
Error inserting row 2235: tuple index out of range
Row data: Date/Time           4/3/2012 2:00
Temp_C                       -0.9
Dew Point Temp_C            -13.2
Rel Hum_%                      39
Wind Speed_km/h                 6
Visibility_km                25.0
Press_kPa                  100.84
Weather                     Clear
Name: 2234, dtype: object
Inserting row 2236
Error inserting row 2236: tuple index out of range
Row data: Date/Time           4/3/2012 3:00
Temp_C                       -3.0
Dew Point Temp_C            -12.0
Rel Hum_%                      50
Wind Speed_km/h                 9
Visibility_km                25.0
Press_kPa                  100.87
Weather                     Clear
Name: 2235, dtype: object
Inserting row 2237
Error inserting row 2237: tuple index out of range
Row data: Date/Time           4/3/2012 4:00
Temp_C                       -2.1
Dew Point Temp_C            -11.8
Rel Hum_%                      47
Wind Speed_km/h                13
Visibility_km                25.0
Press_kPa                  100.92
Weather                     Clear
Name: 2236, dtype: object
Inserting row 2238
Error inserting row 2238: tuple index out of range
Row data: Date/Time           4/3/2012 5:00
Temp_C                       -2.6
Dew Point Temp_C            -12.4
Rel Hum_%                      47
Wind Speed_km/h                 6
Visibility_km                25.0
Press_kPa                  100.99
Weather                     Clear
Name: 2237, dtype: object
Inserting row 2239
Error inserting row 2239: tuple index out of range
Row data: Date/Time           4/3/2012 6:00
Temp_C                       -2.0
Dew Point Temp_C            -12.4
Rel Hum_%                      45
Wind Speed_km/h                 6
Visibility_km                48.3
Press_kPa                  101.03
Weather                     Clear
Name: 2238, dtype: object
Inserting row 2240
Error inserting row 2240: tuple index out of range
Row data: Date/Time           4/3/2012 7:00
Temp_C                        0.3
Dew Point Temp_C            -11.3
Rel Hum_%                      41
Wind Speed_km/h                11
Visibility_km                48.3
Press_kPa                  101.09
Weather                     Clear
Name: 2239, dtype: object
Inserting row 2241
Error inserting row 2241: tuple index out of range
Row data: Date/Time           4/3/2012 8:00
Temp_C                        1.7
Dew Point Temp_C            -11.7
Rel Hum_%                      36
Wind Speed_km/h                19
Visibility_km                48.3
Press_kPa                  101.08
Weather                     Clear
Name: 2240, dtype: object
Inserting row 2242
Error inserting row 2242: tuple index out of range
Row data: Date/Time           4/3/2012 9:00
Temp_C                        2.5
Dew Point Temp_C            -11.0
Rel Hum_%                      36
Wind Speed_km/h                15
Visibility_km                48.3
Press_kPa                  101.07
Weather                     Clear
Name: 2241, dtype: object
Inserting row 2243
Error inserting row 2243: tuple index out of range
Row data: Date/Time           4/3/2012 10:00
Temp_C                         4.3
Dew Point Temp_C             -10.3
Rel Hum_%                       34
Wind Speed_km/h                 17
Visibility_km                 48.3
Press_kPa                   100.98
Weather                      Clear
Name: 2242, dtype: object
Inserting row 2244
Error inserting row 2244: tuple index out of range
Row data: Date/Time           4/3/2012 11:00
Temp_C                         6.4
Dew Point Temp_C              -9.1
Rel Hum_%                       32
Wind Speed_km/h                 11
Visibility_km                 48.3
Press_kPa                   100.91
Weather               Mainly Clear
Name: 2243, dtype: object
Inserting row 2245
Error inserting row 2245: tuple index out of range
Row data: Date/Time           4/3/2012 12:00
Temp_C                         7.1
Dew Point Temp_C              -8.6
Rel Hum_%                       32
Wind Speed_km/h                 11
Visibility_km                 48.3
Press_kPa                   100.82
Weather              Mostly Cloudy
Name: 2244, dtype: object
Inserting row 2246
Error inserting row 2246: tuple index out of range
Row data: Date/Time           4/3/2012 13:00
Temp_C                         8.7
Dew Point Temp_C              -9.1
Rel Hum_%                       27
Wind Speed_km/h                 11
Visibility_km                 48.3
Press_kPa                   100.76
Weather              Mostly Cloudy
Name: 2245, dtype: object
Inserting row 2247
Error inserting row 2247: tuple index out of range
Row data: Date/Time           4/3/2012 14:00
Temp_C                        10.0
Dew Point Temp_C              -8.9
Rel Hum_%                       25
Wind Speed_km/h                 13
Visibility_km                 48.3
Press_kPa                   100.65
Weather              Mostly Cloudy
Name: 2246, dtype: object
Inserting row 2248
Error inserting row 2248: tuple index out of range
Row data: Date/Time           4/3/2012 15:00
Temp_C                        10.9
Dew Point Temp_C              -9.0
Rel Hum_%                       24
Wind Speed_km/h                 24
Visibility_km                 48.3
Press_kPa                   100.54
Weather               Mainly Clear
Name: 2247, dtype: object
Inserting row 2249
Error inserting row 2249: tuple index out of range
Row data: Date/Time           4/3/2012 16:00
Temp_C                        10.8
Dew Point Temp_C              -9.1
Rel Hum_%                       24
Wind Speed_km/h                 30
Visibility_km                 48.3
Press_kPa                   100.51
Weather               Mainly Clear
Name: 2248, dtype: object
Inserting row 2250
Error inserting row 2250: tuple index out of range
Row data: Date/Time           4/3/2012 17:00
Temp_C                         9.7
Dew Point Temp_C              -9.0
Rel Hum_%                       26
Wind Speed_km/h                 28
Visibility_km                 48.3
Press_kPa                   100.52
Weather              Mostly Cloudy
Name: 2249, dtype: object
Inserting row 2251
Error inserting row 2251: tuple index out of range
Row data: Date/Time           4/3/2012 18:00
Temp_C                         8.9

Row data: Date/Time           4/10/2012 0:00
Temp_C                         5.1
Dew Point Temp_C               1.7
Rel Hum_%                       79
Wind Speed_km/h                 19
Visibility_km                 25.0
Press_kPa                    99.43
Weather                     Cloudy
Name: 2400, dtype: object
Inserting row 2402
Error inserting row 2402: tuple index out of range
Row data: Date/Time           4/10/2012 1:00
Temp_C                         4.9
Dew Point Temp_C               2.2
Rel Hum_%                       83
Wind Speed_km/h                 20
Visibility_km                 25.0
Press_kPa                    99.41
Weather                     Cloudy
Name: 2401, dtype: object
Inserting row 2403
Error inserting row 2403: tuple index out of range
Row data: Date/Time           4/10/2012 2:00
Temp_C                         4.6
Dew Point Temp_C               1.8
Rel Hum_%                       82
Wind Speed_km/h                 19
Visibility_km                 25.0
Press_kPa                     99.4
Weather              Mostly Cloudy
Name: 2402, dtype: object
Inserting row 2404
Error inserting row 2404: tuple index out of range
Row data: Date/Time           4/10/2012 3:00
Temp_C                         4.3
Dew Point Temp_C               1.6
Rel Hum_%                       83
Wind Speed_km/h                 17
Visibility_km                 25.0
Press_kPa                    99.37
Weather              Mostly Cloudy
Name: 2403, dtype: object
Inserting row 2405
Error inserting row 2405: tuple index out of range
Row data: Date/Time           4/10/2012 4:00
Temp_C                         4.0
Dew Point Temp_C               1.5
Rel Hum_%                       84
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                    99.39
Weather              Mostly Cloudy
Name: 2404, dtype: object
Inserting row 2406
Error inserting row 2406: tuple index out of range
Row data: Date/Time           4/10/2012 5:00
Temp_C                         4.0
Dew Point Temp_C               1.6
Rel Hum_%                       84
Wind Speed_km/h                  9
Visibility_km                 24.1
Press_kPa                    99.39
Weather                     Cloudy
Name: 2405, dtype: object
Inserting row 2407
Error inserting row 2407: tuple index out of range
Row data: Date/Time           4/10/2012 6:00
Temp_C                         4.3
Dew Point Temp_C               1.7
Rel Hum_%                       83
Wind Speed_km/h                  9
Visibility_km                 24.1
Press_kPa                    99.45
Weather              Mostly Cloudy
Name: 2406, dtype: object
Inserting row 2408
Error inserting row 2408: tuple index out of range
Row data: Date/Time           4/10/2012 7:00
Temp_C                         5.0
Dew Point Temp_C               1.5
Rel Hum_%                       78
Wind Speed_km/h                  9
Visibility_km                 24.1
Press_kPa                    99.48
Weather                     Cloudy
Name: 2407, dtype: object
Inserting row 2409
Error inserting row 2409: tuple index out of range
Row data: Date/Time           4/10/2012 8:00
Temp_C                         5.3
Dew Point Temp_C               1.5
Rel Hum_%                       76
Wind Speed_km/h                 17
Visibility_km                 24.1
Press_kPa                    99.51
Weather               Rain Showers
Name: 2408, dtype: object
Inserting row 2410
Error inserting row 2410: tuple index out of range
Row data: Date/Time           4/10/2012 9:00
Temp_C                         5.7
Dew Point Temp_C               1.8
Rel Hum_%                       76
Wind Speed_km/h                 15
Visibility_km                 24.1
Press_kPa                    99.53
Weather              Mostly Cloudy
Name: 2409, dtype: object
Inserting row 2411
Error inserting row 2411: tuple index out of range
Row data: Date/Time           4/10/2012 10:00
Temp_C                          6.9
Dew Point Temp_C                0.9
Rel Hum_%                        66
Wind Speed_km/h                  20
Visibility_km                  24.1
Press_kPa                     99.56
Weather               Mostly Cloudy
Name: 2410, dtype: object
Inserting row 2412
Error inserting row 2412: tuple index out of range
Row data: Date/Time           4/10/2012 11:00
Temp_C                          6.9
Dew Point Temp_C                2.5
Rel Hum_%                        74
Wind Speed_km/h                  15
Visibility_km                  24.1
Press_kPa                     99.58
Weather                Rain Showers
Name: 2411, dtype: object
Inserting row 2413
Error inserting row 2413: tuple index out of range
Row data: Date/Time           4/10/2012 12:00
Temp_C                          8.0
Dew Point Temp_C                0.5
Rel Hum_%                        59
Wind Speed_km/h                  19
Visibility_km                  24.1
Press_kPa                     99.58
Weather                      Cloudy
Name: 2412, dtype: object
Inserting row 2414
Error inserting row 2414: tuple index out of range
Row data: Date/Time           4/10/2012 13:00
Temp_C                          8.8
Dew Point Temp_C                1.0
Rel Hum_%                        58
Wind Speed_km/h                  22
Visibility_km                  24.1
Press_kPa                      99.6
Weather               Mostly Cloudy
Name: 2413, dtype: object
Inserting row 2415
Error inserting row 2415: tuple index out of range
Row data: Date/Time           4/10/2012 14:00
Temp_C                          7.6
Dew Point Temp_C                2.4
Rel Hum_%                        70
Wind Speed_km/h                  33
Visibility_km                  16.1
Press_kPa                     99.63
Weather                Rain Showers
Name: 2414, dtype: object
Inserting row 2416
Error inserting row 2416: tuple index out of range
Row data: Date/Time           4/10/2012 15:00
Temp_C                          6.2
Dew Point Temp_C                3.2
Rel Hum_%                        81
Wind Speed_km/h                  19
Visibility_km                  24.1
Press_kPa                     99.71
Weather                Rain Showers
Name: 2415, dtype: object
Inserting row 2417
Error inserting row 2417: tuple index out of range
Row data: Date/Time           4/10/2012 16:00
Temp_C                          6.7
Dew Point Temp_C                2.9
Rel Hum_%                        77
Wind Speed_km/h                  20
Visibility_km                  24.1
Press_kPa                     99.77
Weather               Mostly Cloudy
Name: 2416, dtype: object
Inserting row 2418
Error inserting row 2418: tuple index out of range
Row data: Date/Time           4/10/2012 17:00
Temp_C                          6.8
Dew Point Temp_C                2.4
Rel Hum_%                        73
Wind Speed_km/h                  19
Visibility_km                  24.1
Press_kPa                     99.83
Weather               Mostly Cloudy
Name: 2417, dtype: object
Inserting row 2419
Error inserting row 2419: tuple index out of range
Row data: Date/Time           4/10/2012 18:00
Temp_C                          6.0
Dew Point Temp_C                2.5
Rel Hum_%                        78
Wind Speed_km/h                  24
Visibility_km                  24.1
Press_kPa                     99.91
Weather               Mostly Cloudy
Name: 2418, dtype: object
Inserting row 2420
Error inserting row 2420: tuple index out of range
Row data: Date/Time           4/10/2012 19:00
Temp_C                          5.8
Dew Point Temp_C                2.3
Rel Hum_%                        78
Wind Speed_km/h                  19
Visibility_km                  25.0
Press_kPa                    100.01
Weather               Mostly Cloudy
Name: 2419, dtype: object
Inserting row 2421
Error inserting row 2421: tuple index out of range
Row data: Date/Time           4/10/2012 20:00
Temp_C                          5.2
Dew Point Temp_C                1.8
Rel Hum_%                        79
Wind Speed_km/h                  20
Visibility_km                  25.0
Press_kPa                    100.12
Weather               Mostly Cloudy
Name: 2420, dtype: object
Inserting row 2422
Error inserting row 2422: tuple index out of range
Row data: Date/Time           4/10/2012 21:00
Temp_C                          5.1
Dew Point Temp_C                2.3
Rel Hum_%                        82
Wind Speed_km/h                  22
Visibility_km                  25.0
Press_kPa                    100.15
Weather               Mostly Cloudy
Name: 2421, dtype: object
Inserting row 2423
Error inserting row 2423: tuple index out of range
Row data: Date/Time           4/10/2012 22:00
Temp_C                          4.4
Dew Point Temp_C                1.9
Rel Hum_%                        84
Wind Speed_km/h                  11
Visibility_km                  25.0
Press_kPa                    100.16
Weather               Mostly Cloudy
Name: 2422, dtype: object
Inserting row 2424
Error inserting row 2424: tuple index out of range
Row data: Date/Time           4/10/2012 23:00
Temp_C                          4.7
Dew Point Temp_C                2.4
Rel Hum_%                        85
Wind Speed_km/h                  15
Visibility_km                  25.0
Press_kPa                    100.21
Weather               Mostly Cloudy
Name: 2423, dtype: object
Inserting row 2425
Error inserting row 2425: tuple index out of range
Row data: Date/Time           4/11/2012 0:00
Temp_C                         4.3
Dew Point Temp_C               1.9
Rel Hum_%                       84
Wind Speed_km/h                 17
Visibility_km                 25.0
Press_kPa                   100.24
Weather              Mostly Cloudy
Name: 2424, dtype: object
Inserting row 2426
Error inserting row 2426: tuple index out of range
Row data: Date/Time           4/11/2012 1:00
Temp_C                         4.0
Dew Point Temp_C               1.7
Rel Hum_%                       85
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                   100.26
Weather              Mostly Cloudy
Name: 2425, dtype: object
Inserting row 2427
Error inserting row 2427: tuple index out of range
Row data: Date/Time           4/11/2012 2:00
Temp_C                         3.2
Dew Point Temp_C               1.4
Rel Hum_%                       88
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   100.26
Weather              Mostly Cloudy
Name: 2426, dtype: object
Inserting row 2428
Error inserting row 2428: tuple index out of range
Row data: Date/Time           4/11/2012 3:00
Temp_C                         3.0
Dew Point Temp_C               1.3
Rel Hum_%                       89
Wind Speed_km/h                  0
Visibility_km                 25.0
Press_kPa                    100.3
Weather              Mostly Cloudy
Name: 2427, dtype: object
Inserting row 2429
Error inserting row 2429: tuple index out of range
Row data: Date/Time           4/11/2012 4:00
Temp_C                         1.6
Dew Point Temp_C               0.1
Rel Hum_%                       90
Wind Speed_km/h                  0
Visibility_km                 25.0
Press_kPa                   100.34
Weather               Mainly Clear
Name: 2428, dtype: object
Inserting row 2430
Error inserting row 2430: tuple index out of range
Row data: Date/Time           4/11/2012 5:00
Temp_C                         0.7
Dew Point Temp_C              -0.8
Rel Hum_%                       90
Wind Speed_km/h                  6
Visibility_km                 24.1
Press_kPa                    100.4
Weather              Mostly Cloudy
Name: 2429, dtype: object
Inserting row 2431
Error inserting row 2431: tuple index out of range
Row data: Date/Time           4/11/2012 6:00
Temp_C                         2.4
Dew Point Temp_C               0.8
Rel Hum_%                       89
Wind Speed_km/h                  6
Visibility_km                 24.1
Press_kPa                    100.5
Weather              Mostly Cloudy
Name: 2430, dtype: object
Inserting row 2432
Error inserting row 2432: tuple index out of range
Row data: Date/Time           4/11/2012 7:00
Temp_C                         3.2
Dew Point Temp_C               1.2
Rel Hum_%                       87
Wind Speed_km/h                  4
Visibility_km                 24.1
Press_kPa                   100.58
Weather                     Cloudy
Name: 2431, dtype: object
Inserting row 2433
Error inserting row 2433: tuple index out of range
Row data: Date/Time           4/11/2012 8:00
Temp_C                         4.6
Dew Point Temp_C               1.7
Rel Hum_%                       81
Wind Speed_km/h                  4
Visibility_km                 24.1
Press_kPa                   100.65
Weather                     Cloudy
Name: 2432, dtype: object
Inserting row 2434
Error inserting row 2434: tuple index out of range
Row data: Date/Time           4/11/2012 9:00
Temp_C                         6.1
Dew Point Temp_C               1.4
Rel Hum_%                       72
Wind Speed_km/h                  0
Visibility_km                 24.1
Press_kPa                   100.72
Weather                     Cloudy
Name: 2433, dtype: object
Inserting row 2435
Error inserting row 2435: tuple index out of range
Row data: Date/Time           4/11/2012 10:00
Temp_C                          6.7
Dew Point Temp_C                2.2
Rel Hum_%                        73
Wind Speed_km/h                   4
Visibility_km                  24.1
Press_kPa                    100.76
Weather               Mostly Cloudy
Name: 2434, dtype: object
Inserting row 2436
Error inserting row 2436: tuple index out of range
Row data: Date/Time           4/11/2012 11:00
Temp_C                          6.7
Dew Point Temp_C                2.0
Rel Hum_%                        72
Wind Speed_km/h                  11
Visibility_km                  24.1
Press_kPa                    100.78
Weather                      Cloudy
Name: 2435, dtype: object
Inserting row 2437
Error inserting row 2437: tuple index out of range
Row data: Date/Time           4/11/2012 12:00
Temp_C                          8.8
Dew Point Temp_C                2.5
Rel Hum_%                        65
Wind Speed_km/h                   9
Visibility_km                  24.1
Press_kPa                    100.76
Weather                Mainly Clear
Name: 2436, dtype: object
Inserting row 2438
Error inserting row 2438: tuple index out of range
Row data: Date/Time           4/11/2012 13:00
Temp_C                         11.0
Dew Point Temp_C                1.9
Rel Hum_%                        53
Wind Speed_km/h                   4
Visibility_km                  24.1
Press_kPa                    100.74
Weather               Mostly Cloudy
Name: 2437, dtype: object
Inserting row 2439
Error inserting row 2439: tuple index out of range
Row data: Date/Time           4/11/2012 14:00
Temp_C                          8.4
Dew Point Temp_C                0.3
Rel Hum_%                        57
Wind Speed_km/h                  32
Visibility_km                  24.1
Press_kPa                    100.79
Weather                Rain Showers
Name: 2438, dtype: object
Inserting row 2440
Error inserting row 2440: tuple index out of range
Row data: Date/Time           4/11/2012 15:00
Temp_C                          7.5
Dew Point Temp_C                3.1
Rel Hum_%                        74
Wind Speed_km/h                   7
Visibility_km                  24.1
Press_kPa                    100.79
Weather               Mostly Cloudy
Name: 2439, dtype: object
Inserting row 2441
Error inserting row 2441: tuple index out of range
Row data: Date/Time           4/11/2012 16:00
Temp_C                          9.5
Dew Point Temp_C                1.4
Rel Hum_%                        57
Wind Speed_km/h                  20
Visibility_km                  24.1
Press_kPa                    100.82
Weather               Mostly Cloudy
Name: 2440, dtype: object
Inserting row 2442
Error inserting row 2442: tuple index out of range
Row data: Date/Time           4/11/2012 17:00
Temp_C                          9.3
Dew Point Temp_C                1.3
Rel Hum_%                        57
Wind Speed_km/h                  33
Visibility_km                  24.1
Press_kPa                    100.91
Weather                Rain Showers
Name: 2441, dtype: object
Inserting row 2443
Error inserting row 2443: tuple index out of range
Row data: Date/Time           4/11/2012 18:00
Temp_C                          8.4
Dew Point Temp_C               -0.2
Rel Hum_%                        55
Wind Speed_km/h                  17
Visibility_km                  24.1
Press_kPa                    100.92
Weather                Mainly Clear
Name: 2442, dtype: object
Inserting row 2444
Error inserting row 2444: tuple index out of range
Row data: Date/Time           4/11/2012 19:00
Temp_C                          6.4
Dew Point Temp_C               -0.4
Rel Hum_%                        62
Wind Speed_km/h                  11
Visibility_km                  24.1
Press_kPa                     101.0
Weather                Mainly Clear
Name: 2443, dtype: object
Inserting row 2445
Error inserting row 2445: tuple index out of range
Row data: Date/Time           4/11/2012 20:00
Temp_C                          7.4
Dew Point Temp_C                0.8
Rel Hum_%                        63
Wind Speed_km/h                  13
Visibility_km                  25.0
Press_kPa                    101.07
Weather               Mostly Cloudy
Name: 2444, dtype: object
Inserting row 2446
Error inserting row 2446: tuple index out of range
Row data: Date/Time           4/11/2012 21:00
Temp_C                          6.9
Dew Point Temp_C                0.9
Rel Hum_%                        66
Wind Speed_km/h                   7
Visibility_km                  25.0
Press_kPa                    101.08
Weather               Mostly Cloudy
Name: 2445, dtype: object
Inserting row 2447
Error inserting row 2447: tuple index out of range
Row data: Date/Time           4/11/2012 22:00
Temp_C                          3.3
Dew Point Temp_C               -0.9
Rel Hum_%                        74
Wind Speed_km/h                  11
Visibility_km                  25.0
Press_kPa                    101.09
Weather               Mostly Cloudy
Name: 2446, dtype: object
Inserting row 2448
Error inserting row 2448: tuple index out of range
Row data: Date/Time           4/11/2012 23:00
Temp_C                          6.6
Dew Point Temp_C               -0.3
Rel Hum_%                        61
Wind Speed_km/h                  13
Visibility_km                  25.0
Press_kPa                    101.11
Weather               Mostly Cloudy
Name: 2447, dtype: object
Inserting row 2449
Error inserting row 2449: tuple index out of range
Row data: Date/Time           4/12/2012 0:00
Temp_C                         5.5
Dew Point Temp_C              -1.5
Rel Hum_%                       61
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   101.14
Weather               Mainly Clear
Name: 2448, dtype: object
Inserting row 2450
Error inserting row 2450: tuple index out of range
Row data: Date/Time           4/12/2012 1:00
Temp_C                         5.8
Dew Point Temp_C              -2.2
Rel Hum_%                       56
Wind Speed_km/h                 15
Visibility_km                 25.0
Press_kPa                   101.15
Weather              Mostly Cloudy
Name: 2449, dtype: object
Inserting row 2451
Error inserting row 2451: tuple index out of range
Row data: Date/Time           4/12/2012 2:00
Temp_C                         4.8
Dew Point Temp_C              -2.6
Rel Hum_%                       59
Wind Speed_km/h                 17
Visibility_km                 25.0
Press_kPa                   101.18
Weather               Mainly Clear
Name: 2450, dtype: object
Inserting row 2452
Error inserting row 2452: tuple index out of range
Row data: Date/Time           4/12/2012 3:00
Temp_C                         4.3

Error inserting row 2614: tuple index out of range
Row data: Date/Time           4/18/2012 21:00
Temp_C                          7.9
Dew Point Temp_C               -4.2
Rel Hum_%                        42
Wind Speed_km/h                   4
Visibility_km                  25.0
Press_kPa                    101.56
Weather               Mostly Cloudy
Name: 2613, dtype: object
Inserting row 2615
Error inserting row 2615: tuple index out of range
Row data: Date/Time           4/18/2012 22:00
Temp_C                          8.4
Dew Point Temp_C               -4.1
Rel Hum_%                        41
Wind Speed_km/h                   0
Visibility_km                  25.0
Press_kPa                    101.53
Weather               Mostly Cloudy
Name: 2614, dtype: object
Inserting row 2616
Error inserting row 2616: tuple index out of range
Row data: Date/Time           4/18/2012 23:00
Temp_C                          6.8
Dew Point Temp_C               -2.6
Rel Hum_%                        51
Wind Speed_km/h                   6
Visibility_km                  25.0
Press_kPa                     101.5
Weather                Mainly Clear
Name: 2615, dtype: object
Inserting row 2617
Error inserting row 2617: tuple index out of range
Row data: Date/Time           4/19/2012 0:00
Temp_C                         6.5
Dew Point Temp_C              -2.7
Rel Hum_%                       52
Wind Speed_km/h                  4
Visibility_km                 25.0
Press_kPa                   101.44
Weather               Mainly Clear
Name: 2616, dtype: object
Inserting row 2618
Error inserting row 2618: tuple index out of range
Row data: Date/Time           4/19/2012 1:00
Temp_C                         5.5
Dew Point Temp_C              -2.7
Rel Hum_%                       55
Wind Speed_km/h                  6
Visibility_km                 25.0
Press_kPa                   101.42
Weather                      Clear
Name: 2617, dtype: object
Inserting row 2619
Error inserting row 2619: tuple index out of range
Row data: Date/Time           4/19/2012 2:00
Temp_C                         3.3
Dew Point Temp_C              -2.8
Rel Hum_%                       64
Wind Speed_km/h                  7
Visibility_km                 25.0
Press_kPa                   101.33
Weather                      Clear
Name: 2618, dtype: object
Inserting row 2620
Error inserting row 2620: tuple index out of range
Row data: Date/Time           4/19/2012 3:00
Temp_C                         4.4
Dew Point Temp_C              -3.3
Rel Hum_%                       57
Wind Speed_km/h                  4
Visibility_km                 25.0
Press_kPa                   101.28
Weather               Mainly Clear
Name: 2619, dtype: object
Inserting row 2621
Error inserting row 2621: tuple index out of range
Row data: Date/Time           4/19/2012 4:00
Temp_C                         3.4
Dew Point Temp_C              -3.2
Rel Hum_%                       62
Wind Speed_km/h                  0
Visibility_km                 25.0
Press_kPa                   101.27
Weather               Mainly Clear
Name: 2620, dtype: object
Inserting row 2622
Error inserting row 2622: tuple index out of range
Row data: Date/Time           4/19/2012 5:00
Temp_C                         3.4
Dew Point Temp_C              -2.9
Rel Hum_%                       63
Wind Speed_km/h                  4
Visibility_km                 24.1
Press_kPa                   101.25
Weather               Mainly Clear
Name: 2621, dtype: object
Inserting row 2623
Error inserting row 2623: tuple index out of range
Row data: Date/Time           4/19/2012 6:00
Temp_C                         4.7
Dew Point Temp_C              -0.8
Rel Hum_%                       67
Wind Speed_km/h                  4
Visibility_km                 48.3
Press_kPa                   101.28
Weather              Mostly Cloudy
Name: 2622, dtype: object
Inserting row 2624
Error inserting row 2624: tuple index out of range
Row data: Date/Time           4/19/2012 7:00
Temp_C                         7.1
Dew Point Temp_C              -0.4
Rel Hum_%                       59
Wind Speed_km/h                  4
Visibility_km                 48.3
Press_kPa                   101.24
Weather              Mostly Cloudy
Name: 2623, dtype: object
Inserting row 2625
Error inserting row 2625: tuple index out of range
Row data: Date/Time           4/19/2012 8:00
Temp_C                         8.6
Dew Point Temp_C              -1.1
Rel Hum_%                       50
Wind Speed_km/h                  7
Visibility_km                 48.3
Press_kPa                   101.18
Weather              Mostly Cloudy
Name: 2624, dtype: object
Inserting row 2626
Error inserting row 2626: tuple index out of range
Row data: Date/Time           4/19/2012 9:00
Temp_C                        11.8
Dew Point Temp_C              -0.5
Rel Hum_%                       43
Wind Speed_km/h                  7
Visibility_km                 48.3
Press_kPa                   101.14
Weather               Mainly Clear
Name: 2625, dtype: object
Inserting row 2627
Error inserting row 2627: tuple index out of range
Row data: Date/Time           4/19/2012 10:00
Temp_C                         14.0
Dew Point Temp_C               -0.4
Rel Hum_%                        37
Wind Speed_km/h                  13
Visibility_km                  48.3
Press_kPa                    101.05
Weather                Mainly Clear
Name: 2626, dtype: object
Inserting row 2628
Error inserting row 2628: tuple index out of range
Row data: Date/Time           4/19/2012 11:00
Temp_C                         15.8
Dew Point Temp_C                0.5
Rel Hum_%                        35
Wind Speed_km/h                  19
Visibility_km                  48.3
Press_kPa                    101.02
Weather               Mostly Cloudy
Name: 2627, dtype: object
Inserting row 2629
Error inserting row 2629: tuple index out of range
Row data: Date/Time           4/19/2012 12:00
Temp_C                         16.6
Dew Point Temp_C                0.9
Rel Hum_%                        35
Wind Speed_km/h                  15
Visibility_km                  48.3
Press_kPa                    100.95
Weather               Mostly Cloudy
Name: 2628, dtype: object
Inserting row 2630
Error inserting row 2630: tuple index out of range
Row data: Date/Time           4/19/2012 13:00
Temp_C                         18.4
Dew Point Temp_C                1.7
Rel Hum_%                        33
Wind Speed_km/h                  20
Visibility_km                  48.3
Press_kPa                    100.88
Weather               Mostly Cloudy
Name: 2629, dtype: object
Inserting row 2631
Error inserting row 2631: tuple index out of range
Row data: Date/Time           4/19/2012 14:00
Temp_C                         19.3
Dew Point Temp_C                2.6
Rel Hum_%                        33
Wind Speed_km/h                  17
Visibility_km                  48.3
Press_kPa                    100.78
Weather               Mostly Cloudy
Name: 2630, dtype: object
Inserting row 2632
Error inserting row 2632: tuple index out of range
Row data: Date/Time           4/19/2012 15:00
Temp_C                         20.2
Dew Point Temp_C                3.9
Rel Hum_%                        34
Wind Speed_km/h                  28
Visibility_km                  48.3
Press_kPa                    100.69
Weather               Mostly Cloudy
Name: 2631, dtype: object
Inserting row 2633
Error inserting row 2633: tuple index out of range
Row data: Date/Time           4/19/2012 16:00
Temp_C                         20.7
Dew Point Temp_C                4.0
Rel Hum_%                        33
Wind Speed_km/h                  26
Visibility_km                  48.3
Press_kPa                    100.65
Weather               Mostly Cloudy
Name: 2632, dtype: object
Inserting row 2634
Error inserting row 2634: tuple index out of range
Row data: Date/Time           4/19/2012 17:00
Temp_C                         20.0
Dew Point Temp_C                4.3
Rel Hum_%                        36
Wind Speed_km/h                  24
Visibility_km                  48.3
Press_kPa                    100.62
Weather                Mainly Clear
Name: 2633, dtype: object
Inserting row 2635
Error inserting row 2635: tuple index out of range
Row data: Date/Time           4/19/2012 18:00
Temp_C                         18.7
Dew Point Temp_C                4.5
Rel Hum_%                        39
Wind Speed_km/h                  22
Visibility_km                  48.3
Press_kPa                    100.63
Weather                Mainly Clear
Name: 2634, dtype: object
Inserting row 2636
Error inserting row 2636: tuple index out of range
Row data: Date/Time           4/19/2012 19:00
Temp_C                         18.0
Dew Point Temp_C                4.1
Rel Hum_%                        40
Wind Speed_km/h                  15
Visibility_km                  48.3
Press_kPa                    100.69
Weather                Mainly Clear
Name: 2635, dtype: object
Inserting row 2637
Error inserting row 2637: tuple index out of range
Row data: Date/Time           4/19/2012 20:00
Temp_C                         16.6
Dew Point Temp_C                4.5
Rel Hum_%                        45
Wind Speed_km/h                  17
Visibility_km                  25.0
Press_kPa                    100.73
Weather                Mainly Clear
Name: 2636, dtype: object
Inserting row 2638
Error inserting row 2638: tuple index out of range
Row data: Date/Time           4/19/2012 21:00
Temp_C                         16.1
Dew Point Temp_C                4.5
Rel Hum_%                        46
Wind Speed_km/h                  11
Visibility_km                  25.0
Press_kPa                    100.72
Weather                       Clear
Name: 2637, dtype: object
Inserting row 2639
Error inserting row 2639: tuple index out of range
Row data: Date/Time           4/19/2012 22:00
Temp_C                         13.9
Dew Point Temp_C                4.8
Rel Hum_%                        54
Wind Speed_km/h                  13
Visibility_km                  25.0
Press_kPa                    100.73
Weather                Mainly Clear
Name: 2638, dtype: object
Inserting row 2640
Error inserting row 2640: tuple index out of range
Row data: Date/Time           4/19/2012 23:00
Temp_C                         12.6
Dew Point Temp_C                4.6
Rel Hum_%                        58
Wind Speed_km/h                   9
Visibility_km                  25.0
Press_kPa                    100.78
Weather                Mainly Clear
Name: 2639, dtype: object
Inserting row 2641
Error inserting row 2641: tuple index out of range
Row data: Date/Time           4/20/2012 0:00
Temp_C                        12.5
Dew Point Temp_C               2.5
Rel Hum_%                       50
Wind Speed_km/h                 19
Visibility_km                 25.0
Press_kPa                   100.88
Weather               Mainly Clear
Name: 2640, dtype: object
Inserting row 2642
Error inserting row 2642: tuple index out of range
Row data: Date/Time           4/20/2012 1:00
Temp_C                        10.9
Dew Point Temp_C               1.8
Rel Hum_%                       53
Wind Speed_km/h                 19
Visibility_km                 25.0
Press_kPa                   100.91
Weather                      Clear
Name: 2641, dtype: object
Inserting row 2643
Error inserting row 2643: tuple index out of range
Row data: Date/Time           4/20/2012 2:00
Temp_C                         9.9
Dew Point Temp_C               1.3
Rel Hum_%                       55
Wind Speed_km/h                 20
Visibility_km                 25.0
Press_kPa                   100.94
Weather               Mainly Clear
Name: 2642, dtype: object
Inserting row 2644
Error inserting row 2644: tuple index out of range
Row data: Date/Time           4/20/2012 3:00
Temp_C                         9.1
Dew Point Temp_C               1.5
Rel Hum_%                       59
Wind Speed_km/h                 15
Visibility_km                 25.0
Press_kPa                    101.0
Weather               Mainly Clear
Name: 2643, dtype: object
Inserting row 2645
Error inserting row 2645: tuple index out of range
Row data: Date/Time           4/20/2012 4:00
Temp_C                         8.8
Dew Point Temp_C               1.1
Rel Hum_%                       58
Wind Speed_km/h                 19
Visibility_km                 25.0
Press_kPa                   101.02
Weather               Mainly Clear
Name: 2644, dtype: object
Inserting row 2646
Error inserting row 2646: tuple index out of range
Row data: Date/Time           4/20/2012 5:00
Temp_C                         8.7
Dew Point Temp_C              -0.6
Rel Hum_%                       52
Wind Speed_km/h                 22
Visibility_km                 25.0
Press_kPa                   101.04
Weather              Mostly Cloudy
Name: 2645, dtype: object
Inserting row 2647
Error inserting row 2647: tuple index out of range
Row data: Date/Time           4/20/2012 6:00
Temp_C                         7.8
Dew Point Temp_C              -0.4
Rel Hum_%                       56
Wind Speed_km/h                 28
Visibility_km                 24.1
Press_kPa                   101.11
Weather              Mostly Cloudy
Name: 2646, dtype: object
Inserting row 2648
Error inserting row 2648: tuple index out of range
Row data: Date/Time           4/20/2012 7:00
Temp_C                         6.9
Dew Point Temp_C               0.3
Rel Hum_%                       63
Wind Speed_km/h                 22
Visibility_km                 24.1
Press_kPa                   101.17
Weather               Rain Showers
Name: 2647, dtype: object
Inserting row 2649
Error inserting row 2649: tuple index out of range
Row data: Date/Time           4/20/2012 8:00
Temp_C                         6.1
Dew Point Temp_C               1.4
Rel Hum_%                       72
Wind Speed_km/h                 26
Visibility_km                 24.1
Press_kPa                   101.12
Weather                     Cloudy
Name: 2648, dtype: object
Inserting row 2650
Error inserting row 2650: tuple index out of range
Row data: Date/Time           4/20/2012 9:00
Temp_C                         6.3
Dew Point Temp_C               1.4
Rel Hum_%                       71
Wind Speed_km/h                 19
Visibility_km                 48.3
Press_kPa                   101.13
Weather                     Cloudy
Name: 2649, dtype: object
Inserting row 2651
Error inserting row 2651: tuple index out of range
Row data: Date/Time           4/20/2012 10:00
Temp_C                          6.6
Dew Point Temp_C                1.6
Rel Hum_%                        70
Wind Speed_km/h                  24
Visibility_km                  24.1
Press_kPa                    101.07
Weather                        Rain
Name: 2650, dtype: object
Inserting row 2652
Error inserting row 2652: tuple index out of range
Row data: Date/Time           4/20/2012 11:00
Temp_C                          6.9
Dew Point Temp_C                1.0
Rel Hum_%                        66
Wind Speed_km/h                  20
Visibility_km                  24.1
Press_kPa                    101.06
Weather                      Cloudy
Name: 2651, dtype: object
Inserting row 2653
Error inserting row 2653: tuple index out of range
Row data: Date/Time           4/20/2012 12:00
Temp_C                          7.2
Dew Point Temp_C                1.7
Rel Hum_%                        68
Wind Speed_km/h                  26
Visibility_km                  24.1
Press_kPa                    100.98
Weather                Rain Showers
Name: 2652, dtype: object
Inserting row 2654
Error inserting row 2654: tuple index out of range
Row data: Date/Time           4/20/2012 13:00
Temp_C                          7.5
Dew Point Temp_C                2.0
Rel Hum_%                        68
Wind Speed_km/h                  24
Visibility_km                  24.1
Press_kPa                    100.91
Weather                Rain Showers
Name: 2653, dtype: object
Inserting row 2655
Error inserting row 2655: tuple index out of range
Row data: Date/Time           4/20/2012 14:00
Temp_C                          9.6
Dew Point Temp_C                3.2
Rel Hum_%                        64
Wind Speed_km/h                  24
Visibility_km                  24.1
Press_kPa                     100.8
Weather                      Cloudy
Name: 2654, dtype: object
Inserting row 2656
Error inserting row 2656: tuple index out of range
Row data: Date/Time           4/20/2012 15:00
Temp_C                          9.5
Dew Point Temp_C                3.0
Rel Hum_%                        64
Wind Speed_km/h                  24
Visibility_km                  24.1
Press_kPa                     100.7
Weather                      Cloudy
Name: 2655, dtype: object
Inserting row 2657
Error inserting row 2657: tuple index out of range
Row data: Date/Time           4/20/2012 16:00
Temp_C                          8.4
Dew Point Temp_C                2.9
Rel Hum_%                        68
Wind Speed_km/h                  33
Visibility_km                  24.1
Press_kPa                    100.67
Weather                      Cloudy
Name: 2656, dtype: object
Inserting row 2658
Error inserting row 2658: tuple index out of range
Row data: Date/Time           4/20/2012 17:00
Temp_C                          7.8
Dew Point Temp_C                2.6
Rel Hum_%                        70
Wind Speed_km/h                  26
Visibility_km                  24.1
Press_kPa                    100.59
Weather                      Cloudy
Name: 2657, dtype: object
Inserting row 2659
Error inserting row 2659: tuple index out of range
Row data: Date/Time           4/20/2012 18:00
Temp_C                          7.4
Dew Point Temp_C                2.9
Rel Hum_%                        73
Wind Speed_km/h                  28
Visibility_km                  24.1
Press_kPa                    100.54
Weather                      Cloudy
Name: 2658, dtype: object
Inserting row 2660
Error inserting row 2660: tuple index out of range
Row data: Date/Time           4/20/2012 19:00
Temp_C                          7.0
Dew Point Temp_C                3.2
Rel Hum_%                        77
Wind Speed_km/h                  26
Visibility_km                  24.1
Press_kPa                     100.5
Weather                      Cloudy
Name: 2659, dtype: object
Inserting row 2661
Error inserting row 2661: tuple index out of range
Row data: Date/Time           4/20/2012 20:00
Temp_C                          6.9
Dew Point Temp_C                3.5
Rel Hum_%                        79
Wind Speed_km/h                  24
Visibility_km                  25.0
Press_kPa                    100.46
Weather                      Cloudy
Name: 2660, dtype: object
Inserting row 2662
Error inserting row 2662: tuple index out of range
Row data: Date/Time           4/20/2012 21:00
Temp_C                          6.6
Dew Point Temp_C                3.5
Rel Hum_%                        81
Wind Speed_km/h                  17
Visibility_km                  25.0
Press_kPa                    100.35
Weather                      Cloudy
Name: 2661, dtype: object
Inserting row 2663
Error inserting row 2663: tuple index out of range
Row data: Date/Time           4/20/2012 22:00
Temp_C                          6.5
Dew Point Temp_C                3.4
Rel Hum_%                        81
Wind Speed_km/h                  17
Visibility_km                  25.0
Press_kPa                    100.32
Weather                      Cloudy
Name: 2662, dtype: object
Inserting row 2664
Error inserting row 2664: tuple index out of range
Row data: Date/Time           4/20/2012 23:00
Temp_C                          6.6
Dew Point Temp_C                3.5
Rel Hum_%                        81
Wind Speed_km/h                  20
Visibility_km                  25.0
Press_kPa                    100.27
Weather                      Cloudy
Name: 2663, dtype: object
Inserting row 2665
Error inserting row 2665: tuple index out of range

Row data: Date/Time           4/28/2012 7:00
Temp_C                        -1.3
Dew Point Temp_C             -10.0
Rel Hum_%                       52
Wind Speed_km/h                 30
Visibility_km                 48.3
Press_kPa                   101.75
Weather               Mainly Clear
Name: 2839, dtype: object
Inserting row 2841
Error inserting row 2841: tuple index out of range
Row data: Date/Time           4/28/2012 8:00
Temp_C                        -0.4
Dew Point Temp_C             -10.0
Rel Hum_%                       48
Wind Speed_km/h                 24
Visibility_km                 48.3
Press_kPa                   101.78
Weather               Mainly Clear
Name: 2840, dtype: object
Inserting row 2842
Error inserting row 2842: tuple index out of range
Row data: Date/Time           4/28/2012 9:00
Temp_C                         0.6
Dew Point Temp_C              -9.7
Rel Hum_%                       46
Wind Speed_km/h                 32
Visibility_km                 48.3
Press_kPa                   101.79
Weather               Mainly Clear
Name: 2841, dtype: object
Inserting row 2843
Error inserting row 2843: tuple index out of range
Row data: Date/Time           4/28/2012 10:00
Temp_C                          2.0
Dew Point Temp_C               -7.4
Rel Hum_%                        50
Wind Speed_km/h                  28
Visibility_km                  48.3
Press_kPa                    101.73
Weather                Mainly Clear
Name: 2842, dtype: object
Inserting row 2844
Error inserting row 2844: tuple index out of range
Row data: Date/Time           4/28/2012 11:00
Temp_C                          3.9
Dew Point Temp_C               -9.9
Rel Hum_%                        36
Wind Speed_km/h                  24
Visibility_km                  48.3
Press_kPa                    101.71
Weather                Mainly Clear
Name: 2843, dtype: object
Inserting row 2845
Error inserting row 2845: tuple index out of range
Row data: Date/Time           4/28/2012 12:00
Temp_C                          5.0
Dew Point Temp_C               -9.7
Rel Hum_%                        34
Wind Speed_km/h                  30
Visibility_km                  48.3
Press_kPa                    101.68
Weather                Mainly Clear
Name: 2844, dtype: object
Inserting row 2846
Error inserting row 2846: tuple index out of range
Row data: Date/Time           4/28/2012 13:00
Temp_C                          5.4
Dew Point Temp_C              -11.1
Rel Hum_%                        29
Wind Speed_km/h                  32
Visibility_km                  48.3
Press_kPa                    101.62
Weather                Mainly Clear
Name: 2845, dtype: object
Inserting row 2847
Error inserting row 2847: tuple index out of range
Row data: Date/Time           4/28/2012 14:00
Temp_C                          6.4
Dew Point Temp_C              -10.7
Rel Hum_%                        28
Wind Speed_km/h                  24
Visibility_km                  48.3
Press_kPa                    101.57
Weather                Mainly Clear
Name: 2846, dtype: object
Inserting row 2848
Error inserting row 2848: tuple index out of range
Row data: Date/Time           4/28/2012 15:00
Temp_C                          7.2
Dew Point Temp_C              -10.5
Rel Hum_%                        27
Wind Speed_km/h                  35
Visibility_km                  48.3
Press_kPa                     101.5
Weather                Mainly Clear
Name: 2847, dtype: object
Inserting row 2849
Error inserting row 2849: tuple index out of range
Row data: Date/Time           4/28/2012 16:00
Temp_C                          7.4
Dew Point Temp_C              -11.0
Rel Hum_%                        26
Wind Speed_km/h                  30
Visibility_km                  48.3
Press_kPa                    101.46
Weather                Mainly Clear
Name: 2848, dtype: object
Inserting row 2850
Error inserting row 2850: tuple index out of range
Row data: Date/Time           4/28/2012 17:00
Temp_C                          7.7
Dew Point Temp_C              -11.2
Rel Hum_%                        25
Wind Speed_km/h                  28
Visibility_km                  48.3
Press_kPa                    101.45
Weather                Mainly Clear
Name: 2849, dtype: object
Inserting row 2851
Error inserting row 2851: tuple index out of range
Row data: Date/Time           4/28/2012 18:00
Temp_C                          7.2
Dew Point Temp_C              -11.3
Rel Hum_%                        25
Wind Speed_km/h                  24
Visibility_km                  48.3
Press_kPa                    101.43
Weather                       Clear
Name: 2850, dtype: object
Inserting row 2852
Error inserting row 2852: tuple index out of range
Row data: Date/Time           4/28/2012 19:00
Temp_C                          6.1
Dew Point Temp_C              -11.4
Rel Hum_%                        27
Wind Speed_km/h                  19
Visibility_km                  48.3
Press_kPa                    101.46
Weather                       Clear
Name: 2851, dtype: object
Inserting row 2853
Error inserting row 2853: tuple index out of range
Row data: Date/Time           4/28/2012 20:00
Temp_C                          4.1
Dew Point Temp_C              -10.2
Rel Hum_%                        34
Wind Speed_km/h                  11
Visibility_km                  25.0
Press_kPa                    101.51
Weather                Mainly Clear
Name: 2852, dtype: object
Inserting row 2854
Error inserting row 2854: tuple index out of range
Row data: Date/Time           4/28/2012 21:00
Temp_C                          2.3
Dew Point Temp_C               -9.7
Rel Hum_%                        41
Wind Speed_km/h                  11
Visibility_km                  25.0
Press_kPa                    101.55
Weather                       Clear
Name: 2853, dtype: object
Inserting row 2855
Error inserting row 2855: tuple index out of range
Row data: Date/Time           4/28/2012 22:00
Temp_C                          1.9
Dew Point Temp_C               -9.9
Rel Hum_%                        41
Wind Speed_km/h                   9
Visibility_km                  25.0
Press_kPa                    101.56
Weather               Mostly Cloudy
Name: 2854, dtype: object
Inserting row 2856
Error inserting row 2856: tuple index out of range
Row data: Date/Time           4/28/2012 23:00
Temp_C                          0.8
Dew Point Temp_C               -9.1
Rel Hum_%                        47
Wind Speed_km/h                   6
Visibility_km                  25.0
Press_kPa                    101.55
Weather               Mostly Cloudy
Name: 2855, dtype: object
Inserting row 2857
Error inserting row 2857: tuple index out of range
Row data: Date/Time           4/29/2012 0:00
Temp_C                         0.8
Dew Point Temp_C              -8.8
Rel Hum_%                       49
Wind Speed_km/h                  7
Visibility_km                 25.0
Press_kPa                   101.52
Weather                     Cloudy
Name: 2856, dtype: object
Inserting row 2858
Error inserting row 2858: tuple index out of range
Row data: Date/Time           4/29/2012 1:00
Temp_C                         1.3
Dew Point Temp_C              -8.7
Rel Hum_%                       47
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   101.49
Weather               Mainly Clear
Name: 2857, dtype: object
Inserting row 2859
Error inserting row 2859: tuple index out of range
Row data: Date/Time           4/29/2012 2:00
Temp_C                         1.3
Dew Point Temp_C              -7.5
Rel Hum_%                       52
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   101.49
Weather               Mainly Clear
Name: 2858, dtype: object
Inserting row 2860
Error inserting row 2860: tuple index out of range
Row data: Date/Time           4/29/2012 3:00
Temp_C                         0.8
Dew Point Temp_C              -7.8
Rel Hum_%                       53
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   101.47
Weather              Mostly Cloudy
Name: 2859, dtype: object
Inserting row 2861
Error inserting row 2861: tuple index out of range
Row data: Date/Time           4/29/2012 4:00
Temp_C                        -0.1
Dew Point Temp_C              -7.7
Rel Hum_%                       57
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                   101.48
Weather               Mainly Clear
Name: 2860, dtype: object
Inserting row 2862
Error inserting row 2862: tuple index out of range
Row data: Date/Time           4/29/2012 5:00
Temp_C                         0.9
Dew Point Temp_C             -10.5
Rel Hum_%                       42
Wind Speed_km/h                 19
Visibility_km                 48.3
Press_kPa                   101.52
Weather              Mostly Cloudy
Name: 2861, dtype: object
Inserting row 2863
Error inserting row 2863: tuple index out of range
Row data: Date/Time           4/29/2012 6:00
Temp_C                         1.2
Dew Point Temp_C             -11.4
Rel Hum_%                       38
Wind Speed_km/h                 20
Visibility_km                 48.3
Press_kPa                   101.58
Weather              Mostly Cloudy
Name: 2862, dtype: object
Inserting row 2864
Error inserting row 2864: tuple index out of range
Row data: Date/Time           4/29/2012 7:00
Temp_C                         1.8
Dew Point Temp_C             -11.9
Rel Hum_%                       35
Wind Speed_km/h                 26
Visibility_km                 48.3
Press_kPa                   101.64
Weather              Mostly Cloudy
Name: 2863, dtype: object
Inserting row 2865
Error inserting row 2865: tuple index out of range
Row data: Date/Time           4/29/2012 8:00
Temp_C                         2.6
Dew Point Temp_C             -11.7
Rel Hum_%                       34
Wind Speed_km/h                 19
Visibility_km                 48.3
Press_kPa                   101.65
Weather              Mostly Cloudy
Name: 2864, dtype: object
Inserting row 2866
Error inserting row 2866: tuple index out of range
Row data: Date/Time           4/29/2012 9:00
Temp_C                         4.3
Dew Point Temp_C             -11.7
Rel Hum_%                       30
Wind Speed_km/h                 19
Visibility_km                 48.3
Press_kPa                   101.64
Weather               Mainly Clear
Name: 2865, dtype: object
Inserting row 2867
Error inserting row 2867: tuple index out of range
Row data: Date/Time           4/29/2012 10:00
Temp_C                          5.5
Dew Point Temp_C              -11.4
Rel Hum_%                        28
Wind Speed_km/h                  26
Visibility_km                  48.3
Press_kPa                    101.67
Weather                       Clear
Name: 2866, dtype: object
Inserting row 2868
Error inserting row 2868: tuple index out of range
Row data: Date/Time           4/29/2012 11:00
Temp_C                          6.2
Dew Point Temp_C              -11.6
Rel Hum_%                        27
Wind Speed_km/h                  24
Visibility_km                  48.3
Press_kPa                    101.62
Weather                       Clear
Name: 2867, dtype: object
Inserting row 2869
Error inserting row 2869: tuple index out of range
Row data: Date/Time           4/29/2012 12:00
Temp_C                          7.4
Dew Point Temp_C              -10.5
Rel Hum_%                        27
Wind Speed_km/h                  24
Visibility_km                  48.3
Press_kPa                    101.62
Weather                       Clear
Name: 2868, dtype: object
Inserting row 2870
Error inserting row 2870: tuple index out of range
Row data: Date/Time           4/29/2012 13:00
Temp_C                          8.4
Dew Point Temp_C              -11.1
Rel Hum_%                        24
Wind Speed_km/h                  32
Visibility_km                  48.3
Press_kPa                    101.64
Weather                       Clear
Name: 2869, dtype: object
Inserting row 2871
Error inserting row 2871: tuple index out of range
Row data: Date/Time           4/29/2012 14:00
Temp_C                          8.7
Dew Point Temp_C              -11.7
Rel Hum_%                        22
Wind Speed_km/h                  22
Visibility_km                  48.3
Press_kPa                    101.65
Weather                       Clear
Name: 2870, dtype: object
Inserting row 2872
Error inserting row 2872: tuple index out of range
Row data: Date/Time           4/29/2012 15:00
Temp_C                          9.0
Dew Point Temp_C              -12.0
Rel Hum_%                        21
Wind Speed_km/h                  32
Visibility_km                  48.3
Press_kPa                    101.63
Weather                       Clear
Name: 2871, dtype: object
Inserting row 2873
Error inserting row 2873: tuple index out of range
Row data: Date/Time           4/29/2012 16:00
Temp_C                          9.2
Dew Point Temp_C              -11.8
Rel Hum_%                        21
Wind Speed_km/h                  28
Visibility_km                  48.3
Press_kPa                    101.66
Weather                Mainly Clear
Name: 2872, dtype: object
Inserting row 2874
Error inserting row 2874: tuple index out of range
Row data: Date/Time           4/29/2012 17:00
Temp_C                          9.0
Dew Point Temp_C              -11.5
Rel Hum_%                        22
Wind Speed_km/h                  30
Visibility_km                  48.3
Press_kPa                    101.72
Weather                       Clear
Name: 2873, dtype: object
Inserting row 2875
Error inserting row 2875: tuple index out of range
Row data: Date/Time           4/29/2012 18:00
Temp_C                          8.1
Dew Point Temp_C              -11.9
Rel Hum_%                        23
Wind Speed_km/h                  28
Visibility_km                  48.3
Press_kPa                    101.77
Weather                       Clear
Name: 2874, dtype: object
Inserting row 2876
Error inserting row 2876: tuple index out of range
Row data: Date/Time           4/29/2012 19:00
Temp_C                          6.9
Dew Point Temp_C              -11.7
Rel Hum_%                        25
Wind Speed_km/h                  20
Visibility_km                  48.3
Press_kPa                    101.82
Weather                       Clear
Name: 2875, dtype: object
Inserting row 2877
Error inserting row 2877: tuple index out of range
Row data: Date/Time           4/29/2012 20:00
Temp_C                          6.3
Dew Point Temp_C              -11.4
Rel Hum_%                        27
Wind Speed_km/h                  15
Visibility_km                  25.0
Press_kPa                    101.93
Weather                Mainly Clear
Name: 2876, dtype: object
Inserting row 2878
Error inserting row 2878: tuple index out of range
Row data: Date/Time           4/29/2012 21:00
Temp_C                          5.4
Dew Point Temp_C              -11.0
Rel Hum_%                        29
Wind Speed_km/h                  19
Visibility_km                  25.0
Press_kPa                    102.01
Weather                Mainly Clear
Name: 2877, dtype: object
Inserting row 2879
Error inserting row 2879: tuple index out of range
Row data: Date/Time           4/29/2012 22:00
Temp_C                          5.1
Dew Point Temp_C              -10.7
Rel Hum_%                        31
Wind Speed_km/h                  15
Visibility_km                  25.0
Press_kPa                    102.05
Weather                       Clear
Name: 2878, dtype: object
Inserting row 2880
Error inserting row 2880: tuple index out of range
Row data: Date/Time           4/29/2012 23:00
Temp_C                          4.1
Dew Point Temp_C              -10.3
Rel Hum_%                        34
Wind Speed_km/h                  13
Visibility_km                  25.0
Press_kPa                    102.09
Weather                       Clear
Name: 2879, dtype: object
Inserting row 2881
Error inserting row 2881: tuple index out of range
Row data: Date/Time           4/30/2012 0:00
Temp_C                         3.3
Dew Point Temp_C             -10.3
Rel Hum_%                       36
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                   102.06
Weather                      Clear
Name: 2880, dtype: object
Inserting row 2882
Error inserting row 2882: tuple index out of range
Row data: Date/Time           4/30/2012 1:00
Temp_C                         2.2
Dew Point Temp_C              -9.7
Rel Hum_%                       41
Wind Speed_km/h                  6
Visibility_km                 25.0
Press_kPa                   102.12
Weather                      Clear
Name: 2881, dtype: object
Inserting row 2883
Error inserting row 2883: tuple index out of range
Row data: Date/Time           4/30/2012 2:00
Temp_C                         3.2
Dew Point Temp_C             -10.4
Rel Hum_%                       36
Wind Speed_km/h                  0
Visibility_km                 25.0
Press_kPa                   102.09
Weather                      Clear
Name: 2882, dtype: object
Inserting row 2884
Error inserting row 2884: tuple index out of range
Row data: Date/Time           4/30/2012 3:00
Temp_C                         2.4
Dew Point Temp_C              -9.2
Rel Hum_%                       42
Wind Speed_km/h                  0
Visibility_km                 25.0
Press_kPa                   102.09
Weather                      Clear
Name: 2883, dtype: object
Inserting row 2885
Error inserting row 2885: tuple index out of range
Row data: Date/Time           4/30/2012 4:00
Temp_C                         0.7
Dew Point Temp_C              -9.0
Rel Hum_%                       48
Wind Speed_km/h                  4
Visibility_km                 25.0
Press_kPa                   102.14
Weather                      Clear
Name: 2884, dtype: object
Inserting row 2886
Error inserting row 2886: tuple index out of range
Row data: Date/Time           4/30/2012 5:00
Temp_C                        -0.7
Dew Point Temp_C              -6.9
Rel Hum_%                       63
Wind Speed_km/h                  4
Visibility_km                 48.3
Press_kPa                   102.23
Weather               Mainly Clear
Name: 2885, dtype: object
Inserting row 2887
Error inserting row 2887: tuple index out of range
Row data: Date/Time           4/30/2012 6:00
Temp_C                         3.0
Dew Point Temp_C              -4.3
Rel Hum_%                       59
Wind Speed_km/h                  0
Visibility_km                 48.3
Press_kPa                   102.33
Weather               Mainly Clear
Name: 2886, dtype: object
Inserting row 2888
Error inserting row 2888: tuple index out of range
Row data: Date/Time           4/30/2012 7:00
Temp_C                         6.0
Dew Point Temp_C              -7.3
Rel Hum_%                       38
Wind Speed_km/h                  0
Visibility_km                 48.3
Press_kPa                   102.37
Weather               Mainly Clear
Name: 2887, dtype: object
Inserting row 2889
Error inserting row 2889: tuple index out of range
Row data: Date/Time           4/30/2012 8:00
Temp_C                         6.6
Dew Point Temp_C              -6.3
Rel Hum_%                       39
Wind Speed_km/h                 11
Visibility_km                 48.3
Press_kPa                   102.41
Weather              Mostly Cloudy
Name: 2888, dtype: object
Inserting row 2890
Error inserting row 2890: tuple index out of range
Row data: Date/Time           4/30/2012 9:00
Temp_C                         7.2
Dew Point Temp_C              -6.4
Rel Hum_%                       37
Wind Speed_km/h                  7
Visibility_km                 48.3
Press_kPa                   102.31
Weather              Mostly Cloudy
Name: 2889, dtype: object
Inserting row 2891
Error inserting row 2891: tuple index out of range
Row data: Date/Time           4/30/2012 10:00
Temp_C                          7.6

Row data: Date/Time           5/6/2012 22:00
Temp_C                        11.7
Dew Point Temp_C              -1.6
Rel Hum_%                       40
Wind Speed_km/h                  0
Visibility_km                 25.0
Press_kPa                   101.58
Weather               Mainly Clear
Name: 3046, dtype: object
Inserting row 3048
Error inserting row 3048: tuple index out of range
Row data: Date/Time           5/6/2012 23:00
Temp_C                        11.1
Dew Point Temp_C              -2.1
Rel Hum_%                       40
Wind Speed_km/h                  0
Visibility_km                 25.0
Press_kPa                   101.57
Weather                      Clear
Name: 3047, dtype: object
Inserting row 3049
Error inserting row 3049: tuple index out of range
Row data: Date/Time           5/7/2012 0:00
Temp_C                        9.9
Dew Point Temp_C             -1.6
Rel Hum_%                      45
Wind Speed_km/h                 0
Visibility_km                25.0
Press_kPa                  101.57
Weather                     Clear
Name: 3048, dtype: object
Inserting row 3050
Error inserting row 3050: tuple index out of range
Row data: Date/Time           5/7/2012 1:00
Temp_C                        6.9
Dew Point Temp_C              0.3
Rel Hum_%                      63
Wind Speed_km/h                 0
Visibility_km                25.0
Press_kPa                  101.55
Weather                     Clear
Name: 3049, dtype: object
Inserting row 3051
Error inserting row 3051: tuple index out of range
Row data: Date/Time           5/7/2012 2:00
Temp_C                        5.2
Dew Point Temp_C             -0.8
Rel Hum_%                      65
Wind Speed_km/h                 4
Visibility_km                25.0
Press_kPa                  101.56
Weather                     Clear
Name: 3050, dtype: object
Inserting row 3052
Error inserting row 3052: tuple index out of range
Row data: Date/Time           5/7/2012 3:00
Temp_C                        4.6
Dew Point Temp_C             -0.4
Rel Hum_%                      70
Wind Speed_km/h                 4
Visibility_km                25.0
Press_kPa                  101.55
Weather                     Clear
Name: 3051, dtype: object
Inserting row 3053
Error inserting row 3053: tuple index out of range
Row data: Date/Time           5/7/2012 4:00
Temp_C                        5.1
Dew Point Temp_C              0.6
Rel Hum_%                      73
Wind Speed_km/h                 0
Visibility_km                25.0
Press_kPa                  101.61
Weather                     Clear
Name: 3052, dtype: object
Inserting row 3054
Error inserting row 3054: tuple index out of range
Row data: Date/Time           5/7/2012 5:00
Temp_C                        5.7
Dew Point Temp_C              0.4
Rel Hum_%                      69
Wind Speed_km/h                 4
Visibility_km                48.3
Press_kPa                   101.6
Weather                     Clear
Name: 3053, dtype: object
Inserting row 3055
Error inserting row 3055: tuple index out of range
Row data: Date/Time           5/7/2012 6:00
Temp_C                        8.2
Dew Point Temp_C              3.3
Rel Hum_%                      71
Wind Speed_km/h                 6
Visibility_km                48.3
Press_kPa                  101.63
Weather                     Clear
Name: 3054, dtype: object
Inserting row 3056
Error inserting row 3056: tuple index out of range
Row data: Date/Time           5/7/2012 7:00
Temp_C                       12.3
Dew Point Temp_C              0.6
Rel Hum_%                      45
Wind Speed_km/h                 4
Visibility_km                48.3
Press_kPa                  101.64
Weather                     Clear
Name: 3055, dtype: object
Inserting row 3057
Error inserting row 3057: tuple index out of range
Row data: Date/Time           5/7/2012 8:00
Temp_C                       14.0
Dew Point Temp_C              1.0
Rel Hum_%                      41
Wind Speed_km/h                 7
Visibility_km                48.3
Press_kPa                  101.67
Weather                     Clear
Name: 3056, dtype: object
Inserting row 3058
Error inserting row 3058: tuple index out of range
Row data: Date/Time           5/7/2012 9:00
Temp_C                       16.0
Dew Point Temp_C             -3.0
Rel Hum_%                      27
Wind Speed_km/h                 7
Visibility_km                48.3
Press_kPa                  101.68
Weather                     Clear
Name: 3057, dtype: object
Inserting row 3059
Error inserting row 3059: tuple index out of range
Row data: Date/Time           5/7/2012 10:00
Temp_C                        17.1
Dew Point Temp_C              -5.9
Rel Hum_%                       20
Wind Speed_km/h                 13
Visibility_km                 48.3
Press_kPa                   101.67
Weather                      Clear
Name: 3058, dtype: object
Inserting row 3060
Error inserting row 3060: tuple index out of range
Row data: Date/Time           5/7/2012 11:00
Temp_C                        17.8
Dew Point Temp_C              -3.1
Rel Hum_%                       24
Wind Speed_km/h                  7
Visibility_km                 48.3
Press_kPa                   101.59
Weather               Mainly Clear
Name: 3059, dtype: object
Inserting row 3061
Error inserting row 3061: tuple index out of range
Row data: Date/Time           5/7/2012 12:00
Temp_C                        18.9
Dew Point Temp_C              -4.2
Rel Hum_%                       21
Wind Speed_km/h                 13
Visibility_km                 48.3
Press_kPa                   101.48
Weather               Mainly Clear
Name: 3060, dtype: object
Inserting row 3062
Error inserting row 3062: tuple index out of range
Row data: Date/Time           5/7/2012 13:00
Temp_C                        19.7
Dew Point Temp_C              -2.3
Rel Hum_%                       22
Wind Speed_km/h                 13
Visibility_km                 48.3
Press_kPa                   101.43
Weather               Mainly Clear
Name: 3061, dtype: object
Inserting row 3063
Error inserting row 3063: tuple index out of range
Row data: Date/Time           5/7/2012 14:00
Temp_C                        20.1
Dew Point Temp_C              -3.6
Rel Hum_%                       20
Wind Speed_km/h                 19
Visibility_km                 48.3
Press_kPa                   101.36
Weather               Mainly Clear
Name: 3062, dtype: object
Inserting row 3064
Error inserting row 3064: tuple index out of range
Row data: Date/Time           5/7/2012 15:00
Temp_C                        20.6
Dew Point Temp_C              -2.3
Rel Hum_%                       21
Wind Speed_km/h                  7
Visibility_km                 48.3
Press_kPa                   101.25
Weather              Mostly Cloudy
Name: 3063, dtype: object
Inserting row 3065
Error inserting row 3065: tuple index out of range
Row data: Date/Time           5/7/2012 16:00
Temp_C                        20.9
Dew Point Temp_C              -2.0
Rel Hum_%                       21
Wind Speed_km/h                 11
Visibility_km                 48.3
Press_kPa                   101.14
Weather              Mostly Cloudy
Name: 3064, dtype: object
Inserting row 3066
Error inserting row 3066: tuple index out of range
Row data: Date/Time           5/7/2012 17:00
Temp_C                        21.0
Dew Point Temp_C              -2.9
Rel Hum_%                       20
Wind Speed_km/h                 13
Visibility_km                 48.3
Press_kPa                   101.07
Weather              Mostly Cloudy
Name: 3065, dtype: object
Inserting row 3067
Error inserting row 3067: tuple index out of range
Row data: Date/Time           5/7/2012 18:00
Temp_C                        20.7
Dew Point Temp_C              -4.4
Rel Hum_%                       18
Wind Speed_km/h                 13
Visibility_km                 48.3
Press_kPa                    101.0
Weather              Mostly Cloudy
Name: 3066, dtype: object
Inserting row 3068
Error inserting row 3068: tuple index out of range
Row data: Date/Time           5/7/2012 19:00
Temp_C                        19.9
Dew Point Temp_C              -4.0
Rel Hum_%                       20
Wind Speed_km/h                 11
Visibility_km                 48.3
Press_kPa                   100.93
Weather              Mostly Cloudy
Name: 3067, dtype: object
Inserting row 3069
Error inserting row 3069: tuple index out of range
Row data: Date/Time           5/7/2012 20:00
Temp_C                        19.2
Dew Point Temp_C              -3.8
Rel Hum_%                       21
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                    100.9
Weather              Mostly Cloudy
Name: 3068, dtype: object
Inserting row 3070
Error inserting row 3070: tuple index out of range
Row data: Date/Time           5/7/2012 21:00
Temp_C                        18.7
Dew Point Temp_C              -4.1
Rel Hum_%                       21
Wind Speed_km/h                 15
Visibility_km                 25.0
Press_kPa                   100.87
Weather                      Clear
Name: 3069, dtype: object
Inserting row 3071
Error inserting row 3071: tuple index out of range
Row data: Date/Time           5/7/2012 22:00
Temp_C                        18.1
Dew Point Temp_C              -3.5
Rel Hum_%                       23
Wind Speed_km/h                 17
Visibility_km                 25.0
Press_kPa                   100.84
Weather               Mainly Clear
Name: 3070, dtype: object
Inserting row 3072
Error inserting row 3072: tuple index out of range
Row data: Date/Time           5/7/2012 23:00
Temp_C                        17.6
Dew Point Temp_C              -2.2
Rel Hum_%                       26
Wind Speed_km/h                 15
Visibility_km                 25.0
Press_kPa                   100.77
Weather              Mostly Cloudy
Name: 3071, dtype: object
Inserting row 3073
Error inserting row 3073: tuple index out of range
Row data: Date/Time           5/8/2012 0:00
Temp_C                       16.1
Dew Point Temp_C              0.2
Rel Hum_%                      34
Wind Speed_km/h                11
Visibility_km                25.0
Press_kPa                  100.77
Weather             Mostly Cloudy
Name: 3072, dtype: object
Inserting row 3074
Error inserting row 3074: tuple index out of range
Row data: Date/Time           5/8/2012 1:00
Temp_C                       16.0
Dew Point Temp_C              4.8
Rel Hum_%                      47
Wind Speed_km/h                15
Visibility_km                25.0
Press_kPa                  100.74
Weather              Rain Showers
Name: 3073, dtype: object
Inserting row 3075
Error inserting row 3075: tuple index out of range
Row data: Date/Time           5/8/2012 2:00
Temp_C                       14.8
Dew Point Temp_C              5.4
Rel Hum_%                      53
Wind Speed_km/h                 4
Visibility_km                25.0
Press_kPa                  100.71
Weather                    Cloudy
Name: 3074, dtype: object
Inserting row 3076
Error inserting row 3076: tuple index out of range
Row data: Date/Time           5/8/2012 3:00
Temp_C                       15.2
Dew Point Temp_C              6.6
Rel Hum_%                      56
Wind Speed_km/h                 6
Visibility_km                25.0
Press_kPa                  100.64
Weather                      Rain
Name: 3075, dtype: object
Inserting row 3077
Error inserting row 3077: tuple index out of range
Row data: Date/Time           5/8/2012 4:00
Temp_C                       14.2
Dew Point Temp_C             10.4
Rel Hum_%                      78
Wind Speed_km/h                17
Visibility_km                25.0
Press_kPa                   100.6
Weather                      Rain
Name: 3076, dtype: object
Inserting row 3078
Error inserting row 3078: tuple index out of range
Row data: Date/Time           5/8/2012 5:00
Temp_C                       13.7
Dew Point Temp_C             10.3
Rel Hum_%                      80
Wind Speed_km/h                19
Visibility_km                24.1
Press_kPa                  100.53
Weather                    Cloudy
Name: 3077, dtype: object
Inserting row 3079
Error inserting row 3079: tuple index out of range
Row data: Date/Time           5/8/2012 6:00
Temp_C                       12.6
Dew Point Temp_C             10.4
Rel Hum_%                      86
Wind Speed_km/h                22
Visibility_km                 9.7
Press_kPa                  100.51
Weather                      Rain
Name: 3078, dtype: object
Inserting row 3080
Error inserting row 3080: tuple index out of range
Row data: Date/Time           5/8/2012 7:00
Temp_C                       12.2
Dew Point Temp_C             10.1
Rel Hum_%                      87
Wind Speed_km/h                24
Visibility_km                 6.4
Press_kPa                  100.48
Weather                      Rain
Name: 3079, dtype: object
Inserting row 3081
Error inserting row 3081: tuple index out of range
Row data: Date/Time           5/8/2012 8:00
Temp_C                       11.6
Dew Point Temp_C              9.5
Rel Hum_%                      87
Wind Speed_km/h                26
Visibility_km                 6.4
Press_kPa                  100.45
Weather                      Rain
Name: 3080, dtype: object
Inserting row 3082
Error inserting row 3082: tuple index out of range
Row data: Date/Time           5/8/2012 9:00
Temp_C                       11.1
Dew Point Temp_C              9.1
Rel Hum_%                      87
Wind Speed_km/h                32
Visibility_km                 6.4
Press_kPa                  100.41
Weather                      Rain
Name: 3081, dtype: object
Inserting row 3083
Error inserting row 3083: tuple index out of range
Row data: Date/Time           5/8/2012 10:00
Temp_C                        10.9
Dew Point Temp_C               8.9
Rel Hum_%                       87
Wind Speed_km/h                 26
Visibility_km                  8.0
Press_kPa                   100.39
Weather                   Rain,Fog
Name: 3082, dtype: object
Inserting row 3084
Error inserting row 3084: tuple index out of range
Row data: Date/Time           5/8/2012 11:00
Temp_C                        11.0
Dew Point Temp_C               9.2
Rel Hum_%                       89
Wind Speed_km/h                 20
Visibility_km                  6.4
Press_kPa                   100.37
Weather                   Rain,Fog
Name: 3083, dtype: object
Inserting row 3085
Error inserting row 3085: tuple index out of range
Row data: Date/Time           5/8/2012 12:00
Temp_C                        11.1
Dew Point Temp_C               9.3
Rel Hum_%                       89
Wind Speed_km/h                 19
Visibility_km                  6.4
Press_kPa                   100.37
Weather                   Rain,Fog
Name: 3084, dtype: object
Inserting row 3086
Error inserting row 3086: tuple index out of range
Row data: Date/Time           5/8/2012 13:00
Temp_C                        11.5
Dew Point Temp_C               9.6
Rel Hum_%                       88
Wind Speed_km/h                 17
Visibility_km                  6.4
Press_kPa                   100.35
Weather                   Rain,Fog
Name: 3085, dtype: object
Inserting row 3087
Error inserting row 3087: tuple index out of range
Row data: Date/Time           5/8/2012 14:00
Temp_C                        11.7
Dew Point Temp_C               9.9
Rel Hum_%                       89
Wind Speed_km/h                 19
Visibility_km                  8.0
Press_kPa                   100.32
Weather                   Rain,Fog
Name: 3086, dtype: object
Inserting row 3088
Error inserting row 3088: tuple index out of range
Row data: Date/Time           5/8/2012 15:00
Temp_C                        12.0
Dew Point Temp_C              10.0
Rel Hum_%                       88
Wind Speed_km/h                 17
Visibility_km                 12.9
Press_kPa                    100.3
Weather                       Rain
Name: 3087, dtype: object
Inserting row 3089
Error inserting row 3089: tuple index out of range
Row data: Date/Time           5/8/2012 16:00
Temp_C                        12.2
Dew Point Temp_C              10.3
Rel Hum_%                       88
Wind Speed_km/h                 15
Visibility_km                 12.9
Press_kPa                   100.28
Weather                       Rain
Name: 3088, dtype: object
Inserting row 3090
Error inserting row 3090: tuple index out of range
Row data: Date/Time           5/8/2012 17:00
Temp_C                        12.2
Dew Point Temp_C              10.3
Rel Hum_%                       88
Wind Speed_km/h                  9
Visibility_km                 12.9
Press_kPa                   100.29
Weather                       Rain
Name: 3089, dtype: object
Inserting row 3091
Error inserting row 3091: tuple index out of range
Row data: Date/Time           5/8/2012 18:00
Temp_C                        12.1
Dew Point Temp_C              10.3
Rel Hum_%                       89
Wind Speed_km/h                 11
Visibility_km                  9.7
Press_kPa                   100.29
Weather                   Rain,Fog
Name: 3090, dtype: object
Inserting row 3092
Error inserting row 3092: tuple index out of range
Row data: Date/Time           5/8/2012 19:00
Temp_C                        12.3
Dew Point Temp_C              10.5
Rel Hum_%                       89
Wind Speed_km/h                  6
Visibility_km                  8.0
Press_kPa                    100.3
Weather                        Fog
Name: 3091, dtype: object
Inserting row 3093
Error inserting row 3093: tuple index out of range
Row data: Date/Time           5/8/2012 20:00
Temp_C                        12.1
Dew Point Temp_C              10.5
Rel Hum_%                       90
Wind Speed_km/h                  9
Visibility_km                  8.0
Press_kPa                   100.33
Weather                Drizzle,Fog
Name: 3092, dtype: object
Inserting row 3094
Error inserting row 3094: tuple index out of range
Row data: Date/Time           5/8/2012 21:00
Temp_C                        12.2
Dew Point Temp_C              10.6
Rel Hum_%                       90
Wind Speed_km/h                  6
Visibility_km                  8.0
Press_kPa                   100.31
Weather                        Fog
Name: 3093, dtype: object
Inserting row 3095
Error inserting row 3095: tuple index out of range
Row data: Date/Time           5/8/2012 22:00
Temp_C                        12.3
Dew Point Temp_C              10.7
Rel Hum_%                       90
Wind Speed_km/h                  6
Visibility_km                  8.0
Press_kPa                    100.3
Weather                        Fog
Name: 3094, dtype: object
Inserting row 3096
Error inserting row 3096: tuple index out of range
Row data: Date/Time           5/8/2012 23:00
Temp_C                        12.4
Dew Point Temp_C              10.9
Rel Hum_%                       91
Wind Speed_km/h                  4
Visibility_km                  6.4
Press_kPa                   100.26
Weather                Drizzle,Fog
Name: 3095, dtype: object
Inserting row 3097
Error inserting row 3097: tuple index out of range
Row data: Date/Time           5/9/2012 0:00
Temp_C                       12.5
Dew Point Temp_C             11.0
Rel Hum_%                      91
Wind Speed_km/h                 0
Visibility_km                 3.2
Press_kPa                  100.27
Weather                  Rain,Fog
Name: 3096, dtype: object
Inserting row 3098
Error inserting row 3098: tuple index out of range
Row data: Date/Time           5/9/2012 1:00
Temp_C                       12.6
Dew Point Temp_C             11.2
Rel Hum_%                      91
Wind Speed_km/h                 0
Visibility_km                 3.2
Press_kPa                   100.2
Weather                  Rain,Fog
Name: 3097, dtype: object
Inserting row 3099
Error inserting row 3099: tuple index out of range
Row data: Date/Time           5/9/2012 2:00
Temp_C                       12.8

Inserting row 3254
Error inserting row 3254: tuple index out of range
Row data: Date/Time           5/15/2012 13:00
Temp_C                         20.1
Dew Point Temp_C               14.6
Rel Hum_%                        71
Wind Speed_km/h                  20
Visibility_km                  24.1
Press_kPa                    101.02
Weather                      Cloudy
Name: 3253, dtype: object
Inserting row 3255
Error inserting row 3255: tuple index out of range
Row data: Date/Time           5/15/2012 14:00
Temp_C                         19.2
Dew Point Temp_C               14.4
Rel Hum_%                        74
Wind Speed_km/h                  19
Visibility_km                  24.1
Press_kPa                    100.98
Weather                      Cloudy
Name: 3254, dtype: object
Inserting row 3256
Error inserting row 3256: tuple index out of range
Row data: Date/Time           5/15/2012 15:00
Temp_C                         17.8
Dew Point Temp_C               15.2
Rel Hum_%                        85
Wind Speed_km/h                   9
Visibility_km                  16.1
Press_kPa                    100.95
Weather                Rain Showers
Name: 3255, dtype: object
Inserting row 3257
Error inserting row 3257: tuple index out of range
Row data: Date/Time           5/15/2012 16:00
Temp_C                         18.2
Dew Point Temp_C               15.4
Rel Hum_%                        84
Wind Speed_km/h                  15
Visibility_km                  24.1
Press_kPa                     100.9
Weather                      Cloudy
Name: 3256, dtype: object
Inserting row 3258
Error inserting row 3258: tuple index out of range
Row data: Date/Time           5/15/2012 17:00
Temp_C                         18.2
Dew Point Temp_C               15.3
Rel Hum_%                        83
Wind Speed_km/h                  17
Visibility_km                  24.1
Press_kPa                    100.85
Weather               Mostly Cloudy
Name: 3257, dtype: object
Inserting row 3259
Error inserting row 3259: tuple index out of range
Row data: Date/Time           5/15/2012 18:00
Temp_C                         17.9
Dew Point Temp_C               15.1
Rel Hum_%                        84
Wind Speed_km/h                  19
Visibility_km                  24.1
Press_kPa                    100.83
Weather               Mostly Cloudy
Name: 3258, dtype: object
Inserting row 3260
Error inserting row 3260: tuple index out of range
Row data: Date/Time           5/15/2012 19:00
Temp_C                         17.4
Dew Point Temp_C               15.0
Rel Hum_%                        86
Wind Speed_km/h                  17
Visibility_km                  24.1
Press_kPa                    100.81
Weather               Mostly Cloudy
Name: 3259, dtype: object
Inserting row 3261
Error inserting row 3261: tuple index out of range
Row data: Date/Time           5/15/2012 20:00
Temp_C                         17.0
Dew Point Temp_C               14.4
Rel Hum_%                        85
Wind Speed_km/h                  17
Visibility_km                  24.1
Press_kPa                    100.79
Weather               Mostly Cloudy
Name: 3260, dtype: object
Inserting row 3262
Error inserting row 3262: tuple index out of range
Row data: Date/Time           5/15/2012 21:00
Temp_C                         16.6
Dew Point Temp_C               14.0
Rel Hum_%                        85
Wind Speed_km/h                  15
Visibility_km                  25.0
Press_kPa                    100.77
Weather               Mostly Cloudy
Name: 3261, dtype: object
Inserting row 3263
Error inserting row 3263: tuple index out of range
Row data: Date/Time           5/15/2012 22:00
Temp_C                         15.9
Dew Point Temp_C               13.6
Rel Hum_%                        86
Wind Speed_km/h                  11
Visibility_km                  25.0
Press_kPa                    100.75
Weather                       Clear
Name: 3262, dtype: object
Inserting row 3264
Error inserting row 3264: tuple index out of range
Row data: Date/Time           5/15/2012 23:00
Temp_C                         15.4
Dew Point Temp_C               13.2
Rel Hum_%                        87
Wind Speed_km/h                  11
Visibility_km                  25.0
Press_kPa                    100.74
Weather                       Clear
Name: 3263, dtype: object
Inserting row 3265
Error inserting row 3265: tuple index out of range
Row data: Date/Time           5/16/2012 0:00
Temp_C                        14.6
Dew Point Temp_C              12.6
Rel Hum_%                       88
Wind Speed_km/h                  4
Visibility_km                 25.0
Press_kPa                   100.71
Weather                      Clear
Name: 3264, dtype: object
Inserting row 3266
Error inserting row 3266: tuple index out of range
Row data: Date/Time           5/16/2012 1:00
Temp_C                        13.9
Dew Point Temp_C              12.0
Rel Hum_%                       88
Wind Speed_km/h                  6
Visibility_km                 25.0
Press_kPa                   100.66
Weather                      Clear
Name: 3265, dtype: object
Inserting row 3267
Error inserting row 3267: tuple index out of range
Row data: Date/Time           5/16/2012 2:00
Temp_C                        13.9
Dew Point Temp_C              12.0
Rel Hum_%                       88
Wind Speed_km/h                  6
Visibility_km                 25.0
Press_kPa                    100.6
Weather                      Clear
Name: 3266, dtype: object
Inserting row 3268
Error inserting row 3268: tuple index out of range
Row data: Date/Time           5/16/2012 3:00
Temp_C                        13.3
Dew Point Temp_C              11.4
Rel Hum_%                       88
Wind Speed_km/h                  0
Visibility_km                 25.0
Press_kPa                   100.58
Weather                      Clear
Name: 3267, dtype: object
Inserting row 3269
Error inserting row 3269: tuple index out of range
Row data: Date/Time           5/16/2012 4:00
Temp_C                        12.9
Dew Point Temp_C              11.0
Rel Hum_%                       88
Wind Speed_km/h                  6
Visibility_km                 19.3
Press_kPa                   100.59
Weather               Mainly Clear
Name: 3268, dtype: object
Inserting row 3270
Error inserting row 3270: tuple index out of range
Row data: Date/Time           5/16/2012 5:00
Temp_C                        13.0
Dew Point Temp_C              11.1
Rel Hum_%                       88
Wind Speed_km/h                  0
Visibility_km                 16.1
Press_kPa                   100.56
Weather              Mostly Cloudy
Name: 3269, dtype: object
Inserting row 3271
Error inserting row 3271: tuple index out of range
Row data: Date/Time           5/16/2012 6:00
Temp_C                        13.8
Dew Point Temp_C              12.0
Rel Hum_%                       89
Wind Speed_km/h                 11
Visibility_km                 19.3
Press_kPa                   100.56
Weather              Mostly Cloudy
Name: 3270, dtype: object
Inserting row 3272
Error inserting row 3272: tuple index out of range
Row data: Date/Time           5/16/2012 7:00
Temp_C                        15.0
Dew Point Temp_C              12.8
Rel Hum_%                       87
Wind Speed_km/h                  9
Visibility_km                 24.1
Press_kPa                   100.57
Weather              Mostly Cloudy
Name: 3271, dtype: object
Inserting row 3273
Error inserting row 3273: tuple index out of range
Row data: Date/Time           5/16/2012 8:00
Temp_C                        17.5
Dew Point Temp_C              13.9
Rel Hum_%                       79
Wind Speed_km/h                  9
Visibility_km                 24.1
Press_kPa                   100.54
Weather              Mostly Cloudy
Name: 3272, dtype: object
Inserting row 3274
Error inserting row 3274: tuple index out of range
Row data: Date/Time           5/16/2012 9:00
Temp_C                        20.1
Dew Point Temp_C              14.2
Rel Hum_%                       69
Wind Speed_km/h                 13
Visibility_km                 24.1
Press_kPa                   100.45
Weather               Mainly Clear
Name: 3273, dtype: object
Inserting row 3275
Error inserting row 3275: tuple index out of range
Row data: Date/Time           5/16/2012 10:00
Temp_C                         21.9
Dew Point Temp_C               14.1
Rel Hum_%                        61
Wind Speed_km/h                  15
Visibility_km                  24.1
Press_kPa                    100.35
Weather                Mainly Clear
Name: 3274, dtype: object
Inserting row 3276
Error inserting row 3276: tuple index out of range
Row data: Date/Time           5/16/2012 11:00
Temp_C                         22.0
Dew Point Temp_C               13.1
Rel Hum_%                        57
Wind Speed_km/h                  20
Visibility_km                  19.3
Press_kPa                    100.35
Weather               Mostly Cloudy
Name: 3275, dtype: object
Inserting row 3277
Error inserting row 3277: tuple index out of range
Row data: Date/Time           5/16/2012 12:00
Temp_C                         22.9
Dew Point Temp_C               12.5
Rel Hum_%                        52
Wind Speed_km/h                  11
Visibility_km                  24.1
Press_kPa                    100.23
Weather               Mostly Cloudy
Name: 3276, dtype: object
Inserting row 3278
Error inserting row 3278: tuple index out of range
Row data: Date/Time           5/16/2012 13:00
Temp_C                         23.4
Dew Point Temp_C               12.3
Rel Hum_%                        50
Wind Speed_km/h                  15
Visibility_km                  24.1
Press_kPa                    100.21
Weather               Mostly Cloudy
Name: 3277, dtype: object
Inserting row 3279
Error inserting row 3279: tuple index out of range
Row data: Date/Time           5/16/2012 14:00
Temp_C                         17.9
Dew Point Temp_C               13.2
Rel Hum_%                        74
Wind Speed_km/h                  19
Visibility_km                  19.3
Press_kPa                    100.22
Weather                      Cloudy
Name: 3278, dtype: object
Inserting row 3280
Error inserting row 3280: tuple index out of range
Row data: Date/Time           5/16/2012 15:00
Temp_C                         19.3
Dew Point Temp_C               10.4
Rel Hum_%                        56
Wind Speed_km/h                  32
Visibility_km                  24.1
Press_kPa                    100.29
Weather               Mostly Cloudy
Name: 3279, dtype: object
Inserting row 3281
Error inserting row 3281: tuple index out of range
Row data: Date/Time           5/16/2012 16:00
Temp_C                         18.7
Dew Point Temp_C               10.2
Rel Hum_%                        58
Wind Speed_km/h                  33
Visibility_km                  24.1
Press_kPa                    100.27
Weather               Mostly Cloudy
Name: 3280, dtype: object
Inserting row 3282
Error inserting row 3282: tuple index out of range
Row data: Date/Time           5/16/2012 17:00
Temp_C                         17.6
Dew Point Temp_C               10.7
Rel Hum_%                        64
Wind Speed_km/h                  22
Visibility_km                  24.1
Press_kPa                    100.32
Weather               Mostly Cloudy
Name: 3281, dtype: object
Inserting row 3283
Error inserting row 3283: tuple index out of range
Row data: Date/Time           5/16/2012 18:00
Temp_C                         18.2
Dew Point Temp_C               11.1
Rel Hum_%                        63
Wind Speed_km/h                  26
Visibility_km                  24.1
Press_kPa                    100.35
Weather                Mainly Clear
Name: 3282, dtype: object
Inserting row 3284
Error inserting row 3284: tuple index out of range
Row data: Date/Time           5/16/2012 19:00
Temp_C                         17.6
Dew Point Temp_C               10.7
Rel Hum_%                        64
Wind Speed_km/h                  22
Visibility_km                  24.1
Press_kPa                    100.34
Weather                Mainly Clear
Name: 3283, dtype: object
Inserting row 3285
Error inserting row 3285: tuple index out of range
Row data: Date/Time           5/16/2012 20:00
Temp_C                         17.1
Dew Point Temp_C                9.9
Rel Hum_%                        63
Wind Speed_km/h                  17
Visibility_km                  25.0
Press_kPa                    100.37
Weather                Mainly Clear
Name: 3284, dtype: object
Inserting row 3286
Error inserting row 3286: tuple index out of range
Row data: Date/Time           5/16/2012 21:00
Temp_C                         14.2
Dew Point Temp_C                6.9
Rel Hum_%                        61
Wind Speed_km/h                  17
Visibility_km                  25.0
Press_kPa                    100.53
Weather               Mostly Cloudy
Name: 3285, dtype: object
Inserting row 3287
Error inserting row 3287: tuple index out of range
Row data: Date/Time           5/16/2012 22:00
Temp_C                         13.3
Dew Point Temp_C                5.7
Rel Hum_%                        60
Wind Speed_km/h                  20
Visibility_km                  25.0
Press_kPa                    100.66
Weather               Mostly Cloudy
Name: 3286, dtype: object
Inserting row 3288
Error inserting row 3288: tuple index out of range
Row data: Date/Time           5/16/2012 23:00
Temp_C                         11.5
Dew Point Temp_C                3.2
Rel Hum_%                        57
Wind Speed_km/h                  22
Visibility_km                  25.0
Press_kPa                    100.82
Weather               Mostly Cloudy
Name: 3287, dtype: object
Inserting row 3289
Error inserting row 3289: tuple index out of range
Row data: Date/Time           5/17/2012 0:00
Temp_C                        10.0
Dew Point Temp_C               2.9
Rel Hum_%                       61
Wind Speed_km/h                 24
Visibility_km                 25.0
Press_kPa                   100.93
Weather              Mostly Cloudy
Name: 3288, dtype: object
Inserting row 3290
Error inserting row 3290: tuple index out of range
Row data: Date/Time           5/17/2012 1:00
Temp_C                         9.8
Dew Point Temp_C               2.1
Rel Hum_%                       59
Wind Speed_km/h                 24
Visibility_km                 25.0
Press_kPa                   101.05
Weather              Mostly Cloudy
Name: 3289, dtype: object
Inserting row 3291
Error inserting row 3291: tuple index out of range
Row data: Date/Time           5/17/2012 2:00
Temp_C                         8.3
Dew Point Temp_C               1.6
Rel Hum_%                       63
Wind Speed_km/h                 15
Visibility_km                 25.0
Press_kPa                   101.07
Weather                      Clear
Name: 3290, dtype: object
Inserting row 3292
Error inserting row 3292: tuple index out of range
Row data: Date/Time           5/17/2012 3:00
Temp_C                         7.3
Dew Point Temp_C               1.6
Rel Hum_%                       67
Wind Speed_km/h                 15
Visibility_km                 25.0
Press_kPa                   101.16
Weather                      Clear
Name: 3291, dtype: object
Inserting row 3293
Error inserting row 3293: tuple index out of range
Row data: Date/Time           5/17/2012 4:00
Temp_C                         6.6
Dew Point Temp_C               1.4
Rel Hum_%                       69
Wind Speed_km/h                  9
Visibility_km                 48.3
Press_kPa                   101.24
Weather                      Clear
Name: 3292, dtype: object
Inserting row 3294
Error inserting row 3294: tuple index out of range
Row data: Date/Time           5/17/2012 5:00
Temp_C                         6.0
Dew Point Temp_C               1.0
Rel Hum_%                       70
Wind Speed_km/h                 11
Visibility_km                 48.3
Press_kPa                   101.32
Weather                      Clear
Name: 3293, dtype: object
Inserting row 3295
Error inserting row 3295: tuple index out of range
Row data: Date/Time           5/17/2012 6:00
Temp_C                         8.5
Dew Point Temp_C               1.9
Rel Hum_%                       63
Wind Speed_km/h                  9
Visibility_km                 48.3
Press_kPa                    101.4
Weather                      Clear
Name: 3294, dtype: object
Inserting row 3296
Error inserting row 3296: tuple index out of range
Row data: Date/Time           5/17/2012 7:00
Temp_C                        10.2
Dew Point Temp_C               1.8
Rel Hum_%                       56
Wind Speed_km/h                 15
Visibility_km                 48.3
Press_kPa                   101.45
Weather              Mostly Cloudy
Name: 3295, dtype: object
Inserting row 3297
Error inserting row 3297: tuple index out of range
Row data: Date/Time           5/17/2012 8:00
Temp_C                        10.7
Dew Point Temp_C               2.2
Rel Hum_%                       56
Wind Speed_km/h                 15
Visibility_km                 48.3
Press_kPa                    101.5
Weather              Mostly Cloudy
Name: 3296, dtype: object
Inserting row 3298
Error inserting row 3298: tuple index out of range
Row data: Date/Time           5/17/2012 9:00
Temp_C                        11.3
Dew Point Temp_C               2.1
Rel Hum_%                       53
Wind Speed_km/h                 22
Visibility_km                 48.3
Press_kPa                   101.48
Weather               Mainly Clear
Name: 3297, dtype: object
Inserting row 3299
Error inserting row 3299: tuple index out of range
Row data: Date/Time           5/17/2012 10:00
Temp_C                         12.2
Dew Point Temp_C                2.2
Rel Hum_%                        50
Wind Speed_km/h                  26
Visibility_km                  48.3
Press_kPa                    101.46
Weather               Mostly Cloudy
Name: 3298, dtype: object
Inserting row 3300
Error inserting row 3300: tuple index out of range
Row data: Date/Time           5/17/2012 11:00
Temp_C                         13.9
Dew Point Temp_C                2.5
Rel Hum_%                        46
Wind Speed_km/h                  22
Visibility_km                  48.3
Press_kPa                    101.49
Weather                Mainly Clear
Name: 3299, dtype: object
Inserting row 3301
Error inserting row 3301: tuple index out of range
Row data: Date/Time           5/17/2012 12:00
Temp_C                         14.3
Dew Point Temp_C                1.8
Rel Hum_%                        43
Wind Speed_km/h                  17
Visibility_km                  48.3
Press_kPa                    101.49
Weather               Mostly Cloudy
Name: 3300, dtype: object
Inserting row 3302
Error inserting row 3302: tuple index out of range
Row data: Date/Time           5/17/2012 13:00
Temp_C                         15.4
Dew Point Temp_C                0.5
Rel Hum_%                        36
Wind Speed_km/h                  26
Visibility_km                  48.3
Press_kPa                    101.46
Weather                Mainly Clear
Name: 3301, dtype: object
Inserting row 3303
Error inserting row 3303: tuple index out of range
Row data: Date/Time           5/17/2012 14:00
Temp_C                         15.3
Dew Point Temp_C                0.9
Rel Hum_%                        38
Wind Speed_km/h                  20
Visibility_km                  48.3
Press_kPa                    101.48
Weather                Mainly Clear
Name: 3302, dtype: object
Inserting row 3304
Error inserting row 3304: tuple index out of range
Row data: Date/Time           5/17/2012 15:00
Temp_C                         15.8
Dew Point Temp_C                0.4
Rel Hum_%                        35
Wind Speed_km/h                  24
Visibility_km                  48.3
Press_kPa                    101.46
Weather                Mainly Clear
Name: 3303, dtype: object
Inserting row 3305

Row data: Date/Time           5/25/2012 17:00
Temp_C                         27.2
Dew Point Temp_C               16.7
Rel Hum_%                        53
Wind Speed_km/h                  19
Visibility_km                  24.1
Press_kPa                    100.72
Weather               Mostly Cloudy
Name: 3497, dtype: object
Inserting row 3499
Error inserting row 3499: tuple index out of range
Row data: Date/Time           5/25/2012 18:00
Temp_C                         26.2
Dew Point Temp_C               16.1
Rel Hum_%                        54
Wind Speed_km/h                  20
Visibility_km                  24.1
Press_kPa                    100.65
Weather               Mostly Cloudy
Name: 3498, dtype: object
Inserting row 3500
Error inserting row 3500: tuple index out of range
Row data: Date/Time           5/25/2012 19:00
Temp_C                         26.4
Dew Point Temp_C               16.1
Rel Hum_%                        53
Wind Speed_km/h                  22
Visibility_km                  25.0
Press_kPa                    100.59
Weather                      Cloudy
Name: 3499, dtype: object
Inserting row 3501
Error inserting row 3501: tuple index out of range
Row data: Date/Time              5/25/2012 20:00
Temp_C                            21.3
Dew Point Temp_C                  18.3
Rel Hum_%                           83
Wind Speed_km/h                     13
Visibility_km                     16.1
Press_kPa                       100.83
Weather             Thunderstorms,Rain
Name: 3500, dtype: object
Inserting row 3502
Error inserting row 3502: tuple index out of range
Row data: Date/Time           5/25/2012 21:00
Temp_C                         22.1
Dew Point Temp_C               18.5
Rel Hum_%                        80
Wind Speed_km/h                  15
Visibility_km                  25.0
Press_kPa                    100.79
Weather                Mainly Clear
Name: 3501, dtype: object
Inserting row 3503
Error inserting row 3503: tuple index out of range
Row data: Date/Time           5/25/2012 22:00
Temp_C                         21.5
Dew Point Temp_C               18.1
Rel Hum_%                        81
Wind Speed_km/h                  11
Visibility_km                  25.0
Press_kPa                    100.88
Weather                Mainly Clear
Name: 3502, dtype: object
Inserting row 3504
Error inserting row 3504: tuple index out of range
Row data: Date/Time           5/25/2012 23:00
Temp_C                         21.3
Dew Point Temp_C               15.4
Rel Hum_%                        69
Wind Speed_km/h                  17
Visibility_km                  25.0
Press_kPa                    100.96
Weather                       Clear
Name: 3503, dtype: object
Inserting row 3505
Error inserting row 3505: tuple index out of range
Row data: Date/Time           5/26/2012 0:00
Temp_C                        19.8
Dew Point Temp_C              14.8
Rel Hum_%                       73
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                    101.0
Weather                      Clear
Name: 3504, dtype: object
Inserting row 3506
Error inserting row 3506: tuple index out of range
Row data: Date/Time           5/26/2012 1:00
Temp_C                        19.3
Dew Point Temp_C              14.0
Rel Hum_%                       71
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   101.09
Weather                      Clear
Name: 3505, dtype: object
Inserting row 3507
Error inserting row 3507: tuple index out of range
Row data: Date/Time           5/26/2012 2:00
Temp_C                        18.6
Dew Point Temp_C              12.3
Rel Hum_%                       67
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   101.16
Weather                      Clear
Name: 3506, dtype: object
Inserting row 3508
Error inserting row 3508: tuple index out of range
Row data: Date/Time           5/26/2012 3:00
Temp_C                        17.1
Dew Point Temp_C              10.5
Rel Hum_%                       65
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   101.21
Weather                      Clear
Name: 3507, dtype: object
Inserting row 3509
Error inserting row 3509: tuple index out of range
Row data: Date/Time           5/26/2012 4:00
Temp_C                        16.4
Dew Point Temp_C              10.1
Rel Hum_%                       66
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                   101.28
Weather                      Clear
Name: 3508, dtype: object
Inserting row 3510
Error inserting row 3510: tuple index out of range
Row data: Date/Time           5/26/2012 5:00
Temp_C                        16.3
Dew Point Temp_C               9.8
Rel Hum_%                       65
Wind Speed_km/h                  9
Visibility_km                 24.1
Press_kPa                   101.36
Weather               Mainly Clear
Name: 3509, dtype: object
Inserting row 3511
Error inserting row 3511: tuple index out of range
Row data: Date/Time           5/26/2012 6:00
Temp_C                        17.1
Dew Point Temp_C              10.0
Rel Hum_%                       63
Wind Speed_km/h                  9
Visibility_km                 48.3
Press_kPa                   101.37
Weather                      Clear
Name: 3510, dtype: object
Inserting row 3512
Error inserting row 3512: tuple index out of range
Row data: Date/Time           5/26/2012 7:00
Temp_C                        18.1
Dew Point Temp_C              10.8
Rel Hum_%                       62
Wind Speed_km/h                  9
Visibility_km                 48.3
Press_kPa                   101.51
Weather                      Clear
Name: 3511, dtype: object
Inserting row 3513
Error inserting row 3513: tuple index out of range
Row data: Date/Time           5/26/2012 8:00
Temp_C                        19.4
Dew Point Temp_C              12.2
Rel Hum_%                       63
Wind Speed_km/h                  6
Visibility_km                 48.3
Press_kPa                   101.56
Weather                      Clear
Name: 3512, dtype: object
Inserting row 3514
Error inserting row 3514: tuple index out of range
Row data: Date/Time           5/26/2012 9:00
Temp_C                        21.1
Dew Point Temp_C              12.7
Rel Hum_%                       59
Wind Speed_km/h                  9
Visibility_km                 24.1
Press_kPa                   101.56
Weather                      Clear
Name: 3513, dtype: object
Inserting row 3515
Error inserting row 3515: tuple index out of range
Row data: Date/Time           5/26/2012 10:00
Temp_C                         21.6
Dew Point Temp_C               12.5
Rel Hum_%                        56
Wind Speed_km/h                   7
Visibility_km                  19.3
Press_kPa                     101.6
Weather               Mostly Cloudy
Name: 3514, dtype: object
Inserting row 3516
Error inserting row 3516: tuple index out of range
Row data: Date/Time           5/26/2012 11:00
Temp_C                         22.6
Dew Point Temp_C               12.5
Rel Hum_%                        53
Wind Speed_km/h                   0
Visibility_km                  16.1
Press_kPa                     101.6
Weather                       Clear
Name: 3515, dtype: object
Inserting row 3517
Error inserting row 3517: tuple index out of range
Row data: Date/Time           5/26/2012 12:00
Temp_C                         23.3
Dew Point Temp_C               12.8
Rel Hum_%                        52
Wind Speed_km/h                  13
Visibility_km                  16.1
Press_kPa                    101.56
Weather                Mainly Clear
Name: 3516, dtype: object
Inserting row 3518
Error inserting row 3518: tuple index out of range
Row data: Date/Time           5/26/2012 13:00
Temp_C                         24.4
Dew Point Temp_C                9.9
Rel Hum_%                        40
Wind Speed_km/h                  30
Visibility_km                  19.3
Press_kPa                    101.53
Weather                Mainly Clear
Name: 3517, dtype: object
Inserting row 3519
Error inserting row 3519: tuple index out of range
Row data: Date/Time           5/26/2012 14:00
Temp_C                         24.2
Dew Point Temp_C               10.6
Rel Hum_%                        42
Wind Speed_km/h                  22
Visibility_km                  19.3
Press_kPa                    101.54
Weather                Mainly Clear
Name: 3518, dtype: object
Inserting row 3520
Error inserting row 3520: tuple index out of range
Row data: Date/Time           5/26/2012 15:00
Temp_C                         23.2
Dew Point Temp_C               10.2
Rel Hum_%                        44
Wind Speed_km/h                  20
Visibility_km                  24.1
Press_kPa                    101.54
Weather                Mainly Clear
Name: 3519, dtype: object
Inserting row 3521
Error inserting row 3521: tuple index out of range
Row data: Date/Time           5/26/2012 16:00
Temp_C                         23.8
Dew Point Temp_C               10.2
Rel Hum_%                        42
Wind Speed_km/h                  22
Visibility_km                  24.1
Press_kPa                    101.52
Weather               Mostly Cloudy
Name: 3520, dtype: object
Inserting row 3522
Error inserting row 3522: tuple index out of range
Row data: Date/Time           5/26/2012 17:00
Temp_C                         23.1
Dew Point Temp_C                9.4
Rel Hum_%                        42
Wind Speed_km/h                  19
Visibility_km                  24.1
Press_kPa                    101.49
Weather               Mostly Cloudy
Name: 3521, dtype: object
Inserting row 3523
Error inserting row 3523: tuple index out of range
Row data: Date/Time           5/26/2012 18:00
Temp_C                         22.2
Dew Point Temp_C                8.6
Rel Hum_%                        42
Wind Speed_km/h                  20
Visibility_km                  24.1
Press_kPa                    101.51
Weather               Mostly Cloudy
Name: 3522, dtype: object
Inserting row 3524
Error inserting row 3524: tuple index out of range
Row data: Date/Time           5/26/2012 19:00
Temp_C                         21.0
Dew Point Temp_C                7.7
Rel Hum_%                        42
Wind Speed_km/h                  13
Visibility_km                  24.1
Press_kPa                    101.56
Weather                Mainly Clear
Name: 3523, dtype: object
Inserting row 3525
Error inserting row 3525: tuple index out of range
Row data: Date/Time           5/26/2012 20:00
Temp_C                         18.5
Dew Point Temp_C                7.4
Rel Hum_%                        48
Wind Speed_km/h                   9
Visibility_km                  24.1
Press_kPa                    101.64
Weather                Mainly Clear
Name: 3524, dtype: object
Inserting row 3526
Error inserting row 3526: tuple index out of range
Row data: Date/Time           5/26/2012 21:00
Temp_C                         16.6
Dew Point Temp_C                7.5
Rel Hum_%                        55
Wind Speed_km/h                   7
Visibility_km                  25.0
Press_kPa                    101.71
Weather                Mainly Clear
Name: 3525, dtype: object
Inserting row 3527
Error inserting row 3527: tuple index out of range
Row data: Date/Time           5/26/2012 22:00
Temp_C                         17.3
Dew Point Temp_C                7.3
Rel Hum_%                        52
Wind Speed_km/h                   6
Visibility_km                  25.0
Press_kPa                    101.71
Weather                Mainly Clear
Name: 3526, dtype: object
Inserting row 3528
Error inserting row 3528: tuple index out of range
Row data: Date/Time           5/26/2012 23:00
Temp_C                         15.6
Dew Point Temp_C                7.7
Rel Hum_%                        59
Wind Speed_km/h                   6
Visibility_km                  25.0
Press_kPa                    101.75
Weather                Mainly Clear
Name: 3527, dtype: object
Inserting row 3529
Error inserting row 3529: tuple index out of range
Row data: Date/Time           5/27/2012 0:00
Temp_C                        15.7
Dew Point Temp_C               7.1
Rel Hum_%                       57
Wind Speed_km/h                  6
Visibility_km                 25.0
Press_kPa                   101.76
Weather                      Clear
Name: 3528, dtype: object
Inserting row 3530
Error inserting row 3530: tuple index out of range
Row data: Date/Time           5/27/2012 1:00
Temp_C                        14.6
Dew Point Temp_C               7.4
Rel Hum_%                       62
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                   101.77
Weather                      Clear
Name: 3529, dtype: object
Inserting row 3531
Error inserting row 3531: tuple index out of range
Row data: Date/Time           5/27/2012 2:00
Temp_C                        13.9
Dew Point Temp_C               6.9
Rel Hum_%                       63
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   101.76
Weather               Mainly Clear
Name: 3530, dtype: object
Inserting row 3532
Error inserting row 3532: tuple index out of range
Row data: Date/Time           5/27/2012 3:00
Temp_C                        14.8
Dew Point Temp_C               3.1
Rel Hum_%                       45
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   101.76
Weather              Mostly Cloudy
Name: 3531, dtype: object
Inserting row 3533
Error inserting row 3533: tuple index out of range
Row data: Date/Time           5/27/2012 4:00
Temp_C                        14.4
Dew Point Temp_C               3.5
Rel Hum_%                       48
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   101.84
Weather              Mostly Cloudy
Name: 3532, dtype: object
Inserting row 3534
Error inserting row 3534: tuple index out of range
Row data: Date/Time           5/27/2012 5:00
Temp_C                        13.7
Dew Point Temp_C               3.9
Rel Hum_%                       52
Wind Speed_km/h                 13
Visibility_km                 24.1
Press_kPa                    101.9
Weather              Mostly Cloudy
Name: 3533, dtype: object
Inserting row 3535
Error inserting row 3535: tuple index out of range
Row data: Date/Time           5/27/2012 6:00
Temp_C                        14.2
Dew Point Temp_C               2.4
Rel Hum_%                       45
Wind Speed_km/h                 17
Visibility_km                 24.1
Press_kPa                   101.92
Weather              Mostly Cloudy
Name: 3534, dtype: object
Inserting row 3536
Error inserting row 3536: tuple index out of range
Row data: Date/Time           5/27/2012 7:00
Temp_C                        14.6
Dew Point Temp_C               4.0
Rel Hum_%                       49
Wind Speed_km/h                  9
Visibility_km                 48.3
Press_kPa                   101.95
Weather              Mostly Cloudy
Name: 3535, dtype: object
Inserting row 3537
Error inserting row 3537: tuple index out of range
Row data: Date/Time           5/27/2012 8:00
Temp_C                        15.6
Dew Point Temp_C               3.1
Rel Hum_%                       43
Wind Speed_km/h                 11
Visibility_km                 48.3
Press_kPa                   101.94
Weather              Mostly Cloudy
Name: 3536, dtype: object
Inserting row 3538
Error inserting row 3538: tuple index out of range
Row data: Date/Time           5/27/2012 9:00
Temp_C                        17.1
Dew Point Temp_C               4.6
Rel Hum_%                       44
Wind Speed_km/h                  9
Visibility_km                 48.3
Press_kPa                   101.95
Weather              Mostly Cloudy
Name: 3537, dtype: object
Inserting row 3539
Error inserting row 3539: tuple index out of range
Row data: Date/Time           5/27/2012 10:00
Temp_C                         18.6
Dew Point Temp_C                4.0
Rel Hum_%                        38
Wind Speed_km/h                   0
Visibility_km                  48.3
Press_kPa                    101.89
Weather               Mostly Cloudy
Name: 3538, dtype: object
Inserting row 3540
Error inserting row 3540: tuple index out of range
Row data: Date/Time           5/27/2012 11:00
Temp_C                         19.5
Dew Point Temp_C                3.9
Rel Hum_%                        36
Wind Speed_km/h                   4
Visibility_km                  48.3
Press_kPa                    101.83
Weather                      Cloudy
Name: 3539, dtype: object
Inserting row 3541
Error inserting row 3541: tuple index out of range
Row data: Date/Time           5/27/2012 12:00
Temp_C                         19.7
Dew Point Temp_C                4.4
Rel Hum_%                        36
Wind Speed_km/h                   0
Visibility_km                  48.3
Press_kPa                    101.76
Weather                      Cloudy
Name: 3540, dtype: object
Inserting row 3542
Error inserting row 3542: tuple index out of range
Row data: Date/Time           5/27/2012 13:00
Temp_C                         20.2
Dew Point Temp_C                5.4
Rel Hum_%                        38
Wind Speed_km/h                  13
Visibility_km                  48.3
Press_kPa                    101.68
Weather                      Cloudy
Name: 3541, dtype: object
Inserting row 3543
Error inserting row 3543: tuple index out of range
Row data: Date/Time           5/27/2012 14:00
Temp_C                         21.2
Dew Point Temp_C                5.4
Rel Hum_%                        36
Wind Speed_km/h                   0
Visibility_km                  48.3
Press_kPa                    101.63
Weather                      Cloudy
Name: 3542, dtype: object
Inserting row 3544
Error inserting row 3544: tuple index out of range
Row data: Date/Time           5/27/2012 15:00
Temp_C                         20.3
Dew Point Temp_C                5.1
Rel Hum_%                        37
Wind Speed_km/h                  11
Visibility_km                  48.3
Press_kPa                    101.57
Weather                      Cloudy
Name: 3543, dtype: object
Inserting row 3545
Error inserting row 3545: tuple index out of range
Row data: Date/Time           5/27/2012 16:00
Temp_C                         20.4
Dew Point Temp_C                5.5
Rel Hum_%                        38
Wind Speed_km/h                  13
Visibility_km                  48.3
Press_kPa                    101.55
Weather                      Cloudy
Name: 3544, dtype: object
Inserting row 3546
Error inserting row 3546: tuple index out of range
Row data: Date/Time           5/27/2012 17:00
Temp_C                         20.3
Dew Point Temp_C                5.3
Rel Hum_%                        37
Wind Speed_km/h                   6
Visibility_km                  48.3
Press_kPa                    101.49
Weather                      Cloudy
Name: 3545, dtype: object
Inserting row 3547
Error inserting row 3547: tuple index out of range
Row data: Date/Time           5/27/2012 18:00
Temp_C                         19.2
Dew Point Temp_C                6.9
Rel Hum_%                        45
Wind Speed_km/h                   7
Visibility_km                  48.3
Press_kPa                    101.41
Weather                Rain Showers
Name: 3546, dtype: object
Inserting row 3548
Error inserting row 3548: tuple index out of range
Row data: Date/Time           5/27/2012 19:00
Temp_C                         18.1
Dew Point Temp_C                9.5
Rel Hum_%                        57
Wind Speed_km/h                   0
Visibility_km                  48.3
Press_kPa                    101.42
Weather                        Rain
Name: 3547, dtype: object
Inserting row 3549
Error inserting row 3549: tuple index out of range

Row data: Date/Time           6/5/2012 9:00
Temp_C                       17.4
Dew Point Temp_C              6.9
Rel Hum_%                      50
Wind Speed_km/h                19
Visibility_km                48.3
Press_kPa                  101.01
Weather                     Clear
Name: 3753, dtype: object
Inserting row 3755
Error inserting row 3755: tuple index out of range
Row data: Date/Time           6/5/2012 10:00
Temp_C                        18.8
Dew Point Temp_C               6.7
Rel Hum_%                       45
Wind Speed_km/h                 19
Visibility_km                 48.3
Press_kPa                   100.99
Weather               Mainly Clear
Name: 3754, dtype: object
Inserting row 3756
Error inserting row 3756: tuple index out of range
Row data: Date/Time           6/5/2012 11:00
Temp_C                        19.8
Dew Point Temp_C               5.3
Rel Hum_%                       39
Wind Speed_km/h                 26
Visibility_km                 48.3
Press_kPa                    101.0
Weather               Mainly Clear
Name: 3755, dtype: object
Inserting row 3757
Error inserting row 3757: tuple index out of range
Row data: Date/Time           6/5/2012 12:00
Temp_C                        20.3
Dew Point Temp_C               4.9
Rel Hum_%                       36
Wind Speed_km/h                 20
Visibility_km                 48.3
Press_kPa                   100.97
Weather               Mainly Clear
Name: 3756, dtype: object
Inserting row 3758
Error inserting row 3758: tuple index out of range
Row data: Date/Time           6/5/2012 13:00
Temp_C                        21.3
Dew Point Temp_C               3.8
Rel Hum_%                       32
Wind Speed_km/h                 15
Visibility_km                 48.3
Press_kPa                   100.93
Weather               Mainly Clear
Name: 3757, dtype: object
Inserting row 3759
Error inserting row 3759: tuple index out of range
Row data: Date/Time           6/5/2012 14:00
Temp_C                        21.6
Dew Point Temp_C               4.4
Rel Hum_%                       32
Wind Speed_km/h                  7
Visibility_km                 48.3
Press_kPa                   100.88
Weather               Mainly Clear
Name: 3758, dtype: object
Inserting row 3760
Error inserting row 3760: tuple index out of range
Row data: Date/Time           6/5/2012 15:00
Temp_C                        21.9
Dew Point Temp_C               4.4
Rel Hum_%                       32
Wind Speed_km/h                 11
Visibility_km                 48.3
Press_kPa                   100.83
Weather               Mainly Clear
Name: 3759, dtype: object
Inserting row 3761
Error inserting row 3761: tuple index out of range
Row data: Date/Time           6/5/2012 16:00
Temp_C                        22.6
Dew Point Temp_C               6.2
Rel Hum_%                       35
Wind Speed_km/h                  4
Visibility_km                 48.3
Press_kPa                   100.75
Weather               Mainly Clear
Name: 3760, dtype: object
Inserting row 3762
Error inserting row 3762: tuple index out of range
Row data: Date/Time           6/5/2012 17:00
Temp_C                        22.2
Dew Point Temp_C               5.4
Rel Hum_%                       34
Wind Speed_km/h                 15
Visibility_km                 48.3
Press_kPa                   100.74
Weather              Mostly Cloudy
Name: 3761, dtype: object
Inserting row 3763
Error inserting row 3763: tuple index out of range
Row data: Date/Time           6/5/2012 18:00
Temp_C                        20.9
Dew Point Temp_C               6.8
Rel Hum_%                       40
Wind Speed_km/h                 11
Visibility_km                 48.3
Press_kPa                   100.76
Weather               Rain Showers
Name: 3762, dtype: object
Inserting row 3764
Error inserting row 3764: tuple index out of range
Row data: Date/Time           6/5/2012 19:00
Temp_C                        17.0
Dew Point Temp_C              10.3
Rel Hum_%                       65
Wind Speed_km/h                 22
Visibility_km                 24.1
Press_kPa                   100.89
Weather               Rain Showers
Name: 3763, dtype: object
Inserting row 3765
Error inserting row 3765: tuple index out of range
Row data: Date/Time           6/5/2012 20:00
Temp_C                        15.6
Dew Point Temp_C              11.6
Rel Hum_%                       77
Wind Speed_km/h                  9
Visibility_km                 24.1
Press_kPa                   100.88
Weather               Rain Showers
Name: 3764, dtype: object
Inserting row 3766
Error inserting row 3766: tuple index out of range
Row data: Date/Time           6/5/2012 21:00
Temp_C                        16.3
Dew Point Temp_C               9.9
Rel Hum_%                       66
Wind Speed_km/h                  6
Visibility_km                 25.0
Press_kPa                    100.9
Weather              Mostly Cloudy
Name: 3765, dtype: object
Inserting row 3767
Error inserting row 3767: tuple index out of range
Row data: Date/Time           6/5/2012 22:00
Temp_C                        14.7
Dew Point Temp_C              11.0
Rel Hum_%                       78
Wind Speed_km/h                  7
Visibility_km                 25.0
Press_kPa                   100.95
Weather              Mostly Cloudy
Name: 3766, dtype: object
Inserting row 3768
Error inserting row 3768: tuple index out of range
Row data: Date/Time           6/5/2012 23:00
Temp_C                        16.4
Dew Point Temp_C               9.3
Rel Hum_%                       63
Wind Speed_km/h                 15
Visibility_km                 25.0
Press_kPa                   100.97
Weather              Mostly Cloudy
Name: 3767, dtype: object
Inserting row 3769
Error inserting row 3769: tuple index out of range
Row data: Date/Time           6/6/2012 0:00
Temp_C                       14.7
Dew Point Temp_C              7.9
Rel Hum_%                      64
Wind Speed_km/h                 9
Visibility_km                25.0
Press_kPa                  100.97
Weather             Mostly Cloudy
Name: 3768, dtype: object
Inserting row 3770
Error inserting row 3770: tuple index out of range
Row data: Date/Time           6/6/2012 1:00
Temp_C                       13.8
Dew Point Temp_C              7.2
Rel Hum_%                      64
Wind Speed_km/h                 9
Visibility_km                25.0
Press_kPa                  100.97
Weather             Mostly Cloudy
Name: 3769, dtype: object
Inserting row 3771
Error inserting row 3771: tuple index out of range
Row data: Date/Time           6/6/2012 2:00
Temp_C                       12.6
Dew Point Temp_C              6.6
Rel Hum_%                      67
Wind Speed_km/h                11
Visibility_km                25.0
Press_kPa                  100.99
Weather             Mostly Cloudy
Name: 3770, dtype: object
Inserting row 3772
Error inserting row 3772: tuple index out of range
Row data: Date/Time           6/6/2012 3:00
Temp_C                       11.0
Dew Point Temp_C              6.8
Rel Hum_%                      75
Wind Speed_km/h                 9
Visibility_km                25.0
Press_kPa                  100.99
Weather             Mostly Cloudy
Name: 3771, dtype: object
Inserting row 3773
Error inserting row 3773: tuple index out of range
Row data: Date/Time           6/6/2012 4:00
Temp_C                       11.2
Dew Point Temp_C              6.9
Rel Hum_%                      75
Wind Speed_km/h                 6
Visibility_km                24.1
Press_kPa                  101.03
Weather             Mostly Cloudy
Name: 3772, dtype: object
Inserting row 3774
Error inserting row 3774: tuple index out of range
Row data: Date/Time           6/6/2012 5:00
Temp_C                       12.0
Dew Point Temp_C              7.2
Rel Hum_%                      72
Wind Speed_km/h                 9
Visibility_km                48.3
Press_kPa                  101.05
Weather             Mostly Cloudy
Name: 3773, dtype: object
Inserting row 3775
Error inserting row 3775: tuple index out of range
Row data: Date/Time           6/6/2012 6:00
Temp_C                       12.4
Dew Point Temp_C              7.7
Rel Hum_%                      73
Wind Speed_km/h                15
Visibility_km                24.1
Press_kPa                  101.07
Weather             Mostly Cloudy
Name: 3774, dtype: object
Inserting row 3776
Error inserting row 3776: tuple index out of range
Row data: Date/Time           6/6/2012 7:00
Temp_C                       14.1
Dew Point Temp_C              8.3
Rel Hum_%                      68
Wind Speed_km/h                13
Visibility_km                24.1
Press_kPa                   101.1
Weather              Mainly Clear
Name: 3775, dtype: object
Inserting row 3777
Error inserting row 3777: tuple index out of range
Row data: Date/Time           6/6/2012 8:00
Temp_C                       15.3
Dew Point Temp_C              9.6
Rel Hum_%                      69
Wind Speed_km/h                 7
Visibility_km                24.1
Press_kPa                  101.14
Weather              Mainly Clear
Name: 3776, dtype: object
Inserting row 3778
Error inserting row 3778: tuple index out of range
Row data: Date/Time           6/6/2012 9:00
Temp_C                       16.1
Dew Point Temp_C              9.6
Rel Hum_%                      65
Wind Speed_km/h                 9
Visibility_km                24.1
Press_kPa                  101.13
Weather              Mainly Clear
Name: 3777, dtype: object
Inserting row 3779
Error inserting row 3779: tuple index out of range
Row data: Date/Time           6/6/2012 10:00
Temp_C                        17.6
Dew Point Temp_C               9.7
Rel Hum_%                       60
Wind Speed_km/h                 11
Visibility_km                 24.1
Press_kPa                   101.12
Weather               Mainly Clear
Name: 3778, dtype: object
Inserting row 3780
Error inserting row 3780: tuple index out of range
Row data: Date/Time           6/6/2012 11:00
Temp_C                        19.4
Dew Point Temp_C               9.4
Rel Hum_%                       52
Wind Speed_km/h                  7
Visibility_km                 24.1
Press_kPa                   101.08
Weather               Mainly Clear
Name: 3779, dtype: object
Inserting row 3781
Error inserting row 3781: tuple index out of range
Row data: Date/Time           6/6/2012 12:00
Temp_C                        19.8
Dew Point Temp_C               9.7
Rel Hum_%                       52
Wind Speed_km/h                  9
Visibility_km                 24.1
Press_kPa                   101.05
Weather               Mainly Clear
Name: 3780, dtype: object
Inserting row 3782
Error inserting row 3782: tuple index out of range
Row data: Date/Time           6/6/2012 13:00
Temp_C                        19.6
Dew Point Temp_C               9.6
Rel Hum_%                       52
Wind Speed_km/h                  0
Visibility_km                 24.1
Press_kPa                   101.01
Weather               Mainly Clear
Name: 3781, dtype: object
Inserting row 3783
Error inserting row 3783: tuple index out of range
Row data: Date/Time           6/6/2012 14:00
Temp_C                        20.6
Dew Point Temp_C               9.8
Rel Hum_%                       50
Wind Speed_km/h                  4
Visibility_km                 48.3
Press_kPa                   100.94
Weather              Mostly Cloudy
Name: 3782, dtype: object
Inserting row 3784
Error inserting row 3784: tuple index out of range
Row data: Date/Time           6/6/2012 15:00
Temp_C                        20.3
Dew Point Temp_C               9.3
Rel Hum_%                       49
Wind Speed_km/h                  7
Visibility_km                 48.3
Press_kPa                   100.89
Weather              Mostly Cloudy
Name: 3783, dtype: object
Inserting row 3785
Error inserting row 3785: tuple index out of range
Row data: Date/Time           6/6/2012 16:00
Temp_C                        21.3
Dew Point Temp_C               8.2
Rel Hum_%                       43
Wind Speed_km/h                 13
Visibility_km                 48.3
Press_kPa                    100.9
Weather              Mostly Cloudy
Name: 3784, dtype: object
Inserting row 3786
Error inserting row 3786: tuple index out of range
Row data: Date/Time           6/6/2012 17:00
Temp_C                        20.6
Dew Point Temp_C               7.4
Rel Hum_%                       42
Wind Speed_km/h                 11
Visibility_km                 24.1
Press_kPa                   100.91
Weather              Mostly Cloudy
Name: 3785, dtype: object
Inserting row 3787
Error inserting row 3787: tuple index out of range
Row data: Date/Time           6/6/2012 18:00
Temp_C                        20.0
Dew Point Temp_C               7.6
Rel Hum_%                       45
Wind Speed_km/h                 15
Visibility_km                 24.1
Press_kPa                   100.95
Weather              Mostly Cloudy
Name: 3786, dtype: object
Inserting row 3788
Error inserting row 3788: tuple index out of range
Row data: Date/Time           6/6/2012 19:00
Temp_C                        18.9
Dew Point Temp_C               7.8
Rel Hum_%                       48
Wind Speed_km/h                 15
Visibility_km                 24.1
Press_kPa                    101.0
Weather              Mostly Cloudy
Name: 3787, dtype: object
Inserting row 3789
Error inserting row 3789: tuple index out of range
Row data: Date/Time           6/6/2012 20:00
Temp_C                        17.4
Dew Point Temp_C               9.6
Rel Hum_%                       60
Wind Speed_km/h                  9
Visibility_km                 24.1
Press_kPa                   101.04
Weather               Rain Showers
Name: 3788, dtype: object
Inserting row 3790
Error inserting row 3790: tuple index out of range
Row data: Date/Time           6/6/2012 21:00
Temp_C                        16.3
Dew Point Temp_C               9.7
Rel Hum_%                       65
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   101.04
Weather              Mostly Cloudy
Name: 3789, dtype: object
Inserting row 3791
Error inserting row 3791: tuple index out of range
Row data: Date/Time           6/6/2012 22:00
Temp_C                        17.4
Dew Point Temp_C               9.3
Rel Hum_%                       59
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                   101.04
Weather                     Cloudy
Name: 3790, dtype: object
Inserting row 3792
Error inserting row 3792: tuple index out of range
Row data: Date/Time           6/6/2012 23:00
Temp_C                        17.1
Dew Point Temp_C               9.1
Rel Hum_%                       59
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   101.05
Weather               Rain Showers
Name: 3791, dtype: object
Inserting row 3793
Error inserting row 3793: tuple index out of range
Row data: Date/Time           6/7/2012 0:00
Temp_C                       14.9
Dew Point Temp_C              9.0
Rel Hum_%                      68
Wind Speed_km/h                 9
Visibility_km                25.0
Press_kPa                  101.06
Weather              Mainly Clear
Name: 3792, dtype: object
Inserting row 3794
Error inserting row 3794: tuple index out of range
Row data: Date/Time           6/7/2012 1:00
Temp_C                       13.3
Dew Point Temp_C              9.2
Rel Hum_%                      76
Wind Speed_km/h                 7
Visibility_km                25.0
Press_kPa                  101.06
Weather              Mainly Clear
Name: 3793, dtype: object
Inserting row 3795
Error inserting row 3795: tuple index out of range
Row data: Date/Time           6/7/2012 2:00
Temp_C                       12.8
Dew Point Temp_C              9.4
Rel Hum_%                      80
Wind Speed_km/h                11
Visibility_km                25.0
Press_kPa                  101.04
Weather                     Clear
Name: 3794, dtype: object
Inserting row 3796
Error inserting row 3796: tuple index out of range
Row data: Date/Time           6/7/2012 3:00
Temp_C                       12.3
Dew Point Temp_C              8.9
Rel Hum_%                      80
Wind Speed_km/h                17
Visibility_km                25.0
Press_kPa                  101.02
Weather                     Clear
Name: 3795, dtype: object
Inserting row 3797
Error inserting row 3797: tuple index out of range
Row data: Date/Time           6/7/2012 4:00
Temp_C                       12.0
Dew Point Temp_C              8.3
Rel Hum_%                      78
Wind Speed_km/h                 9
Visibility_km                24.1
Press_kPa                  101.05
Weather              Mainly Clear
Name: 3796, dtype: object
Inserting row 3798
Error inserting row 3798: tuple index out of range
Row data: Date/Time           6/7/2012 5:00
Temp_C                       11.3
Dew Point Temp_C              8.1
Rel Hum_%                      81
Wind Speed_km/h                11
Visibility_km                48.3
Press_kPa                  101.11
Weather              Mainly Clear
Name: 3797, dtype: object
Inserting row 3799
Error inserting row 3799: tuple index out of range
Row data: Date/Time           6/7/2012 6:00
Temp_C                       12.3
Dew Point Temp_C              8.4
Rel Hum_%                      77
Wind Speed_km/h                13
Visibility_km                48.3
Press_kPa                  101.12
Weather              Mainly Clear
Name: 3798, dtype: object
Inserting row 3800
Error inserting row 3800: tuple index out of range
Row data: Date/Time           6/7/2012 7:00
Temp_C                       13.9
Dew Point Temp_C              8.4
Rel Hum_%                      69
Wind Speed_km/h                 4
Visibility_km                24.1
Press_kPa                  101.13
Weather              Mainly Clear
Name: 3799, dtype: object
Inserting row 3801
Error inserting row 3801: tuple index out of range
Row data: Date/Time           6/7/2012 8:00
Temp_C                       15.9
Dew Point Temp_C              9.2
Rel Hum_%                      64
Wind Speed_km/h                11
Visibility_km                24.1
Press_kPa                  101.12
Weather              Mainly Clear
Name: 3800, dtype: object
Inserting row 3802
Error inserting row 3802: tuple index out of range
Row data: Date/Time           6/7/2012 9:00
Temp_C                       17.5
Dew Point Temp_C              9.5
Rel Hum_%                      59
Wind Speed_km/h                 6
Visibility_km                48.3
Press_kPa                  101.09
Weather              Mainly Clear
Name: 3801, dtype: object
Inserting row 3803
Error inserting row 3803: tuple index out of range
Row data: Date/Time           6/7/2012 10:00
Temp_C                        19.4
Dew Point Temp_C               9.6
Rel Hum_%                       53
Wind Speed_km/h                  6
Visibility_km                 48.3
Press_kPa                   101.05
Weather               Mainly Clear
Name: 3802, dtype: object
Inserting row 3804
Error inserting row 3804: tuple index out of range
Row data: Date/Time           6/7/2012 11:00
Temp_C                        20.1
Dew Point Temp_C              10.5
Rel Hum_%                       54
Wind Speed_km/h                  7
Visibility_km                 48.3
Press_kPa                   101.02
Weather               Mainly Clear
Name: 3803, dtype: object
Inserting row 3805
Error inserting row 3805: tuple index out of range
Row data: Date/Time           6/7/2012 12:00
Temp_C                        20.8
Dew Point Temp_C              10.1
Rel Hum_%                       50
Wind Speed_km/h                 13
Visibility_km                 48.3
Press_kPa                   100.98
Weather               Mainly Clear
Name: 3804, dtype: object
Inserting row 3806
Error inserting row 3806: tuple index out of range
Row data: Date/Time           6/7/2012 13:00
Temp_C                        21.6

Row data: Date/Time           6/16/2012 7:00
Temp_C                        16.2
Dew Point Temp_C               9.3
Rel Hum_%                       64
Wind Speed_km/h                 15
Visibility_km                 48.3
Press_kPa                   102.25
Weather              Mostly Cloudy
Name: 4015, dtype: object
Inserting row 4017
Error inserting row 4017: tuple index out of range
Row data: Date/Time           6/16/2012 8:00
Temp_C                        17.4
Dew Point Temp_C               9.5
Rel Hum_%                       60
Wind Speed_km/h                  9
Visibility_km                 48.3
Press_kPa                   102.23
Weather              Mostly Cloudy
Name: 4016, dtype: object
Inserting row 4018
Error inserting row 4018: tuple index out of range
Row data: Date/Time           6/16/2012 9:00
Temp_C                        18.9
Dew Point Temp_C              10.7
Rel Hum_%                       59
Wind Speed_km/h                 11
Visibility_km                 48.3
Press_kPa                    102.2
Weather                     Cloudy
Name: 4017, dtype: object
Inserting row 4019
Error inserting row 4019: tuple index out of range
Row data: Date/Time           6/16/2012 10:00
Temp_C                         21.6
Dew Point Temp_C               12.0
Rel Hum_%                        54
Wind Speed_km/h                   4
Visibility_km                  48.3
Press_kPa                    102.15
Weather                      Cloudy
Name: 4018, dtype: object
Inserting row 4020
Error inserting row 4020: tuple index out of range
Row data: Date/Time           6/16/2012 11:00
Temp_C                         21.9
Dew Point Temp_C               11.6
Rel Hum_%                        52
Wind Speed_km/h                   6
Visibility_km                  48.3
Press_kPa                     102.1
Weather                      Cloudy
Name: 4019, dtype: object
Inserting row 4021
Error inserting row 4021: tuple index out of range
Row data: Date/Time           6/16/2012 12:00
Temp_C                         23.8
Dew Point Temp_C               13.1
Rel Hum_%                        51
Wind Speed_km/h                   6
Visibility_km                  48.3
Press_kPa                    102.04
Weather               Mostly Cloudy
Name: 4020, dtype: object
Inserting row 4022
Error inserting row 4022: tuple index out of range
Row data: Date/Time           6/16/2012 13:00
Temp_C                         24.6
Dew Point Temp_C               12.5
Rel Hum_%                        47
Wind Speed_km/h                   9
Visibility_km                  48.3
Press_kPa                    101.96
Weather                      Cloudy
Name: 4021, dtype: object
Inserting row 4023
Error inserting row 4023: tuple index out of range
Row data: Date/Time           6/16/2012 14:00
Temp_C                         24.9
Dew Point Temp_C               13.5
Rel Hum_%                        49
Wind Speed_km/h                   6
Visibility_km                  48.3
Press_kPa                    101.91
Weather               Mostly Cloudy
Name: 4022, dtype: object
Inserting row 4024
Error inserting row 4024: tuple index out of range
Row data: Date/Time           6/16/2012 15:00
Temp_C                         26.0
Dew Point Temp_C               13.6
Rel Hum_%                        46
Wind Speed_km/h                   6
Visibility_km                  48.3
Press_kPa                    101.84
Weather               Mostly Cloudy
Name: 4023, dtype: object
Inserting row 4025
Error inserting row 4025: tuple index out of range
Row data: Date/Time           6/16/2012 16:00
Temp_C                         26.5
Dew Point Temp_C               11.0
Rel Hum_%                        38
Wind Speed_km/h                   7
Visibility_km                  48.3
Press_kPa                    101.77
Weather               Mostly Cloudy
Name: 4024, dtype: object
Inserting row 4026
Error inserting row 4026: tuple index out of range
Row data: Date/Time           6/16/2012 17:00
Temp_C                         26.5
Dew Point Temp_C               11.3
Rel Hum_%                        39
Wind Speed_km/h                   4
Visibility_km                  48.3
Press_kPa                    101.73
Weather               Mostly Cloudy
Name: 4025, dtype: object
Inserting row 4027
Error inserting row 4027: tuple index out of range
Row data: Date/Time           6/16/2012 18:00
Temp_C                         26.2
Dew Point Temp_C               12.1
Rel Hum_%                        41
Wind Speed_km/h                   6
Visibility_km                  48.3
Press_kPa                    101.71
Weather                Mainly Clear
Name: 4026, dtype: object
Inserting row 4028
Error inserting row 4028: tuple index out of range
Row data: Date/Time           6/16/2012 19:00
Temp_C                         25.0
Dew Point Temp_C               13.0
Rel Hum_%                        47
Wind Speed_km/h                   7
Visibility_km                  48.3
Press_kPa                    101.66
Weather                Mainly Clear
Name: 4027, dtype: object
Inserting row 4029
Error inserting row 4029: tuple index out of range
Row data: Date/Time           6/16/2012 20:00
Temp_C                         23.1
Dew Point Temp_C               11.8
Rel Hum_%                        49
Wind Speed_km/h                   4
Visibility_km                  48.3
Press_kPa                    101.62
Weather                Mainly Clear
Name: 4028, dtype: object
Inserting row 4030
Error inserting row 4030: tuple index out of range
Row data: Date/Time           6/16/2012 21:00
Temp_C                         20.8
Dew Point Temp_C               12.3
Rel Hum_%                        58
Wind Speed_km/h                   0
Visibility_km                  25.0
Press_kPa                     101.6
Weather                       Clear
Name: 4029, dtype: object
Inserting row 4031
Error inserting row 4031: tuple index out of range
Row data: Date/Time           6/16/2012 22:00
Temp_C                         21.5
Dew Point Temp_C               11.9
Rel Hum_%                        54
Wind Speed_km/h                   9
Visibility_km                  25.0
Press_kPa                     101.6
Weather                Mainly Clear
Name: 4030, dtype: object
Inserting row 4032
Error inserting row 4032: tuple index out of range
Row data: Date/Time           6/16/2012 23:00
Temp_C                         20.9
Dew Point Temp_C               12.9
Rel Hum_%                        60
Wind Speed_km/h                   0
Visibility_km                  25.0
Press_kPa                    101.58
Weather                Mainly Clear
Name: 4031, dtype: object
Inserting row 4033
Error inserting row 4033: tuple index out of range
Row data: Date/Time           6/17/2012 0:00
Temp_C                        19.3
Dew Point Temp_C              12.6
Rel Hum_%                       65
Wind Speed_km/h                  0
Visibility_km                 25.0
Press_kPa                   101.55
Weather               Mainly Clear
Name: 4032, dtype: object
Inserting row 4034
Error inserting row 4034: tuple index out of range
Row data: Date/Time           6/17/2012 1:00
Temp_C                        19.8
Dew Point Temp_C              13.7
Rel Hum_%                       68
Wind Speed_km/h                  7
Visibility_km                 25.0
Press_kPa                   101.52
Weather               Mainly Clear
Name: 4033, dtype: object
Inserting row 4035
Error inserting row 4035: tuple index out of range
Row data: Date/Time           6/17/2012 2:00
Temp_C                        18.6
Dew Point Temp_C              13.5
Rel Hum_%                       72
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   101.48
Weather               Mainly Clear
Name: 4034, dtype: object
Inserting row 4036
Error inserting row 4036: tuple index out of range
Row data: Date/Time           6/17/2012 3:00
Temp_C                        18.4
Dew Point Temp_C              13.7
Rel Hum_%                       74
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   101.45
Weather                      Clear
Name: 4035, dtype: object
Inserting row 4037
Error inserting row 4037: tuple index out of range
Row data: Date/Time           6/17/2012 4:00
Temp_C                        17.4
Dew Point Temp_C              13.4
Rel Hum_%                       77
Wind Speed_km/h                  9
Visibility_km                 24.1
Press_kPa                   101.46
Weather               Mainly Clear
Name: 4036, dtype: object
Inserting row 4038
Error inserting row 4038: tuple index out of range
Row data: Date/Time           6/17/2012 5:00
Temp_C                        17.3
Dew Point Temp_C              13.7
Rel Hum_%                       79
Wind Speed_km/h                  6
Visibility_km                 48.3
Press_kPa                   101.47
Weather               Mainly Clear
Name: 4037, dtype: object
Inserting row 4039
Error inserting row 4039: tuple index out of range
Row data: Date/Time           6/17/2012 6:00
Temp_C                        18.9
Dew Point Temp_C              14.1
Rel Hum_%                       74
Wind Speed_km/h                  9
Visibility_km                 48.3
Press_kPa                   101.51
Weather               Mainly Clear
Name: 4038, dtype: object
Inserting row 4040
Error inserting row 4040: tuple index out of range
Row data: Date/Time           6/17/2012 7:00
Temp_C                        20.2
Dew Point Temp_C              14.4
Rel Hum_%                       69
Wind Speed_km/h                 11
Visibility_km                 48.3
Press_kPa                   101.52
Weather               Mainly Clear
Name: 4039, dtype: object
Inserting row 4041
Error inserting row 4041: tuple index out of range
Row data: Date/Time           6/17/2012 8:00
Temp_C                        22.2
Dew Point Temp_C              15.1
Rel Hum_%                       64
Wind Speed_km/h                  9
Visibility_km                 48.3
Press_kPa                    101.5
Weather               Mainly Clear
Name: 4040, dtype: object
Inserting row 4042
Error inserting row 4042: tuple index out of range
Row data: Date/Time           6/17/2012 9:00
Temp_C                        23.4
Dew Point Temp_C              15.3
Rel Hum_%                       60
Wind Speed_km/h                  9
Visibility_km                 48.3
Press_kPa                   101.47
Weather               Mainly Clear
Name: 4041, dtype: object
Inserting row 4043
Error inserting row 4043: tuple index out of range
Row data: Date/Time           6/17/2012 10:00
Temp_C                         25.0
Dew Point Temp_C               16.1
Rel Hum_%                        58
Wind Speed_km/h                   9
Visibility_km                  48.3
Press_kPa                    101.43
Weather                Mainly Clear
Name: 4042, dtype: object
Inserting row 4044
Error inserting row 4044: tuple index out of range
Row data: Date/Time           6/17/2012 11:00
Temp_C                         25.7
Dew Point Temp_C               16.3
Rel Hum_%                        56
Wind Speed_km/h                   9
Visibility_km                  48.3
Press_kPa                    101.39
Weather                      Cloudy
Name: 4043, dtype: object
Inserting row 4045
Error inserting row 4045: tuple index out of range
Row data: Date/Time           6/17/2012 12:00
Temp_C                         26.0
Dew Point Temp_C               16.3
Rel Hum_%                        55
Wind Speed_km/h                   6
Visibility_km                  48.3
Press_kPa                    101.33
Weather                      Cloudy
Name: 4044, dtype: object
Inserting row 4046
Error inserting row 4046: tuple index out of range
Row data: Date/Time           6/17/2012 13:00
Temp_C                         26.6
Dew Point Temp_C               16.7
Rel Hum_%                        55
Wind Speed_km/h                  11
Visibility_km                  48.3
Press_kPa                    101.23
Weather               Mostly Cloudy
Name: 4045, dtype: object
Inserting row 4047
Error inserting row 4047: tuple index out of range
Row data: Date/Time           6/17/2012 14:00
Temp_C                         26.1
Dew Point Temp_C               16.5
Rel Hum_%                        55
Wind Speed_km/h                  17
Visibility_km                  48.3
Press_kPa                    101.17
Weather                      Cloudy
Name: 4046, dtype: object
Inserting row 4048
Error inserting row 4048: tuple index out of range
Row data: Date/Time           6/17/2012 15:00
Temp_C                         27.0
Dew Point Temp_C               16.8
Rel Hum_%                        54
Wind Speed_km/h                  17
Visibility_km                  48.3
Press_kPa                     101.1
Weather                      Cloudy
Name: 4047, dtype: object
Inserting row 4049
Error inserting row 4049: tuple index out of range
Row data: Date/Time           6/17/2012 16:00
Temp_C                         27.4
Dew Point Temp_C               16.3
Rel Hum_%                        51
Wind Speed_km/h                  20
Visibility_km                  48.3
Press_kPa                    101.02
Weather                      Cloudy
Name: 4048, dtype: object
Inserting row 4050
Error inserting row 4050: tuple index out of range
Row data: Date/Time           6/17/2012 17:00
Temp_C                         26.2
Dew Point Temp_C               14.7
Rel Hum_%                        49
Wind Speed_km/h                  19
Visibility_km                  48.3
Press_kPa                    100.97
Weather                      Cloudy
Name: 4049, dtype: object
Inserting row 4051
Error inserting row 4051: tuple index out of range
Row data: Date/Time           6/17/2012 18:00
Temp_C                         26.0
Dew Point Temp_C               15.9
Rel Hum_%                        54
Wind Speed_km/h                  17
Visibility_km                  48.3
Press_kPa                    100.92
Weather                      Cloudy
Name: 4050, dtype: object
Inserting row 4052
Error inserting row 4052: tuple index out of range
Row data: Date/Time           6/17/2012 19:00
Temp_C                         25.5
Dew Point Temp_C               16.4
Rel Hum_%                        57
Wind Speed_km/h                  17
Visibility_km                  48.3
Press_kPa                    100.91
Weather                      Cloudy
Name: 4051, dtype: object
Inserting row 4053
Error inserting row 4053: tuple index out of range
Row data: Date/Time           6/17/2012 20:00
Temp_C                         24.5
Dew Point Temp_C               15.1
Rel Hum_%                        56
Wind Speed_km/h                  15
Visibility_km                  48.3
Press_kPa                    100.95
Weather                      Cloudy
Name: 4052, dtype: object
Inserting row 4054
Error inserting row 4054: tuple index out of range
Row data: Date/Time           6/17/2012 21:00
Temp_C                         24.1
Dew Point Temp_C               14.1
Rel Hum_%                        54
Wind Speed_km/h                  19
Visibility_km                  25.0
Press_kPa                    100.99
Weather               Mostly Cloudy
Name: 4053, dtype: object
Inserting row 4055
Error inserting row 4055: tuple index out of range
Row data: Date/Time           6/17/2012 22:00
Temp_C                         23.4
Dew Point Temp_C               13.8
Rel Hum_%                        55
Wind Speed_km/h                  22
Visibility_km                  25.0
Press_kPa                     101.0
Weather               Mostly Cloudy
Name: 4054, dtype: object
Inserting row 4056
Error inserting row 4056: tuple index out of range
Row data: Date/Time           6/17/2012 23:00
Temp_C                         23.2
Dew Point Temp_C               13.7
Rel Hum_%                        55
Wind Speed_km/h                  13
Visibility_km                  25.0
Press_kPa                    101.03
Weather               Mostly Cloudy
Name: 4055, dtype: object
Inserting row 4057
Error inserting row 4057: tuple index out of range
Row data: Date/Time           6/18/2012 0:00
Temp_C                        21.7
Dew Point Temp_C              13.4
Rel Hum_%                       59
Wind Speed_km/h                 15
Visibility_km                 25.0
Press_kPa                   101.04
Weather               Mainly Clear
Name: 4056, dtype: object
Inserting row 4058
Error inserting row 4058: tuple index out of range
Row data: Date/Time           6/18/2012 1:00
Temp_C                        20.5
Dew Point Temp_C              13.4
Rel Hum_%                       64
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   101.07
Weather               Mainly Clear
Name: 4057, dtype: object
Inserting row 4059
Error inserting row 4059: tuple index out of range
Row data: Date/Time           6/18/2012 2:00
Temp_C                        19.7
Dew Point Temp_C              13.5
Rel Hum_%                       67
Wind Speed_km/h                 19
Visibility_km                 25.0
Press_kPa                   101.08
Weather               Mainly Clear
Name: 4058, dtype: object
Inserting row 4060
Error inserting row 4060: tuple index out of range
Row data: Date/Time           6/18/2012 3:00
Temp_C                        19.3
Dew Point Temp_C              13.4
Rel Hum_%                       69
Wind Speed_km/h                 17
Visibility_km                 25.0
Press_kPa                   101.06
Weather               Mainly Clear
Name: 4059, dtype: object
Inserting row 4061
Error inserting row 4061: tuple index out of range
Row data: Date/Time           6/18/2012 4:00
Temp_C                        18.4
Dew Point Temp_C              13.3
Rel Hum_%                       72
Wind Speed_km/h                 17
Visibility_km                 25.0
Press_kPa                    101.1
Weather               Mainly Clear
Name: 4060, dtype: object
Inserting row 4062
Error inserting row 4062: tuple index out of range
Row data: Date/Time           6/18/2012 5:00
Temp_C                        17.9
Dew Point Temp_C              13.2
Rel Hum_%                       74
Wind Speed_km/h                 19
Visibility_km                 24.1
Press_kPa                   101.12
Weather              Mostly Cloudy
Name: 4061, dtype: object
Inserting row 4063
Error inserting row 4063: tuple index out of range
Row data: Date/Time           6/18/2012 6:00
Temp_C                        18.2
Dew Point Temp_C              13.3
Rel Hum_%                       73
Wind Speed_km/h                 20
Visibility_km                 24.1
Press_kPa                   101.14
Weather              Mostly Cloudy
Name: 4062, dtype: object
Inserting row 4064
Error inserting row 4064: tuple index out of range
Row data: Date/Time           6/18/2012 7:00
Temp_C                        19.3
Dew Point Temp_C              13.4
Rel Hum_%                       69
Wind Speed_km/h                 17
Visibility_km                 48.3
Press_kPa                   101.16
Weather              Mostly Cloudy
Name: 4063, dtype: object
Inserting row 4065
Error inserting row 4065: tuple index out of range
Row data: Date/Time           6/18/2012 8:00
Temp_C                        20.6
Dew Point Temp_C              14.0
Rel Hum_%                       66
Wind Speed_km/h                 17
Visibility_km                 48.3
Press_kPa                   101.17
Weather              Mostly Cloudy
Name: 4064, dtype: object
Inserting row 4066
Error inserting row 4066: tuple index out of range
Row data: Date/Time           6/18/2012 9:00
Temp_C                        22.0
Dew Point Temp_C              14.4
Rel Hum_%                       62
Wind Speed_km/h                 17
Visibility_km                 48.3
Press_kPa                   101.15
Weather              Mostly Cloudy
Name: 4065, dtype: object
Inserting row 4067
Error inserting row 4067: tuple index out of range
Row data: Date/Time           6/18/2012 10:00
Temp_C                         22.6

Error inserting row 4279: tuple index out of range
Row data: Date/Time           6/27/2012 6:00
Temp_C                        15.4
Dew Point Temp_C              12.2
Rel Hum_%                       81
Wind Speed_km/h                 15
Visibility_km                 24.1
Press_kPa                    99.79
Weather                       Rain
Name: 4278, dtype: object
Inserting row 4280
Error inserting row 4280: tuple index out of range
Row data: Date/Time           6/27/2012 7:00
Temp_C                        16.3
Dew Point Temp_C              12.2
Rel Hum_%                       77
Wind Speed_km/h                 20
Visibility_km                 24.1
Press_kPa                    99.81
Weather                       Rain
Name: 4279, dtype: object
Inserting row 4281
Error inserting row 4281: tuple index out of range
Row data: Date/Time           6/27/2012 8:00
Temp_C                        18.0
Dew Point Temp_C              12.9
Rel Hum_%                       72
Wind Speed_km/h                 28
Visibility_km                 24.1
Press_kPa                    99.83
Weather              Mostly Cloudy
Name: 4280, dtype: object
Inserting row 4282
Error inserting row 4282: tuple index out of range
Row data: Date/Time           6/27/2012 9:00
Temp_C                        18.0
Dew Point Temp_C              12.0
Rel Hum_%                       68
Wind Speed_km/h                 20
Visibility_km                 24.1
Press_kPa                    99.86
Weather                     Cloudy
Name: 4281, dtype: object
Inserting row 4283
Error inserting row 4283: tuple index out of range
Row data: Date/Time           6/27/2012 10:00
Temp_C                         18.7
Dew Point Temp_C               13.0
Rel Hum_%                        69
Wind Speed_km/h                  20
Visibility_km                  24.1
Press_kPa                     99.89
Weather                        Rain
Name: 4282, dtype: object
Inserting row 4284
Error inserting row 4284: tuple index out of range
Row data: Date/Time           6/27/2012 11:00
Temp_C                         17.8
Dew Point Temp_C               13.5
Rel Hum_%                        76
Wind Speed_km/h                  24
Visibility_km                  24.1
Press_kPa                     99.93
Weather                        Rain
Name: 4283, dtype: object
Inserting row 4285
Error inserting row 4285: tuple index out of range
Row data: Date/Time           6/27/2012 12:00
Temp_C                         19.8
Dew Point Temp_C               13.5
Rel Hum_%                        67
Wind Speed_km/h                  20
Visibility_km                  19.3
Press_kPa                     99.92
Weather                        Rain
Name: 4284, dtype: object
Inserting row 4286
Error inserting row 4286: tuple index out of range
Row data: Date/Time           6/27/2012 13:00
Temp_C                         19.3
Dew Point Temp_C               14.4
Rel Hum_%                        73
Wind Speed_km/h                  13
Visibility_km                  19.3
Press_kPa                     99.96
Weather                        Rain
Name: 4285, dtype: object
Inserting row 4287
Error inserting row 4287: tuple index out of range
Row data: Date/Time           6/27/2012 14:00
Temp_C                         19.1
Dew Point Temp_C               14.7
Rel Hum_%                        76
Wind Speed_km/h                  19
Visibility_km                  19.3
Press_kPa                     99.99
Weather                        Rain
Name: 4286, dtype: object
Inserting row 4288
Error inserting row 4288: tuple index out of range
Row data: Date/Time           6/27/2012 15:00
Temp_C                         19.6
Dew Point Temp_C               15.1
Rel Hum_%                        75
Wind Speed_km/h                  19
Visibility_km                  24.1
Press_kPa                    100.02
Weather               Mostly Cloudy
Name: 4287, dtype: object
Inserting row 4289
Error inserting row 4289: tuple index out of range
Row data: Date/Time           6/27/2012 16:00
Temp_C                         20.3
Dew Point Temp_C               14.2
Rel Hum_%                        68
Wind Speed_km/h                  20
Visibility_km                  24.1
Press_kPa                    100.03
Weather                        Rain
Name: 4288, dtype: object
Inserting row 4290
Error inserting row 4290: tuple index out of range
Row data: Date/Time           6/27/2012 17:00
Temp_C                         19.9
Dew Point Temp_C               14.3
Rel Hum_%                        70
Wind Speed_km/h                  20
Visibility_km                  24.1
Press_kPa                    100.05
Weather               Mostly Cloudy
Name: 4289, dtype: object
Inserting row 4291
Error inserting row 4291: tuple index out of range
Row data: Date/Time           6/27/2012 18:00
Temp_C                         21.1
Dew Point Temp_C               14.1
Rel Hum_%                        64
Wind Speed_km/h                  15
Visibility_km                  24.1
Press_kPa                    100.06
Weather               Mostly Cloudy
Name: 4290, dtype: object
Inserting row 4292
Error inserting row 4292: tuple index out of range
Row data: Date/Time           6/27/2012 19:00
Temp_C                         19.4
Dew Point Temp_C               13.8
Rel Hum_%                        70
Wind Speed_km/h                  17
Visibility_km                  24.1
Press_kPa                    100.09
Weather                        Rain
Name: 4291, dtype: object
Inserting row 4293
Error inserting row 4293: tuple index out of range
Row data: Date/Time           6/27/2012 20:00
Temp_C                         19.3
Dew Point Temp_C               13.2
Rel Hum_%                        68
Wind Speed_km/h                  11
Visibility_km                  24.1
Press_kPa                    100.13
Weather                      Cloudy
Name: 4292, dtype: object
Inserting row 4294
Error inserting row 4294: tuple index out of range
Row data: Date/Time           6/27/2012 21:00
Temp_C                         19.3
Dew Point Temp_C               12.7
Rel Hum_%                        66
Wind Speed_km/h                  13
Visibility_km                  25.0
Press_kPa                    100.19
Weather               Mostly Cloudy
Name: 4293, dtype: object
Inserting row 4295
Error inserting row 4295: tuple index out of range
Row data: Date/Time           6/27/2012 22:00
Temp_C                         18.7
Dew Point Temp_C               13.4
Rel Hum_%                        71
Wind Speed_km/h                  11
Visibility_km                  25.0
Press_kPa                    100.19
Weather                      Cloudy
Name: 4294, dtype: object
Inserting row 4296
Error inserting row 4296: tuple index out of range
Row data: Date/Time           6/27/2012 23:00
Temp_C                         17.5
Dew Point Temp_C               14.1
Rel Hum_%                        80
Wind Speed_km/h                   9
Visibility_km                  25.0
Press_kPa                    100.17
Weather                      Cloudy
Name: 4295, dtype: object
Inserting row 4297
Error inserting row 4297: tuple index out of range
Row data: Date/Time           6/28/2012 0:00
Temp_C                        17.2
Dew Point Temp_C              14.0
Rel Hum_%                       81
Wind Speed_km/h                  6
Visibility_km                 25.0
Press_kPa                   100.17
Weather                     Cloudy
Name: 4296, dtype: object
Inserting row 4298
Error inserting row 4298: tuple index out of range
Row data: Date/Time           6/28/2012 1:00
Temp_C                        17.7
Dew Point Temp_C              13.3
Rel Hum_%                       75
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   100.15
Weather                     Cloudy
Name: 4297, dtype: object
Inserting row 4299
Error inserting row 4299: tuple index out of range
Row data: Date/Time           6/28/2012 2:00
Temp_C                        17.6
Dew Point Temp_C              13.4
Rel Hum_%                       76
Wind Speed_km/h                  7
Visibility_km                 25.0
Press_kPa                   100.16
Weather                     Cloudy
Name: 4298, dtype: object
Inserting row 4300
Error inserting row 4300: tuple index out of range
Row data: Date/Time           6/28/2012 3:00
Temp_C                        17.5
Dew Point Temp_C              13.3
Rel Hum_%                       76
Wind Speed_km/h                  6
Visibility_km                 25.0
Press_kPa                   100.18
Weather                       Rain
Name: 4299, dtype: object
Inserting row 4301
Error inserting row 4301: tuple index out of range
Row data: Date/Time           6/28/2012 4:00
Temp_C                        17.7
Dew Point Temp_C              13.9
Rel Hum_%                       78
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                    100.2
Weather               Rain Showers
Name: 4300, dtype: object
Inserting row 4302
Error inserting row 4302: tuple index out of range
Row data: Date/Time           6/28/2012 5:00
Temp_C                        17.6
Dew Point Temp_C              13.7
Rel Hum_%                       78
Wind Speed_km/h                  9
Visibility_km                 48.3
Press_kPa                   100.25
Weather              Mostly Cloudy
Name: 4301, dtype: object
Inserting row 4303
Error inserting row 4303: tuple index out of range
Row data: Date/Time           6/28/2012 6:00
Temp_C                        17.7
Dew Point Temp_C              13.7
Rel Hum_%                       77
Wind Speed_km/h                 11
Visibility_km                 48.3
Press_kPa                   100.27
Weather              Mostly Cloudy
Name: 4302, dtype: object
Inserting row 4304
Error inserting row 4304: tuple index out of range
Row data: Date/Time           6/28/2012 7:00
Temp_C                        18.6
Dew Point Temp_C              14.2
Rel Hum_%                       76
Wind Speed_km/h                 11
Visibility_km                 48.3
Press_kPa                   100.29
Weather              Mostly Cloudy
Name: 4303, dtype: object
Inserting row 4305
Error inserting row 4305: tuple index out of range
Row data: Date/Time           6/28/2012 8:00
Temp_C                        19.4
Dew Point Temp_C              14.2
Rel Hum_%                       72
Wind Speed_km/h                  9
Visibility_km                 48.3
Press_kPa                   100.28
Weather              Mostly Cloudy
Name: 4304, dtype: object
Inserting row 4306
Error inserting row 4306: tuple index out of range
Row data: Date/Time           6/28/2012 9:00
Temp_C                        20.4
Dew Point Temp_C              14.1
Rel Hum_%                       67
Wind Speed_km/h                 11
Visibility_km                 48.3
Press_kPa                   100.27
Weather              Mostly Cloudy
Name: 4305, dtype: object
Inserting row 4307
Error inserting row 4307: tuple index out of range
Row data: Date/Time           6/28/2012 10:00
Temp_C                         21.7
Dew Point Temp_C               14.7
Rel Hum_%                        64
Wind Speed_km/h                  11
Visibility_km                  48.3
Press_kPa                    100.23
Weather               Mostly Cloudy
Name: 4306, dtype: object
Inserting row 4308
Error inserting row 4308: tuple index out of range
Row data: Date/Time           6/28/2012 11:00
Temp_C                         23.0
Dew Point Temp_C               14.7
Rel Hum_%                        60
Wind Speed_km/h                  13
Visibility_km                  48.3
Press_kPa                    100.21
Weather               Mostly Cloudy
Name: 4307, dtype: object
Inserting row 4309
Error inserting row 4309: tuple index out of range
Row data: Date/Time           6/28/2012 12:00
Temp_C                         24.6
Dew Point Temp_C               15.3
Rel Hum_%                        56
Wind Speed_km/h                   9
Visibility_km                  48.3
Press_kPa                    100.19
Weather               Mostly Cloudy
Name: 4308, dtype: object
Inserting row 4310
Error inserting row 4310: tuple index out of range
Row data: Date/Time           6/28/2012 13:00
Temp_C                         24.9
Dew Point Temp_C               15.0
Rel Hum_%                        54
Wind Speed_km/h                  17
Visibility_km                  48.3
Press_kPa                    100.11
Weather                Mainly Clear
Name: 4309, dtype: object
Inserting row 4311
Error inserting row 4311: tuple index out of range
Row data: Date/Time           6/28/2012 14:00
Temp_C                         25.5
Dew Point Temp_C               15.3
Rel Hum_%                        53
Wind Speed_km/h                  22
Visibility_km                  48.3
Press_kPa                    100.08
Weather                Mainly Clear
Name: 4310, dtype: object
Inserting row 4312
Error inserting row 4312: tuple index out of range
Row data: Date/Time           6/28/2012 15:00
Temp_C                         27.0
Dew Point Temp_C               14.8
Rel Hum_%                        47
Wind Speed_km/h                  22
Visibility_km                  48.3
Press_kPa                    100.03
Weather                Mainly Clear
Name: 4311, dtype: object
Inserting row 4313
Error inserting row 4313: tuple index out of range
Row data: Date/Time           6/28/2012 16:00
Temp_C                         27.1
Dew Point Temp_C               14.0
Rel Hum_%                        45
Wind Speed_km/h                  22
Visibility_km                  48.3
Press_kPa                    100.01
Weather                Mainly Clear
Name: 4312, dtype: object
Inserting row 4314
Error inserting row 4314: tuple index out of range
Row data: Date/Time           6/28/2012 17:00
Temp_C                         27.2
Dew Point Temp_C               12.6
Rel Hum_%                        40
Wind Speed_km/h                  19
Visibility_km                  48.3
Press_kPa                     99.92
Weather               Mostly Cloudy
Name: 4313, dtype: object
Inserting row 4315
Error inserting row 4315: tuple index out of range
Row data: Date/Time           6/28/2012 18:00
Temp_C                         26.4
Dew Point Temp_C               12.1
Rel Hum_%                        41
Wind Speed_km/h                  19
Visibility_km                  48.3
Press_kPa                      99.9
Weather               Mostly Cloudy
Name: 4314, dtype: object
Inserting row 4316
Error inserting row 4316: tuple index out of range
Row data: Date/Time           6/28/2012 19:00
Temp_C                         25.4
Dew Point Temp_C               12.9
Rel Hum_%                        46
Wind Speed_km/h                  13
Visibility_km                  48.3
Press_kPa                     99.91
Weather               Mostly Cloudy
Name: 4315, dtype: object
Inserting row 4317
Error inserting row 4317: tuple index out of range
Row data: Date/Time           6/28/2012 20:00
Temp_C                         24.1
Dew Point Temp_C               13.5
Rel Hum_%                        52
Wind Speed_km/h                  11
Visibility_km                  24.1
Press_kPa                     99.89
Weather                Mainly Clear
Name: 4316, dtype: object
Inserting row 4318
Error inserting row 4318: tuple index out of range
Row data: Date/Time           6/28/2012 21:00
Temp_C                         23.6
Dew Point Temp_C               14.3
Rel Hum_%                        56
Wind Speed_km/h                  11
Visibility_km                  25.0
Press_kPa                     99.95
Weather                Mainly Clear
Name: 4317, dtype: object
Inserting row 4319
Error inserting row 4319: tuple index out of range
Row data: Date/Time           6/28/2012 22:00
Temp_C                         22.5
Dew Point Temp_C               15.0
Rel Hum_%                        63
Wind Speed_km/h                  11
Visibility_km                  25.0
Press_kPa                     99.88
Weather               Mostly Cloudy
Name: 4318, dtype: object
Inserting row 4320
Error inserting row 4320: tuple index out of range
Row data: Date/Time           6/28/2012 23:00
Temp_C                         21.9
Dew Point Temp_C               15.4
Rel Hum_%                        67
Wind Speed_km/h                  15
Visibility_km                  25.0
Press_kPa                     99.85
Weather               Mostly Cloudy
Name: 4319, dtype: object
Inserting row 4321
Error inserting row 4321: tuple index out of range
Row data: Date/Time           6/29/2012 0:00
Temp_C                        22.2
Dew Point Temp_C              14.0
Rel Hum_%                       60
Wind Speed_km/h                 15
Visibility_km                 25.0
Press_kPa                    99.83
Weather               Rain Showers
Name: 4320, dtype: object
Inserting row 4322
Error inserting row 4322: tuple index out of range
Row data: Date/Time           6/29/2012 1:00
Temp_C                        21.1
Dew Point Temp_C              14.7
Rel Hum_%                       67
Wind Speed_km/h                  4
Visibility_km                 25.0
Press_kPa                    99.75
Weather                     Cloudy
Name: 4321, dtype: object
Inserting row 4323
Error inserting row 4323: tuple index out of range
Row data: Date/Time           6/29/2012 2:00
Temp_C                        20.3
Dew Point Temp_C              15.3
Rel Hum_%                       73
Wind Speed_km/h                  7
Visibility_km                 25.0
Press_kPa                    99.71
Weather                     Cloudy
Name: 4322, dtype: object
Inserting row 4324
Error inserting row 4324: tuple index out of range
Row data: Date/Time                           6/29/2012 3:00
Temp_C                                        19.5
Dew Point Temp_C                              16.1
Rel Hum_%                                       81
Wind Speed_km/h                                  7
Visibility_km                                  9.7
Press_kPa                                    99.71
Weather             Thunderstorms,Rain Showers,Fog
Name: 4323, dtype: object
Inserting row 4325
Error inserting row 4325: tuple index out of range
Row data: Date/Time           6/29/2012 4:00
Temp_C                        18.8
Dew Point Temp_C              16.5
Rel Hum_%                       86
Wind Speed_km/h                  9
Visibility_km                 24.1
Press_kPa                    99.68
Weather                     Cloudy
Name: 4324, dtype: object
Inserting row 4326
Error inserting row 4326: tuple index out of range
Row data: Date/Time           6/29/2012 5:00
Temp_C                        18.9
Dew Point Temp_C              16.4
Rel Hum_%                       85
Wind Speed_km/h                 13
Visibility_km                 24.1
Press_kPa                    99.71
Weather              Mostly Cloudy
Name: 4325, dtype: object
Inserting row 4327
Error inserting row 4327: tuple index out of range
Row data: Date/Time           6/29/2012 6:00
Temp_C                        19.7
Dew Point Temp_C              16.7
Rel Hum_%                       83
Wind Speed_km/h                 17
Visibility_km                 24.1
Press_kPa                    99.72
Weather              Mostly Cloudy
Name: 4326, dtype: object
Inserting row 4328
Error inserting row 4328: tuple index out of range
Row data: Date/Time           6/29/2012 7:00
Temp_C                        21.4
Dew Point Temp_C              16.7
Rel Hum_%                       75
Wind Speed_km/h                 20
Visibility_km                 24.1
Press_kPa                    99.65
Weather               Mainly Clear
Name: 4327, dtype: object
Inserting row 4329
Error inserting row 4329: tuple index out of range
Row data: Date/Time           6/29/2012 8:00
Temp_C                        22.8
Dew Point Temp_C              17.4
Rel Hum_%                       72
Wind Speed_km/h                 24
Visibility_km                 24.1
Press_kPa                    99.61
Weather               Mainly Clear

Row data: Date/Time           7/8/2012 12:00
Temp_C                        23.0
Dew Point Temp_C               7.8
Rel Hum_%                       38
Wind Speed_km/h                 24
Visibility_km                 48.3
Press_kPa                   100.79
Weather                      Clear
Name: 4548, dtype: object
Inserting row 4550
Error inserting row 4550: tuple index out of range
Row data: Date/Time           7/8/2012 13:00
Temp_C                        23.9
Dew Point Temp_C               7.7
Rel Hum_%                       35
Wind Speed_km/h                 17
Visibility_km                 48.3
Press_kPa                   100.76
Weather               Mainly Clear
Name: 4549, dtype: object
Inserting row 4551
Error inserting row 4551: tuple index out of range
Row data: Date/Time           7/8/2012 14:00
Temp_C                        24.5
Dew Point Temp_C               9.6
Rel Hum_%                       39
Wind Speed_km/h                 17
Visibility_km                 48.3
Press_kPa                   100.72
Weather               Mainly Clear
Name: 4550, dtype: object
Inserting row 4552
Error inserting row 4552: tuple index out of range
Row data: Date/Time           7/8/2012 15:00
Temp_C                        24.3
Dew Point Temp_C               8.5
Rel Hum_%                       37
Wind Speed_km/h                 15
Visibility_km                 48.3
Press_kPa                   100.72
Weather               Mainly Clear
Name: 4551, dtype: object
Inserting row 4553
Error inserting row 4553: tuple index out of range
Row data: Date/Time           7/8/2012 16:00
Temp_C                        24.5
Dew Point Temp_C               7.7
Rel Hum_%                       34
Wind Speed_km/h                 24
Visibility_km                 48.3
Press_kPa                   100.72
Weather               Mainly Clear
Name: 4552, dtype: object
Inserting row 4554
Error inserting row 4554: tuple index out of range
Row data: Date/Time           7/8/2012 17:00
Temp_C                        24.2
Dew Point Temp_C               7.8
Rel Hum_%                       35
Wind Speed_km/h                 26
Visibility_km                 48.3
Press_kPa                    100.7
Weather               Mainly Clear
Name: 4553, dtype: object
Inserting row 4555
Error inserting row 4555: tuple index out of range
Row data: Date/Time           7/8/2012 18:00
Temp_C                        23.6
Dew Point Temp_C               8.3
Rel Hum_%                       38
Wind Speed_km/h                 20
Visibility_km                 48.3
Press_kPa                   100.69
Weather               Mainly Clear
Name: 4554, dtype: object
Inserting row 4556
Error inserting row 4556: tuple index out of range
Row data: Date/Time           7/8/2012 19:00
Temp_C                        22.2
Dew Point Temp_C               8.5
Rel Hum_%                       41
Wind Speed_km/h                 19
Visibility_km                 48.3
Press_kPa                   100.72
Weather               Mainly Clear
Name: 4555, dtype: object
Inserting row 4557
Error inserting row 4557: tuple index out of range
Row data: Date/Time           7/8/2012 20:00
Temp_C                        20.3
Dew Point Temp_C               8.4
Rel Hum_%                       46
Wind Speed_km/h                 11
Visibility_km                 48.3
Press_kPa                   100.74
Weather                      Clear
Name: 4556, dtype: object
Inserting row 4558
Error inserting row 4558: tuple index out of range
Row data: Date/Time           7/8/2012 21:00
Temp_C                        19.8
Dew Point Temp_C               8.0
Rel Hum_%                       46
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                    100.8
Weather                      Clear
Name: 4557, dtype: object
Inserting row 4559
Error inserting row 4559: tuple index out of range
Row data: Date/Time           7/8/2012 22:00
Temp_C                        17.9
Dew Point Temp_C               8.1
Rel Hum_%                       53
Wind Speed_km/h                  7
Visibility_km                 25.0
Press_kPa                   100.81
Weather                      Clear
Name: 4558, dtype: object
Inserting row 4560
Error inserting row 4560: tuple index out of range
Row data: Date/Time           7/8/2012 23:00
Temp_C                        17.1
Dew Point Temp_C               8.4
Rel Hum_%                       57
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                   100.85
Weather                      Clear
Name: 4559, dtype: object
Inserting row 4561
Error inserting row 4561: tuple index out of range
Row data: Date/Time           7/9/2012 0:00
Temp_C                       16.0
Dew Point Temp_C              8.9
Rel Hum_%                      63
Wind Speed_km/h                13
Visibility_km                25.0
Press_kPa                  100.83
Weather                     Clear
Name: 4560, dtype: object
Inserting row 4562
Error inserting row 4562: tuple index out of range
Row data: Date/Time           7/9/2012 1:00
Temp_C                       14.4
Dew Point Temp_C              9.0
Rel Hum_%                      70
Wind Speed_km/h                 9
Visibility_km                25.0
Press_kPa                  100.84
Weather                     Clear
Name: 4561, dtype: object
Inserting row 4563
Error inserting row 4563: tuple index out of range
Row data: Date/Time           7/9/2012 2:00
Temp_C                       14.9
Dew Point Temp_C              9.1
Rel Hum_%                      68
Wind Speed_km/h                 9
Visibility_km                25.0
Press_kPa                  100.86
Weather                     Clear
Name: 4562, dtype: object
Inserting row 4564
Error inserting row 4564: tuple index out of range
Row data: Date/Time           7/9/2012 3:00
Temp_C                       13.2
Dew Point Temp_C              9.0
Rel Hum_%                      76
Wind Speed_km/h                 9
Visibility_km                25.0
Press_kPa                  100.88
Weather              Mainly Clear
Name: 4563, dtype: object
Inserting row 4565
Error inserting row 4565: tuple index out of range
Row data: Date/Time           7/9/2012 4:00
Temp_C                       13.5
Dew Point Temp_C              8.9
Rel Hum_%                      74
Wind Speed_km/h                 9
Visibility_km                25.0
Press_kPa                  100.91
Weather              Mainly Clear
Name: 4564, dtype: object
Inserting row 4566
Error inserting row 4566: tuple index out of range
Row data: Date/Time           7/9/2012 5:00
Temp_C                       12.8
Dew Point Temp_C              9.4
Rel Hum_%                      80
Wind Speed_km/h                 7
Visibility_km                24.1
Press_kPa                  100.98
Weather              Mainly Clear
Name: 4565, dtype: object
Inserting row 4567
Error inserting row 4567: tuple index out of range
Row data: Date/Time           7/9/2012 6:00
Temp_C                       16.1
Dew Point Temp_C              9.6
Rel Hum_%                      65
Wind Speed_km/h                13
Visibility_km                48.3
Press_kPa                  101.07
Weather              Mainly Clear
Name: 4566, dtype: object
Inserting row 4568
Error inserting row 4568: tuple index out of range
Row data: Date/Time           7/9/2012 7:00
Temp_C                       17.8
Dew Point Temp_C              8.7
Rel Hum_%                      55
Wind Speed_km/h                11
Visibility_km                48.3
Press_kPa                   101.1
Weather                     Clear
Name: 4567, dtype: object
Inserting row 4569
Error inserting row 4569: tuple index out of range
Row data: Date/Time           7/9/2012 8:00
Temp_C                       18.2
Dew Point Temp_C              8.1
Rel Hum_%                      52
Wind Speed_km/h                11
Visibility_km                48.3
Press_kPa                  101.13
Weather                     Clear
Name: 4568, dtype: object
Inserting row 4570
Error inserting row 4570: tuple index out of range
Row data: Date/Time           7/9/2012 9:00
Temp_C                       19.2
Dew Point Temp_C              7.9
Rel Hum_%                      48
Wind Speed_km/h                 9
Visibility_km                48.3
Press_kPa                  101.13
Weather                     Clear
Name: 4569, dtype: object
Inserting row 4571
Error inserting row 4571: tuple index out of range
Row data: Date/Time           7/9/2012 10:00
Temp_C                        19.9
Dew Point Temp_C               7.5
Rel Hum_%                       45
Wind Speed_km/h                 17
Visibility_km                 48.3
Press_kPa                   101.12
Weather                      Clear
Name: 4570, dtype: object
Inserting row 4572
Error inserting row 4572: tuple index out of range
Row data: Date/Time           7/9/2012 11:00
Temp_C                        21.4
Dew Point Temp_C               7.9
Rel Hum_%                       42
Wind Speed_km/h                 20
Visibility_km                 48.3
Press_kPa                   101.09
Weather                      Clear
Name: 4571, dtype: object
Inserting row 4573
Error inserting row 4573: tuple index out of range
Row data: Date/Time           7/9/2012 12:00
Temp_C                        22.2
Dew Point Temp_C               7.1
Rel Hum_%                       38
Wind Speed_km/h                 13
Visibility_km                 48.3
Press_kPa                   101.07
Weather                      Clear
Name: 4572, dtype: object
Inserting row 4574
Error inserting row 4574: tuple index out of range
Row data: Date/Time           7/9/2012 13:00
Temp_C                        23.1
Dew Point Temp_C               7.9
Rel Hum_%                       38
Wind Speed_km/h                 19
Visibility_km                 48.3
Press_kPa                   101.04
Weather               Mainly Clear
Name: 4573, dtype: object
Inserting row 4575
Error inserting row 4575: tuple index out of range
Row data: Date/Time           7/9/2012 14:00
Temp_C                        24.3
Dew Point Temp_C               6.5
Rel Hum_%                       32
Wind Speed_km/h                 22
Visibility_km                 48.3
Press_kPa                   101.01
Weather               Mainly Clear
Name: 4574, dtype: object
Inserting row 4576
Error inserting row 4576: tuple index out of range
Row data: Date/Time           7/9/2012 15:00
Temp_C                        24.4
Dew Point Temp_C               5.3
Rel Hum_%                       29
Wind Speed_km/h                 17
Visibility_km                 48.3
Press_kPa                    101.0
Weather               Mainly Clear
Name: 4575, dtype: object
Inserting row 4577
Error inserting row 4577: tuple index out of range
Row data: Date/Time           7/9/2012 16:00
Temp_C                        24.5
Dew Point Temp_C               4.7
Rel Hum_%                       28
Wind Speed_km/h                 15
Visibility_km                 48.3
Press_kPa                   100.99
Weather               Mainly Clear
Name: 4576, dtype: object
Inserting row 4578
Error inserting row 4578: tuple index out of range
Row data: Date/Time           7/9/2012 17:00
Temp_C                        24.2
Dew Point Temp_C               5.3
Rel Hum_%                       29
Wind Speed_km/h                 11
Visibility_km                 48.3
Press_kPa                   100.98
Weather               Mainly Clear
Name: 4577, dtype: object
Inserting row 4579
Error inserting row 4579: tuple index out of range
Row data: Date/Time           7/9/2012 18:00
Temp_C                        23.6
Dew Point Temp_C               6.9
Rel Hum_%                       34
Wind Speed_km/h                 13
Visibility_km                 48.3
Press_kPa                    101.0
Weather               Mainly Clear
Name: 4578, dtype: object
Inserting row 4580
Error inserting row 4580: tuple index out of range
Row data: Date/Time           7/9/2012 19:00
Temp_C                        22.3
Dew Point Temp_C               7.2
Rel Hum_%                       38
Wind Speed_km/h                 13
Visibility_km                 48.3
Press_kPa                   101.01
Weather               Mainly Clear
Name: 4579, dtype: object
Inserting row 4581
Error inserting row 4581: tuple index out of range
Row data: Date/Time           7/9/2012 20:00
Temp_C                        19.5
Dew Point Temp_C               7.9
Rel Hum_%                       47
Wind Speed_km/h                  7
Visibility_km                 48.3
Press_kPa                   101.02
Weather                      Clear
Name: 4580, dtype: object
Inserting row 4582
Error inserting row 4582: tuple index out of range
Row data: Date/Time           7/9/2012 21:00
Temp_C                        19.9
Dew Point Temp_C               8.1
Rel Hum_%                       46
Wind Speed_km/h                  6
Visibility_km                 25.0
Press_kPa                   101.05
Weather               Mainly Clear
Name: 4581, dtype: object
Inserting row 4583
Error inserting row 4583: tuple index out of range
Row data: Date/Time           7/9/2012 22:00
Temp_C                        17.6
Dew Point Temp_C               9.0
Rel Hum_%                       57
Wind Speed_km/h                  4
Visibility_km                 25.0
Press_kPa                   101.04
Weather                      Clear
Name: 4582, dtype: object
Inserting row 4584
Error inserting row 4584: tuple index out of range
Row data: Date/Time           7/9/2012 23:00
Temp_C                        16.3
Dew Point Temp_C               9.6
Rel Hum_%                       64
Wind Speed_km/h                  6
Visibility_km                 25.0
Press_kPa                   101.05
Weather               Mainly Clear
Name: 4583, dtype: object
Inserting row 4585
Error inserting row 4585: tuple index out of range
Row data: Date/Time           7/10/2012 0:00
Temp_C                        18.2
Dew Point Temp_C              11.2
Rel Hum_%                       64
Wind Speed_km/h                  7
Visibility_km                 25.0
Press_kPa                   101.04
Weather                      Clear
Name: 4584, dtype: object
Inserting row 4586
Error inserting row 4586: tuple index out of range
Row data: Date/Time           7/10/2012 1:00
Temp_C                        18.7
Dew Point Temp_C               9.4
Rel Hum_%                       55
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   101.04
Weather                      Clear
Name: 4585, dtype: object
Inserting row 4587
Error inserting row 4587: tuple index out of range
Row data: Date/Time           7/10/2012 2:00
Temp_C                        17.0
Dew Point Temp_C               9.8
Rel Hum_%                       63
Wind Speed_km/h                  7
Visibility_km                 25.0
Press_kPa                   101.06
Weather                      Clear
Name: 4586, dtype: object
Inserting row 4588
Error inserting row 4588: tuple index out of range
Row data: Date/Time           7/10/2012 3:00
Temp_C                        16.6
Dew Point Temp_C              11.0
Rel Hum_%                       69
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                   101.06
Weather                      Clear
Name: 4587, dtype: object
Inserting row 4589
Error inserting row 4589: tuple index out of range
Row data: Date/Time           7/10/2012 4:00
Temp_C                        16.4
Dew Point Temp_C              12.4
Rel Hum_%                       77
Wind Speed_km/h                 11
Visibility_km                 24.1
Press_kPa                   101.11
Weather                      Clear
Name: 4588, dtype: object
Inserting row 4590
Error inserting row 4590: tuple index out of range
Row data: Date/Time           7/10/2012 5:00
Temp_C                        16.6
Dew Point Temp_C              11.7
Rel Hum_%                       73
Wind Speed_km/h                  9
Visibility_km                 48.3
Press_kPa                   101.15
Weather               Mainly Clear
Name: 4589, dtype: object
Inserting row 4591
Error inserting row 4591: tuple index out of range
Row data: Date/Time           7/10/2012 6:00
Temp_C                        17.1
Dew Point Temp_C              12.3
Rel Hum_%                       73
Wind Speed_km/h                  9
Visibility_km                 48.3
Press_kPa                   101.19
Weather               Mainly Clear
Name: 4590, dtype: object
Inserting row 4592
Error inserting row 4592: tuple index out of range
Row data: Date/Time           7/10/2012 7:00
Temp_C                        19.3
Dew Point Temp_C              11.8
Rel Hum_%                       62
Wind Speed_km/h                  9
Visibility_km                 48.3
Press_kPa                   101.22
Weather               Mainly Clear
Name: 4591, dtype: object
Inserting row 4593
Error inserting row 4593: tuple index out of range
Row data: Date/Time           7/10/2012 8:00
Temp_C                        20.4
Dew Point Temp_C              13.7
Rel Hum_%                       65
Wind Speed_km/h                 15
Visibility_km                 48.3
Press_kPa                   101.22
Weather               Mainly Clear
Name: 4592, dtype: object
Inserting row 4594
Error inserting row 4594: tuple index out of range
Row data: Date/Time           7/10/2012 9:00
Temp_C                        22.3
Dew Point Temp_C              12.9
Rel Hum_%                       55
Wind Speed_km/h                  9
Visibility_km                 48.3
Press_kPa                   101.24
Weather               Mainly Clear
Name: 4593, dtype: object
Inserting row 4595
Error inserting row 4595: tuple index out of range
Row data: Date/Time           7/10/2012 10:00
Temp_C                         23.6
Dew Point Temp_C               11.6
Rel Hum_%                        47
Wind Speed_km/h                   9
Visibility_km                  48.3
Press_kPa                    101.23
Weather                Mainly Clear
Name: 4594, dtype: object
Inserting row 4596
Error inserting row 4596: tuple index out of range
Row data: Date/Time           7/10/2012 11:00
Temp_C                         25.0
Dew Point Temp_C               10.7
Rel Hum_%                        41
Wind Speed_km/h                  15
Visibility_km                  48.3
Press_kPa                    101.21
Weather                Mainly Clear
Name: 4595, dtype: object
Inserting row 4597
Error inserting row 4597: tuple index out of range
Row data: Date/Time           7/10/2012 12:00
Temp_C                         25.9
Dew Point Temp_C                9.4
Rel Hum_%                        35
Wind Speed_km/h                  26
Visibility_km                  48.3
Press_kPa                    101.15
Weather                Mainly Clear
Name: 4596, dtype: object
Inserting row 4598
Error inserting row 4598: tuple index out of range
Row data: Date/Time           7/10/2012 13:00
Temp_C                         25.8
Dew Point Temp_C                8.5
Rel Hum_%                        33
Wind Speed_km/h                  22
Visibility_km                  48.3
Press_kPa                    101.14
Weather                Mainly Clear
Name: 4597, dtype: object
Inserting row 4599
Error inserting row 4599: tuple index out of range
Row data: Date/Time           7/10/2012 14:00
Temp_C                         27.0
Dew Point Temp_C               10.7
Rel Hum_%                        36
Wind Speed_km/h                  19
Visibility_km                  48.3
Press_kPa                    101.11
Weather               Mostly Cloudy
Name: 4598, dtype: object
Inserting row 4600
Error inserting row 4600: tuple index out of range
Row data: Date/Time           7/10/2012 15:00
Temp_C                         26.5
Dew Point Temp_C               11.2
Rel Hum_%                        38
Wind Speed_km/h                  19
Visibility_km                  48.3
Press_kPa                    101.09
Weather                Mainly Clear
Name: 4599, dtype: object
Inserting row 4601

Row data: Date/Time           7/20/2012 2:00
Temp_C                        14.6
Dew Point Temp_C               9.8
Rel Hum_%                       73
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   101.46
Weather                      Clear
Name: 4826, dtype: object
Inserting row 4828
Error inserting row 4828: tuple index out of range
Row data: Date/Time           7/20/2012 3:00
Temp_C                        14.2
Dew Point Temp_C               9.8
Rel Hum_%                       75
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   101.44
Weather                      Clear
Name: 4827, dtype: object
Inserting row 4829
Error inserting row 4829: tuple index out of range
Row data: Date/Time           7/20/2012 4:00
Temp_C                        14.4
Dew Point Temp_C               9.3
Rel Hum_%                       71
Wind Speed_km/h                 11
Visibility_km                 48.3
Press_kPa                   101.49
Weather                      Clear
Name: 4828, dtype: object
Inserting row 4830
Error inserting row 4830: tuple index out of range
Row data: Date/Time           7/20/2012 5:00
Temp_C                        14.5
Dew Point Temp_C               9.3
Rel Hum_%                       71
Wind Speed_km/h                 13
Visibility_km                 48.3
Press_kPa                   101.51
Weather                      Clear
Name: 4829, dtype: object
Inserting row 4831
Error inserting row 4831: tuple index out of range
Row data: Date/Time           7/20/2012 6:00
Temp_C                        15.5
Dew Point Temp_C               9.6
Rel Hum_%                       68
Wind Speed_km/h                 13
Visibility_km                 48.3
Press_kPa                   101.55
Weather               Mainly Clear
Name: 4830, dtype: object
Inserting row 4832
Error inserting row 4832: tuple index out of range
Row data: Date/Time           7/20/2012 7:00
Temp_C                        17.1
Dew Point Temp_C               9.9
Rel Hum_%                       63
Wind Speed_km/h                  9
Visibility_km                 48.3
Press_kPa                   101.56
Weather               Mainly Clear
Name: 4831, dtype: object
Inserting row 4833
Error inserting row 4833: tuple index out of range
Row data: Date/Time           7/20/2012 8:00
Temp_C                        19.3
Dew Point Temp_C              10.1
Rel Hum_%                       55
Wind Speed_km/h                  9
Visibility_km                 48.3
Press_kPa                   101.57
Weather               Mainly Clear
Name: 4832, dtype: object
Inserting row 4834
Error inserting row 4834: tuple index out of range
Row data: Date/Time           7/20/2012 9:00
Temp_C                        20.3
Dew Point Temp_C               9.7
Rel Hum_%                       51
Wind Speed_km/h                 11
Visibility_km                 48.3
Press_kPa                   101.58
Weather               Mainly Clear
Name: 4833, dtype: object
Inserting row 4835
Error inserting row 4835: tuple index out of range
Row data: Date/Time           7/20/2012 10:00
Temp_C                         21.3
Dew Point Temp_C               10.8
Rel Hum_%                        51
Wind Speed_km/h                  13
Visibility_km                  48.3
Press_kPa                    101.57
Weather                Mainly Clear
Name: 4834, dtype: object
Inserting row 4836
Error inserting row 4836: tuple index out of range
Row data: Date/Time           7/20/2012 11:00
Temp_C                         21.3
Dew Point Temp_C               10.7
Rel Hum_%                        51
Wind Speed_km/h                   9
Visibility_km                  48.3
Press_kPa                    101.57
Weather                Mainly Clear
Name: 4835, dtype: object
Inserting row 4837
Error inserting row 4837: tuple index out of range
Row data: Date/Time           7/20/2012 12:00
Temp_C                         22.6
Dew Point Temp_C                9.5
Rel Hum_%                        43
Wind Speed_km/h                   6
Visibility_km                  48.3
Press_kPa                    101.51
Weather                Mainly Clear
Name: 4836, dtype: object
Inserting row 4838
Error inserting row 4838: tuple index out of range
Row data: Date/Time           7/20/2012 13:00
Temp_C                         23.2
Dew Point Temp_C               10.4
Rel Hum_%                        44
Wind Speed_km/h                   9
Visibility_km                  48.3
Press_kPa                    101.45
Weather                Mainly Clear
Name: 4837, dtype: object
Inserting row 4839
Error inserting row 4839: tuple index out of range
Row data: Date/Time           7/20/2012 14:00
Temp_C                         23.9
Dew Point Temp_C               10.0
Rel Hum_%                        41
Wind Speed_km/h                  13
Visibility_km                  48.3
Press_kPa                    101.42
Weather                Mainly Clear
Name: 4838, dtype: object
Inserting row 4840
Error inserting row 4840: tuple index out of range
Row data: Date/Time           7/20/2012 15:00
Temp_C                         24.2
Dew Point Temp_C                9.9
Rel Hum_%                        40
Wind Speed_km/h                   4
Visibility_km                  48.3
Press_kPa                    101.37
Weather                Mainly Clear
Name: 4839, dtype: object
Inserting row 4841
Error inserting row 4841: tuple index out of range
Row data: Date/Time           7/20/2012 16:00
Temp_C                         24.4
Dew Point Temp_C                9.7
Rel Hum_%                        39
Wind Speed_km/h                  11
Visibility_km                  48.3
Press_kPa                    101.34
Weather                Mainly Clear
Name: 4840, dtype: object
Inserting row 4842
Error inserting row 4842: tuple index out of range
Row data: Date/Time           7/20/2012 17:00
Temp_C                         24.2
Dew Point Temp_C                9.8
Rel Hum_%                        40
Wind Speed_km/h                   4
Visibility_km                  48.3
Press_kPa                    101.34
Weather                Mainly Clear
Name: 4841, dtype: object
Inserting row 4843
Error inserting row 4843: tuple index out of range
Row data: Date/Time           7/20/2012 18:00
Temp_C                         24.6
Dew Point Temp_C                9.6
Rel Hum_%                        39
Wind Speed_km/h                   4
Visibility_km                  48.3
Press_kPa                    101.35
Weather                Mainly Clear
Name: 4842, dtype: object
Inserting row 4844
Error inserting row 4844: tuple index out of range
Row data: Date/Time           7/20/2012 19:00
Temp_C                         23.5
Dew Point Temp_C                7.6
Rel Hum_%                        36
Wind Speed_km/h                   7
Visibility_km                  48.3
Press_kPa                    101.33
Weather                Mainly Clear
Name: 4843, dtype: object
Inserting row 4845
Error inserting row 4845: tuple index out of range
Row data: Date/Time           7/20/2012 20:00
Temp_C                         22.2
Dew Point Temp_C                9.5
Rel Hum_%                        44
Wind Speed_km/h                   6
Visibility_km                  48.3
Press_kPa                    101.34
Weather                Mainly Clear
Name: 4844, dtype: object
Inserting row 4846
Error inserting row 4846: tuple index out of range
Row data: Date/Time           7/20/2012 21:00
Temp_C                         19.6
Dew Point Temp_C               12.0
Rel Hum_%                        61
Wind Speed_km/h                   0
Visibility_km                  25.0
Press_kPa                    101.36
Weather                       Clear
Name: 4845, dtype: object
Inserting row 4847
Error inserting row 4847: tuple index out of range
Row data: Date/Time           7/20/2012 22:00
Temp_C                         18.1
Dew Point Temp_C               12.3
Rel Hum_%                        69
Wind Speed_km/h                   0
Visibility_km                  25.0
Press_kPa                    101.37
Weather                       Clear
Name: 4846, dtype: object
Inserting row 4848
Error inserting row 4848: tuple index out of range
Row data: Date/Time           7/20/2012 23:00
Temp_C                         18.2
Dew Point Temp_C               12.3
Rel Hum_%                        68
Wind Speed_km/h                   0
Visibility_km                  25.0
Press_kPa                    101.36
Weather                       Clear
Name: 4847, dtype: object
Inserting row 4849
Error inserting row 4849: tuple index out of range
Row data: Date/Time           7/21/2012 0:00
Temp_C                        17.2
Dew Point Temp_C              12.6
Rel Hum_%                       74
Wind Speed_km/h                  4
Visibility_km                 25.0
Press_kPa                    101.4
Weather                      Clear
Name: 4848, dtype: object
Inserting row 4850
Error inserting row 4850: tuple index out of range
Row data: Date/Time           7/21/2012 1:00
Temp_C                        17.2
Dew Point Temp_C              12.4
Rel Hum_%                       73
Wind Speed_km/h                  0
Visibility_km                 25.0
Press_kPa                    101.4
Weather                      Clear
Name: 4849, dtype: object
Inserting row 4851
Error inserting row 4851: tuple index out of range
Row data: Date/Time           7/21/2012 2:00
Temp_C                        15.1
Dew Point Temp_C              12.4
Rel Hum_%                       84
Wind Speed_km/h                  0
Visibility_km                 25.0
Press_kPa                   101.39
Weather                      Clear
Name: 4850, dtype: object
Inserting row 4852
Error inserting row 4852: tuple index out of range
Row data: Date/Time           7/21/2012 3:00
Temp_C                        14.0
Dew Point Temp_C              12.3
Rel Hum_%                       89
Wind Speed_km/h                  0
Visibility_km                 25.0
Press_kPa                   101.37
Weather                      Clear
Name: 4851, dtype: object
Inserting row 4853
Error inserting row 4853: tuple index out of range
Row data: Date/Time           7/21/2012 4:00
Temp_C                        14.6
Dew Point Temp_C              12.9
Rel Hum_%                       90
Wind Speed_km/h                  0
Visibility_km                 24.1
Press_kPa                    101.4
Weather                      Clear
Name: 4852, dtype: object
Inserting row 4854
Error inserting row 4854: tuple index out of range
Row data: Date/Time           7/21/2012 5:00
Temp_C                        14.5
Dew Point Temp_C              12.5
Rel Hum_%                       88
Wind Speed_km/h                  4
Visibility_km                 48.3
Press_kPa                   101.38
Weather                      Clear
Name: 4853, dtype: object
Inserting row 4855
Error inserting row 4855: tuple index out of range
Row data: Date/Time           7/21/2012 6:00
Temp_C                        16.9
Dew Point Temp_C              13.7
Rel Hum_%                       81
Wind Speed_km/h                  4
Visibility_km                 48.3
Press_kPa                    101.4
Weather                      Clear
Name: 4854, dtype: object
Inserting row 4856
Error inserting row 4856: tuple index out of range
Row data: Date/Time           7/21/2012 7:00
Temp_C                        20.0
Dew Point Temp_C              15.0
Rel Hum_%                       73
Wind Speed_km/h                  0
Visibility_km                 48.3
Press_kPa                   101.43
Weather                      Clear
Name: 4855, dtype: object
Inserting row 4857
Error inserting row 4857: tuple index out of range
Row data: Date/Time           7/21/2012 8:00
Temp_C                        21.1
Dew Point Temp_C              14.2
Rel Hum_%                       65
Wind Speed_km/h                  0
Visibility_km                 48.3
Press_kPa                   101.47
Weather               Mainly Clear
Name: 4856, dtype: object
Inserting row 4858
Error inserting row 4858: tuple index out of range
Row data: Date/Time           7/21/2012 9:00
Temp_C                        22.3
Dew Point Temp_C              14.5
Rel Hum_%                       61
Wind Speed_km/h                  7
Visibility_km                 48.3
Press_kPa                   101.44
Weather               Mainly Clear
Name: 4857, dtype: object
Inserting row 4859
Error inserting row 4859: tuple index out of range
Row data: Date/Time           7/21/2012 10:00
Temp_C                         23.2
Dew Point Temp_C               14.1
Rel Hum_%                        57
Wind Speed_km/h                   9
Visibility_km                  48.3
Press_kPa                     101.4
Weather                Mainly Clear
Name: 4858, dtype: object
Inserting row 4860
Error inserting row 4860: tuple index out of range
Row data: Date/Time           7/21/2012 11:00
Temp_C                         24.7
Dew Point Temp_C               13.7
Rel Hum_%                        50
Wind Speed_km/h                   9
Visibility_km                  48.3
Press_kPa                    101.39
Weather                Mainly Clear
Name: 4859, dtype: object
Inserting row 4861
Error inserting row 4861: tuple index out of range
Row data: Date/Time           7/21/2012 12:00
Temp_C                         24.9
Dew Point Temp_C               12.3
Rel Hum_%                        45
Wind Speed_km/h                   6
Visibility_km                  48.3
Press_kPa                    101.36
Weather                Mainly Clear
Name: 4860, dtype: object
Inserting row 4862
Error inserting row 4862: tuple index out of range
Row data: Date/Time           7/21/2012 13:00
Temp_C                         25.5
Dew Point Temp_C               12.1
Rel Hum_%                        43
Wind Speed_km/h                  11
Visibility_km                  48.3
Press_kPa                     101.3
Weather                Mainly Clear
Name: 4861, dtype: object
Inserting row 4863
Error inserting row 4863: tuple index out of range
Row data: Date/Time           7/21/2012 14:00
Temp_C                         26.2
Dew Point Temp_C               13.5
Rel Hum_%                        45
Wind Speed_km/h                  17
Visibility_km                  48.3
Press_kPa                    101.26
Weather               Mostly Cloudy
Name: 4862, dtype: object
Inserting row 4864
Error inserting row 4864: tuple index out of range
Row data: Date/Time           7/21/2012 15:00
Temp_C                         26.3
Dew Point Temp_C               12.3
Rel Hum_%                        42
Wind Speed_km/h                  17
Visibility_km                  48.3
Press_kPa                    101.22
Weather               Mostly Cloudy
Name: 4863, dtype: object
Inserting row 4865
Error inserting row 4865: tuple index out of range
Row data: Date/Time           7/21/2012 16:00
Temp_C                         26.2
Dew Point Temp_C               13.1
Rel Hum_%                        44
Wind Speed_km/h                  15
Visibility_km                  48.3
Press_kPa                    101.19
Weather               Mostly Cloudy
Name: 4864, dtype: object
Inserting row 4866
Error inserting row 4866: tuple index out of range
Row data: Date/Time           7/21/2012 17:00
Temp_C                         26.9
Dew Point Temp_C               12.1
Rel Hum_%                        40
Wind Speed_km/h                  15
Visibility_km                  48.3
Press_kPa                    101.13
Weather                Mainly Clear
Name: 4865, dtype: object
Inserting row 4867
Error inserting row 4867: tuple index out of range
Row data: Date/Time           7/21/2012 18:00
Temp_C                         26.1
Dew Point Temp_C               10.8
Rel Hum_%                        38
Wind Speed_km/h                  15
Visibility_km                  48.3
Press_kPa                    101.11
Weather                Mainly Clear
Name: 4866, dtype: object
Inserting row 4868
Error inserting row 4868: tuple index out of range
Row data: Date/Time           7/21/2012 19:00
Temp_C                         25.4
Dew Point Temp_C               11.7
Rel Hum_%                        42
Wind Speed_km/h                  13
Visibility_km                  24.1
Press_kPa                    101.06
Weather               Mostly Cloudy
Name: 4867, dtype: object
Inserting row 4869
Error inserting row 4869: tuple index out of range
Row data: Date/Time           7/21/2012 20:00
Temp_C                         24.6
Dew Point Temp_C               13.5
Rel Hum_%                        50
Wind Speed_km/h                  13
Visibility_km                  25.0
Press_kPa                    101.08
Weather               Mostly Cloudy
Name: 4868, dtype: object
Inserting row 4870
Error inserting row 4870: tuple index out of range
Row data: Date/Time           7/21/2012 21:00
Temp_C                         23.4
Dew Point Temp_C               12.9
Rel Hum_%                        52
Wind Speed_km/h                   4
Visibility_km                  25.0
Press_kPa                    101.18
Weather               Mostly Cloudy
Name: 4869, dtype: object
Inserting row 4871
Error inserting row 4871: tuple index out of range
Row data: Date/Time           7/21/2012 22:00
Temp_C                         23.0
Dew Point Temp_C               15.3
Rel Hum_%                        62
Wind Speed_km/h                   4
Visibility_km                  25.0
Press_kPa                    101.19
Weather               Mostly Cloudy
Name: 4870, dtype: object
Inserting row 4872
Error inserting row 4872: tuple index out of range
Row data: Date/Time           7/21/2012 23:00
Temp_C                         22.9
Dew Point Temp_C               14.4
Rel Hum_%                        59
Wind Speed_km/h                   9
Visibility_km                  25.0
Press_kPa                    101.19
Weather                      Cloudy
Name: 4871, dtype: object
Inserting row 4873
Error inserting row 4873: tuple index out of range
Row data: Date/Time           7/22/2012 0:00
Temp_C                        22.7
Dew Point Temp_C              14.9
Rel Hum_%                       61
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   101.19
Weather                     Cloudy
Name: 4872, dtype: object
Inserting row 4874
Error inserting row 4874: tuple index out of range
Row data: Date/Time           7/22/2012 1:00
Temp_C                        22.5
Dew Point Temp_C              15.4
Rel Hum_%                       64
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   101.17
Weather              Mostly Cloudy
Name: 4873, dtype: object
Inserting row 4875
Error inserting row 4875: tuple index out of range
Row data: Date/Time           7/22/2012 2:00
Temp_C                        22.4
Dew Point Temp_C              15.9
Rel Hum_%                       67
Wind Speed_km/h                 15
Visibility_km                 25.0
Press_kPa                   101.13
Weather              Mostly Cloudy
Name: 4874, dtype: object
Inserting row 4876
Error inserting row 4876: tuple index out of range
Row data: Date/Time           7/22/2012 3:00
Temp_C                        22.4
Dew Point Temp_C              14.8
Rel Hum_%                       62
Wind Speed_km/h                 15
Visibility_km                 25.0
Press_kPa                   101.12
Weather              Mostly Cloudy
Name: 4875, dtype: object
Inserting row 4877
Error inserting row 4877: tuple index out of range
Row data: Date/Time           7/22/2012 4:00
Temp_C                        21.9
Dew Point Temp_C              15.3
Rel Hum_%                       66
Wind Speed_km/h                 15
Visibility_km                 25.0
Press_kPa                   101.15
Weather               Mainly Clear
Name: 4876, dtype: object
Inserting row 4878
Error inserting row 4878: tuple index out of range
Row data: Date/Time           7/22/2012 5:00
Temp_C                        21.8

Row data: Date/Time           7/30/2012 6:00
Temp_C                        20.5
Dew Point Temp_C              16.9
Rel Hum_%                       80
Wind Speed_km/h                  6
Visibility_km                 24.1
Press_kPa                   101.28
Weather               Mainly Clear
Name: 5070, dtype: object
Inserting row 5072
Error inserting row 5072: tuple index out of range
Row data: Date/Time           7/30/2012 7:00
Temp_C                        21.6
Dew Point Temp_C              17.2
Rel Hum_%                       76
Wind Speed_km/h                  6
Visibility_km                 48.3
Press_kPa                   101.31
Weather               Mainly Clear
Name: 5071, dtype: object
Inserting row 5073
Error inserting row 5073: tuple index out of range
Row data: Date/Time           7/30/2012 8:00
Temp_C                        22.4
Dew Point Temp_C              16.7
Rel Hum_%                       70
Wind Speed_km/h                  7
Visibility_km                 48.3
Press_kPa                   101.31
Weather                      Clear
Name: 5072, dtype: object
Inserting row 5074
Error inserting row 5074: tuple index out of range
Row data: Date/Time           7/30/2012 9:00
Temp_C                        24.1
Dew Point Temp_C              16.9
Rel Hum_%                       64
Wind Speed_km/h                  7
Visibility_km                 48.3
Press_kPa                   101.31
Weather               Mainly Clear
Name: 5073, dtype: object
Inserting row 5075
Error inserting row 5075: tuple index out of range
Row data: Date/Time           7/30/2012 10:00
Temp_C                         25.0
Dew Point Temp_C               15.8
Rel Hum_%                        57
Wind Speed_km/h                  15
Visibility_km                  48.3
Press_kPa                    101.29
Weather                Mainly Clear
Name: 5074, dtype: object
Inserting row 5076
Error inserting row 5076: tuple index out of range
Row data: Date/Time           7/30/2012 11:00
Temp_C                         26.0
Dew Point Temp_C               15.0
Rel Hum_%                        51
Wind Speed_km/h                  15
Visibility_km                  48.3
Press_kPa                    101.27
Weather                Mainly Clear
Name: 5075, dtype: object
Inserting row 5077
Error inserting row 5077: tuple index out of range
Row data: Date/Time           7/30/2012 12:00
Temp_C                         27.2
Dew Point Temp_C               15.8
Rel Hum_%                        50
Wind Speed_km/h                  19
Visibility_km                  48.3
Press_kPa                    101.22
Weather                Mainly Clear
Name: 5076, dtype: object
Inserting row 5078
Error inserting row 5078: tuple index out of range
Row data: Date/Time           7/30/2012 13:00
Temp_C                         28.5
Dew Point Temp_C               15.5
Rel Hum_%                        45
Wind Speed_km/h                  15
Visibility_km                  48.3
Press_kPa                    101.17
Weather               Mostly Cloudy
Name: 5077, dtype: object
Inserting row 5079
Error inserting row 5079: tuple index out of range
Row data: Date/Time           7/30/2012 14:00
Temp_C                         29.3
Dew Point Temp_C               15.9
Rel Hum_%                        44
Wind Speed_km/h                  17
Visibility_km                  48.3
Press_kPa                    101.13
Weather                      Cloudy
Name: 5078, dtype: object
Inserting row 5080
Error inserting row 5080: tuple index out of range
Row data: Date/Time           7/30/2012 15:00
Temp_C                         29.0
Dew Point Temp_C               13.5
Rel Hum_%                        39
Wind Speed_km/h                  17
Visibility_km                  48.3
Press_kPa                     101.1
Weather                      Cloudy
Name: 5079, dtype: object
Inserting row 5081
Error inserting row 5081: tuple index out of range
Row data: Date/Time           7/30/2012 16:00
Temp_C                         29.9
Dew Point Temp_C               14.3
Rel Hum_%                        39
Wind Speed_km/h                   9
Visibility_km                  48.3
Press_kPa                    101.04
Weather                      Cloudy
Name: 5080, dtype: object
Inserting row 5082
Error inserting row 5082: tuple index out of range
Row data: Date/Time           7/30/2012 17:00
Temp_C                         29.4
Dew Point Temp_C               12.9
Rel Hum_%                        36
Wind Speed_km/h                   9
Visibility_km                  48.3
Press_kPa                    101.03
Weather                      Cloudy
Name: 5081, dtype: object
Inserting row 5083
Error inserting row 5083: tuple index out of range
Row data: Date/Time           7/30/2012 18:00
Temp_C                         28.2
Dew Point Temp_C               15.4
Rel Hum_%                        46
Wind Speed_km/h                  13
Visibility_km                  48.3
Press_kPa                    101.01
Weather                Mainly Clear
Name: 5082, dtype: object
Inserting row 5084
Error inserting row 5084: tuple index out of range
Row data: Date/Time           7/30/2012 19:00
Temp_C                         26.9
Dew Point Temp_C               16.4
Rel Hum_%                        53
Wind Speed_km/h                  11
Visibility_km                  48.3
Press_kPa                    101.01
Weather                Mainly Clear
Name: 5083, dtype: object
Inserting row 5085
Error inserting row 5085: tuple index out of range
Row data: Date/Time           7/30/2012 20:00
Temp_C                         25.2
Dew Point Temp_C               16.5
Rel Hum_%                        59
Wind Speed_km/h                   7
Visibility_km                  48.3
Press_kPa                    101.01
Weather                Mainly Clear
Name: 5084, dtype: object
Inserting row 5086
Error inserting row 5086: tuple index out of range
Row data: Date/Time           7/30/2012 21:00
Temp_C                         24.3
Dew Point Temp_C               16.9
Rel Hum_%                        63
Wind Speed_km/h                  11
Visibility_km                  25.0
Press_kPa                     101.0
Weather                       Clear
Name: 5085, dtype: object
Inserting row 5087
Error inserting row 5087: tuple index out of range
Row data: Date/Time           7/30/2012 22:00
Temp_C                         23.8
Dew Point Temp_C               17.6
Rel Hum_%                        68
Wind Speed_km/h                   9
Visibility_km                  25.0
Press_kPa                     101.0
Weather                       Clear
Name: 5086, dtype: object
Inserting row 5088
Error inserting row 5088: tuple index out of range
Row data: Date/Time           7/30/2012 23:00
Temp_C                         22.9
Dew Point Temp_C               17.7
Rel Hum_%                        73
Wind Speed_km/h                   6
Visibility_km                  25.0
Press_kPa                    101.02
Weather                Mainly Clear
Name: 5087, dtype: object
Inserting row 5089
Error inserting row 5089: tuple index out of range
Row data: Date/Time           7/31/2012 0:00
Temp_C                        22.2
Dew Point Temp_C              19.0
Rel Hum_%                       82
Wind Speed_km/h                  6
Visibility_km                 25.0
Press_kPa                   101.03
Weather               Mainly Clear
Name: 5088, dtype: object
Inserting row 5090
Error inserting row 5090: tuple index out of range
Row data: Date/Time           7/31/2012 1:00
Temp_C                        21.3
Dew Point Temp_C              18.0
Rel Hum_%                       81
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                   101.03
Weather               Mainly Clear
Name: 5089, dtype: object
Inserting row 5091
Error inserting row 5091: tuple index out of range
Row data: Date/Time           7/31/2012 2:00
Temp_C                        21.5
Dew Point Temp_C              16.6
Rel Hum_%                       74
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   101.02
Weather               Mainly Clear
Name: 5090, dtype: object
Inserting row 5092
Error inserting row 5092: tuple index out of range
Row data: Date/Time           7/31/2012 3:00
Temp_C                        20.1
Dew Point Temp_C              16.1
Rel Hum_%                       78
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   101.02
Weather                      Clear
Name: 5091, dtype: object
Inserting row 5093
Error inserting row 5093: tuple index out of range
Row data: Date/Time           7/31/2012 4:00
Temp_C                        19.4
Dew Point Temp_C              15.8
Rel Hum_%                       80
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                   101.03
Weather               Mainly Clear
Name: 5092, dtype: object
Inserting row 5094
Error inserting row 5094: tuple index out of range
Row data: Date/Time           7/31/2012 5:00
Temp_C                        19.8
Dew Point Temp_C              17.1
Rel Hum_%                       84
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   101.04
Weather               Mainly Clear
Name: 5093, dtype: object
Inserting row 5095
Error inserting row 5095: tuple index out of range
Row data: Date/Time           7/31/2012 6:00
Temp_C                        21.1
Dew Point Temp_C              17.7
Rel Hum_%                       81
Wind Speed_km/h                  7
Visibility_km                 48.3
Press_kPa                   101.05
Weather               Mainly Clear
Name: 5094, dtype: object
Inserting row 5096
Error inserting row 5096: tuple index out of range
Row data: Date/Time           7/31/2012 7:00
Temp_C                        22.6
Dew Point Temp_C              18.2
Rel Hum_%                       76
Wind Speed_km/h                  9
Visibility_km                 48.3
Press_kPa                   101.03
Weather                      Clear
Name: 5095, dtype: object
Inserting row 5097
Error inserting row 5097: tuple index out of range
Row data: Date/Time           7/31/2012 8:00
Temp_C                        24.2
Dew Point Temp_C              18.5
Rel Hum_%                       71
Wind Speed_km/h                  9
Visibility_km                 48.3
Press_kPa                   101.02
Weather                      Clear
Name: 5096, dtype: object
Inserting row 5098
Error inserting row 5098: tuple index out of range
Row data: Date/Time           7/31/2012 9:00
Temp_C                        25.9
Dew Point Temp_C              19.5
Rel Hum_%                       68
Wind Speed_km/h                  7
Visibility_km                 24.1
Press_kPa                   100.98
Weather               Mainly Clear
Name: 5097, dtype: object
Inserting row 5099
Error inserting row 5099: tuple index out of range
Row data: Date/Time           7/31/2012 10:00
Temp_C                         27.3
Dew Point Temp_C               19.8
Rel Hum_%                        64
Wind Speed_km/h                  11
Visibility_km                  24.1
Press_kPa                    100.97
Weather                Mainly Clear
Name: 5098, dtype: object
Inserting row 5100
Error inserting row 5100: tuple index out of range
Row data: Date/Time           7/31/2012 11:00
Temp_C                         28.4
Dew Point Temp_C               20.8
Rel Hum_%                        63
Wind Speed_km/h                  13
Visibility_km                  24.1
Press_kPa                    100.93
Weather                Mainly Clear
Name: 5099, dtype: object
Inserting row 5101
Error inserting row 5101: tuple index out of range
Row data: Date/Time           7/31/2012 12:00
Temp_C                         28.9
Dew Point Temp_C               20.7
Rel Hum_%                        61
Wind Speed_km/h                  19
Visibility_km                  24.1
Press_kPa                    100.87
Weather                Mainly Clear
Name: 5100, dtype: object
Inserting row 5102
Error inserting row 5102: tuple index out of range
Row data: Date/Time           7/31/2012 13:00
Temp_C                         28.7
Dew Point Temp_C               19.2
Rel Hum_%                        56
Wind Speed_km/h                  19
Visibility_km                  24.1
Press_kPa                    100.79
Weather                Mainly Clear
Name: 5101, dtype: object
Inserting row 5103
Error inserting row 5103: tuple index out of range
Row data: Date/Time           7/31/2012 14:00
Temp_C                         28.8
Dew Point Temp_C               18.4
Rel Hum_%                        53
Wind Speed_km/h                  20
Visibility_km                  24.1
Press_kPa                     100.7
Weather                Mainly Clear
Name: 5102, dtype: object
Inserting row 5104
Error inserting row 5104: tuple index out of range
Row data: Date/Time           7/31/2012 15:00
Temp_C                         28.8
Dew Point Temp_C               18.4
Rel Hum_%                        53
Wind Speed_km/h                  19
Visibility_km                  24.1
Press_kPa                    100.64
Weather                Mainly Clear
Name: 5103, dtype: object
Inserting row 5105
Error inserting row 5105: tuple index out of range
Row data: Date/Time           7/31/2012 16:00
Temp_C                         28.8
Dew Point Temp_C               19.1
Rel Hum_%                        56
Wind Speed_km/h                  22
Visibility_km                  24.1
Press_kPa                    100.58
Weather               Mostly Cloudy
Name: 5104, dtype: object
Inserting row 5106
Error inserting row 5106: tuple index out of range
Row data: Date/Time           7/31/2012 17:00
Temp_C                         28.0
Dew Point Temp_C               17.7
Rel Hum_%                        54
Wind Speed_km/h                  20
Visibility_km                  24.1
Press_kPa                    100.55
Weather               Mostly Cloudy
Name: 5105, dtype: object
Inserting row 5107
Error inserting row 5107: tuple index out of range
Row data: Date/Time           7/31/2012 18:00
Temp_C                         25.3
Dew Point Temp_C               19.3
Rel Hum_%                        69
Wind Speed_km/h                  17
Visibility_km                  24.1
Press_kPa                    100.53
Weather               Mostly Cloudy
Name: 5106, dtype: object
Inserting row 5108
Error inserting row 5108: tuple index out of range
Row data: Date/Time           7/31/2012 19:00
Temp_C                         24.8
Dew Point Temp_C               18.3
Rel Hum_%                        67
Wind Speed_km/h                  22
Visibility_km                  24.1
Press_kPa                    100.55
Weather                Rain Showers
Name: 5107, dtype: object
Inserting row 5109
Error inserting row 5109: tuple index out of range
Row data: Date/Time                          7/31/2012 20:00
Temp_C                                        22.4
Dew Point Temp_C                              18.7
Rel Hum_%                                       80
Wind Speed_km/h                                 35
Visibility_km                                  9.7
Press_kPa                                   100.64
Weather             Thunderstorms,Rain Showers,Fog
Name: 5108, dtype: object
Inserting row 5110
Error inserting row 5110: tuple index out of range
Row data: Date/Time                      7/31/2012 21:00
Temp_C                                    22.8
Dew Point Temp_C                          18.8
Rel Hum_%                                   78
Wind Speed_km/h                             13
Visibility_km                             25.0
Press_kPa                               100.65
Weather             Thunderstorms,Rain Showers
Name: 5109, dtype: object
Inserting row 5111
Error inserting row 5111: tuple index out of range
Row data: Date/Time           7/31/2012 22:00
Temp_C                         22.8
Dew Point Temp_C               19.4
Rel Hum_%                        81
Wind Speed_km/h                   7
Visibility_km                  25.0
Press_kPa                    100.57
Weather               Mostly Cloudy
Name: 5110, dtype: object
Inserting row 5112
Error inserting row 5112: tuple index out of range
Row data: Date/Time           7/31/2012 23:00
Temp_C                         21.8
Dew Point Temp_C               19.2
Rel Hum_%                        85
Wind Speed_km/h                   4
Visibility_km                  25.0
Press_kPa                    100.52
Weather                Mainly Clear
Name: 5111, dtype: object
Inserting row 5113
Error inserting row 5113: tuple index out of range
Row data: Date/Time           8/1/2012 0:00
Temp_C                       21.0
Dew Point Temp_C             19.8
Rel Hum_%                      93
Wind Speed_km/h                 0
Visibility_km                25.0
Press_kPa                  100.53
Weather              Mainly Clear
Name: 5112, dtype: object
Inserting row 5114
Error inserting row 5114: tuple index out of range
Row data: Date/Time           8/1/2012 1:00
Temp_C                       21.0
Dew Point Temp_C             19.6
Rel Hum_%                      92
Wind Speed_km/h                 4
Visibility_km                25.0
Press_kPa                  100.54
Weather                     Clear
Name: 5113, dtype: object
Inserting row 5115
Error inserting row 5115: tuple index out of range
Row data: Date/Time           8/1/2012 2:00
Temp_C                       21.3
Dew Point Temp_C             19.1
Rel Hum_%                      87
Wind Speed_km/h                 9
Visibility_km                25.0
Press_kPa                  100.55
Weather             Mostly Cloudy
Name: 5114, dtype: object
Inserting row 5116
Error inserting row 5116: tuple index out of range
Row data: Date/Time           8/1/2012 3:00
Temp_C                       20.8
Dew Point Temp_C             19.0
Rel Hum_%                      89
Wind Speed_km/h                 9
Visibility_km                25.0
Press_kPa                  100.54
Weather                    Cloudy
Name: 5115, dtype: object
Inserting row 5117
Error inserting row 5117: tuple index out of range
Row data: Date/Time           8/1/2012 4:00
Temp_C                       20.8
Dew Point Temp_C             18.7
Rel Hum_%                      88
Wind Speed_km/h                 6
Visibility_km                25.0
Press_kPa                  100.57
Weather             Mostly Cloudy
Name: 5116, dtype: object
Inserting row 5118
Error inserting row 5118: tuple index out of range
Row data: Date/Time           8/1/2012 5:00
Temp_C                       20.8
Dew Point Temp_C             18.1
Rel Hum_%                      85
Wind Speed_km/h                 9
Visibility_km                25.0
Press_kPa                  100.58
Weather                    Cloudy
Name: 5117, dtype: object
Inserting row 5119
Error inserting row 5119: tuple index out of range
Row data: Date/Time           8/1/2012 6:00
Temp_C                       20.4
Dew Point Temp_C             18.6
Rel Hum_%                      89
Wind Speed_km/h                 7
Visibility_km                25.0
Press_kPa                  100.62
Weather              Rain Showers
Name: 5118, dtype: object
Inserting row 5120
Error inserting row 5120: tuple index out of range
Row data: Date/Time           8/1/2012 7:00
Temp_C                       20.8
Dew Point Temp_C             18.7
Rel Hum_%                      88
Wind Speed_km/h                11
Visibility_km                24.1
Press_kPa                  100.64
Weather                    Cloudy
Name: 5119, dtype: object
Inserting row 5121
Error inserting row 5121: tuple index out of range
Row data: Date/Time           8/1/2012 8:00
Temp_C                       21.2
Dew Point Temp_C             18.9
Rel Hum_%                      87
Wind Speed_km/h                 9
Visibility_km                24.1
Press_kPa                  100.65
Weather                    Cloudy
Name: 5120, dtype: object
Inserting row 5122

Row data: Date/Time           8/8/2012 14:00
Temp_C                        28.0
Dew Point Temp_C              15.6
Rel Hum_%                       47
Wind Speed_km/h                 11
Visibility_km                 24.1
Press_kPa                   100.98
Weather               Mainly Clear
Name: 5294, dtype: object
Inserting row 5296
Error inserting row 5296: tuple index out of range
Row data: Date/Time           8/8/2012 15:00
Temp_C                        28.3
Dew Point Temp_C              14.7
Rel Hum_%                       43
Wind Speed_km/h                  7
Visibility_km                 24.1
Press_kPa                   100.94
Weather              Mostly Cloudy
Name: 5295, dtype: object
Inserting row 5297
Error inserting row 5297: tuple index out of range
Row data: Date/Time           8/8/2012 16:00
Temp_C                        28.0
Dew Point Temp_C              16.1
Rel Hum_%                       48
Wind Speed_km/h                  9
Visibility_km                 24.1
Press_kPa                   100.92
Weather              Mostly Cloudy
Name: 5296, dtype: object
Inserting row 5298
Error inserting row 5298: tuple index out of range
Row data: Date/Time           8/8/2012 17:00
Temp_C                        24.8
Dew Point Temp_C              17.1
Rel Hum_%                       62
Wind Speed_km/h                 19
Visibility_km                 24.1
Press_kPa                   100.91
Weather              Mostly Cloudy
Name: 5297, dtype: object
Inserting row 5299
Error inserting row 5299: tuple index out of range
Row data: Date/Time           8/8/2012 18:00
Temp_C                        25.1
Dew Point Temp_C              16.8
Rel Hum_%                       60
Wind Speed_km/h                  9
Visibility_km                 24.1
Press_kPa                    100.9
Weather              Mostly Cloudy
Name: 5298, dtype: object
Inserting row 5300
Error inserting row 5300: tuple index out of range
Row data: Date/Time           8/8/2012 19:00
Temp_C                        25.1
Dew Point Temp_C              17.0
Rel Hum_%                       61
Wind Speed_km/h                  7
Visibility_km                 24.1
Press_kPa                    100.9
Weather               Rain Showers
Name: 5299, dtype: object
Inserting row 5301
Error inserting row 5301: tuple index out of range
Row data: Date/Time           8/8/2012 20:00
Temp_C                        24.3
Dew Point Temp_C              17.2
Rel Hum_%                       65
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   100.92
Weather               Rain Showers
Name: 5300, dtype: object
Inserting row 5302
Error inserting row 5302: tuple index out of range
Row data: Date/Time           8/8/2012 21:00
Temp_C                        23.0
Dew Point Temp_C              17.8
Rel Hum_%                       73
Wind Speed_km/h                  6
Visibility_km                 25.0
Press_kPa                   100.93
Weather              Mostly Cloudy
Name: 5301, dtype: object
Inserting row 5303
Error inserting row 5303: tuple index out of range
Row data: Date/Time           8/8/2012 22:00
Temp_C                        23.5
Dew Point Temp_C              17.1
Rel Hum_%                       67
Wind Speed_km/h                  4
Visibility_km                 25.0
Press_kPa                   100.89
Weather              Mostly Cloudy
Name: 5302, dtype: object
Inserting row 5304
Error inserting row 5304: tuple index out of range
Row data: Date/Time           8/8/2012 23:00
Temp_C                        23.1
Dew Point Temp_C              17.0
Rel Hum_%                       69
Wind Speed_km/h                  6
Visibility_km                 25.0
Press_kPa                   100.92
Weather              Mostly Cloudy
Name: 5303, dtype: object
Inserting row 5305
Error inserting row 5305: tuple index out of range
Row data: Date/Time           8/9/2012 0:00
Temp_C                       22.8
Dew Point Temp_C             17.7
Rel Hum_%                      73
Wind Speed_km/h                 9
Visibility_km                25.0
Press_kPa                  100.93
Weather              Mainly Clear
Name: 5304, dtype: object
Inserting row 5306
Error inserting row 5306: tuple index out of range
Row data: Date/Time           8/9/2012 1:00
Temp_C                       22.8
Dew Point Temp_C             16.7
Rel Hum_%                      68
Wind Speed_km/h                11
Visibility_km                25.0
Press_kPa                  100.89
Weather             Mostly Cloudy
Name: 5305, dtype: object
Inserting row 5307
Error inserting row 5307: tuple index out of range
Row data: Date/Time           8/9/2012 2:00
Temp_C                       22.4
Dew Point Temp_C             16.7
Rel Hum_%                      70
Wind Speed_km/h                 4
Visibility_km                25.0
Press_kPa                  100.91
Weather                    Cloudy
Name: 5306, dtype: object
Inserting row 5308
Error inserting row 5308: tuple index out of range
Row data: Date/Time           8/9/2012 3:00
Temp_C                       21.8
Dew Point Temp_C             17.4
Rel Hum_%                      76
Wind Speed_km/h                 9
Visibility_km                25.0
Press_kPa                  100.89
Weather                    Cloudy
Name: 5307, dtype: object
Inserting row 5309
Error inserting row 5309: tuple index out of range
Row data: Date/Time           8/9/2012 4:00
Temp_C                       21.4
Dew Point Temp_C             17.4
Rel Hum_%                      78
Wind Speed_km/h                11
Visibility_km                25.0
Press_kPa                   100.9
Weather             Mostly Cloudy
Name: 5308, dtype: object
Inserting row 5310
Error inserting row 5310: tuple index out of range
Row data: Date/Time           8/9/2012 5:00
Temp_C                       21.1
Dew Point Temp_C             16.9
Rel Hum_%                      77
Wind Speed_km/h                13
Visibility_km                24.1
Press_kPa                  100.93
Weather                    Cloudy
Name: 5309, dtype: object
Inserting row 5311
Error inserting row 5311: tuple index out of range
Row data: Date/Time           8/9/2012 6:00
Temp_C                       20.9
Dew Point Temp_C             17.0
Rel Hum_%                      78
Wind Speed_km/h                15
Visibility_km                24.1
Press_kPa                  100.98
Weather                    Cloudy
Name: 5310, dtype: object
Inserting row 5312
Error inserting row 5312: tuple index out of range
Row data: Date/Time           8/9/2012 7:00
Temp_C                       20.7
Dew Point Temp_C             17.3
Rel Hum_%                      81
Wind Speed_km/h                13
Visibility_km                24.1
Press_kPa                  101.01
Weather                    Cloudy
Name: 5311, dtype: object
Inserting row 5313
Error inserting row 5313: tuple index out of range
Row data: Date/Time           8/9/2012 8:00
Temp_C                       21.1
Dew Point Temp_C             17.5
Rel Hum_%                      80
Wind Speed_km/h                19
Visibility_km                24.1
Press_kPa                  101.01
Weather                    Cloudy
Name: 5312, dtype: object
Inserting row 5314
Error inserting row 5314: tuple index out of range
Row data: Date/Time           8/9/2012 9:00
Temp_C                       21.7
Dew Point Temp_C             17.5
Rel Hum_%                      77
Wind Speed_km/h                22
Visibility_km                24.1
Press_kPa                  100.98
Weather                    Cloudy
Name: 5313, dtype: object
Inserting row 5315
Error inserting row 5315: tuple index out of range
Row data: Date/Time           8/9/2012 10:00
Temp_C                        21.7
Dew Point Temp_C              17.0
Rel Hum_%                       75
Wind Speed_km/h                 17
Visibility_km                 24.1
Press_kPa                   100.98
Weather                     Cloudy
Name: 5314, dtype: object
Inserting row 5316
Error inserting row 5316: tuple index out of range
Row data: Date/Time           8/9/2012 11:00
Temp_C                        23.2
Dew Point Temp_C              17.3
Rel Hum_%                       69
Wind Speed_km/h                 13
Visibility_km                 24.1
Press_kPa                   100.98
Weather                     Cloudy
Name: 5315, dtype: object
Inserting row 5317
Error inserting row 5317: tuple index out of range
Row data: Date/Time           8/9/2012 12:00
Temp_C                        24.2
Dew Point Temp_C              17.8
Rel Hum_%                       67
Wind Speed_km/h                 17
Visibility_km                 24.1
Press_kPa                   100.92
Weather                     Cloudy
Name: 5316, dtype: object
Inserting row 5318
Error inserting row 5318: tuple index out of range
Row data: Date/Time           8/9/2012 13:00
Temp_C                        23.6
Dew Point Temp_C              17.4
Rel Hum_%                       68
Wind Speed_km/h                 19
Visibility_km                 24.1
Press_kPa                   100.94
Weather                     Cloudy
Name: 5317, dtype: object
Inserting row 5319
Error inserting row 5319: tuple index out of range
Row data: Date/Time           8/9/2012 14:00
Temp_C                        24.0
Dew Point Temp_C              17.8
Rel Hum_%                       68
Wind Speed_km/h                 20
Visibility_km                 24.1
Press_kPa                   100.86
Weather               Rain Showers
Name: 5318, dtype: object
Inserting row 5320
Error inserting row 5320: tuple index out of range
Row data: Date/Time           8/9/2012 15:00
Temp_C                        23.7
Dew Point Temp_C              17.0
Rel Hum_%                       66
Wind Speed_km/h                 17
Visibility_km                 16.1
Press_kPa                   100.91
Weather               Rain Showers
Name: 5319, dtype: object
Inserting row 5321
Error inserting row 5321: tuple index out of range
Row data: Date/Time           8/9/2012 16:00
Temp_C                        22.3
Dew Point Temp_C              18.7
Rel Hum_%                       80
Wind Speed_km/h                 19
Visibility_km                 19.3
Press_kPa                   100.89
Weather                       Rain
Name: 5320, dtype: object
Inserting row 5322
Error inserting row 5322: tuple index out of range
Row data: Date/Time           8/9/2012 17:00
Temp_C                        21.3
Dew Point Temp_C              18.7
Rel Hum_%                       85
Wind Speed_km/h                 17
Visibility_km                 12.9
Press_kPa                   100.93
Weather                       Rain
Name: 5321, dtype: object
Inserting row 5323
Error inserting row 5323: tuple index out of range
Row data: Date/Time           8/9/2012 18:00
Temp_C                        20.4
Dew Point Temp_C              18.6
Rel Hum_%                       89
Wind Speed_km/h                 20
Visibility_km                 16.1
Press_kPa                   100.87
Weather                       Rain
Name: 5322, dtype: object
Inserting row 5324
Error inserting row 5324: tuple index out of range
Row data: Date/Time           8/9/2012 19:00
Temp_C                        20.2
Dew Point Temp_C              18.2
Rel Hum_%                       88
Wind Speed_km/h                 13
Visibility_km                 19.3
Press_kPa                   100.92
Weather                       Rain
Name: 5323, dtype: object
Inserting row 5325
Error inserting row 5325: tuple index out of range
Row data: Date/Time           8/9/2012 20:00
Temp_C                        20.2
Dew Point Temp_C              17.7
Rel Hum_%                       86
Wind Speed_km/h                 15
Visibility_km                 25.0
Press_kPa                   100.88
Weather                     Cloudy
Name: 5324, dtype: object
Inserting row 5326
Error inserting row 5326: tuple index out of range
Row data: Date/Time           8/9/2012 21:00
Temp_C                        19.9
Dew Point Temp_C              17.5
Rel Hum_%                       86
Wind Speed_km/h                 19
Visibility_km                 25.0
Press_kPa                   100.87
Weather                     Cloudy
Name: 5325, dtype: object
Inserting row 5327
Error inserting row 5327: tuple index out of range
Row data: Date/Time           8/9/2012 22:00
Temp_C                        20.1
Dew Point Temp_C              17.0
Rel Hum_%                       82
Wind Speed_km/h                 19
Visibility_km                 25.0
Press_kPa                   100.83
Weather                     Cloudy
Name: 5326, dtype: object
Inserting row 5328
Error inserting row 5328: tuple index out of range
Row data: Date/Time           8/9/2012 23:00
Temp_C                        19.8
Dew Point Temp_C              17.0
Rel Hum_%                       84
Wind Speed_km/h                 20
Visibility_km                 25.0
Press_kPa                   100.77
Weather                     Cloudy
Name: 5327, dtype: object
Inserting row 5329
Error inserting row 5329: tuple index out of range
Row data: Date/Time           8/10/2012 0:00
Temp_C                        19.5
Dew Point Temp_C              17.0
Rel Hum_%                       85
Wind Speed_km/h                 17
Visibility_km                 25.0
Press_kPa                   100.74
Weather                     Cloudy
Name: 5328, dtype: object
Inserting row 5330
Error inserting row 5330: tuple index out of range
Row data: Date/Time           8/10/2012 1:00
Temp_C                        19.3
Dew Point Temp_C              16.8
Rel Hum_%                       85
Wind Speed_km/h                 19
Visibility_km                 25.0
Press_kPa                   100.68
Weather                     Cloudy
Name: 5329, dtype: object
Inserting row 5331
Error inserting row 5331: tuple index out of range
Row data: Date/Time           8/10/2012 2:00
Temp_C                        20.1
Dew Point Temp_C              17.0
Rel Hum_%                       82
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   100.66
Weather                     Cloudy
Name: 5330, dtype: object
Inserting row 5332
Error inserting row 5332: tuple index out of range
Row data: Date/Time           8/10/2012 3:00
Temp_C                        19.7
Dew Point Temp_C              17.3
Rel Hum_%                       86
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   100.65
Weather                     Cloudy
Name: 5331, dtype: object
Inserting row 5333
Error inserting row 5333: tuple index out of range
Row data: Date/Time           8/10/2012 4:00
Temp_C                        19.3
Dew Point Temp_C              17.6
Rel Hum_%                       90
Wind Speed_km/h                  9
Visibility_km                  9.7
Press_kPa                   100.67
Weather                       Rain
Name: 5332, dtype: object
Inserting row 5334
Error inserting row 5334: tuple index out of range
Row data: Date/Time           8/10/2012 5:00
Temp_C                        19.0
Dew Point Temp_C              17.7
Rel Hum_%                       92
Wind Speed_km/h                 19
Visibility_km                 12.9
Press_kPa                   100.58
Weather                       Rain
Name: 5333, dtype: object
Inserting row 5335
Error inserting row 5335: tuple index out of range
Row data: Date/Time           8/10/2012 6:00
Temp_C                        19.0
Dew Point Temp_C              17.7
Rel Hum_%                       92
Wind Speed_km/h                  9
Visibility_km                 16.1
Press_kPa                   100.69
Weather                     Cloudy
Name: 5334, dtype: object
Inserting row 5336
Error inserting row 5336: tuple index out of range
Row data: Date/Time           8/10/2012 7:00
Temp_C                        19.7
Dew Point Temp_C              18.2
Rel Hum_%                       91
Wind Speed_km/h                  7
Visibility_km                 12.9
Press_kPa                   100.66
Weather                     Cloudy
Name: 5335, dtype: object
Inserting row 5337
Error inserting row 5337: tuple index out of range
Row data: Date/Time           8/10/2012 8:00
Temp_C                        20.8
Dew Point Temp_C              18.9
Rel Hum_%                       89
Wind Speed_km/h                  9
Visibility_km                 12.9
Press_kPa                   100.69
Weather                     Cloudy
Name: 5336, dtype: object
Inserting row 5338
Error inserting row 5338: tuple index out of range
Row data: Date/Time           8/10/2012 9:00
Temp_C                        20.2
Dew Point Temp_C              18.6
Rel Hum_%                       91
Wind Speed_km/h                 13
Visibility_km                 11.3
Press_kPa                    100.7
Weather                     Cloudy
Name: 5337, dtype: object
Inserting row 5339
Error inserting row 5339: tuple index out of range
Row data: Date/Time           8/10/2012 10:00
Temp_C                         20.2
Dew Point Temp_C               18.5
Rel Hum_%                        90
Wind Speed_km/h                  11
Visibility_km                  11.3
Press_kPa                    100.75
Weather                      Cloudy
Name: 5338, dtype: object
Inserting row 5340
Error inserting row 5340: tuple index out of range
Row data: Date/Time           8/10/2012 11:00
Temp_C                         19.9
Dew Point Temp_C               18.5
Rel Hum_%                        92
Wind Speed_km/h                  15
Visibility_km                   6.4
Press_kPa                    100.73
Weather                         Fog
Name: 5339, dtype: object
Inserting row 5341
Error inserting row 5341: tuple index out of range
Row data: Date/Time           8/10/2012 12:00
Temp_C                         20.8
Dew Point Temp_C               18.8
Rel Hum_%                        88
Wind Speed_km/h                  17
Visibility_km                   6.4
Press_kPa                    100.73
Weather                         Fog
Name: 5340, dtype: object
Inserting row 5342
Error inserting row 5342: tuple index out of range
Row data: Date/Time           8/10/2012 13:00
Temp_C                         21.3
Dew Point Temp_C               19.2
Rel Hum_%                        88
Wind Speed_km/h                  19
Visibility_km                   6.4
Press_kPa                     100.7
Weather                    Rain,Fog
Name: 5341, dtype: object
Inserting row 5343
Error inserting row 5343: tuple index out of range
Row data: Date/Time           8/10/2012 14:00
Temp_C                         21.7
Dew Point Temp_C               19.3
Rel Hum_%                        86
Wind Speed_km/h                  19
Visibility_km                   8.0
Press_kPa                    100.64
Weather                    Rain,Fog
Name: 5342, dtype: object
Inserting row 5344
Error inserting row 5344: tuple index out of range
Row data: Date/Time           8/10/2012 15:00
Temp_C                         21.0
Dew Point Temp_C               19.5
Rel Hum_%                        91
Wind Speed_km/h                  20
Visibility_km                   6.4
Press_kPa                    100.63
Weather                    Rain,Fog
Name: 5343, dtype: object
Inserting row 5345
Error inserting row 5345: tuple index out of range
Row data: Date/Time           8/10/2012 16:00
Temp_C                         20.7
Dew Point Temp_C               19.0
Rel Hum_%                        90
Wind Speed_km/h                  20
Visibility_km                   8.0
Press_kPa                    100.65
Weather                    Rain,Fog
Name: 5344, dtype: object
Inserting row 5346
Error inserting row 5346: tuple index out of range
Row data: Date/Time           8/10/2012 17:00
Temp_C                         20.6
Dew Point Temp_C               19.0
Rel Hum_%                        91
Wind Speed_km/h                  20
Visibility_km                   8.0
Press_kPa                    100.63
Weather                    Rain,Fog
Name: 5345, dtype: object

Row data: Date/Time           8/20/2012 3:00
Temp_C                        15.6
Dew Point Temp_C              13.3
Rel Hum_%                       86
Wind Speed_km/h                  0
Visibility_km                 25.0
Press_kPa                   100.75
Weather               Mainly Clear
Name: 5571, dtype: object
Inserting row 5573
Error inserting row 5573: tuple index out of range
Row data: Date/Time           8/20/2012 4:00
Temp_C                        15.3
Dew Point Temp_C              13.2
Rel Hum_%                       87
Wind Speed_km/h                  0
Visibility_km                 25.0
Press_kPa                   100.72
Weather               Mainly Clear
Name: 5572, dtype: object
Inserting row 5574
Error inserting row 5574: tuple index out of range
Row data: Date/Time           8/20/2012 5:00
Temp_C                        14.5
Dew Point Temp_C              13.4
Rel Hum_%                       93
Wind Speed_km/h                  0
Visibility_km                 25.0
Press_kPa                   100.72
Weather               Mainly Clear
Name: 5573, dtype: object
Inserting row 5575
Error inserting row 5575: tuple index out of range
Row data: Date/Time           8/20/2012 6:00
Temp_C                        16.0
Dew Point Temp_C              12.8
Rel Hum_%                       81
Wind Speed_km/h                  6
Visibility_km                 48.3
Press_kPa                   100.76
Weather               Mainly Clear
Name: 5574, dtype: object
Inserting row 5576
Error inserting row 5576: tuple index out of range
Row data: Date/Time           8/20/2012 7:00
Temp_C                        17.8
Dew Point Temp_C              13.6
Rel Hum_%                       76
Wind Speed_km/h                  7
Visibility_km                 48.3
Press_kPa                   100.77
Weather               Mainly Clear
Name: 5575, dtype: object
Inserting row 5577
Error inserting row 5577: tuple index out of range
Row data: Date/Time           8/20/2012 8:00
Temp_C                        19.0
Dew Point Temp_C              14.4
Rel Hum_%                       75
Wind Speed_km/h                 11
Visibility_km                 48.3
Press_kPa                   100.76
Weather               Mainly Clear
Name: 5576, dtype: object
Inserting row 5578
Error inserting row 5578: tuple index out of range
Row data: Date/Time           8/20/2012 9:00
Temp_C                        20.2
Dew Point Temp_C              13.9
Rel Hum_%                       67
Wind Speed_km/h                 11
Visibility_km                 48.3
Press_kPa                   100.78
Weather                      Clear
Name: 5577, dtype: object
Inserting row 5579
Error inserting row 5579: tuple index out of range
Row data: Date/Time           8/20/2012 10:00
Temp_C                         21.6
Dew Point Temp_C               14.2
Rel Hum_%                        63
Wind Speed_km/h                  17
Visibility_km                  48.3
Press_kPa                    100.77
Weather               Mostly Cloudy
Name: 5578, dtype: object
Inserting row 5580
Error inserting row 5580: tuple index out of range
Row data: Date/Time           8/20/2012 11:00
Temp_C                         23.1
Dew Point Temp_C               15.7
Rel Hum_%                        63
Wind Speed_km/h                  13
Visibility_km                  48.3
Press_kPa                    100.74
Weather                Mainly Clear
Name: 5579, dtype: object
Inserting row 5581
Error inserting row 5581: tuple index out of range
Row data: Date/Time           8/20/2012 12:00
Temp_C                         24.8
Dew Point Temp_C               13.5
Rel Hum_%                        49
Wind Speed_km/h                  17
Visibility_km                  24.1
Press_kPa                    100.69
Weather                Mainly Clear
Name: 5580, dtype: object
Inserting row 5582
Error inserting row 5582: tuple index out of range
Row data: Date/Time           8/20/2012 13:00
Temp_C                         24.6
Dew Point Temp_C               13.2
Rel Hum_%                        49
Wind Speed_km/h                  17
Visibility_km                  24.1
Press_kPa                    100.64
Weather                Mainly Clear
Name: 5581, dtype: object
Inserting row 5583
Error inserting row 5583: tuple index out of range
Row data: Date/Time           8/20/2012 14:00
Temp_C                         25.2
Dew Point Temp_C               11.7
Rel Hum_%                        43
Wind Speed_km/h                  11
Visibility_km                  24.1
Press_kPa                    100.62
Weather                Mainly Clear
Name: 5582, dtype: object
Inserting row 5584
Error inserting row 5584: tuple index out of range
Row data: Date/Time           8/20/2012 15:00
Temp_C                         24.6
Dew Point Temp_C               10.5
Rel Hum_%                        41
Wind Speed_km/h                  15
Visibility_km                  24.1
Press_kPa                     100.6
Weather                Mainly Clear
Name: 5583, dtype: object
Inserting row 5585
Error inserting row 5585: tuple index out of range
Row data: Date/Time           8/20/2012 16:00
Temp_C                         24.4
Dew Point Temp_C               10.4
Rel Hum_%                        41
Wind Speed_km/h                  13
Visibility_km                  24.1
Press_kPa                    100.56
Weather                       Clear
Name: 5584, dtype: object
Inserting row 5586
Error inserting row 5586: tuple index out of range
Row data: Date/Time           8/20/2012 17:00
Temp_C                         23.8
Dew Point Temp_C               10.6
Rel Hum_%                        43
Wind Speed_km/h                  13
Visibility_km                  24.1
Press_kPa                    100.57
Weather                Mainly Clear
Name: 5585, dtype: object
Inserting row 5587
Error inserting row 5587: tuple index out of range
Row data: Date/Time           8/20/2012 18:00
Temp_C                         22.5
Dew Point Temp_C               10.0
Rel Hum_%                        45
Wind Speed_km/h                  17
Visibility_km                  24.1
Press_kPa                    100.64
Weather                Mainly Clear
Name: 5586, dtype: object
Inserting row 5588
Error inserting row 5588: tuple index out of range
Row data: Date/Time           8/20/2012 19:00
Temp_C                         20.1
Dew Point Temp_C                9.0
Rel Hum_%                        49
Wind Speed_km/h                   9
Visibility_km                  24.1
Press_kPa                    100.69
Weather                Mainly Clear
Name: 5587, dtype: object
Inserting row 5589
Error inserting row 5589: tuple index out of range
Row data: Date/Time           8/20/2012 20:00
Temp_C                         18.4
Dew Point Temp_C                9.4
Rel Hum_%                        56
Wind Speed_km/h                   9
Visibility_km                  25.0
Press_kPa                    100.75
Weather                       Clear
Name: 5588, dtype: object
Inserting row 5590
Error inserting row 5590: tuple index out of range
Row data: Date/Time           8/20/2012 21:00
Temp_C                         18.2
Dew Point Temp_C                9.9
Rel Hum_%                        58
Wind Speed_km/h                   7
Visibility_km                  25.0
Press_kPa                    100.77
Weather                Mainly Clear
Name: 5589, dtype: object
Inserting row 5591
Error inserting row 5591: tuple index out of range
Row data: Date/Time           8/20/2012 22:00
Temp_C                         18.5
Dew Point Temp_C               10.0
Rel Hum_%                        58
Wind Speed_km/h                   7
Visibility_km                  25.0
Press_kPa                    100.78
Weather                Mainly Clear
Name: 5590, dtype: object
Inserting row 5592
Error inserting row 5592: tuple index out of range
Row data: Date/Time           8/20/2012 23:00
Temp_C                         16.6
Dew Point Temp_C               10.8
Rel Hum_%                        69
Wind Speed_km/h                   6
Visibility_km                  25.0
Press_kPa                     100.8
Weather                Mainly Clear
Name: 5591, dtype: object
Inserting row 5593
Error inserting row 5593: tuple index out of range
Row data: Date/Time           8/21/2012 0:00
Temp_C                        16.5
Dew Point Temp_C              10.4
Rel Hum_%                       67
Wind Speed_km/h                  4
Visibility_km                 25.0
Press_kPa                   100.82
Weather               Mainly Clear
Name: 5592, dtype: object
Inserting row 5594
Error inserting row 5594: tuple index out of range
Row data: Date/Time           8/21/2012 1:00
Temp_C                        15.0
Dew Point Temp_C              10.8
Rel Hum_%                       76
Wind Speed_km/h                  4
Visibility_km                 25.0
Press_kPa                   100.85
Weather               Mainly Clear
Name: 5593, dtype: object
Inserting row 5595
Error inserting row 5595: tuple index out of range
Row data: Date/Time           8/21/2012 2:00
Temp_C                        15.9
Dew Point Temp_C              11.0
Rel Hum_%                       73
Wind Speed_km/h                  0
Visibility_km                 25.0
Press_kPa                    100.9
Weather              Mostly Cloudy
Name: 5594, dtype: object
Inserting row 5596
Error inserting row 5596: tuple index out of range
Row data: Date/Time           8/21/2012 3:00
Temp_C                        15.9
Dew Point Temp_C              11.3
Rel Hum_%                       74
Wind Speed_km/h                  0
Visibility_km                 25.0
Press_kPa                   100.92
Weather              Mostly Cloudy
Name: 5595, dtype: object
Inserting row 5597
Error inserting row 5597: tuple index out of range
Row data: Date/Time           8/21/2012 4:00
Temp_C                        16.1
Dew Point Temp_C              11.0
Rel Hum_%                       72
Wind Speed_km/h                  6
Visibility_km                 25.0
Press_kPa                   100.93
Weather               Mainly Clear
Name: 5596, dtype: object
Inserting row 5598
Error inserting row 5598: tuple index out of range
Row data: Date/Time           8/21/2012 5:00
Temp_C                        15.0
Dew Point Temp_C              10.3
Rel Hum_%                       73
Wind Speed_km/h                  0
Visibility_km                 24.1
Press_kPa                   100.99
Weather               Mainly Clear
Name: 5597, dtype: object
Inserting row 5599
Error inserting row 5599: tuple index out of range
Row data: Date/Time           8/21/2012 6:00
Temp_C                        14.6
Dew Point Temp_C              10.9
Rel Hum_%                       78
Wind Speed_km/h                  7
Visibility_km                 48.3
Press_kPa                   101.02
Weather               Mainly Clear
Name: 5598, dtype: object
Inserting row 5600
Error inserting row 5600: tuple index out of range
Row data: Date/Time           8/21/2012 7:00
Temp_C                        17.2
Dew Point Temp_C              12.6
Rel Hum_%                       74
Wind Speed_km/h                  6
Visibility_km                 48.3
Press_kPa                   101.08
Weather               Mainly Clear
Name: 5599, dtype: object
Inserting row 5601
Error inserting row 5601: tuple index out of range
Row data: Date/Time           8/21/2012 8:00
Temp_C                        19.3
Dew Point Temp_C              11.8
Rel Hum_%                       62
Wind Speed_km/h                  7
Visibility_km                 48.3
Press_kPa                   101.12
Weather              Mostly Cloudy
Name: 5600, dtype: object
Inserting row 5602
Error inserting row 5602: tuple index out of range
Row data: Date/Time           8/21/2012 9:00
Temp_C                        20.4
Dew Point Temp_C               9.1
Rel Hum_%                       48
Wind Speed_km/h                 13
Visibility_km                 48.3
Press_kPa                   101.15
Weather              Mostly Cloudy
Name: 5601, dtype: object
Inserting row 5603
Error inserting row 5603: tuple index out of range
Row data: Date/Time           8/21/2012 10:00
Temp_C                         21.8
Dew Point Temp_C               10.9
Rel Hum_%                        50
Wind Speed_km/h                  13
Visibility_km                  48.3
Press_kPa                    101.18
Weather                Mainly Clear
Name: 5602, dtype: object
Inserting row 5604
Error inserting row 5604: tuple index out of range
Row data: Date/Time           8/21/2012 11:00
Temp_C                         21.1
Dew Point Temp_C                9.6
Rel Hum_%                        48
Wind Speed_km/h                  11
Visibility_km                  48.3
Press_kPa                    101.17
Weather                Mainly Clear
Name: 5603, dtype: object
Inserting row 5605
Error inserting row 5605: tuple index out of range
Row data: Date/Time           8/21/2012 12:00
Temp_C                         23.7
Dew Point Temp_C               10.4
Rel Hum_%                        43
Wind Speed_km/h                  17
Visibility_km                  48.3
Press_kPa                    101.19
Weather                Mainly Clear
Name: 5604, dtype: object
Inserting row 5606
Error inserting row 5606: tuple index out of range
Row data: Date/Time           8/21/2012 13:00
Temp_C                         23.2
Dew Point Temp_C               10.3
Rel Hum_%                        44
Wind Speed_km/h                  22
Visibility_km                  48.3
Press_kPa                    101.19
Weather               Mostly Cloudy
Name: 5605, dtype: object
Inserting row 5607
Error inserting row 5607: tuple index out of range
Row data: Date/Time           8/21/2012 14:00
Temp_C                         22.6
Dew Point Temp_C               10.9
Rel Hum_%                        48
Wind Speed_km/h                  15
Visibility_km                  48.3
Press_kPa                    101.18
Weather               Mostly Cloudy
Name: 5606, dtype: object
Inserting row 5608
Error inserting row 5608: tuple index out of range
Row data: Date/Time           8/21/2012 15:00
Temp_C                         23.4
Dew Point Temp_C               11.4
Rel Hum_%                        47
Wind Speed_km/h                  19
Visibility_km                  48.3
Press_kPa                    101.15
Weather               Mostly Cloudy
Name: 5607, dtype: object
Inserting row 5609
Error inserting row 5609: tuple index out of range
Row data: Date/Time           8/21/2012 16:00
Temp_C                         23.1
Dew Point Temp_C               11.9
Rel Hum_%                        49
Wind Speed_km/h                  17
Visibility_km                  48.3
Press_kPa                    101.14
Weather               Mostly Cloudy
Name: 5608, dtype: object
Inserting row 5610
Error inserting row 5610: tuple index out of range
Row data: Date/Time           8/21/2012 17:00
Temp_C                         22.6
Dew Point Temp_C               10.9
Rel Hum_%                        48
Wind Speed_km/h                  19
Visibility_km                  48.3
Press_kPa                    101.17
Weather               Mostly Cloudy
Name: 5609, dtype: object
Inserting row 5611
Error inserting row 5611: tuple index out of range
Row data: Date/Time           8/21/2012 18:00
Temp_C                         22.4
Dew Point Temp_C               10.8
Rel Hum_%                        48
Wind Speed_km/h                  13
Visibility_km                  48.3
Press_kPa                    101.18
Weather               Mostly Cloudy
Name: 5610, dtype: object
Inserting row 5612
Error inserting row 5612: tuple index out of range
Row data: Date/Time           8/21/2012 19:00
Temp_C                         22.1
Dew Point Temp_C               11.7
Rel Hum_%                        52
Wind Speed_km/h                   7
Visibility_km                  48.3
Press_kPa                    101.21
Weather               Mostly Cloudy
Name: 5611, dtype: object
Inserting row 5613
Error inserting row 5613: tuple index out of range
Row data: Date/Time           8/21/2012 20:00
Temp_C                         21.5
Dew Point Temp_C               10.7
Rel Hum_%                        50
Wind Speed_km/h                   6
Visibility_km                  25.0
Press_kPa                    101.25
Weather                Mainly Clear
Name: 5612, dtype: object
Inserting row 5614
Error inserting row 5614: tuple index out of range
Row data: Date/Time           8/21/2012 21:00
Temp_C                         19.2
Dew Point Temp_C               12.9
Rel Hum_%                        67
Wind Speed_km/h                  20
Visibility_km                  24.1
Press_kPa                    101.36
Weather               Mostly Cloudy
Name: 5613, dtype: object
Inserting row 5615
Error inserting row 5615: tuple index out of range
Row data: Date/Time           8/21/2012 22:00
Temp_C                         18.5
Dew Point Temp_C               13.3
Rel Hum_%                        72
Wind Speed_km/h                   6
Visibility_km                  25.0
Press_kPa                    101.33
Weather               Mostly Cloudy
Name: 5614, dtype: object
Inserting row 5616
Error inserting row 5616: tuple index out of range
Row data: Date/Time           8/21/2012 23:00
Temp_C                         18.1
Dew Point Temp_C               13.6
Rel Hum_%                        75
Wind Speed_km/h                   4
Visibility_km                  25.0
Press_kPa                    101.34
Weather               Mostly Cloudy
Name: 5615, dtype: object
Inserting row 5617
Error inserting row 5617: tuple index out of range
Row data: Date/Time           8/22/2012 0:00
Temp_C                        19.0
Dew Point Temp_C              14.6
Rel Hum_%                       76
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   101.34
Weather              Mostly Cloudy
Name: 5616, dtype: object
Inserting row 5618
Error inserting row 5618: tuple index out of range
Row data: Date/Time           8/22/2012 1:00
Temp_C                        18.6
Dew Point Temp_C              14.7
Rel Hum_%                       78
Wind Speed_km/h                 15
Visibility_km                 25.0
Press_kPa                   101.33
Weather               Rain Showers
Name: 5617, dtype: object
Inserting row 5619
Error inserting row 5619: tuple index out of range
Row data: Date/Time           8/22/2012 2:00
Temp_C                        18.8
Dew Point Temp_C              13.8
Rel Hum_%                       73
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   101.35
Weather              Mostly Cloudy
Name: 5618, dtype: object
Inserting row 5620
Error inserting row 5620: tuple index out of range
Row data: Date/Time           8/22/2012 3:00
Temp_C                        18.8
Dew Point Temp_C              12.0
Rel Hum_%                       65
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   101.38
Weather                     Cloudy
Name: 5619, dtype: object
Inserting row 5621
Error inserting row 5621: tuple index out of range
Row data: Date/Time           8/22/2012 4:00
Temp_C                        18.6
Dew Point Temp_C              12.1
Rel Hum_%                       66
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                   101.39
Weather                     Cloudy
Name: 5620, dtype: object
Inserting row 5622
Error inserting row 5622: tuple index out of range
Row data: Date/Time           8/22/2012 5:00
Temp_C                        18.0
Dew Point Temp_C              12.4
Rel Hum_%                       70
Wind Speed_km/h                  7
Visibility_km                 48.3
Press_kPa                   101.41
Weather               Mainly Clear
Name: 5621, dtype: object
Inserting row 5623
Error inserting row 5623: tuple index out of range
Row data: Date/Time           8/22/2012 6:00
Temp_C                        17.6

Row data: Date/Time           8/31/2012 14:00
Temp_C                         24.1
Dew Point Temp_C               18.2
Rel Hum_%                        70
Wind Speed_km/h                  22
Visibility_km                  24.1
Press_kPa                    100.38
Weather                      Cloudy
Name: 5846, dtype: object
Inserting row 5848
Error inserting row 5848: tuple index out of range
Row data: Date/Time           8/31/2012 15:00
Temp_C                         25.6
Dew Point Temp_C               18.6
Rel Hum_%                        65
Wind Speed_km/h                  30
Visibility_km                  24.1
Press_kPa                    100.35
Weather               Mostly Cloudy
Name: 5847, dtype: object
Inserting row 5849
Error inserting row 5849: tuple index out of range
Row data: Date/Time           8/31/2012 16:00
Temp_C                         24.8
Dew Point Temp_C               18.5
Rel Hum_%                        68
Wind Speed_km/h                  20
Visibility_km                  24.1
Press_kPa                    100.38
Weather               Mostly Cloudy
Name: 5848, dtype: object
Inserting row 5850
Error inserting row 5850: tuple index out of range
Row data: Date/Time           8/31/2012 17:00
Temp_C                         25.0
Dew Point Temp_C               18.4
Rel Hum_%                        67
Wind Speed_km/h                  17
Visibility_km                  24.1
Press_kPa                    100.41
Weather               Mostly Cloudy
Name: 5849, dtype: object
Inserting row 5851
Error inserting row 5851: tuple index out of range
Row data: Date/Time           8/31/2012 18:00
Temp_C                         24.2
Dew Point Temp_C               18.6
Rel Hum_%                        71
Wind Speed_km/h                  13
Visibility_km                  24.1
Press_kPa                    100.47
Weather               Mostly Cloudy
Name: 5850, dtype: object
Inserting row 5852
Error inserting row 5852: tuple index out of range
Row data: Date/Time           8/31/2012 19:00
Temp_C                         23.1
Dew Point Temp_C               18.9
Rel Hum_%                        77
Wind Speed_km/h                   9
Visibility_km                  25.0
Press_kPa                    100.52
Weather                Mainly Clear
Name: 5851, dtype: object
Inserting row 5853
Error inserting row 5853: tuple index out of range
Row data: Date/Time           8/31/2012 20:00
Temp_C                         22.3
Dew Point Temp_C               19.1
Rel Hum_%                        82
Wind Speed_km/h                  11
Visibility_km                  25.0
Press_kPa                    100.61
Weather                Mainly Clear
Name: 5852, dtype: object
Inserting row 5854
Error inserting row 5854: tuple index out of range
Row data: Date/Time           8/31/2012 21:00
Temp_C                         21.6
Dew Point Temp_C               19.0
Rel Hum_%                        85
Wind Speed_km/h                  11
Visibility_km                  25.0
Press_kPa                    100.65
Weather                Mainly Clear
Name: 5853, dtype: object
Inserting row 5855
Error inserting row 5855: tuple index out of range
Row data: Date/Time           8/31/2012 22:00
Temp_C                         21.7
Dew Point Temp_C               16.9
Rel Hum_%                        74
Wind Speed_km/h                  20
Visibility_km                  25.0
Press_kPa                    100.78
Weather                Mainly Clear
Name: 5854, dtype: object
Inserting row 5856
Error inserting row 5856: tuple index out of range
Row data: Date/Time           8/31/2012 23:00
Temp_C                         20.8
Dew Point Temp_C               12.9
Rel Hum_%                        61
Wind Speed_km/h                  11
Visibility_km                  25.0
Press_kPa                    100.84
Weather                       Clear
Name: 5855, dtype: object
Inserting row 5857
Error inserting row 5857: tuple index out of range
Row data: Date/Time           9/1/2012 0:00
Temp_C                       19.6
Dew Point Temp_C             13.1
Rel Hum_%                      66
Wind Speed_km/h                11
Visibility_km                25.0
Press_kPa                  100.94
Weather              Mainly Clear
Name: 5856, dtype: object
Inserting row 5858
Error inserting row 5858: tuple index out of range
Row data: Date/Time           9/1/2012 1:00
Temp_C                       19.1
Dew Point Temp_C             12.5
Rel Hum_%                      66
Wind Speed_km/h                 4
Visibility_km                25.0
Press_kPa                   101.0
Weather              Mainly Clear
Name: 5857, dtype: object
Inserting row 5859
Error inserting row 5859: tuple index out of range
Row data: Date/Time           9/1/2012 2:00
Temp_C                       19.1
Dew Point Temp_C             12.6
Rel Hum_%                      66
Wind Speed_km/h                 9
Visibility_km                25.0
Press_kPa                  101.05
Weather              Mainly Clear
Name: 5858, dtype: object
Inserting row 5860
Error inserting row 5860: tuple index out of range
Row data: Date/Time           9/1/2012 3:00
Temp_C                       17.7
Dew Point Temp_C             12.8
Rel Hum_%                      73
Wind Speed_km/h                11
Visibility_km                25.0
Press_kPa                  101.13
Weather              Mainly Clear
Name: 5859, dtype: object
Inserting row 5861
Error inserting row 5861: tuple index out of range
Row data: Date/Time           9/1/2012 4:00
Temp_C                       16.3
Dew Point Temp_C             12.8
Rel Hum_%                      80
Wind Speed_km/h                11
Visibility_km                25.0
Press_kPa                  101.21
Weather                     Clear
Name: 5860, dtype: object
Inserting row 5862
Error inserting row 5862: tuple index out of range
Row data: Date/Time           9/1/2012 5:00
Temp_C                       16.0
Dew Point Temp_C             12.9
Rel Hum_%                      82
Wind Speed_km/h                13
Visibility_km                25.0
Press_kPa                  101.31
Weather              Mainly Clear
Name: 5861, dtype: object
Inserting row 5863
Error inserting row 5863: tuple index out of range
Row data: Date/Time           9/1/2012 6:00
Temp_C                       16.2
Dew Point Temp_C             12.5
Rel Hum_%                      79
Wind Speed_km/h                13
Visibility_km                48.3
Press_kPa                  101.41
Weather              Mainly Clear
Name: 5862, dtype: object
Inserting row 5864
Error inserting row 5864: tuple index out of range
Row data: Date/Time           9/1/2012 7:00
Temp_C                       17.8
Dew Point Temp_C             10.6
Rel Hum_%                      63
Wind Speed_km/h                24
Visibility_km                48.3
Press_kPa                  101.48
Weather              Mainly Clear
Name: 5863, dtype: object
Inserting row 5865
Error inserting row 5865: tuple index out of range
Row data: Date/Time           9/1/2012 8:00
Temp_C                       18.6
Dew Point Temp_C              9.5
Rel Hum_%                      55
Wind Speed_km/h                20
Visibility_km                48.3
Press_kPa                  101.54
Weather              Mainly Clear
Name: 5864, dtype: object
Inserting row 5866
Error inserting row 5866: tuple index out of range
Row data: Date/Time           9/1/2012 9:00
Temp_C                       20.4
Dew Point Temp_C              8.8
Rel Hum_%                      47
Wind Speed_km/h                15
Visibility_km                48.3
Press_kPa                  101.59
Weather                     Clear
Name: 5865, dtype: object
Inserting row 5867
Error inserting row 5867: tuple index out of range
Row data: Date/Time           9/1/2012 10:00
Temp_C                        22.0
Dew Point Temp_C               8.5
Rel Hum_%                       42
Wind Speed_km/h                 20
Visibility_km                 48.3
Press_kPa                    101.6
Weather                      Clear
Name: 5866, dtype: object
Inserting row 5868
Error inserting row 5868: tuple index out of range
Row data: Date/Time           9/1/2012 11:00
Temp_C                        22.7
Dew Point Temp_C               6.2
Rel Hum_%                       34
Wind Speed_km/h                 15
Visibility_km                 48.3
Press_kPa                    101.6
Weather               Mainly Clear
Name: 5867, dtype: object
Inserting row 5869
Error inserting row 5869: tuple index out of range
Row data: Date/Time           9/1/2012 12:00
Temp_C                        23.2
Dew Point Temp_C               7.0
Rel Hum_%                       35
Wind Speed_km/h                 13
Visibility_km                 48.3
Press_kPa                   101.57
Weather                      Clear
Name: 5868, dtype: object
Inserting row 5870
Error inserting row 5870: tuple index out of range
Row data: Date/Time           9/1/2012 13:00
Temp_C                        23.6
Dew Point Temp_C               7.0
Rel Hum_%                       34
Wind Speed_km/h                  6
Visibility_km                 48.3
Press_kPa                   101.54
Weather                      Clear
Name: 5869, dtype: object
Inserting row 5871
Error inserting row 5871: tuple index out of range
Row data: Date/Time           9/1/2012 14:00
Temp_C                        23.5
Dew Point Temp_C               6.7
Rel Hum_%                       34
Wind Speed_km/h                  7
Visibility_km                 48.3
Press_kPa                   101.47
Weather                      Clear
Name: 5870, dtype: object
Inserting row 5872
Error inserting row 5872: tuple index out of range
Row data: Date/Time           9/1/2012 15:00
Temp_C                        24.3
Dew Point Temp_C               7.3
Rel Hum_%                       34
Wind Speed_km/h                  7
Visibility_km                 48.3
Press_kPa                   101.44
Weather                      Clear
Name: 5871, dtype: object
Inserting row 5873
Error inserting row 5873: tuple index out of range
Row data: Date/Time           9/1/2012 16:00
Temp_C                        24.2
Dew Point Temp_C               7.0
Rel Hum_%                       33
Wind Speed_km/h                  4
Visibility_km                 48.3
Press_kPa                   101.43
Weather                      Clear
Name: 5872, dtype: object
Inserting row 5874
Error inserting row 5874: tuple index out of range
Row data: Date/Time           9/1/2012 17:00
Temp_C                        24.0
Dew Point Temp_C               6.6
Rel Hum_%                       33
Wind Speed_km/h                  7
Visibility_km                 48.3
Press_kPa                   101.39
Weather                      Clear
Name: 5873, dtype: object
Inserting row 5875
Error inserting row 5875: tuple index out of range
Row data: Date/Time           9/1/2012 18:00
Temp_C                        22.7
Dew Point Temp_C               8.4
Rel Hum_%                       40
Wind Speed_km/h                  9
Visibility_km                 48.3
Press_kPa                   101.41
Weather                      Clear
Name: 5874, dtype: object
Inserting row 5876
Error inserting row 5876: tuple index out of range
Row data: Date/Time           9/1/2012 19:00
Temp_C                        20.9
Dew Point Temp_C               8.3
Rel Hum_%                       44
Wind Speed_km/h                  6
Visibility_km                 48.3
Press_kPa                   101.45
Weather                      Clear
Name: 5875, dtype: object
Inserting row 5877
Error inserting row 5877: tuple index out of range
Row data: Date/Time           9/1/2012 20:00
Temp_C                        18.8
Dew Point Temp_C               9.9
Rel Hum_%                       56
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   101.46
Weather                      Clear
Name: 5876, dtype: object
Inserting row 5878
Error inserting row 5878: tuple index out of range
Row data: Date/Time           9/1/2012 21:00
Temp_C                        18.5
Dew Point Temp_C               7.6
Rel Hum_%                       49
Wind Speed_km/h                  7
Visibility_km                 25.0
Press_kPa                   101.47
Weather                      Clear
Name: 5877, dtype: object
Inserting row 5879
Error inserting row 5879: tuple index out of range
Row data: Date/Time           9/1/2012 22:00
Temp_C                        17.5
Dew Point Temp_C               9.2
Rel Hum_%                       58
Wind Speed_km/h                  6
Visibility_km                 25.0
Press_kPa                   101.46
Weather                      Clear
Name: 5878, dtype: object
Inserting row 5880
Error inserting row 5880: tuple index out of range
Row data: Date/Time           9/1/2012 23:00
Temp_C                        17.0
Dew Point Temp_C               9.1
Rel Hum_%                       60
Wind Speed_km/h                  7
Visibility_km                 25.0
Press_kPa                   101.45
Weather               Mainly Clear
Name: 5879, dtype: object
Inserting row 5881
Error inserting row 5881: tuple index out of range
Row data: Date/Time           9/2/2012 0:00
Temp_C                       16.1
Dew Point Temp_C              9.0
Rel Hum_%                      63
Wind Speed_km/h                 4
Visibility_km                25.0
Press_kPa                  101.47
Weather                     Clear
Name: 5880, dtype: object
Inserting row 5882
Error inserting row 5882: tuple index out of range
Row data: Date/Time           9/2/2012 1:00
Temp_C                       14.0
Dew Point Temp_C              9.3
Rel Hum_%                      73
Wind Speed_km/h                 4
Visibility_km                25.0
Press_kPa                  101.47
Weather                     Clear
Name: 5881, dtype: object
Inserting row 5883
Error inserting row 5883: tuple index out of range
Row data: Date/Time           9/2/2012 2:00
Temp_C                       13.5
Dew Point Temp_C              9.5
Rel Hum_%                      77
Wind Speed_km/h                 4
Visibility_km                25.0
Press_kPa                  101.47
Weather                     Clear
Name: 5882, dtype: object
Inserting row 5884
Error inserting row 5884: tuple index out of range
Row data: Date/Time           9/2/2012 3:00
Temp_C                       13.0
Dew Point Temp_C              9.5
Rel Hum_%                      79
Wind Speed_km/h                 0
Visibility_km                25.0
Press_kPa                  101.43
Weather              Mainly Clear
Name: 5883, dtype: object
Inserting row 5885
Error inserting row 5885: tuple index out of range
Row data: Date/Time           9/2/2012 4:00
Temp_C                       13.3
Dew Point Temp_C              9.7
Rel Hum_%                      79
Wind Speed_km/h                 0
Visibility_km                25.0
Press_kPa                  101.41
Weather              Mainly Clear
Name: 5884, dtype: object
Inserting row 5886
Error inserting row 5886: tuple index out of range
Row data: Date/Time           9/2/2012 5:00
Temp_C                       14.2
Dew Point Temp_C             10.2
Rel Hum_%                      77
Wind Speed_km/h                 6
Visibility_km                25.0
Press_kPa                  101.43
Weather              Mainly Clear
Name: 5885, dtype: object
Inserting row 5887
Error inserting row 5887: tuple index out of range
Row data: Date/Time           9/2/2012 6:00
Temp_C                       13.0
Dew Point Temp_C             10.8
Rel Hum_%                      86
Wind Speed_km/h                 7
Visibility_km                24.1
Press_kPa                  101.48
Weather              Mainly Clear
Name: 5886, dtype: object
Inserting row 5888
Error inserting row 5888: tuple index out of range
Row data: Date/Time           9/2/2012 7:00
Temp_C                       15.5
Dew Point Temp_C             11.6
Rel Hum_%                      78
Wind Speed_km/h                 4
Visibility_km                48.3
Press_kPa                  101.49
Weather              Mainly Clear
Name: 5887, dtype: object
Inserting row 5889
Error inserting row 5889: tuple index out of range
Row data: Date/Time           9/2/2012 8:00
Temp_C                       17.3
Dew Point Temp_C             11.7
Rel Hum_%                      70
Wind Speed_km/h                 7
Visibility_km                48.3
Press_kPa                  101.51
Weather             Mostly Cloudy
Name: 5888, dtype: object
Inserting row 5890
Error inserting row 5890: tuple index out of range
Row data: Date/Time           9/2/2012 9:00
Temp_C                       19.1
Dew Point Temp_C             11.5
Rel Hum_%                      61
Wind Speed_km/h                 4
Visibility_km                48.3
Press_kPa                  101.52
Weather             Mostly Cloudy
Name: 5889, dtype: object
Inserting row 5891
Error inserting row 5891: tuple index out of range
Row data: Date/Time           9/2/2012 10:00
Temp_C                        20.7
Dew Point Temp_C              11.4
Rel Hum_%                       55
Wind Speed_km/h                  6
Visibility_km                 48.3
Press_kPa                   101.53
Weather              Mostly Cloudy
Name: 5890, dtype: object
Inserting row 5892
Error inserting row 5892: tuple index out of range
Row data: Date/Time           9/2/2012 11:00
Temp_C                        21.8
Dew Point Temp_C              10.3
Rel Hum_%                       48
Wind Speed_km/h                  4
Visibility_km                 48.3
Press_kPa                   101.52
Weather              Mostly Cloudy
Name: 5891, dtype: object
Inserting row 5893
Error inserting row 5893: tuple index out of range
Row data: Date/Time           9/2/2012 12:00
Temp_C                        24.4
Dew Point Temp_C               8.8
Rel Hum_%                       37
Wind Speed_km/h                  4
Visibility_km                 48.3
Press_kPa                   101.49
Weather               Mainly Clear
Name: 5892, dtype: object
Inserting row 5894
Error inserting row 5894: tuple index out of range
Row data: Date/Time           9/2/2012 13:00
Temp_C                        25.5
Dew Point Temp_C               7.0
Rel Hum_%                       31
Wind Speed_km/h                  9
Visibility_km                 48.3
Press_kPa                   101.47
Weather               Mainly Clear
Name: 5893, dtype: object
Inserting row 5895
Error inserting row 5895: tuple index out of range
Row data: Date/Time           9/2/2012 14:00
Temp_C                        25.3
Dew Point Temp_C               7.4
Rel Hum_%                       32
Wind Speed_km/h                  9
Visibility_km                 48.3
Press_kPa                   101.45
Weather               Mainly Clear
Name: 5894, dtype: object
Inserting row 5896
Error inserting row 5896: tuple index out of range
Row data: Date/Time           9/2/2012 15:00
Temp_C                        25.6
Dew Point Temp_C               6.5
Rel Hum_%                       29
Wind Speed_km/h                  7
Visibility_km                 48.3
Press_kPa                   101.41
Weather               Mainly Clear
Name: 5895, dtype: object
Inserting row 5897
Error inserting row 5897: tuple index out of range
Row data: Date/Time           9/2/2012 16:00
Temp_C                        25.4
Dew Point Temp_C               6.0
Rel Hum_%                       29
Wind Speed_km/h                 11
Visibility_km                 48.3
Press_kPa                   101.43
Weather               Mainly Clear
Name: 5896, dtype: object
Inserting row 5898
Error inserting row 5898: tuple index out of range
Row data: Date/Time           9/2/2012 17:00
Temp_C                        23.6
Dew Point Temp_C               6.9
Rel Hum_%                       34
Wind Speed_km/h                  9
Visibility_km                 48.3
Press_kPa                   101.44
Weather               Mainly Clear
Name: 5897, dtype: object
Inserting row 5899
Error inserting row 5899: tuple index out of range

Row data: Date/Time           9/11/2012 23:00
Temp_C                         17.8
Dew Point Temp_C               11.9
Rel Hum_%                        68
Wind Speed_km/h                  15
Visibility_km                  25.0
Press_kPa                     101.8
Weather                       Clear
Name: 6119, dtype: object
Inserting row 6121
Error inserting row 6121: tuple index out of range
Row data: Date/Time           9/12/2012 0:00
Temp_C                        17.5
Dew Point Temp_C              10.6
Rel Hum_%                       64
Wind Speed_km/h                 17
Visibility_km                 25.0
Press_kPa                   101.82
Weather                      Clear
Name: 6120, dtype: object
Inserting row 6122
Error inserting row 6122: tuple index out of range
Row data: Date/Time           9/12/2012 1:00
Temp_C                        17.2
Dew Point Temp_C               9.9
Rel Hum_%                       62
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   101.85
Weather                      Clear
Name: 6121, dtype: object
Inserting row 6123
Error inserting row 6123: tuple index out of range
Row data: Date/Time           9/12/2012 2:00
Temp_C                        14.5
Dew Point Temp_C               9.6
Rel Hum_%                       72
Wind Speed_km/h                  6
Visibility_km                 25.0
Press_kPa                   101.86
Weather                      Clear
Name: 6122, dtype: object
Inserting row 6124
Error inserting row 6124: tuple index out of range
Row data: Date/Time           9/12/2012 3:00
Temp_C                        13.2
Dew Point Temp_C               9.9
Rel Hum_%                       80
Wind Speed_km/h                  4
Visibility_km                 25.0
Press_kPa                    101.9
Weather                      Clear
Name: 6123, dtype: object
Inserting row 6125
Error inserting row 6125: tuple index out of range
Row data: Date/Time           9/12/2012 4:00
Temp_C                        13.7
Dew Point Temp_C              10.0
Rel Hum_%                       78
Wind Speed_km/h                  0
Visibility_km                 25.0
Press_kPa                   101.91
Weather                      Clear
Name: 6124, dtype: object
Inserting row 6126
Error inserting row 6126: tuple index out of range
Row data: Date/Time           9/12/2012 5:00
Temp_C                        13.1
Dew Point Temp_C              10.7
Rel Hum_%                       85
Wind Speed_km/h                  6
Visibility_km                 25.0
Press_kPa                   101.96
Weather                      Clear
Name: 6125, dtype: object
Inserting row 6127
Error inserting row 6127: tuple index out of range
Row data: Date/Time           9/12/2012 6:00
Temp_C                        13.5
Dew Point Temp_C              11.2
Rel Hum_%                       86
Wind Speed_km/h                  0
Visibility_km                 48.3
Press_kPa                   102.02
Weather                      Clear
Name: 6126, dtype: object
Inserting row 6128
Error inserting row 6128: tuple index out of range
Row data: Date/Time           9/12/2012 7:00
Temp_C                        15.8
Dew Point Temp_C              11.8
Rel Hum_%                       77
Wind Speed_km/h                  9
Visibility_km                 48.3
Press_kPa                   102.02
Weather                      Clear
Name: 6127, dtype: object
Inserting row 6129
Error inserting row 6129: tuple index out of range
Row data: Date/Time           9/12/2012 8:00
Temp_C                        17.4
Dew Point Temp_C              11.1
Rel Hum_%                       66
Wind Speed_km/h                  7
Visibility_km                 48.3
Press_kPa                   102.04
Weather                      Clear
Name: 6128, dtype: object
Inserting row 6130
Error inserting row 6130: tuple index out of range
Row data: Date/Time           9/12/2012 9:00
Temp_C                        19.6
Dew Point Temp_C              11.9
Rel Hum_%                       61
Wind Speed_km/h                  7
Visibility_km                 48.3
Press_kPa                   102.05
Weather                      Clear
Name: 6129, dtype: object
Inserting row 6131
Error inserting row 6131: tuple index out of range
Row data: Date/Time           9/12/2012 10:00
Temp_C                         21.9
Dew Point Temp_C               13.2
Rel Hum_%                        58
Wind Speed_km/h                  11
Visibility_km                  48.3
Press_kPa                    102.02
Weather                Mainly Clear
Name: 6130, dtype: object
Inserting row 6132
Error inserting row 6132: tuple index out of range
Row data: Date/Time           9/12/2012 11:00
Temp_C                         23.9
Dew Point Temp_C               13.3
Rel Hum_%                        51
Wind Speed_km/h                  20
Visibility_km                  48.3
Press_kPa                    101.98
Weather                       Clear
Name: 6131, dtype: object
Inserting row 6133
Error inserting row 6133: tuple index out of range
Row data: Date/Time           9/12/2012 12:00
Temp_C                         25.3
Dew Point Temp_C               13.4
Rel Hum_%                        48
Wind Speed_km/h                  19
Visibility_km                  48.3
Press_kPa                    101.95
Weather                Mainly Clear
Name: 6132, dtype: object
Inserting row 6134
Error inserting row 6134: tuple index out of range
Row data: Date/Time           9/12/2012 13:00
Temp_C                         26.1
Dew Point Temp_C               14.0
Rel Hum_%                        47
Wind Speed_km/h                  13
Visibility_km                  48.3
Press_kPa                    101.87
Weather                Mainly Clear
Name: 6133, dtype: object
Inserting row 6135
Error inserting row 6135: tuple index out of range
Row data: Date/Time           9/12/2012 14:00
Temp_C                         26.9
Dew Point Temp_C               13.5
Rel Hum_%                        44
Wind Speed_km/h                  17
Visibility_km                  48.3
Press_kPa                    101.84
Weather                Mainly Clear
Name: 6134, dtype: object
Inserting row 6136
Error inserting row 6136: tuple index out of range
Row data: Date/Time           9/12/2012 15:00
Temp_C                         27.3
Dew Point Temp_C               13.4
Rel Hum_%                        42
Wind Speed_km/h                  17
Visibility_km                  48.3
Press_kPa                     101.8
Weather                Mainly Clear
Name: 6135, dtype: object
Inserting row 6137
Error inserting row 6137: tuple index out of range
Row data: Date/Time           9/12/2012 16:00
Temp_C                         27.3
Dew Point Temp_C               12.2
Rel Hum_%                        39
Wind Speed_km/h                  19
Visibility_km                  48.3
Press_kPa                    101.77
Weather                Mainly Clear
Name: 6136, dtype: object
Inserting row 6138
Error inserting row 6138: tuple index out of range
Row data: Date/Time           9/12/2012 17:00
Temp_C                         26.8
Dew Point Temp_C               11.6
Rel Hum_%                        39
Wind Speed_km/h                  17
Visibility_km                  48.3
Press_kPa                    101.77
Weather                Mainly Clear
Name: 6137, dtype: object
Inserting row 6139
Error inserting row 6139: tuple index out of range
Row data: Date/Time           9/12/2012 18:00
Temp_C                         25.0
Dew Point Temp_C               12.9
Rel Hum_%                        47
Wind Speed_km/h                  11
Visibility_km                  48.3
Press_kPa                    101.78
Weather                Mainly Clear
Name: 6138, dtype: object
Inserting row 6140
Error inserting row 6140: tuple index out of range
Row data: Date/Time           9/12/2012 19:00
Temp_C                         22.2
Dew Point Temp_C               15.0
Rel Hum_%                        64
Wind Speed_km/h                  11
Visibility_km                  25.0
Press_kPa                    101.83
Weather                Mainly Clear
Name: 6139, dtype: object
Inserting row 6141
Error inserting row 6141: tuple index out of range
Row data: Date/Time           9/12/2012 20:00
Temp_C                         22.4
Dew Point Temp_C               14.0
Rel Hum_%                        59
Wind Speed_km/h                  11
Visibility_km                  25.0
Press_kPa                    101.88
Weather                Mainly Clear
Name: 6140, dtype: object
Inserting row 6142
Error inserting row 6142: tuple index out of range
Row data: Date/Time           9/12/2012 21:00
Temp_C                         22.2
Dew Point Temp_C               13.2
Rel Hum_%                        57
Wind Speed_km/h                  11
Visibility_km                  25.0
Press_kPa                    101.91
Weather                       Clear
Name: 6141, dtype: object
Inserting row 6143
Error inserting row 6143: tuple index out of range
Row data: Date/Time           9/12/2012 22:00
Temp_C                         21.0
Dew Point Temp_C               14.4
Rel Hum_%                        66
Wind Speed_km/h                  13
Visibility_km                  25.0
Press_kPa                    101.95
Weather                Mainly Clear
Name: 6142, dtype: object
Inserting row 6144
Error inserting row 6144: tuple index out of range
Row data: Date/Time           9/12/2012 23:00
Temp_C                         20.2
Dew Point Temp_C               14.6
Rel Hum_%                        70
Wind Speed_km/h                  11
Visibility_km                  25.0
Press_kPa                    101.96
Weather                Mainly Clear
Name: 6143, dtype: object
Inserting row 6145
Error inserting row 6145: tuple index out of range
Row data: Date/Time           9/13/2012 0:00
Temp_C                        19.8
Dew Point Temp_C              13.6
Rel Hum_%                       67
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                   101.96
Weather               Mainly Clear
Name: 6144, dtype: object
Inserting row 6146
Error inserting row 6146: tuple index out of range
Row data: Date/Time           9/13/2012 1:00
Temp_C                        19.5
Dew Point Temp_C              13.4
Rel Hum_%                       68
Wind Speed_km/h                  7
Visibility_km                 25.0
Press_kPa                   101.97
Weather               Mainly Clear
Name: 6145, dtype: object
Inserting row 6147
Error inserting row 6147: tuple index out of range
Row data: Date/Time           9/13/2012 2:00
Temp_C                        16.3
Dew Point Temp_C              12.9
Rel Hum_%                       80
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   101.98
Weather               Mainly Clear
Name: 6146, dtype: object
Inserting row 6148
Error inserting row 6148: tuple index out of range
Row data: Date/Time           9/13/2012 3:00
Temp_C                        15.7
Dew Point Temp_C              13.1
Rel Hum_%                       85
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                   101.96
Weather                      Clear
Name: 6147, dtype: object
Inserting row 6149
Error inserting row 6149: tuple index out of range
Row data: Date/Time           9/13/2012 4:00
Temp_C                        15.5
Dew Point Temp_C              12.8
Rel Hum_%                       84
Wind Speed_km/h                 11
Visibility_km                 25.0
Press_kPa                   101.96
Weather                      Clear
Name: 6148, dtype: object
Inserting row 6150
Error inserting row 6150: tuple index out of range
Row data: Date/Time           9/13/2012 5:00
Temp_C                        14.9
Dew Point Temp_C              11.8
Rel Hum_%                       82
Wind Speed_km/h                  4
Visibility_km                 25.0
Press_kPa                    102.0
Weather                      Clear
Name: 6149, dtype: object
Inserting row 6151
Error inserting row 6151: tuple index out of range
Row data: Date/Time           9/13/2012 6:00
Temp_C                        15.7
Dew Point Temp_C              12.4
Rel Hum_%                       81
Wind Speed_km/h                  6
Visibility_km                 48.3
Press_kPa                   102.02
Weather               Mainly Clear
Name: 6150, dtype: object
Inserting row 6152
Error inserting row 6152: tuple index out of range
Row data: Date/Time           9/13/2012 7:00
Temp_C                        18.1
Dew Point Temp_C              13.8
Rel Hum_%                       76
Wind Speed_km/h                  6
Visibility_km                 48.3
Press_kPa                   102.03
Weather               Mainly Clear
Name: 6151, dtype: object
Inserting row 6153
Error inserting row 6153: tuple index out of range
Row data: Date/Time           9/13/2012 8:00
Temp_C                        19.8
Dew Point Temp_C              12.8
Rel Hum_%                       64
Wind Speed_km/h                  9
Visibility_km                 48.3
Press_kPa                   102.04
Weather               Mainly Clear
Name: 6152, dtype: object
Inserting row 6154
Error inserting row 6154: tuple index out of range
Row data: Date/Time           9/13/2012 9:00
Temp_C                        21.5
Dew Point Temp_C              13.7
Rel Hum_%                       61
Wind Speed_km/h                 13
Visibility_km                 48.3
Press_kPa                   102.05
Weather               Mainly Clear
Name: 6153, dtype: object
Inserting row 6155
Error inserting row 6155: tuple index out of range
Row data: Date/Time           9/13/2012 10:00
Temp_C                         22.6
Dew Point Temp_C               14.2
Rel Hum_%                        59
Wind Speed_km/h                  17
Visibility_km                  48.3
Press_kPa                    102.05
Weather                Mainly Clear
Name: 6154, dtype: object
Inserting row 6156
Error inserting row 6156: tuple index out of range
Row data: Date/Time           9/13/2012 11:00
Temp_C                         24.6
Dew Point Temp_C               14.8
Rel Hum_%                        54
Wind Speed_km/h                  15
Visibility_km                  48.3
Press_kPa                    102.02
Weather                Mainly Clear
Name: 6155, dtype: object
Inserting row 6157
Error inserting row 6157: tuple index out of range
Row data: Date/Time           9/13/2012 12:00
Temp_C                         26.2
Dew Point Temp_C               14.9
Rel Hum_%                        50
Wind Speed_km/h                  17
Visibility_km                  48.3
Press_kPa                    101.97
Weather                Mainly Clear
Name: 6156, dtype: object
Inserting row 6158
Error inserting row 6158: tuple index out of range
Row data: Date/Time           9/13/2012 13:00
Temp_C                         27.3
Dew Point Temp_C               14.2
Rel Hum_%                        45
Wind Speed_km/h                  19
Visibility_km                  48.3
Press_kPa                    101.89
Weather                Mainly Clear
Name: 6157, dtype: object
Inserting row 6159
Error inserting row 6159: tuple index out of range
Row data: Date/Time           9/13/2012 14:00
Temp_C                         27.9
Dew Point Temp_C               13.7
Rel Hum_%                        42
Wind Speed_km/h                  24
Visibility_km                  48.3
Press_kPa                    101.82
Weather                Mainly Clear
Name: 6158, dtype: object
Inserting row 6160
Error inserting row 6160: tuple index out of range
Row data: Date/Time           9/13/2012 15:00
Temp_C                         28.2
Dew Point Temp_C               13.9
Rel Hum_%                        42
Wind Speed_km/h                  22
Visibility_km                  48.3
Press_kPa                    101.77
Weather                Mainly Clear
Name: 6159, dtype: object
Inserting row 6161
Error inserting row 6161: tuple index out of range
Row data: Date/Time           9/13/2012 16:00
Temp_C                         28.4
Dew Point Temp_C               14.0
Rel Hum_%                        41
Wind Speed_km/h                  19
Visibility_km                  48.3
Press_kPa                    101.73
Weather                Mainly Clear
Name: 6160, dtype: object
Inserting row 6162
Error inserting row 6162: tuple index out of range
Row data: Date/Time           9/13/2012 17:00
Temp_C                         27.8
Dew Point Temp_C               13.1
Rel Hum_%                        40
Wind Speed_km/h                  20
Visibility_km                  48.3
Press_kPa                    101.73
Weather                Mainly Clear
Name: 6161, dtype: object
Inserting row 6163
Error inserting row 6163: tuple index out of range
Row data: Date/Time           9/13/2012 18:00
Temp_C                         26.0
Dew Point Temp_C               14.7
Rel Hum_%                        50
Wind Speed_km/h                   9
Visibility_km                  48.3
Press_kPa                    101.71
Weather                Mainly Clear
Name: 6162, dtype: object
Inserting row 6164
Error inserting row 6164: tuple index out of range
Row data: Date/Time           9/13/2012 19:00
Temp_C                         24.2
Dew Point Temp_C               15.8
Rel Hum_%                        59
Wind Speed_km/h                  11
Visibility_km                  25.0
Press_kPa                    101.72
Weather                Mainly Clear
Name: 6163, dtype: object
Inserting row 6165
Error inserting row 6165: tuple index out of range
Row data: Date/Time           9/13/2012 20:00
Temp_C                         23.2
Dew Point Temp_C               15.7
Rel Hum_%                        63
Wind Speed_km/h                  11
Visibility_km                  25.0
Press_kPa                    101.74
Weather                       Clear
Name: 6164, dtype: object
Inserting row 6166
Error inserting row 6166: tuple index out of range
Row data: Date/Time           9/13/2012 21:00
Temp_C                         22.3
Dew Point Temp_C               16.0
Rel Hum_%                        68
Wind Speed_km/h                  13
Visibility_km                  25.0
Press_kPa                    101.71
Weather                Mainly Clear
Name: 6165, dtype: object
Inserting row 6167
Error inserting row 6167: tuple index out of range
Row data: Date/Time           9/13/2012 22:00
Temp_C                         21.8
Dew Point Temp_C               15.2
Rel Hum_%                        66
Wind Speed_km/h                  15
Visibility_km                  25.0
Press_kPa                     101.7
Weather                Mainly Clear
Name: 6166, dtype: object
Inserting row 6168
Error inserting row 6168: tuple index out of range
Row data: Date/Time           9/13/2012 23:00
Temp_C                         20.7
Dew Point Temp_C               15.3
Rel Hum_%                        71
Wind Speed_km/h                  13
Visibility_km                  25.0
Press_kPa                    101.72
Weather                       Clear
Name: 6167, dtype: object
Inserting row 6169
Error inserting row 6169: tuple index out of range
Row data: Date/Time           9/14/2012 0:00
Temp_C                        19.5
Dew Point Temp_C              15.5
Rel Hum_%                       78
Wind Speed_km/h                  9
Visibility_km                 25.0
Press_kPa                   101.72
Weather                      Clear
Name: 6168, dtype: object
Inserting row 6170
Error inserting row 6170: tuple index out of range
Row data: Date/Time           9/14/2012 1:00
Temp_C                        16.6
Dew Point Temp_C              14.9
Rel Hum_%                       90
Wind Speed_km/h                  0
Visibility_km                 25.0
Press_kPa                   101.71
Weather                      Clear
Name: 6169, dtype: object
Inserting row 6171
Error inserting row 6171: tuple index out of range
Row data: Date/Time           9/14/2012 2:00
Temp_C                        18.2

Row data: Date/Time           9/23/2012 12:00
Temp_C                         15.6
Dew Point Temp_C                4.5
Rel Hum_%                        48
Wind Speed_km/h                  26
Visibility_km                  48.3
Press_kPa                     101.0
Weather                Mainly Clear
Name: 6396, dtype: object
Inserting row 6398
Error inserting row 6398: tuple index out of range
Row data: Date/Time           9/23/2012 13:00
Temp_C                         14.6
Dew Point Temp_C                4.2
Rel Hum_%                        50
Wind Speed_km/h                  30
Visibility_km                  48.3
Press_kPa                    101.01
Weather                Mainly Clear
Name: 6397, dtype: object
Inserting row 6399
Error inserting row 6399: tuple index out of range
Row data: Date/Time           9/23/2012 14:00
Temp_C                         16.0
Dew Point Temp_C                4.1
Rel Hum_%                        45
Wind Speed_km/h                  28
Visibility_km                  48.3
Press_kPa                    101.02
Weather                Mainly Clear
Name: 6398, dtype: object
Inserting row 6400
Error inserting row 6400: tuple index out of range
Row data: Date/Time           9/23/2012 15:00
Temp_C                         15.1
Dew Point Temp_C                4.6
Rel Hum_%                        49
Wind Speed_km/h                  24
Visibility_km                  48.3
Press_kPa                    101.04
Weather                Mainly Clear
Name: 6399, dtype: object
Inserting row 6401
Error inserting row 6401: tuple index out of range
Row data: Date/Time           9/23/2012 16:00
Temp_C                         15.1
Dew Point Temp_C                5.7
Rel Hum_%                        53
Wind Speed_km/h                  15
Visibility_km                  48.3
Press_kPa                    101.07
Weather                Mainly Clear
Name: 6400, dtype: object
Inserting row 6402
Error inserting row 6402: tuple index out of range
Row data: Date/Time           9/23/2012 17:00
Temp_C                         14.3
Dew Point Temp_C                3.4
Rel Hum_%                        48
Wind Speed_km/h                  20
Visibility_km                  48.3
Press_kPa                    101.11
Weather                Mainly Clear
Name: 6401, dtype: object
Inserting row 6403
Error inserting row 6403: tuple index out of range
Row data: Date/Time           9/23/2012 18:00
Temp_C                         10.9
Dew Point Temp_C                4.3
Rel Hum_%                        64
Wind Speed_km/h                   9
Visibility_km                  25.0
Press_kPa                    101.17
Weather                Mainly Clear
Name: 6402, dtype: object
Inserting row 6404
Error inserting row 6404: tuple index out of range
Row data: Date/Time           9/23/2012 19:00
Temp_C                          9.8
Dew Point Temp_C                5.3
Rel Hum_%                        74
Wind Speed_km/h                   4
Visibility_km                  25.0
Press_kPa                    101.23
Weather                Mainly Clear
Name: 6403, dtype: object
Inserting row 6405
Error inserting row 6405: tuple index out of range
Row data: Date/Time           9/23/2012 20:00
Temp_C                         11.4
Dew Point Temp_C                4.7
Rel Hum_%                        63
Wind Speed_km/h                   9
Visibility_km                  25.0
Press_kPa                    101.31
Weather                Mainly Clear
Name: 6404, dtype: object
Inserting row 6406
Error inserting row 6406: tuple index out of range
Row data: Date/Time           9/23/2012 21:00
Temp_C                          8.7
Dew Point Temp_C                5.2
Rel Hum_%                        79
Wind Speed_km/h                   7
Visibility_km                  25.0
Press_kPa                    101.38
Weather                Mainly Clear
Name: 6405, dtype: object
Inserting row 6407
Error inserting row 6407: tuple index out of range
Row data: Date/Time           9/23/2012 22:00
Temp_C                          7.2
Dew Point Temp_C                4.9
Rel Hum_%                        85
Wind Speed_km/h                   7
Visibility_km                  25.0
Press_kPa                    101.41
Weather                Mainly Clear
Name: 6406, dtype: object
Inserting row 6408
Error inserting row 6408: tuple index out of range
Row data: Date/Time           9/23/2012 23:00
Temp_C                          9.2
Dew Point Temp_C                5.2
Rel Hum_%                        76
Wind Speed_km/h                   7
Visibility_km                  25.0
Press_kPa                    101.43
Weather               Mostly Cloudy
Name: 6407, dtype: object
Inserting row 6409
Error inserting row 6409: tuple index out of range
Row data: Date/Time           9/24/2012 0:00
Temp_C                         7.7
Dew Point Temp_C               5.1
Rel Hum_%                       84
Wind Speed_km/h                  0
Visibility_km                 25.0
Press_kPa                   101.42
Weather               Mainly Clear
Name: 6408, dtype: object
Inserting row 6410
Error inserting row 6410: tuple index out of range
Row data: Date/Time           9/24/2012 1:00
Temp_C                         5.7
Dew Point Temp_C               4.3
Rel Hum_%                       91
Wind Speed_km/h                  6
Visibility_km                 25.0
Press_kPa                   101.41
Weather               Mainly Clear
Name: 6409, dtype: object
Inserting row 6411
Error inserting row 6411: tuple index out of range
Row data: Date/Time           9/24/2012 2:00
Temp_C                         6.9
Dew Point Temp_C               5.1
Rel Hum_%                       88
Wind Speed_km/h                  0
Visibility_km                 25.0
Press_kPa                   101.37
Weather                      Clear
Name: 6410, dtype: object
Inserting row 6412
Error inserting row 6412: tuple index out of range
Row data: Date/Time           9/24/2012 3:00
Temp_C                         5.7
Dew Point Temp_C               4.7
Rel Hum_%                       93
Wind Speed_km/h                  0
Visibility_km                 25.0
Press_kPa                   101.38
Weather                      Clear
Name: 6411, dtype: object
Inserting row 6413
Error inserting row 6413: tuple index out of range
Row data: Date/Time           9/24/2012 4:00
Temp_C                         7.2
Dew Point Temp_C               5.0
Rel Hum_%                       86
Wind Speed_km/h                  4
Visibility_km                 25.0
Press_kPa                   101.42
Weather               Mainly Clear
Name: 6412, dtype: object
Inserting row 6414
Error inserting row 6414: tuple index out of range
Row data: Date/Time           9/24/2012 5:00
Temp_C                         8.0
Dew Point Temp_C               7.8
Rel Hum_%                       99
Wind Speed_km/h                  0
Visibility_km                 25.0
Press_kPa                   101.44
Weather              Mostly Cloudy
Name: 6413, dtype: object
Inserting row 6415
Error inserting row 6415: tuple index out of range
Row data: Date/Time           9/24/2012 6:00
Temp_C                         6.9
Dew Point Temp_C               6.8
Rel Hum_%                       99
Wind Speed_km/h                  9
Visibility_km                 48.3
Press_kPa                   101.47
Weather              Mostly Cloudy
Name: 6414, dtype: object
Inserting row 6416
Error inserting row 6416: tuple index out of range
Row data: Date/Time           9/24/2012 7:00
Temp_C                         7.9
Dew Point Temp_C               7.5
Rel Hum_%                       97
Wind Speed_km/h                  6
Visibility_km                 48.3
Press_kPa                   101.48
Weather              Mostly Cloudy
Name: 6415, dtype: object
Inserting row 6417
Error inserting row 6417: tuple index out of range
Row data: Date/Time           9/24/2012 8:00
Temp_C                         9.9
Dew Point Temp_C               7.5
Rel Hum_%                       85
Wind Speed_km/h                 13
Visibility_km                 48.3
Press_kPa                   101.51
Weather               Mainly Clear
Name: 6416, dtype: object
Inserting row 6418
Error inserting row 6418: tuple index out of range
Row data: Date/Time           9/24/2012 9:00
Temp_C                        11.0
Dew Point Temp_C               7.9
Rel Hum_%                       81
Wind Speed_km/h                 13
Visibility_km                 48.3
Press_kPa                   101.49
Weather               Mainly Clear
Name: 6417, dtype: object
Inserting row 6419
Error inserting row 6419: tuple index out of range
Row data: Date/Time           9/24/2012 10:00
Temp_C                         12.8
Dew Point Temp_C                7.5
Rel Hum_%                        70
Wind Speed_km/h                  22
Visibility_km                  48.3
Press_kPa                    101.46
Weather                Mainly Clear
Name: 6418, dtype: object
Inserting row 6420
Error inserting row 6420: tuple index out of range
Row data: Date/Time           9/24/2012 11:00
Temp_C                         14.2
Dew Point Temp_C                5.5
Rel Hum_%                        56
Wind Speed_km/h                  28
Visibility_km                  48.3
Press_kPa                    101.44
Weather                Mainly Clear
Name: 6419, dtype: object
Inserting row 6421
Error inserting row 6421: tuple index out of range
Row data: Date/Time           9/24/2012 12:00
Temp_C                         15.0
Dew Point Temp_C                5.7
Rel Hum_%                        54
Wind Speed_km/h                  20
Visibility_km                  48.3
Press_kPa                    101.37
Weather                Mainly Clear
Name: 6420, dtype: object
Inserting row 6422
Error inserting row 6422: tuple index out of range
Row data: Date/Time           9/24/2012 13:00
Temp_C                         15.8
Dew Point Temp_C                3.2
Rel Hum_%                        43
Wind Speed_km/h                  28
Visibility_km                  48.3
Press_kPa                    101.28
Weather                Mainly Clear
Name: 6421, dtype: object
Inserting row 6423
Error inserting row 6423: tuple index out of range
Row data: Date/Time           9/24/2012 14:00
Temp_C                         16.6
Dew Point Temp_C                3.7
Rel Hum_%                        42
Wind Speed_km/h                  32
Visibility_km                  48.3
Press_kPa                    101.23
Weather                Mainly Clear
Name: 6422, dtype: object
Inserting row 6424
Error inserting row 6424: tuple index out of range
Row data: Date/Time           9/24/2012 15:00
Temp_C                         16.3
Dew Point Temp_C                3.6
Rel Hum_%                        43
Wind Speed_km/h                  24
Visibility_km                  48.3
Press_kPa                    101.13
Weather                Mainly Clear
Name: 6423, dtype: object
Inserting row 6425
Error inserting row 6425: tuple index out of range
Row data: Date/Time           9/24/2012 16:00
Temp_C                         16.4
Dew Point Temp_C                4.5
Rel Hum_%                        45
Wind Speed_km/h                  26
Visibility_km                  48.3
Press_kPa                    101.09
Weather                Mainly Clear
Name: 6424, dtype: object
Inserting row 6426
Error inserting row 6426: tuple index out of range
Row data: Date/Time           9/24/2012 17:00
Temp_C                         15.3
Dew Point Temp_C                5.2
Rel Hum_%                        51
Wind Speed_km/h                  28
Visibility_km                  48.3
Press_kPa                    101.06
Weather                Mainly Clear
Name: 6425, dtype: object
Inserting row 6427
Error inserting row 6427: tuple index out of range
Row data: Date/Time           9/24/2012 18:00
Temp_C                         14.4
Dew Point Temp_C                5.8
Rel Hum_%                        56
Wind Speed_km/h                  22
Visibility_km                  25.0
Press_kPa                    101.03
Weather                Mainly Clear
Name: 6426, dtype: object
Inserting row 6428
Error inserting row 6428: tuple index out of range
Row data: Date/Time           9/24/2012 19:00
Temp_C                         13.8
Dew Point Temp_C                5.6
Rel Hum_%                        58
Wind Speed_km/h                  33
Visibility_km                  25.0
Press_kPa                    101.05
Weather                Mainly Clear
Name: 6427, dtype: object
Inserting row 6429
Error inserting row 6429: tuple index out of range
Row data: Date/Time           9/24/2012 20:00
Temp_C                         12.1
Dew Point Temp_C                6.3
Rel Hum_%                        68
Wind Speed_km/h                  15
Visibility_km                  25.0
Press_kPa                    101.06
Weather                Mainly Clear
Name: 6428, dtype: object
Inserting row 6430
Error inserting row 6430: tuple index out of range
Row data: Date/Time           9/24/2012 21:00
Temp_C                         11.7
Dew Point Temp_C                6.2
Rel Hum_%                        69
Wind Speed_km/h                  17
Visibility_km                  25.0
Press_kPa                    101.06
Weather               Mostly Cloudy
Name: 6429, dtype: object
Inserting row 6431
Error inserting row 6431: tuple index out of range
Row data: Date/Time           9/24/2012 22:00
Temp_C                         12.6
Dew Point Temp_C                5.6
Rel Hum_%                        62
Wind Speed_km/h                  17
Visibility_km                  25.0
Press_kPa                    101.08
Weather               Mostly Cloudy
Name: 6430, dtype: object
Inserting row 6432
Error inserting row 6432: tuple index out of range
Row data: Date/Time           9/24/2012 23:00
Temp_C                         12.1
Dew Point Temp_C                5.6
Rel Hum_%                        64
Wind Speed_km/h                  20
Visibility_km                  25.0
Press_kPa                    101.04
Weather                Mainly Clear
Name: 6431, dtype: object
Inserting row 6433
Error inserting row 6433: tuple index out of range
Row data: Date/Time           9/25/2012 0:00
Temp_C                        11.9
Dew Point Temp_C               6.0
Rel Hum_%                       67
Wind Speed_km/h                 17
Visibility_km                 25.0
Press_kPa                   101.02
Weather              Mostly Cloudy
Name: 6432, dtype: object
Inserting row 6434
Error inserting row 6434: tuple index out of range
Row data: Date/Time           9/25/2012 1:00
Temp_C                        12.1
Dew Point Temp_C               6.4
Rel Hum_%                       68
Wind Speed_km/h                 19
Visibility_km                 25.0
Press_kPa                   100.92
Weather              Mostly Cloudy
Name: 6433, dtype: object
Inserting row 6435
Error inserting row 6435: tuple index out of range
Row data: Date/Time           9/25/2012 2:00
Temp_C                        11.7
Dew Point Temp_C               5.3
Rel Hum_%                       65
Wind Speed_km/h                 20
Visibility_km                 25.0
Press_kPa                   100.88
Weather              Mostly Cloudy
Name: 6434, dtype: object
Inserting row 6436
Error inserting row 6436: tuple index out of range
Row data: Date/Time           9/25/2012 3:00
Temp_C                        11.2
Dew Point Temp_C               5.5
Rel Hum_%                       68
Wind Speed_km/h                 20
Visibility_km                 25.0
Press_kPa                   100.85
Weather              Mostly Cloudy
Name: 6435, dtype: object
Inserting row 6437
Error inserting row 6437: tuple index out of range
Row data: Date/Time           9/25/2012 4:00
Temp_C                        11.6
Dew Point Temp_C               5.3
Rel Hum_%                       65
Wind Speed_km/h                 24
Visibility_km                 25.0
Press_kPa                   100.85
Weather              Mostly Cloudy
Name: 6436, dtype: object
Inserting row 6438
Error inserting row 6438: tuple index out of range
Row data: Date/Time           9/25/2012 5:00
Temp_C                        11.3
Dew Point Temp_C               6.0
Rel Hum_%                       70
Wind Speed_km/h                 17
Visibility_km                 25.0
Press_kPa                   100.85
Weather                     Cloudy
Name: 6437, dtype: object
Inserting row 6439
Error inserting row 6439: tuple index out of range
Row data: Date/Time           9/25/2012 6:00
Temp_C                        12.4
Dew Point Temp_C               6.1
Rel Hum_%                       65
Wind Speed_km/h                 19
Visibility_km                 48.3
Press_kPa                   100.89
Weather              Mostly Cloudy
Name: 6438, dtype: object
Inserting row 6440
Error inserting row 6440: tuple index out of range
Row data: Date/Time           9/25/2012 7:00
Temp_C                        13.0
Dew Point Temp_C               6.9
Rel Hum_%                       66
Wind Speed_km/h                 28
Visibility_km                 48.3
Press_kPa                   100.89
Weather               Mainly Clear
Name: 6439, dtype: object
Inserting row 6441
Error inserting row 6441: tuple index out of range
Row data: Date/Time           9/25/2012 8:00
Temp_C                        14.1
Dew Point Temp_C               7.2
Rel Hum_%                       63
Wind Speed_km/h                 24
Visibility_km                 48.3
Press_kPa                   100.92
Weather               Mainly Clear
Name: 6440, dtype: object
Inserting row 6442
Error inserting row 6442: tuple index out of range
Row data: Date/Time           9/25/2012 9:00
Temp_C                        16.3
Dew Point Temp_C               8.6
Rel Hum_%                       60
Wind Speed_km/h                 32
Visibility_km                 48.3
Press_kPa                   100.93
Weather               Mainly Clear
Name: 6441, dtype: object
Inserting row 6443
Error inserting row 6443: tuple index out of range
Row data: Date/Time           9/25/2012 10:00
Temp_C                         17.4
Dew Point Temp_C                9.0
Rel Hum_%                        58
Wind Speed_km/h                  35
Visibility_km                  48.3
Press_kPa                    100.92
Weather                Mainly Clear
Name: 6442, dtype: object
Inserting row 6444
Error inserting row 6444: tuple index out of range
Row data: Date/Time           9/25/2012 11:00
Temp_C                         18.0
Dew Point Temp_C                9.2
Rel Hum_%                        56
Wind Speed_km/h                  28
Visibility_km                  48.3
Press_kPa                    100.94
Weather                Mainly Clear
Name: 6443, dtype: object
Inserting row 6445
Error inserting row 6445: tuple index out of range
Row data: Date/Time           9/25/2012 12:00
Temp_C                         18.1
Dew Point Temp_C                9.6
Rel Hum_%                        58
Wind Speed_km/h                  30
Visibility_km                  48.3
Press_kPa                    100.99
Weather               Mostly Cloudy
Name: 6444, dtype: object
Inserting row 6446
Error inserting row 6446: tuple index out of range
Row data: Date/Time           9/25/2012 13:00
Temp_C                         18.9
Dew Point Temp_C                9.9
Rel Hum_%                        56
Wind Speed_km/h                  33
Visibility_km                  48.3
Press_kPa                    100.99
Weather               Mostly Cloudy
Name: 6445, dtype: object
Inserting row 6447
Error inserting row 6447: tuple index out of range
Row data: Date/Time           9/25/2012 14:00
Temp_C                         19.0
Dew Point Temp_C               10.4
Rel Hum_%                        57
Wind Speed_km/h                  32
Visibility_km                  48.3
Press_kPa                    100.97
Weather               Mostly Cloudy
Name: 6446, dtype: object
Inserting row 6448
Error inserting row 6448: tuple index out of range
Row data: Date/Time           9/25/2012 15:00

Row data: Date/Time           10/3/2012 22:00
Temp_C                         18.3
Dew Point Temp_C               14.7
Rel Hum_%                        80
Wind Speed_km/h                   7
Visibility_km                  25.0
Press_kPa                    101.56
Weather                      Cloudy
Name: 6646, dtype: object
Inserting row 6648
Error inserting row 6648: tuple index out of range
Row data: Date/Time           10/3/2012 23:00
Temp_C                         18.0
Dew Point Temp_C               14.9
Rel Hum_%                        82
Wind Speed_km/h                   7
Visibility_km                  25.0
Press_kPa                    101.57
Weather                      Cloudy
Name: 6647, dtype: object
Inserting row 6649
Error inserting row 6649: tuple index out of range
Row data: Date/Time           10/4/2012 0:00
Temp_C                        17.0
Dew Point Temp_C              15.1
Rel Hum_%                       89
Wind Speed_km/h                 11
Visibility_km                 16.1
Press_kPa                   101.55
Weather                     Cloudy
Name: 6648, dtype: object
Inserting row 6650
Error inserting row 6650: tuple index out of range
Row data: Date/Time           10/4/2012 1:00
Temp_C                        16.1
Dew Point Temp_C              14.7
Rel Hum_%                       91
Wind Speed_km/h                 11
Visibility_km                 16.1
Press_kPa                   101.55
Weather                     Cloudy
Name: 6649, dtype: object
Inserting row 6651
Error inserting row 6651: tuple index out of range
Row data: Date/Time           10/4/2012 2:00
Temp_C                        14.7
Dew Point Temp_C              14.1
Rel Hum_%                       96
Wind Speed_km/h                 11
Visibility_km                  6.4
Press_kPa                   101.56
Weather                    Drizzle
Name: 6650, dtype: object
Inserting row 6652
Error inserting row 6652: tuple index out of range
Row data: Date/Time           10/4/2012 3:00
Temp_C                        12.6
Dew Point Temp_C              11.8
Rel Hum_%                       95
Wind Speed_km/h                 13
Visibility_km                  9.7
Press_kPa                   101.55
Weather                Drizzle,Fog
Name: 6651, dtype: object
Inserting row 6653
Error inserting row 6653: tuple index out of range
Row data: Date/Time           10/4/2012 4:00
Temp_C                        11.7
Dew Point Temp_C              11.5
Rel Hum_%                       99
Wind Speed_km/h                 15
Visibility_km                 19.3
Press_kPa                   101.55
Weather                     Cloudy
Name: 6652, dtype: object
Inserting row 6654
Error inserting row 6654: tuple index out of range
Row data: Date/Time           10/4/2012 5:00
Temp_C                        11.5
Dew Point Temp_C              11.0
Rel Hum_%                       97
Wind Speed_km/h                  9
Visibility_km                 16.1
Press_kPa                   101.59
Weather                     Cloudy
Name: 6653, dtype: object
Inserting row 6655
Error inserting row 6655: tuple index out of range
Row data: Date/Time           10/4/2012 6:00
Temp_C                        11.3
Dew Point Temp_C              10.8
Rel Hum_%                       97
Wind Speed_km/h                  9
Visibility_km                  6.4
Press_kPa                   101.58
Weather                        Fog
Name: 6654, dtype: object
Inserting row 6656
Error inserting row 6656: tuple index out of range
Row data: Date/Time           10/4/2012 7:00
Temp_C                        11.4
Dew Point Temp_C              11.1
Rel Hum_%                       98
Wind Speed_km/h                 13
Visibility_km                  4.0
Press_kPa                   101.58
Weather                Drizzle,Fog
Name: 6655, dtype: object
Inserting row 6657
Error inserting row 6657: tuple index out of range
Row data: Date/Time           10/4/2012 8:00
Temp_C                        12.0
Dew Point Temp_C              11.8
Rel Hum_%                       99
Wind Speed_km/h                  7
Visibility_km                  4.0
Press_kPa                   101.57
Weather                        Fog
Name: 6656, dtype: object
Inserting row 6658
Error inserting row 6658: tuple index out of range
Row data: Date/Time           10/4/2012 9:00
Temp_C                        12.1
Dew Point Temp_C              12.0
Rel Hum_%                       99
Wind Speed_km/h                 11
Visibility_km                  2.8
Press_kPa                   101.54
Weather                Drizzle,Fog
Name: 6657, dtype: object
Inserting row 6659
Error inserting row 6659: tuple index out of range
Row data: Date/Time           10/4/2012 10:00
Temp_C                         12.6
Dew Point Temp_C               12.5
Rel Hum_%                        99
Wind Speed_km/h                   9
Visibility_km                   4.8
Press_kPa                    101.47
Weather                 Drizzle,Fog
Name: 6658, dtype: object
Inserting row 6660
Error inserting row 6660: tuple index out of range
Row data: Date/Time           10/4/2012 11:00
Temp_C                         13.3
Dew Point Temp_C               12.8
Rel Hum_%                        97
Wind Speed_km/h                   6
Visibility_km                   6.4
Press_kPa                    101.47
Weather                         Fog
Name: 6659, dtype: object
Inserting row 6661
Error inserting row 6661: tuple index out of range
Row data: Date/Time           10/4/2012 12:00
Temp_C                         13.6
Dew Point Temp_C               13.0
Rel Hum_%                        96
Wind Speed_km/h                   0
Visibility_km                   6.4
Press_kPa                    101.42
Weather                 Drizzle,Fog
Name: 6660, dtype: object
Inserting row 6662
Error inserting row 6662: tuple index out of range
Row data: Date/Time           10/4/2012 13:00
Temp_C                         14.4
Dew Point Temp_C               13.2
Rel Hum_%                        92
Wind Speed_km/h                   0
Visibility_km                   6.4
Press_kPa                    101.38
Weather                 Drizzle,Fog
Name: 6661, dtype: object
Inserting row 6663
Error inserting row 6663: tuple index out of range
Row data: Date/Time           10/4/2012 14:00
Temp_C                         15.6
Dew Point Temp_C               14.3
Rel Hum_%                        92
Wind Speed_km/h                   4
Visibility_km                   8.0
Press_kPa                     101.3
Weather                    Rain,Fog
Name: 6662, dtype: object
Inserting row 6664
Error inserting row 6664: tuple index out of range
Row data: Date/Time           10/4/2012 15:00
Temp_C                         15.9
Dew Point Temp_C               14.7
Rel Hum_%                        93
Wind Speed_km/h                   4
Visibility_km                   9.7
Press_kPa                    101.24
Weather                         Fog
Name: 6663, dtype: object
Inserting row 6665
Error inserting row 6665: tuple index out of range
Row data: Date/Time           10/4/2012 16:00
Temp_C                         16.0
Dew Point Temp_C               15.5
Rel Hum_%                        97
Wind Speed_km/h                   4
Visibility_km                   9.7
Press_kPa                    101.18
Weather                         Fog
Name: 6664, dtype: object
Inserting row 6666
Error inserting row 6666: tuple index out of range
Row data: Date/Time           10/4/2012 17:00
Temp_C                         15.8
Dew Point Temp_C               15.3
Rel Hum_%                        97
Wind Speed_km/h                   4
Visibility_km                   9.7
Press_kPa                    101.13
Weather                         Fog
Name: 6665, dtype: object
Inserting row 6667
Error inserting row 6667: tuple index out of range
Row data: Date/Time           10/4/2012 18:00
Temp_C                         14.6
Dew Point Temp_C               14.5
Rel Hum_%                        99
Wind Speed_km/h                   0
Visibility_km                   9.7
Press_kPa                    101.12
Weather                         Fog
Name: 6666, dtype: object
Inserting row 6668
Error inserting row 6668: tuple index out of range
Row data: Date/Time           10/4/2012 19:00
Temp_C                         14.8
Dew Point Temp_C               14.6
Rel Hum_%                        99
Wind Speed_km/h                   6
Visibility_km                   9.7
Press_kPa                     101.1
Weather                         Fog
Name: 6667, dtype: object
Inserting row 6669
Error inserting row 6669: tuple index out of range
Row data: Date/Time           10/4/2012 20:00
Temp_C                         14.1
Dew Point Temp_C               14.1
Rel Hum_%                       100
Wind Speed_km/h                   4
Visibility_km                   9.7
Press_kPa                     101.1
Weather                         Fog
Name: 6668, dtype: object
Inserting row 6670
Error inserting row 6670: tuple index out of range
Row data: Date/Time           10/4/2012 21:00
Temp_C                         14.4
Dew Point Temp_C               13.7
Rel Hum_%                        96
Wind Speed_km/h                   6
Visibility_km                   9.7
Press_kPa                    101.07
Weather                         Fog
Name: 6669, dtype: object
Inserting row 6671
Error inserting row 6671: tuple index out of range
Row data: Date/Time           10/4/2012 22:00
Temp_C                         15.3
Dew Point Temp_C               13.8
Rel Hum_%                        91
Wind Speed_km/h                  13
Visibility_km                  12.9
Press_kPa                    101.01
Weather                Mainly Clear
Name: 6670, dtype: object
Inserting row 6672
Error inserting row 6672: tuple index out of range
Row data: Date/Time           10/4/2012 23:00
Temp_C                         16.6
Dew Point Temp_C               13.7
Rel Hum_%                        83
Wind Speed_km/h                  13
Visibility_km                   9.7
Press_kPa                    100.97
Weather                    Rain,Fog
Name: 6671, dtype: object
Inserting row 6673
Error inserting row 6673: tuple index out of range
Row data: Date/Time           10/5/2012 0:00
Temp_C                        15.8
Dew Point Temp_C              12.7
Rel Hum_%                       82
Wind Speed_km/h                 11
Visibility_km                 12.9
Press_kPa                   100.94
Weather               Mainly Clear
Name: 6672, dtype: object
Inserting row 6674
Error inserting row 6674: tuple index out of range
Row data: Date/Time           10/5/2012 1:00
Temp_C                        15.3
Dew Point Temp_C              12.6
Rel Hum_%                       84
Wind Speed_km/h                 15
Visibility_km                 12.9
Press_kPa                   100.94
Weather               Mainly Clear
Name: 6673, dtype: object
Inserting row 6675
Error inserting row 6675: tuple index out of range
Row data: Date/Time           10/5/2012 2:00
Temp_C                        15.7
Dew Point Temp_C              12.7
Rel Hum_%                       82
Wind Speed_km/h                 17
Visibility_km                 16.1
Press_kPa                   100.92
Weather                      Clear
Name: 6674, dtype: object
Inserting row 6676
Error inserting row 6676: tuple index out of range
Row data: Date/Time           10/5/2012 3:00
Temp_C                        14.7
Dew Point Temp_C              12.6
Rel Hum_%                       87
Wind Speed_km/h                 17
Visibility_km                 19.3
Press_kPa                   100.94
Weather                      Clear
Name: 6675, dtype: object
Inserting row 6677
Error inserting row 6677: tuple index out of range
Row data: Date/Time           10/5/2012 4:00
Temp_C                        14.4
Dew Point Temp_C              12.6
Rel Hum_%                       89
Wind Speed_km/h                 13
Visibility_km                 19.3
Press_kPa                   100.96
Weather                      Clear
Name: 6676, dtype: object
Inserting row 6678
Error inserting row 6678: tuple index out of range
Row data: Date/Time           10/5/2012 5:00
Temp_C                        13.8
Dew Point Temp_C              12.6
Rel Hum_%                       92
Wind Speed_km/h                 17
Visibility_km                 19.3
Press_kPa                   100.96
Weather                      Clear
Name: 6677, dtype: object
Inserting row 6679
Error inserting row 6679: tuple index out of range
Row data: Date/Time           10/5/2012 6:00
Temp_C                        13.7
Dew Point Temp_C              12.9
Rel Hum_%                       95
Wind Speed_km/h                  4
Visibility_km                 16.1
Press_kPa                   100.93
Weather               Mainly Clear
Name: 6678, dtype: object
Inserting row 6680
Error inserting row 6680: tuple index out of range
Row data: Date/Time           10/5/2012 7:00
Temp_C                        15.3
Dew Point Temp_C              14.0
Rel Hum_%                       92
Wind Speed_km/h                  6
Visibility_km                 24.1
Press_kPa                   100.92
Weather               Mainly Clear
Name: 6679, dtype: object
Inserting row 6681
Error inserting row 6681: tuple index out of range
Row data: Date/Time           10/5/2012 8:00
Temp_C                        16.8
Dew Point Temp_C              14.3
Rel Hum_%                       85
Wind Speed_km/h                  9
Visibility_km                 24.1
Press_kPa                   100.92
Weather              Mostly Cloudy
Name: 6680, dtype: object
Inserting row 6682
Error inserting row 6682: tuple index out of range
Row data: Date/Time           10/5/2012 9:00
Temp_C                        17.3
Dew Point Temp_C              13.6
Rel Hum_%                       79
Wind Speed_km/h                 13
Visibility_km                 24.1
Press_kPa                   100.84
Weather              Mostly Cloudy
Name: 6681, dtype: object
Inserting row 6683
Error inserting row 6683: tuple index out of range
Row data: Date/Time           10/5/2012 10:00
Temp_C                         18.9
Dew Point Temp_C               14.4
Rel Hum_%                        75
Wind Speed_km/h                  11
Visibility_km                  24.1
Press_kPa                    100.87
Weather                Rain Showers
Name: 6682, dtype: object
Inserting row 6684
Error inserting row 6684: tuple index out of range
Row data: Date/Time           10/5/2012 11:00
Temp_C                         17.5
Dew Point Temp_C               14.3
Rel Hum_%                        81
Wind Speed_km/h                  22
Visibility_km                  24.1
Press_kPa                    100.85
Weather                      Cloudy
Name: 6683, dtype: object
Inserting row 6685
Error inserting row 6685: tuple index out of range
Row data: Date/Time           10/5/2012 12:00
Temp_C                         18.5
Dew Point Temp_C               15.3
Rel Hum_%                        82
Wind Speed_km/h                  19
Visibility_km                  24.1
Press_kPa                    100.74
Weather                      Cloudy
Name: 6684, dtype: object
Inserting row 6686
Error inserting row 6686: tuple index out of range
Row data: Date/Time           10/5/2012 13:00
Temp_C                         19.2
Dew Point Temp_C               14.9
Rel Hum_%                        76
Wind Speed_km/h                  20
Visibility_km                  24.1
Press_kPa                    100.69
Weather                      Cloudy
Name: 6685, dtype: object
Inserting row 6687
Error inserting row 6687: tuple index out of range
Row data: Date/Time           10/5/2012 14:00
Temp_C                         20.2
Dew Point Temp_C               15.6
Rel Hum_%                        75
Wind Speed_km/h                  19
Visibility_km                  24.1
Press_kPa                     100.6
Weather               Mostly Cloudy
Name: 6686, dtype: object
Inserting row 6688
Error inserting row 6688: tuple index out of range
Row data: Date/Time           10/5/2012 15:00
Temp_C                         20.7
Dew Point Temp_C               15.4
Rel Hum_%                        72
Wind Speed_km/h                  26
Visibility_km                  24.1
Press_kPa                    100.57
Weather                      Cloudy
Name: 6687, dtype: object
Inserting row 6689
Error inserting row 6689: tuple index out of range
Row data: Date/Time           10/5/2012 16:00
Temp_C                         20.3
Dew Point Temp_C               15.4
Rel Hum_%                        73
Wind Speed_km/h                  28
Visibility_km                  24.1
Press_kPa                    100.55
Weather                      Cloudy
Name: 6688, dtype: object
Inserting row 6690
Error inserting row 6690: tuple index out of range
Row data: Date/Time           10/5/2012 17:00
Temp_C                         19.7
Dew Point Temp_C               14.8
Rel Hum_%                        73
Wind Speed_km/h                  26
Visibility_km                  24.1
Press_kPa                    100.55
Weather                      Cloudy
Name: 6689, dtype: object
Inserting row 6691
Error inserting row 6691: tuple index out of range
Row data: Date/Time           10/5/2012 18:00
Temp_C                         19.0
Dew Point Temp_C               14.8
Rel Hum_%                        77
Wind Speed_km/h                  24
Visibility_km                  25.0
Press_kPa                    100.53
Weather                      Cloudy
Name: 6690, dtype: object
Inserting row 6692
Error inserting row 6692: tuple index out of range
Row data: Date/Time           10/5/2012 19:00
Temp_C                         18.7
Dew Point Temp_C               14.2
Rel Hum_%                        75
Wind Speed_km/h                  32
Visibility_km                  25.0
Press_kPa                    100.53
Weather                      Cloudy
Name: 6691, dtype: object
Inserting row 6693
Error inserting row 6693: tuple index out of range
Row data: Date/Time           10/5/2012 20:00
Temp_C                         18.1
Dew Point Temp_C               14.0
Rel Hum_%                        77
Wind Speed_km/h                  24
Visibility_km                  25.0
Press_kPa                    100.55
Weather                      Cloudy
Name: 6692, dtype: object
Inserting row 6694
Error inserting row 6694: tuple index out of range
Row data: Date/Time           10/5/2012 21:00
Temp_C                         17.8
Dew Point Temp_C               13.8
Rel Hum_%                        77
Wind Speed_km/h                  22
Visibility_km                  25.0
Press_kPa                    100.56
Weather                      Cloudy
Name: 6693, dtype: object
Inserting row 6695
Error inserting row 6695: tuple index out of range
Row data: Date/Time           10/5/2012 22:00
Temp_C                         17.4
Dew Point Temp_C               12.1
Rel Hum_%                        71
Wind Speed_km/h                  19
Visibility_km                  25.0
Press_kPa                    100.54
Weather                      Cloudy
Name: 6694, dtype: object
Inserting row 6696
Error inserting row 6696: tuple index out of range
Row data: Date/Time           10/5/2012 23:00
Temp_C                         17.0
Dew Point Temp_C               10.9
Rel Hum_%                        67
Wind Speed_km/h                  17
Visibility_km                  25.0
Press_kPa                    100.53
Weather                      Cloudy
Name: 6695, dtype: object
Inserting row 6697
Error inserting row 6697: tuple index out of range
Row data: Date/Time           10/6/2012 0:00
Temp_C                        16.8
Dew Point Temp_C              11.2
Rel Hum_%                       70
Wind Speed_km/h                 13
Visibility_km                 25.0
Press_kPa                   100.51
Weather                     Cloudy
Name: 6696, dtype: object
Inserting row 6698
Error inserting row 6698: tuple index out of range
Row data: Date/Time           10/6/2012 1:00

Row data: Date/Time           10/14/2012 12:00
Temp_C                           6.7
Dew Point Temp_C                 6.3
Rel Hum_%                         97
Wind Speed_km/h                   13
Visibility_km                    2.4
Press_kPa                      101.0
Weather                  Drizzle,Fog
Name: 6900, dtype: object
Inserting row 6902
Error inserting row 6902: tuple index out of range
Row data: Date/Time           10/14/2012 13:00
Temp_C                           6.6
Dew Point Temp_C                 6.3
Rel Hum_%                         98
Wind Speed_km/h                   13
Visibility_km                    1.6
Press_kPa                     100.94
Weather                  Drizzle,Fog
Name: 6901, dtype: object
Inserting row 6903
Error inserting row 6903: tuple index out of range
Row data: Date/Time           10/14/2012 14:00
Temp_C                           6.6
Dew Point Temp_C                 6.3
Rel Hum_%                         98
Wind Speed_km/h                   19
Visibility_km                    2.0
Press_kPa                     100.84
Weather                     Rain,Fog
Name: 6902, dtype: object
Inserting row 6904
Error inserting row 6904: tuple index out of range
Row data: Date/Time           10/14/2012 15:00
Temp_C                           7.0
Dew Point Temp_C                 6.6
Rel Hum_%                         97
Wind Speed_km/h                   15
Visibility_km                    8.0
Press_kPa                     100.77
Weather                     Rain,Fog
Name: 6903, dtype: object
Inserting row 6905
Error inserting row 6905: tuple index out of range
Row data: Date/Time           10/14/2012 16:00
Temp_C                           7.5
Dew Point Temp_C                 7.1
Rel Hum_%                         97
Wind Speed_km/h                   15
Visibility_km                    3.2
Press_kPa                     100.68
Weather                     Rain,Fog
Name: 6904, dtype: object
Inserting row 6906
Error inserting row 6906: tuple index out of range
Row data: Date/Time           10/14/2012 17:00
Temp_C                           7.7
Dew Point Temp_C                 7.3
Rel Hum_%                         97
Wind Speed_km/h                   19
Visibility_km                    6.4
Press_kPa                     100.67
Weather                     Rain,Fog
Name: 6905, dtype: object
Inserting row 6907
Error inserting row 6907: tuple index out of range
Row data: Date/Time           10/14/2012 18:00
Temp_C                           9.9
Dew Point Temp_C                 9.4
Rel Hum_%                         97
Wind Speed_km/h                   11
Visibility_km                    2.0
Press_kPa                     100.56
Weather                     Rain,Fog
Name: 6906, dtype: object
Inserting row 6908
Error inserting row 6908: tuple index out of range
Row data: Date/Time           10/14/2012 19:00
Temp_C                           9.6
Dew Point Temp_C                 9.1
Rel Hum_%                         97
Wind Speed_km/h                   15
Visibility_km                    9.7
Press_kPa                     100.48
Weather                  Drizzle,Fog
Name: 6907, dtype: object
Inserting row 6909
Error inserting row 6909: tuple index out of range
Row data: Date/Time           10/14/2012 20:00
Temp_C                          10.0
Dew Point Temp_C                 9.3
Rel Hum_%                         95
Wind Speed_km/h                   15
Visibility_km                    9.7
Press_kPa                     100.31
Weather                          Fog
Name: 6908, dtype: object
Inserting row 6910
Error inserting row 6910: tuple index out of range
Row data: Date/Time           10/14/2012 21:00
Temp_C                           9.8
Dew Point Temp_C                 9.3
Rel Hum_%                         97
Wind Speed_km/h                   11
Visibility_km                    9.7
Press_kPa                     100.27
Weather                          Fog
Name: 6909, dtype: object
Inserting row 6911
Error inserting row 6911: tuple index out of range
Row data: Date/Time           10/14/2012 22:00
Temp_C                           9.4
Dew Point Temp_C                 9.1
Rel Hum_%                         98
Wind Speed_km/h                    7
Visibility_km                    9.7
Press_kPa                     100.17
Weather                          Fog
Name: 6910, dtype: object
Inserting row 6912
Error inserting row 6912: tuple index out of range
Row data: Date/Time           10/14/2012 23:00
Temp_C                           8.9
Dew Point Temp_C                 8.6
Rel Hum_%                         98
Wind Speed_km/h                   15
Visibility_km                    6.4
Press_kPa                     100.13
Weather                     Rain,Fog
Name: 6911, dtype: object
Inserting row 6913
Error inserting row 6913: tuple index out of range
Row data: Date/Time           10/15/2012 0:00
Temp_C                          8.8
Dew Point Temp_C                8.4
Rel Hum_%                        97
Wind Speed_km/h                  13
Visibility_km                   9.7
Press_kPa                    100.05
Weather                    Rain,Fog
Name: 6912, dtype: object
Inserting row 6914
Error inserting row 6914: tuple index out of range
Row data: Date/Time           10/15/2012 1:00
Temp_C                          8.5
Dew Point Temp_C                8.2
Rel Hum_%                        98
Wind Speed_km/h                   9
Visibility_km                   9.7
Press_kPa                    100.02
Weather                    Rain,Fog
Name: 6913, dtype: object
Inserting row 6915
Error inserting row 6915: tuple index out of range
Row data: Date/Time           10/15/2012 2:00
Temp_C                          8.7
Dew Point Temp_C                8.4
Rel Hum_%                        98
Wind Speed_km/h                  11
Visibility_km                   9.7
Press_kPa                     99.88
Weather                    Rain,Fog
Name: 6914, dtype: object
Inserting row 6916
Error inserting row 6916: tuple index out of range
Row data: Date/Time           10/15/2012 3:00
Temp_C                          8.8
Dew Point Temp_C                8.4
Rel Hum_%                        97
Wind Speed_km/h                   9
Visibility_km                   9.7
Press_kPa                     99.78
Weather                    Rain,Fog
Name: 6915, dtype: object
Inserting row 6917
Error inserting row 6917: tuple index out of range
Row data: Date/Time           10/15/2012 4:00
Temp_C                         11.9
Dew Point Temp_C               10.7
Rel Hum_%                        92
Wind Speed_km/h                   4
Visibility_km                  12.9
Press_kPa                     99.66
Weather               Mostly Cloudy
Name: 6916, dtype: object
Inserting row 6918
Error inserting row 6918: tuple index out of range
Row data: Date/Time           10/15/2012 5:00
Temp_C                         13.5
Dew Point Temp_C               11.6
Rel Hum_%                        88
Wind Speed_km/h                  11
Visibility_km                  16.1
Press_kPa                     99.62
Weather               Mostly Cloudy
Name: 6917, dtype: object
Inserting row 6919
Error inserting row 6919: tuple index out of range
Row data: Date/Time           10/15/2012 6:00
Temp_C                         13.6
Dew Point Temp_C               11.5
Rel Hum_%                        87
Wind Speed_km/h                  19
Visibility_km                  24.1
Press_kPa                     99.56
Weather                      Cloudy
Name: 6918, dtype: object
Inserting row 6920
Error inserting row 6920: tuple index out of range
Row data: Date/Time           10/15/2012 7:00
Temp_C                         13.8
Dew Point Temp_C               11.1
Rel Hum_%                        84
Wind Speed_km/h                  19
Visibility_km                  24.1
Press_kPa                     99.53
Weather               Mostly Cloudy
Name: 6919, dtype: object
Inserting row 6921
Error inserting row 6921: tuple index out of range
Row data: Date/Time           10/15/2012 8:00
Temp_C                         14.4
Dew Point Temp_C               11.3
Rel Hum_%                        82
Wind Speed_km/h                  20
Visibility_km                  24.1
Press_kPa                     99.53
Weather                      Cloudy
Name: 6920, dtype: object
Inserting row 6922
Error inserting row 6922: tuple index out of range
Row data: Date/Time           10/15/2012 9:00
Temp_C                         16.4
Dew Point Temp_C               12.1
Rel Hum_%                        76
Wind Speed_km/h                  24
Visibility_km                  24.1
Press_kPa                     99.51
Weather               Mostly Cloudy
Name: 6921, dtype: object
Inserting row 6923
Error inserting row 6923: tuple index out of range
Row data: Date/Time           10/15/2012 10:00
Temp_C                          16.6
Dew Point Temp_C                12.7
Rel Hum_%                         78
Wind Speed_km/h                   20
Visibility_km                   24.1
Press_kPa                       99.5
Weather                       Cloudy
Name: 6922, dtype: object
Inserting row 6924
Error inserting row 6924: tuple index out of range
Row data: Date/Time           10/15/2012 11:00
Temp_C                          16.6
Dew Point Temp_C                12.4
Rel Hum_%                         76
Wind Speed_km/h                   17
Visibility_km                   24.1
Press_kPa                      99.61
Weather                 Rain Showers
Name: 6923, dtype: object
Inserting row 6925
Error inserting row 6925: tuple index out of range
Row data: Date/Time           10/15/2012 12:00
Temp_C                          16.4
Dew Point Temp_C                10.6
Rel Hum_%                         69
Wind Speed_km/h                   22
Visibility_km                   24.1
Press_kPa                      99.63
Weather                Mostly Cloudy
Name: 6924, dtype: object
Inserting row 6926
Error inserting row 6926: tuple index out of range
Row data: Date/Time           10/15/2012 13:00
Temp_C                          16.3
Dew Point Temp_C                10.7
Rel Hum_%                         69
Wind Speed_km/h                   28
Visibility_km                   24.1
Press_kPa                      99.64
Weather                Mostly Cloudy
Name: 6925, dtype: object
Inserting row 6927
Error inserting row 6927: tuple index out of range
Row data: Date/Time           10/15/2012 14:00
Temp_C                          17.8
Dew Point Temp_C                 9.3
Rel Hum_%                         57
Wind Speed_km/h                   30
Visibility_km                   48.3
Press_kPa                      99.65
Weather                Mostly Cloudy
Name: 6926, dtype: object
Inserting row 6928
Error inserting row 6928: tuple index out of range
Row data: Date/Time           10/15/2012 15:00
Temp_C                          16.2
Dew Point Temp_C                 9.0
Rel Hum_%                         62
Wind Speed_km/h                   28
Visibility_km                   24.1
Press_kPa                       99.7
Weather                Mostly Cloudy
Name: 6927, dtype: object
Inserting row 6929
Error inserting row 6929: tuple index out of range
Row data: Date/Time           10/15/2012 16:00
Temp_C                          15.5
Dew Point Temp_C                 8.9
Rel Hum_%                         65
Wind Speed_km/h                   30
Visibility_km                   24.1
Press_kPa                       99.7
Weather                Mostly Cloudy
Name: 6928, dtype: object
Inserting row 6930
Error inserting row 6930: tuple index out of range
Row data: Date/Time           10/15/2012 17:00
Temp_C                          14.7
Dew Point Temp_C                 8.2
Rel Hum_%                         65
Wind Speed_km/h                   33
Visibility_km                   24.1
Press_kPa                      99.69
Weather                Mostly Cloudy
Name: 6929, dtype: object
Inserting row 6931
Error inserting row 6931: tuple index out of range
Row data: Date/Time           10/15/2012 18:00
Temp_C                          13.7
Dew Point Temp_C                 8.7
Rel Hum_%                         72
Wind Speed_km/h                   32
Visibility_km                   25.0
Press_kPa                       99.7
Weather                Mostly Cloudy
Name: 6930, dtype: object
Inserting row 6932
Error inserting row 6932: tuple index out of range
Row data: Date/Time           10/15/2012 19:00
Temp_C                          12.9
Dew Point Temp_C                 8.3
Rel Hum_%                         74
Wind Speed_km/h                   30
Visibility_km                   25.0
Press_kPa                      99.72
Weather                Mostly Cloudy
Name: 6931, dtype: object
Inserting row 6933
Error inserting row 6933: tuple index out of range
Row data: Date/Time           10/15/2012 20:00
Temp_C                          12.6
Dew Point Temp_C                 7.9
Rel Hum_%                         73
Wind Speed_km/h                   30
Visibility_km                   25.0
Press_kPa                      99.76
Weather                 Mainly Clear
Name: 6932, dtype: object
Inserting row 6934
Error inserting row 6934: tuple index out of range
Row data: Date/Time           10/15/2012 21:00
Temp_C                          12.1
Dew Point Temp_C                 6.8
Rel Hum_%                         70
Wind Speed_km/h                   26
Visibility_km                   25.0
Press_kPa                      99.74
Weather                 Mainly Clear
Name: 6933, dtype: object
Inserting row 6935
Error inserting row 6935: tuple index out of range
Row data: Date/Time           10/15/2012 22:00
Temp_C                          12.1
Dew Point Temp_C                 5.1
Rel Hum_%                         62
Wind Speed_km/h                   32
Visibility_km                   25.0
Press_kPa                      99.73
Weather                Mostly Cloudy
Name: 6934, dtype: object
Inserting row 6936
Error inserting row 6936: tuple index out of range
Row data: Date/Time           10/15/2012 23:00
Temp_C                          11.6
Dew Point Temp_C                 3.5
Rel Hum_%                         57
Wind Speed_km/h                   28
Visibility_km                   25.0
Press_kPa                      99.75
Weather                Mostly Cloudy
Name: 6935, dtype: object
Inserting row 6937
Error inserting row 6937: tuple index out of range
Row data: Date/Time           10/16/2012 0:00
Temp_C                          9.8
Dew Point Temp_C                3.8
Rel Hum_%                        66
Wind Speed_km/h                  28
Visibility_km                  25.0
Press_kPa                     99.81
Weather                Mainly Clear
Name: 6936, dtype: object
Inserting row 6938
Error inserting row 6938: tuple index out of range
Row data: Date/Time           10/16/2012 1:00
Temp_C                          9.2
Dew Point Temp_C                3.9
Rel Hum_%                        69
Wind Speed_km/h                  24
Visibility_km                  25.0
Press_kPa                     99.89
Weather               Mostly Cloudy
Name: 6937, dtype: object
Inserting row 6939
Error inserting row 6939: tuple index out of range
Row data: Date/Time           10/16/2012 2:00
Temp_C                          7.6
Dew Point Temp_C                1.8
Rel Hum_%                        67
Wind Speed_km/h                  30
Visibility_km                  25.0
Press_kPa                     99.88
Weather                Mainly Clear
Name: 6938, dtype: object
Inserting row 6940
Error inserting row 6940: tuple index out of range
Row data: Date/Time           10/16/2012 3:00
Temp_C                          6.7
Dew Point Temp_C                2.6
Rel Hum_%                        75
Wind Speed_km/h                  19
Visibility_km                  25.0
Press_kPa                     99.88
Weather               Mostly Cloudy
Name: 6939, dtype: object
Inserting row 6941
Error inserting row 6941: tuple index out of range
Row data: Date/Time           10/16/2012 4:00
Temp_C                          6.6
Dew Point Temp_C                3.0
Rel Hum_%                        78
Wind Speed_km/h                  22
Visibility_km                  25.0
Press_kPa                     99.94
Weather                      Cloudy
Name: 6940, dtype: object
Inserting row 6942
Error inserting row 6942: tuple index out of range
Row data: Date/Time           10/16/2012 5:00
Temp_C                          5.9
Dew Point Temp_C                2.9
Rel Hum_%                        81
Wind Speed_km/h                  19
Visibility_km                  25.0
Press_kPa                     99.99
Weather                      Cloudy
Name: 6941, dtype: object
Inserting row 6943
Error inserting row 6943: tuple index out of range
Row data: Date/Time           10/16/2012 6:00
Temp_C                          5.2
Dew Point Temp_C                1.0
Rel Hum_%                        74
Wind Speed_km/h                  28
Visibility_km                  24.1
Press_kPa                    100.05
Weather               Mostly Cloudy
Name: 6942, dtype: object
Inserting row 6944
Error inserting row 6944: tuple index out of range
Row data: Date/Time           10/16/2012 7:00
Temp_C                          4.8
Dew Point Temp_C                0.8
Rel Hum_%                        75
Wind Speed_km/h                  15
Visibility_km                  24.1
Press_kPa                    100.18
Weather               Mostly Cloudy
Name: 6943, dtype: object
Inserting row 6945
Error inserting row 6945: tuple index out of range
Row data: Date/Time           10/16/2012 8:00
Temp_C                          5.6
Dew Point Temp_C                0.7
Rel Hum_%                        71
Wind Speed_km/h                  22
Visibility_km                  24.1
Press_kPa                    100.24
Weather                Mainly Clear
Name: 6944, dtype: object
Inserting row 6946
Error inserting row 6946: tuple index out of range
Row data: Date/Time           10/16/2012 9:00
Temp_C                          6.0
Dew Point Temp_C                1.3
Rel Hum_%                        72
Wind Speed_km/h                  19
Visibility_km                  24.1
Press_kPa                    100.27
Weather               Mostly Cloudy
Name: 6945, dtype: object
Inserting row 6947
Error inserting row 6947: tuple index out of range
Row data: Date/Time           10/16/2012 10:00
Temp_C                           7.6
Dew Point Temp_C                 1.6
Rel Hum_%                         66
Wind Speed_km/h                   26
Visibility_km                   24.1
Press_kPa                      100.3
Weather                Mostly Cloudy
Name: 6946, dtype: object
Inserting row 6948
Error inserting row 6948: tuple index out of range
Row data: Date/Time           10/16/2012 11:00
Temp_C                           7.7
Dew Point Temp_C                 1.4
Rel Hum_%                         64
Wind Speed_km/h                   22
Visibility_km                   24.1
Press_kPa                     100.34
Weather                Mostly Cloudy
Name: 6947, dtype: object
Inserting row 6949
Error inserting row 6949: tuple index out of range
Row data: Date/Time           10/16/2012 12:00
Temp_C                           7.8
Dew Point Temp_C                 1.6
Rel Hum_%                         65
Wind Speed_km/h                   28
Visibility_km                   24.1
Press_kPa                     100.35
Weather                       Cloudy
Name: 6948, dtype: object
Inserting row 6950
Error inserting row 6950: tuple index out of range
Row data: Date/Time           10/16/2012 13:00
Temp_C                           8.2
Dew Point Temp_C                 1.2
Rel Hum_%                         61
Wind Speed_km/h                   24
Visibility_km                   24.1
Press_kPa                     100.38
Weather                Mostly Cloudy
Name: 6949, dtype: object
Inserting row 6951
Error inserting row 6951: tuple index out of range
Row data: Date/Time           10/16/2012 14:00

Row data: Date/Time           10/22/2012 2:00
Temp_C                          7.6
Dew Point Temp_C                3.9
Rel Hum_%                        77
Wind Speed_km/h                  24
Visibility_km                  25.0
Press_kPa                    100.81
Weather                Mainly Clear
Name: 7082, dtype: object
Inserting row 7084
Error inserting row 7084: tuple index out of range
Row data: Date/Time           10/22/2012 3:00
Temp_C                          7.1
Dew Point Temp_C                3.9
Rel Hum_%                        80
Wind Speed_km/h                  17
Visibility_km                  25.0
Press_kPa                    100.84
Weather                Mainly Clear
Name: 7083, dtype: object
Inserting row 7085
Error inserting row 7085: tuple index out of range
Row data: Date/Time           10/22/2012 4:00
Temp_C                          7.4
Dew Point Temp_C                4.0
Rel Hum_%                        79
Wind Speed_km/h                  19
Visibility_km                  25.0
Press_kPa                    100.84
Weather                Mainly Clear
Name: 7084, dtype: object
Inserting row 7086
Error inserting row 7086: tuple index out of range
Row data: Date/Time           10/22/2012 5:00
Temp_C                          7.4
Dew Point Temp_C                4.2
Rel Hum_%                        80
Wind Speed_km/h                  24
Visibility_km                  25.0
Press_kPa                     100.9
Weather                       Clear
Name: 7085, dtype: object
Inserting row 7087
Error inserting row 7087: tuple index out of range
Row data: Date/Time           10/22/2012 6:00
Temp_C                          7.2
Dew Point Temp_C                4.1
Rel Hum_%                        81
Wind Speed_km/h                  15
Visibility_km                  25.0
Press_kPa                    100.95
Weather                       Clear
Name: 7086, dtype: object
Inserting row 7088
Error inserting row 7088: tuple index out of range
Row data: Date/Time           10/22/2012 7:00
Temp_C                          7.8
Dew Point Temp_C                4.4
Rel Hum_%                        79
Wind Speed_km/h                  15
Visibility_km                  24.1
Press_kPa                     101.0
Weather                Mainly Clear
Name: 7087, dtype: object
Inserting row 7089
Error inserting row 7089: tuple index out of range
Row data: Date/Time           10/22/2012 8:00
Temp_C                         10.0
Dew Point Temp_C                5.1
Rel Hum_%                        72
Wind Speed_km/h                  22
Visibility_km                  24.1
Press_kPa                    101.04
Weather               Mostly Cloudy
Name: 7088, dtype: object
Inserting row 7090
Error inserting row 7090: tuple index out of range
Row data: Date/Time           10/22/2012 9:00
Temp_C                          9.8
Dew Point Temp_C                5.3
Rel Hum_%                        74
Wind Speed_km/h                  24
Visibility_km                  24.1
Press_kPa                    101.08
Weather               Mostly Cloudy
Name: 7089, dtype: object
Inserting row 7091
Error inserting row 7091: tuple index out of range
Row data: Date/Time           10/22/2012 10:00
Temp_C                          11.2
Dew Point Temp_C                 5.6
Rel Hum_%                         68
Wind Speed_km/h                   26
Visibility_km                   48.3
Press_kPa                     101.01
Weather                 Mainly Clear
Name: 7090, dtype: object
Inserting row 7092
Error inserting row 7092: tuple index out of range
Row data: Date/Time           10/22/2012 11:00
Temp_C                          12.7
Dew Point Temp_C                 6.3
Rel Hum_%                         65
Wind Speed_km/h                   30
Visibility_km                   48.3
Press_kPa                     101.06
Weather                 Mainly Clear
Name: 7091, dtype: object
Inserting row 7093
Error inserting row 7093: tuple index out of range
Row data: Date/Time           10/22/2012 12:00
Temp_C                          13.0
Dew Point Temp_C                 5.6
Rel Hum_%                         61
Wind Speed_km/h                   24
Visibility_km                   48.3
Press_kPa                     101.03
Weather                 Mainly Clear
Name: 7092, dtype: object
Inserting row 7094
Error inserting row 7094: tuple index out of range
Row data: Date/Time           10/22/2012 13:00
Temp_C                          14.2
Dew Point Temp_C                 6.2
Rel Hum_%                         59
Wind Speed_km/h                   24
Visibility_km                   48.3
Press_kPa                      101.0
Weather                 Mainly Clear
Name: 7093, dtype: object
Inserting row 7095
Error inserting row 7095: tuple index out of range
Row data: Date/Time           10/22/2012 14:00
Temp_C                          14.5
Dew Point Temp_C                 4.7
Rel Hum_%                         52
Wind Speed_km/h                   22
Visibility_km                   48.3
Press_kPa                     101.04
Weather                 Mainly Clear
Name: 7094, dtype: object
Inserting row 7096
Error inserting row 7096: tuple index out of range
Row data: Date/Time           10/22/2012 15:00
Temp_C                          14.6
Dew Point Temp_C                 5.0
Rel Hum_%                         52
Wind Speed_km/h                   28
Visibility_km                   48.3
Press_kPa                     101.05
Weather                 Mainly Clear
Name: 7095, dtype: object
Inserting row 7097
Error inserting row 7097: tuple index out of range
Row data: Date/Time           10/22/2012 16:00
Temp_C                          14.3
Dew Point Temp_C                 4.9
Rel Hum_%                         53
Wind Speed_km/h                   15
Visibility_km                   48.3
Press_kPa                     101.06
Weather                 Mainly Clear
Name: 7096, dtype: object
Inserting row 7098
Error inserting row 7098: tuple index out of range
Row data: Date/Time           10/22/2012 17:00
Temp_C                          13.2
Dew Point Temp_C                 4.7
Rel Hum_%                         56
Wind Speed_km/h                   20
Visibility_km                   24.1
Press_kPa                     101.11
Weather                 Mainly Clear
Name: 7097, dtype: object
Inserting row 7099
Error inserting row 7099: tuple index out of range
Row data: Date/Time           10/22/2012 18:00
Temp_C                          11.9
Dew Point Temp_C                 5.4
Rel Hum_%                         64
Wind Speed_km/h                   19
Visibility_km                   25.0
Press_kPa                     101.16
Weather                 Mainly Clear
Name: 7098, dtype: object
Inserting row 7100
Error inserting row 7100: tuple index out of range
Row data: Date/Time           10/22/2012 19:00
Temp_C                          11.1
Dew Point Temp_C                 5.7
Rel Hum_%                         69
Wind Speed_km/h                   13
Visibility_km                   25.0
Press_kPa                     101.21
Weather                        Clear
Name: 7099, dtype: object
Inserting row 7101
Error inserting row 7101: tuple index out of range
Row data: Date/Time           10/22/2012 20:00
Temp_C                          10.3
Dew Point Temp_C                 5.8
Rel Hum_%                         74
Wind Speed_km/h                   13
Visibility_km                   25.0
Press_kPa                     101.24
Weather                 Mainly Clear
Name: 7100, dtype: object
Inserting row 7102
Error inserting row 7102: tuple index out of range
Row data: Date/Time           10/22/2012 21:00
Temp_C                           8.4
Dew Point Temp_C                 5.2
Rel Hum_%                         80
Wind Speed_km/h                    9
Visibility_km                   25.0
Press_kPa                     101.29
Weather                        Clear
Name: 7101, dtype: object
Inserting row 7103
Error inserting row 7103: tuple index out of range
Row data: Date/Time           10/22/2012 22:00
Temp_C                           8.1
Dew Point Temp_C                 5.4
Rel Hum_%                         83
Wind Speed_km/h                    7
Visibility_km                   25.0
Press_kPa                     101.34
Weather                 Mainly Clear
Name: 7102, dtype: object
Inserting row 7104
Error inserting row 7104: tuple index out of range
Row data: Date/Time           10/22/2012 23:00
Temp_C                           6.4
Dew Point Temp_C                 4.4
Rel Hum_%                         87
Wind Speed_km/h                    0
Visibility_km                   25.0
Press_kPa                     101.34
Weather                        Clear
Name: 7103, dtype: object
Inserting row 7105
Error inserting row 7105: tuple index out of range
Row data: Date/Time           10/23/2012 0:00
Temp_C                          6.2
Dew Point Temp_C                4.1
Rel Hum_%                        86
Wind Speed_km/h                   6
Visibility_km                  25.0
Press_kPa                    101.36
Weather                       Clear
Name: 7104, dtype: object
Inserting row 7106
Error inserting row 7106: tuple index out of range
Row data: Date/Time           10/23/2012 1:00
Temp_C                          5.8
Dew Point Temp_C                3.8
Rel Hum_%                        87
Wind Speed_km/h                   4
Visibility_km                  25.0
Press_kPa                    101.38
Weather                       Clear
Name: 7105, dtype: object
Inserting row 7107
Error inserting row 7107: tuple index out of range
Row data: Date/Time           10/23/2012 2:00
Temp_C                          4.9
Dew Point Temp_C                3.3
Rel Hum_%                        89
Wind Speed_km/h                   9
Visibility_km                  25.0
Press_kPa                     101.4
Weather                       Clear
Name: 7106, dtype: object
Inserting row 7108
Error inserting row 7108: tuple index out of range
Row data: Date/Time           10/23/2012 3:00
Temp_C                          5.1
Dew Point Temp_C                3.5
Rel Hum_%                        89
Wind Speed_km/h                   7
Visibility_km                  25.0
Press_kPa                    101.42
Weather                       Clear
Name: 7107, dtype: object
Inserting row 7109
Error inserting row 7109: tuple index out of range
Row data: Date/Time           10/23/2012 4:00
Temp_C                          5.1
Dew Point Temp_C                3.5
Rel Hum_%                        89
Wind Speed_km/h                   4
Visibility_km                  25.0
Press_kPa                    101.47
Weather                       Clear
Name: 7108, dtype: object
Inserting row 7110
Error inserting row 7110: tuple index out of range
Row data: Date/Time           10/23/2012 5:00
Temp_C                          5.4
Dew Point Temp_C                3.6
Rel Hum_%                        88
Wind Speed_km/h                   6
Visibility_km                  25.0
Press_kPa                    101.54
Weather                       Clear
Name: 7109, dtype: object
Inserting row 7111
Error inserting row 7111: tuple index out of range
Row data: Date/Time           10/23/2012 6:00
Temp_C                          5.1
Dew Point Temp_C                3.5
Rel Hum_%                        89
Wind Speed_km/h                   6
Visibility_km                  24.1
Press_kPa                    101.59
Weather                Mainly Clear
Name: 7110, dtype: object
Inserting row 7112
Error inserting row 7112: tuple index out of range
Row data: Date/Time           10/23/2012 7:00
Temp_C                          4.2
Dew Point Temp_C                2.8
Rel Hum_%                        91
Wind Speed_km/h                   0
Visibility_km                  24.1
Press_kPa                    101.68
Weather                Mainly Clear
Name: 7111, dtype: object
Inserting row 7113
Error inserting row 7113: tuple index out of range
Row data: Date/Time           10/23/2012 8:00
Temp_C                          6.9
Dew Point Temp_C                4.5
Rel Hum_%                        85
Wind Speed_km/h                  11
Visibility_km                  24.1
Press_kPa                    101.71
Weather               Mostly Cloudy
Name: 7112, dtype: object
Inserting row 7114
Error inserting row 7114: tuple index out of range
Row data: Date/Time           10/23/2012 9:00
Temp_C                          9.4
Dew Point Temp_C                5.0
Rel Hum_%                        74
Wind Speed_km/h                   9
Visibility_km                  24.1
Press_kPa                    101.75
Weather               Mostly Cloudy
Name: 7113, dtype: object
Inserting row 7115
Error inserting row 7115: tuple index out of range
Row data: Date/Time           10/23/2012 10:00
Temp_C                           9.6
Dew Point Temp_C                 4.9
Rel Hum_%                         72
Wind Speed_km/h                    4
Visibility_km                   24.1
Press_kPa                     101.73
Weather                Mostly Cloudy
Name: 7114, dtype: object
Inserting row 7116
Error inserting row 7116: tuple index out of range
Row data: Date/Time           10/23/2012 11:00
Temp_C                          10.9
Dew Point Temp_C                 4.6
Rel Hum_%                         65
Wind Speed_km/h                    0
Visibility_km                   24.1
Press_kPa                     101.69
Weather                Mostly Cloudy
Name: 7115, dtype: object
Inserting row 7117
Error inserting row 7117: tuple index out of range
Row data: Date/Time           10/23/2012 12:00
Temp_C                          11.1
Dew Point Temp_C                 3.8
Rel Hum_%                         61
Wind Speed_km/h                    0
Visibility_km                   24.1
Press_kPa                     101.62
Weather                 Mainly Clear
Name: 7116, dtype: object
Inserting row 7118
Error inserting row 7118: tuple index out of range
Row data: Date/Time           10/23/2012 13:00
Temp_C                          12.2
Dew Point Temp_C                 3.8
Rel Hum_%                         56
Wind Speed_km/h                    4
Visibility_km                   24.1
Press_kPa                     101.59
Weather                Mostly Cloudy
Name: 7117, dtype: object
Inserting row 7119
Error inserting row 7119: tuple index out of range
Row data: Date/Time           10/23/2012 14:00
Temp_C                          13.1
Dew Point Temp_C                 3.8
Rel Hum_%                         53
Wind Speed_km/h                    6
Visibility_km                   24.1
Press_kPa                     101.58
Weather                Mostly Cloudy
Name: 7118, dtype: object
Inserting row 7120
Error inserting row 7120: tuple index out of range
Row data: Date/Time           10/23/2012 15:00
Temp_C                          12.3
Dew Point Temp_C                 4.3
Rel Hum_%                         58
Wind Speed_km/h                   11
Visibility_km                   24.1
Press_kPa                     101.57
Weather                Mostly Cloudy
Name: 7119, dtype: object
Inserting row 7121
Error inserting row 7121: tuple index out of range
Row data: Date/Time           10/23/2012 16:00
Temp_C                          11.9
Dew Point Temp_C                 4.0
Rel Hum_%                         58
Wind Speed_km/h                   11
Visibility_km                   24.1
Press_kPa                     101.57
Weather                Mostly Cloudy
Name: 7120, dtype: object
Inserting row 7122
Error inserting row 7122: tuple index out of range
Row data: Date/Time           10/23/2012 17:00
Temp_C                          10.9
Dew Point Temp_C                 3.6
Rel Hum_%                         61
Wind Speed_km/h                    9
Visibility_km                   24.1
Press_kPa                      101.6
Weather                 Mainly Clear
Name: 7121, dtype: object
Inserting row 7123
Error inserting row 7123: tuple index out of range
Row data: Date/Time           10/23/2012 18:00
Temp_C                           7.9
Dew Point Temp_C                 3.5
Rel Hum_%                         74
Wind Speed_km/h                    0
Visibility_km                   25.0
Press_kPa                     101.64
Weather                 Mainly Clear
Name: 7122, dtype: object
Inserting row 7124
Error inserting row 7124: tuple index out of range
Row data: Date/Time           10/23/2012 19:00
Temp_C                           8.6
Dew Point Temp_C                 3.3
Rel Hum_%                         69
Wind Speed_km/h                    0
Visibility_km                   25.0
Press_kPa                      101.7
Weather                 Mainly Clear
Name: 7123, dtype: object
Inserting row 7125
Error inserting row 7125: tuple index out of range
Row data: Date/Time           10/23/2012 20:00
Temp_C                           7.0
Dew Point Temp_C                 2.9
Rel Hum_%                         75
Wind Speed_km/h                    0
Visibility_km                   25.0
Press_kPa                     101.72
Weather                 Mainly Clear
Name: 7124, dtype: object
Inserting row 7126
Error inserting row 7126: tuple index out of range
Row data: Date/Time           10/23/2012 21:00
Temp_C                           6.9
Dew Point Temp_C                 2.6
Rel Hum_%                         74
Wind Speed_km/h                    0
Visibility_km                   25.0
Press_kPa                     101.73
Weather                 Mainly Clear
Name: 7125, dtype: object
Inserting row 7127
Error inserting row 7127: tuple index out of range
Row data: Date/Time           10/23/2012 22:00
Temp_C                           6.8
Dew Point Temp_C                 3.9
Rel Hum_%                         82
Wind Speed_km/h                    7
Visibility_km                   25.0
Press_kPa                     101.76
Weather                 Mainly Clear
Name: 7126, dtype: object
Inserting row 7128
Error inserting row 7128: tuple index out of range
Row data: Date/Time           10/23/2012 23:00
Temp_C                           7.7
Dew Point Temp_C                 0.2
Rel Hum_%                         59
Wind Speed_km/h                   13
Visibility_km                   25.0
Press_kPa                     101.79
Weather                        Clear
Name: 7127, dtype: object
Inserting row 7129
Error inserting row 7129: tuple index out of range
Row data: Date/Time           10/24/2012 0:00
Temp_C                          7.3
Dew Point Temp_C               -1.4
Rel Hum_%                        54
Wind Speed_km/h                  13
Visibility_km                  25.0
Press_kPa                    101.81
Weather                       Clear
Name: 7128, dtype: object
Inserting row 7130
Error inserting row 7130: tuple index out of range
Row data: Date/Time           10/24/2012 1:00
Temp_C                          5.1
Dew Point Temp_C               -1.0
Rel Hum_%                        65
Wind Speed_km/h                  13
Visibility_km                  25.0
Press_kPa                    101.83
Weather                       Clear
Name: 7129, dtype: object
Inserting row 7131
Error inserting row 7131: tuple index out of range
Row data: Date/Time           10/24/2012 2:00
Temp_C                          4.0
Dew Point Temp_C               -1.2
Rel Hum_%                        69
Wind Speed_km/h                   7
Visibility_km                  25.0
Press_kPa                     101.9
Weather                       Clear
Name: 7130, dtype: object
Inserting row 7132
Error inserting row 7132: tuple index out of range
Row data: Date/Time           10/24/2012 3:00
Temp_C                          4.9
Dew Point Temp_C               -0.9
Rel Hum_%                        66
Wind Speed_km/h                   7
Visibility_km                  25.0
Press_kPa                     101.9
Weather                       Clear
Name: 7131, dtype: object
Inserting row 7133
Error inserting row 7133: tuple index out of range
Row data: Date/Time           10/24/2012 4:00

Row data: Date/Time           10/30/2012 20:00
Temp_C                          18.6
Dew Point Temp_C                12.5
Rel Hum_%                         68
Wind Speed_km/h                   26
Visibility_km                   25.0
Press_kPa                      99.57
Weather                 Rain Showers
Name: 7292, dtype: object
Inserting row 7294
Error inserting row 7294: tuple index out of range
Row data: Date/Time           10/30/2012 21:00
Temp_C                          16.8
Dew Point Temp_C                13.5
Rel Hum_%                         81
Wind Speed_km/h                   26
Visibility_km                   19.3
Press_kPa                       99.6
Weather                         Rain
Name: 7293, dtype: object
Inserting row 7295
Error inserting row 7295: tuple index out of range
Row data: Date/Time           10/30/2012 22:00
Temp_C                          15.0
Dew Point Temp_C                13.9
Rel Hum_%                         93
Wind Speed_km/h                   17
Visibility_km                   25.0
Press_kPa                      99.49
Weather                       Cloudy
Name: 7294, dtype: object
Inserting row 7296
Error inserting row 7296: tuple index out of range
Row data: Date/Time           10/30/2012 23:00
Temp_C                          15.6
Dew Point Temp_C                14.0
Rel Hum_%                         90
Wind Speed_km/h                   11
Visibility_km                   25.0
Press_kPa                      99.45
Weather                 Rain Showers
Name: 7295, dtype: object
Inserting row 7297
Error inserting row 7297: tuple index out of range
Row data: Date/Time           10/31/2012 0:00
Temp_C                         15.0
Dew Point Temp_C               13.9
Rel Hum_%                        93
Wind Speed_km/h                   9
Visibility_km                  16.1
Press_kPa                     99.43
Weather                Rain Showers
Name: 7296, dtype: object
Inserting row 7298
Error inserting row 7298: tuple index out of range
Row data: Date/Time           10/31/2012 1:00
Temp_C                         14.9
Dew Point Temp_C               13.6
Rel Hum_%                        92
Wind Speed_km/h                   9
Visibility_km                  25.0
Press_kPa                     99.36
Weather                Mainly Clear
Name: 7297, dtype: object
Inserting row 7299
Error inserting row 7299: tuple index out of range
Row data: Date/Time           10/31/2012 2:00
Temp_C                         13.7
Dew Point Temp_C               12.7
Rel Hum_%                        94
Wind Speed_km/h                  11
Visibility_km                  25.0
Press_kPa                     99.41
Weather                Mainly Clear
Name: 7298, dtype: object
Inserting row 7300
Error inserting row 7300: tuple index out of range
Row data: Date/Time           10/31/2012 3:00
Temp_C                         13.7
Dew Point Temp_C               12.5
Rel Hum_%                        92
Wind Speed_km/h                  11
Visibility_km                  25.0
Press_kPa                     99.43
Weather                Mainly Clear
Name: 7299, dtype: object
Inserting row 7301
Error inserting row 7301: tuple index out of range
Row data: Date/Time           10/31/2012 4:00
Temp_C                         13.8
Dew Point Temp_C               11.6
Rel Hum_%                        87
Wind Speed_km/h                  13
Visibility_km                  25.0
Press_kPa                     99.37
Weather                Mainly Clear
Name: 7300, dtype: object
Inserting row 7302
Error inserting row 7302: tuple index out of range
Row data: Date/Time           10/31/2012 5:00
Temp_C                         13.6
Dew Point Temp_C               11.2
Rel Hum_%                        85
Wind Speed_km/h                  17
Visibility_km                  25.0
Press_kPa                     99.34
Weather                Mainly Clear
Name: 7301, dtype: object
Inserting row 7303
Error inserting row 7303: tuple index out of range
Row data: Date/Time           10/31/2012 6:00
Temp_C                         14.0
Dew Point Temp_C               10.1
Rel Hum_%                        77
Wind Speed_km/h                  11
Visibility_km                  25.0
Press_kPa                     99.24
Weather               Mostly Cloudy
Name: 7302, dtype: object
Inserting row 7304
Error inserting row 7304: tuple index out of range
Row data: Date/Time           10/31/2012 7:00
Temp_C                         11.6
Dew Point Temp_C               10.4
Rel Hum_%                        92
Wind Speed_km/h                  11
Visibility_km                  24.1
Press_kPa                     99.26
Weather               Mostly Cloudy
Name: 7303, dtype: object
Inserting row 7305
Error inserting row 7305: tuple index out of range
Row data: Date/Time           10/31/2012 8:00
Temp_C                         14.0
Dew Point Temp_C               12.1
Rel Hum_%                        88
Wind Speed_km/h                  17
Visibility_km                  24.1
Press_kPa                     99.22
Weather               Mostly Cloudy
Name: 7304, dtype: object
Inserting row 7306
Error inserting row 7306: tuple index out of range
Row data: Date/Time           10/31/2012 9:00
Temp_C                         14.6
Dew Point Temp_C               12.7
Rel Hum_%                        88
Wind Speed_km/h                  15
Visibility_km                  19.3
Press_kPa                     99.16
Weather                      Cloudy
Name: 7305, dtype: object
Inserting row 7307
Error inserting row 7307: tuple index out of range
Row data: Date/Time           10/31/2012 10:00
Temp_C                          14.6
Dew Point Temp_C                12.9
Rel Hum_%                         90
Wind Speed_km/h                   19
Visibility_km                   16.1
Press_kPa                      99.14
Weather                       Cloudy
Name: 7306, dtype: object
Inserting row 7308
Error inserting row 7308: tuple index out of range
Row data: Date/Time           10/31/2012 11:00
Temp_C                          14.8
Dew Point Temp_C                13.7
Rel Hum_%                         93
Wind Speed_km/h                   11
Visibility_km                    9.7
Press_kPa                      99.12
Weather                 Rain Showers
Name: 7307, dtype: object
Inserting row 7309
Error inserting row 7309: tuple index out of range
Row data: Date/Time           10/31/2012 12:00
Temp_C                          10.8
Dew Point Temp_C                 9.4
Rel Hum_%                         91
Wind Speed_km/h                   24
Visibility_km                   24.1
Press_kPa                       99.2
Weather                       Cloudy
Name: 7308, dtype: object
Inserting row 7310
Error inserting row 7310: tuple index out of range
Row data: Date/Time           10/31/2012 13:00
Temp_C                          10.2
Dew Point Temp_C                 8.5
Rel Hum_%                         89
Wind Speed_km/h                   20
Visibility_km                   24.1
Press_kPa                      99.26
Weather                 Rain Showers
Name: 7309, dtype: object
Inserting row 7311
Error inserting row 7311: tuple index out of range
Row data: Date/Time           10/31/2012 14:00
Temp_C                          10.3
Dew Point Temp_C                 8.8
Rel Hum_%                         90
Wind Speed_km/h                   11
Visibility_km                   12.9
Press_kPa                      99.28
Weather                      Drizzle
Name: 7310, dtype: object
Inserting row 7312
Error inserting row 7312: tuple index out of range
Row data: Date/Time           10/31/2012 15:00
Temp_C                          10.2
Dew Point Temp_C                 8.6
Rel Hum_%                         90
Wind Speed_km/h                    4
Visibility_km                   24.1
Press_kPa                      99.28
Weather                 Rain Showers
Name: 7311, dtype: object
Inserting row 7313
Error inserting row 7313: tuple index out of range
Row data: Date/Time           10/31/2012 16:00
Temp_C                          10.2
Dew Point Temp_C                 8.6
Rel Hum_%                         90
Wind Speed_km/h                    4
Visibility_km                   24.1
Press_kPa                      99.26
Weather                       Cloudy
Name: 7312, dtype: object
Inserting row 7314
Error inserting row 7314: tuple index out of range
Row data: Date/Time           10/31/2012 17:00
Temp_C                           9.7
Dew Point Temp_C                 8.1
Rel Hum_%                         90
Wind Speed_km/h                   15
Visibility_km                   24.1
Press_kPa                      99.31
Weather                       Cloudy
Name: 7313, dtype: object
Inserting row 7315
Error inserting row 7315: tuple index out of range
Row data: Date/Time           10/31/2012 18:00
Temp_C                           8.8
Dew Point Temp_C                 7.4
Rel Hum_%                         91
Wind Speed_km/h                   13
Visibility_km                   25.0
Press_kPa                      99.37
Weather                       Cloudy
Name: 7314, dtype: object
Inserting row 7316
Error inserting row 7316: tuple index out of range
Row data: Date/Time           10/31/2012 19:00
Temp_C                           8.5
Dew Point Temp_C                 6.6
Rel Hum_%                         88
Wind Speed_km/h                    7
Visibility_km                   25.0
Press_kPa                      99.37
Weather                Mostly Cloudy
Name: 7315, dtype: object
Inserting row 7317
Error inserting row 7317: tuple index out of range
Row data: Date/Time           10/31/2012 20:00
Temp_C                           8.4
Dew Point Temp_C                 6.3
Rel Hum_%                         87
Wind Speed_km/h                    7
Visibility_km                   25.0
Press_kPa                       99.4
Weather                Mostly Cloudy
Name: 7316, dtype: object
Inserting row 7318
Error inserting row 7318: tuple index out of range
Row data: Date/Time           10/31/2012 21:00
Temp_C                           8.1
Dew Point Temp_C                 6.5
Rel Hum_%                         90
Wind Speed_km/h                    0
Visibility_km                   25.0
Press_kPa                      99.39
Weather                 Rain Showers
Name: 7317, dtype: object
Inserting row 7319
Error inserting row 7319: tuple index out of range
Row data: Date/Time           10/31/2012 22:00
Temp_C                           7.8
Dew Point Temp_C                 6.7
Rel Hum_%                         93
Wind Speed_km/h                    0
Visibility_km                   25.0
Press_kPa                       99.4
Weather                Mostly Cloudy
Name: 7318, dtype: object
Inserting row 7320
Error inserting row 7320: tuple index out of range
Row data: Date/Time           10/31/2012 23:00
Temp_C                           8.1
Dew Point Temp_C                 6.4
Rel Hum_%                         89
Wind Speed_km/h                    4
Visibility_km                   25.0
Press_kPa                      99.38
Weather                       Cloudy
Name: 7319, dtype: object
Inserting row 7321
Error inserting row 7321: tuple index out of range
Row data: Date/Time           11/1/2012 0:00
Temp_C                         7.8
Dew Point Temp_C               6.8
Rel Hum_%                       93
Wind Speed_km/h                  7
Visibility_km                 25.0
Press_kPa                    99.39
Weather              Mostly Cloudy
Name: 7320, dtype: object
Inserting row 7322
Error inserting row 7322: tuple index out of range
Row data: Date/Time           11/1/2012 1:00
Temp_C                         7.6
Dew Point Temp_C               6.8
Rel Hum_%                       95
Wind Speed_km/h                  6
Visibility_km                 25.0
Press_kPa                    99.37
Weather                     Cloudy
Name: 7321, dtype: object
Inserting row 7323
Error inserting row 7323: tuple index out of range
Row data: Date/Time           11/1/2012 2:00
Temp_C                         7.6
Dew Point Temp_C               6.2
Rel Hum_%                       91
Wind Speed_km/h                  4
Visibility_km                 25.0
Press_kPa                    99.35
Weather               Rain Showers
Name: 7322, dtype: object
Inserting row 7324
Error inserting row 7324: tuple index out of range
Row data: Date/Time           11/1/2012 3:00
Temp_C                         7.3
Dew Point Temp_C               5.5
Rel Hum_%                       88
Wind Speed_km/h                  6
Visibility_km                 19.3
Press_kPa                    99.33
Weather               Rain Showers
Name: 7323, dtype: object
Inserting row 7325
Error inserting row 7325: tuple index out of range
Row data: Date/Time           11/1/2012 4:00
Temp_C                         7.7
Dew Point Temp_C               4.7
Rel Hum_%                       81
Wind Speed_km/h                  0
Visibility_km                 25.0
Press_kPa                    99.32
Weather               Rain Showers
Name: 7324, dtype: object
Inserting row 7326
Error inserting row 7326: tuple index out of range
Row data: Date/Time           11/1/2012 5:00
Temp_C                         7.7
Dew Point Temp_C               5.0
Rel Hum_%                       83
Wind Speed_km/h                  4
Visibility_km                 25.0
Press_kPa                    99.32
Weather                       Rain
Name: 7325, dtype: object
Inserting row 7327
Error inserting row 7327: tuple index out of range
Row data: Date/Time           11/1/2012 6:00
Temp_C                         7.4
Dew Point Temp_C               5.4
Rel Hum_%                       87
Wind Speed_km/h                  4
Visibility_km                 25.0
Press_kPa                    99.31
Weather                     Cloudy
Name: 7326, dtype: object
Inserting row 7328
Error inserting row 7328: tuple index out of range
Row data: Date/Time           11/1/2012 7:00
Temp_C                         7.3
Dew Point Temp_C               4.7
Rel Hum_%                       84
Wind Speed_km/h                  7
Visibility_km                 24.1
Press_kPa                    99.32
Weather                       Rain
Name: 7327, dtype: object
Inserting row 7329
Error inserting row 7329: tuple index out of range
Row data: Date/Time           11/1/2012 8:00
Temp_C                         7.2
Dew Point Temp_C               4.5
Rel Hum_%                       83
Wind Speed_km/h                  9
Visibility_km                 24.1
Press_kPa                    99.33
Weather                       Rain
Name: 7328, dtype: object
Inserting row 7330
Error inserting row 7330: tuple index out of range
Row data: Date/Time           11/1/2012 9:00
Temp_C                         7.6
Dew Point Temp_C               5.6
Rel Hum_%                       87
Wind Speed_km/h                  9
Visibility_km                 24.1
Press_kPa                    99.34
Weather                       Rain
Name: 7329, dtype: object
Inserting row 7331
Error inserting row 7331: tuple index out of range
Row data: Date/Time           11/1/2012 10:00
Temp_C                          7.7
Dew Point Temp_C                5.1
Rel Hum_%                        84
Wind Speed_km/h                   9
Visibility_km                  24.1
Press_kPa                     99.31
Weather                      Cloudy
Name: 7330, dtype: object
Inserting row 7332
Error inserting row 7332: tuple index out of range
Row data: Date/Time           11/1/2012 11:00
Temp_C                          8.1
Dew Point Temp_C                4.7
Rel Hum_%                        79
Wind Speed_km/h                  11
Visibility_km                  24.1
Press_kPa                     99.29
Weather                      Cloudy
Name: 7331, dtype: object
Inserting row 7333
Error inserting row 7333: tuple index out of range
Row data: Date/Time           11/1/2012 12:00
Temp_C                          8.4
Dew Point Temp_C                4.9
Rel Hum_%                        79
Wind Speed_km/h                  13
Visibility_km                  24.1
Press_kPa                     99.25
Weather                      Cloudy
Name: 7332, dtype: object
Inserting row 7334
Error inserting row 7334: tuple index out of range
Row data: Date/Time           11/1/2012 13:00
Temp_C                          8.4
Dew Point Temp_C                4.9
Rel Hum_%                        79
Wind Speed_km/h                  15
Visibility_km                  24.1
Press_kPa                     99.22
Weather                        Rain
Name: 7333, dtype: object
Inserting row 7335
Error inserting row 7335: tuple index out of range
Row data: Date/Time           11/1/2012 14:00
Temp_C                          8.4
Dew Point Temp_C                5.3
Rel Hum_%                        81
Wind Speed_km/h                  17
Visibility_km                  19.3
Press_kPa                     99.22
Weather                     Drizzle
Name: 7334, dtype: object
Inserting row 7336
Error inserting row 7336: tuple index out of range
Row data: Date/Time           11/1/2012 15:00
Temp_C                          7.7
Dew Point Temp_C                6.0
Rel Hum_%                        89
Wind Speed_km/h                  11
Visibility_km                  12.9
Press_kPa                     99.22
Weather                        Rain
Name: 7335, dtype: object
Inserting row 7337
Error inserting row 7337: tuple index out of range
Row data: Date/Time           11/1/2012 16:00
Temp_C                          8.0
Dew Point Temp_C                6.2
Rel Hum_%                        88
Wind Speed_km/h                  17
Visibility_km                  19.3
Press_kPa                     99.23
Weather                        Rain
Name: 7336, dtype: object
Inserting row 7338
Error inserting row 7338: tuple index out of range
Row data: Date/Time           11/1/2012 17:00
Temp_C                          8.1
Dew Point Temp_C                5.9
Rel Hum_%                        86
Wind Speed_km/h                  17
Visibility_km                  16.1
Press_kPa                     99.26
Weather                        Rain
Name: 7337, dtype: object
Inserting row 7339
Error inserting row 7339: tuple index out of range
Row data: Date/Time           11/1/2012 18:00
Temp_C                          7.5
Dew Point Temp_C                4.4
Rel Hum_%                        81
Wind Speed_km/h                  28
Visibility_km                  25.0
Press_kPa                      99.3
Weather                      Cloudy
Name: 7338, dtype: object
Inserting row 7340
Error inserting row 7340: tuple index out of range
Row data: Date/Time           11/1/2012 19:00
Temp_C                          6.9
Dew Point Temp_C                4.7
Rel Hum_%                        86
Wind Speed_km/h                  22
Visibility_km                  25.0
Press_kPa                     99.33
Weather                        Rain
Name: 7339, dtype: object
Inserting row 7341
Error inserting row 7341: tuple index out of range
Row data: Date/Time           11/1/2012 20:00
Temp_C                          6.7
Dew Point Temp_C                4.8
Rel Hum_%                        88
Wind Speed_km/h                  24
Visibility_km                  25.0
Press_kPa                     99.33
Weather                        Rain
Name: 7340, dtype: object
Inserting row 7342
Error inserting row 7342: tuple index out of range
Row data: Date/Time           11/1/2012 21:00
Temp_C                          6.4
Dew Point Temp_C                4.5
Rel Hum_%                        88
Wind Speed_km/h                  22
Visibility_km                  25.0
Press_kPa                     99.35
Weather                        Rain
Name: 7341, dtype: object
Inserting row 7343
Error inserting row 7343: tuple index out of range
Row data: Date/Time           11/1/2012 22:00
Temp_C                          5.6
Dew Point Temp_C                3.6
Rel Hum_%                        87
Wind Speed_km/h                  20
Visibility_km                  25.0